### ISSUE TITLE
User creation

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1]
As an EMF admin, I can create users with first name, last name and email address, so that they can access the platform.

**Comment by JMurphyWeb** [comment]
- one view to create user & organisation

**Comment by asimonw** [comment]
@JMurphyWeb Not sure if this is a question, but I would suggest managing users and orgs in different views. What we have in mind is to attach a primary user to an org. So, in the org admin edit view, there would be a user field, e.g. a drop down field allow you to select an existing user.
