### ISSUE TITLE
Member profile details management

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#10]
As a primary user, I can add and edit a company logo, a mission statement and a set of tags characterising my knowledge/experience, so that I have control over how I represent my organisation on the platform and can update this over time.

Mission statement: limited number of chars?
Parent tags are only used as navigational tool and cannot be selected, nor used to select all corresponding child tags.

**Comment by LucyJW** [comment]
Primary Users should be able to upload member logos too. We already have them available and it may be less constraining (from design and brand approval considerations) for us to upload these as part of the profile page set up for new members.

**Comment by asimonw** [comment]
Maybe we should (initially?) not even allow members to update their logos themselves. Logos do often need some extra preparation to fit the design. I'll add logo upload to #8.

**Comment by LucyJW** [comment]
I would agree, better to not let them update logo themselves yet.

**Comment by asimonw** [comment]
Question: how do we go to "edit" mode and what does this look like? 

Some options:
* the edit form is a different "screen"
* clicking an edit button/link will turn the area into a form (like in the prototype built by EMF)
* editing happens inline, "Trello-style"

Pros and cons of each approach? Other approaches?

**Comment by JMurphyWeb** [comment]
@asimonw I don't know if this is aimed at us but unless editing needs to be done very regularly, I feel like option 1 or 2 would suffice.  A primary member will be filling in details on their organisation in the first place, so would it make sense to bring them back to a this view (with populated fields) if they want to make a change?

Mission statement & tags seem unlikely to change too much over time.

**Comment by asimonw** [comment]
@JMurphyWeb yes I do think 1 or 2 is fine, and on mobile they're pretty much the same thing. If the user clicks on the edit button, the screen turns into a form. The same form is presented (with already populated fields containing existing text) for updates. Does that make sense?

Btw, I can confirm, only mission statement and tags need to be editable by primary users.

**Comment by JMurphyWeb** [comment]
Yeah that sounds good.

**Comment by JMurphyWeb** [comment]
@asimonw  At the moment they are sort of one and the same, but in general are expertise tags attached to the company or the primary user?

**Comment by asimonw** [comment]
@JMurphyWeb they are attached to the organisation. Personal expertise/interests would potentially be a later feature.

**Comment by JMurphyWeb** [comment]
Edit tags view is covered in #105. Selecting tags view is covered in #61. Image hosting setup is covered in #55. 

This view is a primary user editing their profile.

**Comment by JMurphyWeb** [comment]
Time estimate is covered in #55 will add please test once that is resolved
