### ISSUE TITLE
Changing a users organisation will affect the new organisation's primary user

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#100]
What should happen to the new organisation's old primary user?

Unsure how to implement this, so have not built functionality for this use case (updating an org that a user is attached to)

Suggestions welcome @asimonw

**Comment by asimonw** [comment]
@JMurphyWeb Could we for the time being just store both users in an array on the org and only display the first one in the array on the profile? That would allow us to remove the old user afterwards.

We'll need to allow for more people to belong to one org in the future anyway.

**Comment by JMurphyWeb** [comment]
closing as existing functionality can be tested and feed back in a new issue
