### ISSUE TITLE
Save logged in time in Postgres

### ISSUE THREAD

**Issue by SimonLab** [emfoundation/ce100-app#1005]
Currently the time when a user log into the application is saved in Redis:
![image](https://user-images.githubusercontent.com/6057298/32169082-df644b7c-bd66-11e7-85bf-7503e9f1ddf4.png)

For creating a report it would be easier if this information is also saved in Postgres as we wouldn't have to query to databases, see #897

**Comment by iteles** [comment]
@asimonw We've added this issue into the sprint more for your awareness than anything else. It will still need to be prioritised.

**Comment by SimonLab** [comment]
I've just noticed that the ```people``` table contains a ```last_login``` column. So we might already store the information in Postgres. I will double check that it is the case.

**Comment by SimonLab** [comment]
The last login timestamp value should now be saved in postgres under the ```last_login``` column in Postgres. A way to test this is to use Redash to see if the value change
