### ISSUE TITLE
Org edit page: the organisation name is not centered

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1011]
When logged in as a primary contact, go to the org profile edit page.
The organisation name at the top is stuck against the left hand side. 
Could is be centred, please?

**Comment by SimonLab** [comment]
![image](https://user-images.githubusercontent.com/6057298/32182695-357286fa-bd8f-11e7-99c6-36d0fc33899e.png)

**Comment by Cleop** [comment]
Is it meant to be centered on mobile too @asimonw?

<img width="300" alt="screen shot 2017-10-31 at 12 52 11" src="https://user-images.githubusercontent.com/16775804/32224711-7521b842-be3a-11e7-8060-b7be08d24428.png">

**Comment by asimonw** [comment]
@Cleop Yes please 👍
