### ISSUE TITLE
Organisation logos should not have rounded corners and be displayed consistently

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1012]
Currently, all organisation logos still have rounded corners. This is the case on:
* the org list in explore
* the org profile / edit
* search results

On the org list, the aspect ratio is also different from the logo on the profile (stretching the logo when the image doesn't match the aspect ratio). This seems to be a regression because the ratio is consistent in production. Would it be possible to make sure the images are displayed as squares (1:1 aspect ratio) everywhere?

**Comment by SimonLab** [comment]
explore view:
![image](https://user-images.githubusercontent.com/6057298/32183930-9299103a-bd92-11e7-9d0b-ba2e091ac121.png)
org profile:
![image](https://user-images.githubusercontent.com/6057298/32183938-9f1d640a-bd92-11e7-8ce1-06803ecc9d11.png)

**Comment by Cleop** [comment]
- [ ] Remove padding that makes images not appear as round
- [ ] sort ratios so that images are equal height and width

**Comment by asimonw** [comment]
@Cleop Could you also make sure the alignment and aspect ratio works on the search results page?

**Comment by asimonw** [comment]
@Cleop It looks nicely consistent everywhere now, so that's good.
Could you also turn off the border radius now? (that was part of the request)
Since all logos are now white on a white background, squeezing them into circles is an unnecessary nuisance. Note that people profile pictures should remain circles though.

**Comment by Cleop** [comment]
Apologies, @asimonw I misunderstood and thought you meant to get rid of the circle distortion. I'll make that change 👍
