### ISSUE TITLE
Dynamic comment features not working on recent Firefox and Safari

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1013]
Both the dynamically expanding comment box and hiding/showing of Cancel/Comment buttons are not working on recent Firefox and Safari. I don't see any errors in the console, but it looks like the JavaScript isn't running...

**Comment by SimonLab** [comment]
@asimonw do you know the version of Firefox? It's strange as normally new version support more javascript feature.

**Comment by asimonw** [comment]
@SimonLab I'm on version 57. It's the dev edition, but that should be even more ahead in term of JS features.

**Comment by asimonw** [comment]
@SimonLab I looked at it again, and now it's working fine on both Firefox and Safari.. did something change in the meantime?

**Comment by asimonw** [comment]
Let's assume it was a cache thing 😉
