### ISSUE TITLE
New organisation profile layout

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1024]
To resolve some hierarchy issues with the current organisation profile layout, we'd like to change to a tab based structure.

**Comment by asimonw** [comment]
This is still work in progress, but the screenshot below gives an idea of where the UI is headed:
![screen shot 2017-11-01 at 11 25 01](https://user-images.githubusercontent.com/15235804/32278020-95948408-bf14-11e7-86bc-e65d97630423.png)

The tabs are probably not in their final form, but it's good to note that the tabs on Explore will also change to keep the look and feel of tabs in different views consistent (and ideally, the component reusable).

**Comment by asimonw** [comment]
@iteles If @harrygfox has some time before the end of the week to comment on the use of tabs here and whether he agrees that it's a better solution than the current org layout, that'd be a bonus.

@fannyBkane Will update this issue with more final details before the sprint next week.

**Comment by fannyBkane** [comment]
- change layout to one column
- add a tab component
- move circular economy vision + expertise tags to tab
- move people to tab
- other CSS styles changes as described in #1051 

**Mockups** 
- desktop https://invis.io/F5EBBSADM#/262293723_Org_Profile_1
- mobile tbc

**Comment by Cleop** [comment]
- [ ] Center org name and logo in the top section

**Comment by asimonw** [comment]
@Cleop @fannyBkane Is it intentional that the width is different for every tab?

**Comment by fannyBkane** [comment]
Hey @asimonw it may have been, as the mockup didn't specify the width should be the same for all the tabs.

**Comment by asimonw** [comment]
@fannyBkane Wouldn't we need to do that for the search results page anyway? Not a big problem, but indeed not quite there yet.

**Comment by asimonw** [comment]
@Cleop Something else, the edit buttons for individual challenges are not visible on mobile. They're there, but white on white :)

**Comment by asimonw** [comment]
@Cleop One more thing for me: on some sizes (e.g. iPhone 5), the text in the "About us" tab goes to two lines:
<img width="301" alt="screen shot 2017-11-30 at 15 09 32" src="https://user-images.githubusercontent.com/15235804/33434780-9c321de2-d5e0-11e7-9bf5-d1dbc404bf55.png">
Could you play with the padding a bit to prevent that? (Might not need any padding if you centre horizontally.) You could also separate both words by a non-breaking space, that usually does the trick in navs.

@fannyBkane Anything else from you?

**Comment by fannyBkane** [comment]
@asimonw @Cleop 

On viewports smaller than 1160px long tags in the 'About us' tab start wrapping. Can a breakpoint be added so that the topic tags stack under the main content under that width?

As mentioned earlier, the content in each tab, and also in search and explore could be rethought to make them more consistent and look stronger. 

It would be great also to make the toggle-tabs component consistent across the app (in the top nav, on the org profile, on Explore). 

Does it make sense to create an issue for each of the above?

**Comment by asimonw** [comment]
@fannyBkane I think your first point might get solved by @Cleop 's suggestion to reduce the padding below a certain size. But I also agree that switching more quickly to the mobile view would help a lot (across the app).

I would create two new issues for the other ones indeed! Your second point would make sense to consider after we've done user profiles (which will affect both people and challenges lists).

@fannyBkane If all remaining issues are tracked in other issues, happy to close this one?

**Comment by asimonw** [comment]
Sorry, there was still one thing though. @Cleop Could you still address the issue in https://github.com/emfoundation/ce100-app/issues/1024#issuecomment-348198621 ?

**Comment by fannyBkane** [comment]
@asimonw Aside to above comments, looks good to me! :))

**Comment by asimonw** [comment]
Looks good to me. @fannyBkane with the remaining issue being solved with #1078 happy to close this one?

**Comment by fannyBkane** [comment]
@asimonw yes fine by me to close :)
