### ISSUE TITLE
Unable to save an edited comment on recent Firefox

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1031]
This because of a ReferenceError on line 76 in `ui-enhancement.js`. `event` is not defined, should be `e` but for some reason both Chrome and Safari aren't too bothered by that.

**Comment by SimonLab** [comment]
Thanks for spotting this error, Chrome and Safari might convert automatically event to e maybe, I will try to find out if it's the case

**Comment by asimonw** [comment]
LGTM!
