### ISSUE TITLE
Display user profile logo on new comment

### ISSUE THREAD

**Issue by SimonLab** [emfoundation/ce100-app#1045]
The default logo image is display instead of the logo of the user:

![image](https://user-images.githubusercontent.com/6057298/32434026-d97b192a-c2d4-11e7-8181-5f5e99d29ec5.png)

**Comment by asimonw** [comment]
@SimonLab Nice spot!

**Comment by asimonw** [comment]
@SimonLab That works now, but testing this I now realise that the user's profile is also not used next to the initial comment creation box. It's the default picture even after I've uploaded my own picture.

**Comment by SimonLab** [comment]
@asimonw I think you might need to login again to see your new profile image. I'm storing the url of the profile in Redis like this the value is available on all the pages when a user is authenticated.
Let me know if it works after the logout/login

**Comment by SimonLab** [comment]
On the other pages we are loading on the backend all the information about the logged in user, this is needed for the profile page (I'm not sure I understand for the create comment page, I think this page it's where the profile image didn't work?).
I could have executed another request on the backend to get the all the information about the user but I thought it was a bit too much just to get the url logo profile. Instead I store the url of the logo into the Redis session and make this value available on all endpoints with ```request.credentials``` object. I think it's a bit nicer but if necessary we can still add the other request on the backend

**Comment by asimonw** [comment]
@SimonLab Ok, I think we can leave it as it is for now. People won't log out and back in that often I think, but this is not a very critical issue. I'll reopen another issue to address it if necessary at some point.
