### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by fannyBkane** [emfoundation/ce100-app#1051]
**1. Tabs in explore**
- [x] remove border and drop shadow of tab container
- [x] change colour of font and change hover state

**2. Filter in explore**
- [x] update colours, radius, width and text
- [x] Add new filter icon asset (awaiting asset from @fannyBkane)
<img src="https://user-images.githubusercontent.com/16775804/32492339-d81547d0-c3b1-11e7-97b0-a26b79dd9ca9.png" width=30px />
Currently have a png of:
<img src="https://user-images.githubusercontent.com/16775804/32492362-ee17a848-c3b1-11e7-97d6-8b65a5fa6615.png" width=30px />

- [x] move to align with tabs on desktop

**3. Masthead across all pages, except for forms** 
- [x] change height - 13rem - Org page, people, explore, search results, select tag, add challenge, challenge page
- [x] change H1 font weight and font size across all pages: 'Share new opportunity', Org name in org profile, Challenge name, Select tag - title, 'People', 'Explore', 'Welcome Sally' on landing page, Search term inside search bar on search results page, Search inside search bar, Explore insights / explore challenges

**4. Style cards orgs/challenges/insights/people**
- [x] remove border and drop shadow
- [x] change container width 

**5. Nav**
- [x] change hover states

**6. Tags**
- [x] Grey fill across the app

**7. Check hover states**

- [x] Check hover states across the application are 10% darker e.g. button fills, links. **Found:** 
  - [x] Org Profile page: archived challenges link
  - [x] The 'X' on the add new challenge and on the edit org page and in the 'edit tags' modal:
![image](https://user-images.githubusercontent.com/16775804/32562115-c3c9fdda-c4a5-11e7-849b-c0e3f95a1aab.png)
  - [x] The cancel button on the 'edit tags' modal on edit an org page, currently goes to dark blue, should go 10% darker not that dark.
  - [x] The tag categories under 'edit tags' modal
  - [x] The tag categories on 'select tag' page
  - [x] The '<' back chevron on the 'select tag'  page
  - [x] The grey links at the bottom of the login page
![image](https://user-images.githubusercontent.com/16775804/32562489-bcd72dd0-c4a6-11e7-90e4-63f1b74fded5.png)
  - [x]  Add new resource or insight - 'if not do it **here**' link doesn't have hover state:
![image](https://user-images.githubusercontent.com/16775804/32562881-aec7c1f4-c4a7-11e7-88eb-f21546f98a87.png)

  - [x] Add hover state to list items (on people list or challenges etc) - bg: #E6E6E6, font: #010101
  - [x] Add hover to flags and ellipsis

**8. Mobile check**
- [x] Check the effects of the above bullets on mobile and against the mobile designs.
  - [x] Restyle 'Select Tag' section for mobile
  - [x] Restyle 'Explore' view masthead
**Designs:**
<img src="https://user-images.githubusercontent.com/16775804/32563716-dcc1e8d0-c4a9-11e7-8e13-f8933e935df1.png" width=250px />

  - [x] Restyle 'People' masthead
**Designs:**
<img src="https://user-images.githubusercontent.com/16775804/32563849-36ff9450-c4aa-11e7-9ff0-16378bbd60d3.png" width=250px />

- [x] Add a new challenge page - **NOTE:** ignore the background color of the designs, the bg should be the navy and also ignore the wording, the wording should be the existing wording.
**Designs:**
<img src="https://user-images.githubusercontent.com/16775804/32564420-1cafbeca-c4ac-11e7-97d4-2e9e7bddc4a5.png" width=250px />

To preview: 
Desktop https://invis.io/F5EBBSADM
Mobile: link pending
UI static syle guide: https://projects.invisionapp.com/d/main#/console/12499385/262482389/preview

![screen shot 2017-11-07 at 10 56 58](https://user-images.githubusercontent.com/20577339/32490264-726197b0-c3aa-11e7-9102-c83cfde0a5b5.png)

**Comment by Cleop** [comment]
- [ ] Hover state on list items (change color but not pointer cursor)

**Comment by Cleop** [comment]
@fannyBkane - for the first point, I've removed the shadow/border which leaves us with this:
![image](https://user-images.githubusercontent.com/16775804/32491852-205877e4-c3b0-11e7-8730-69732f130948.png)
However if I then change the font to the same colours on invision (white), you wouldn't be able to see the text as I've not changed the background color yet... I'm guessing perhaps that change is referred to in point 4 - 'Masthead on explore section'? Although that isn't likely to be happen yet.

I can follow your invision design, but for the purposes of estimating it would be good to know whether it's your bullet points I should be estimating for or any extra details illustrated in invision?
![image](https://user-images.githubusercontent.com/16775804/32492048-d58c557c-c3b0-11e7-8865-4a47a71adcf4.png)

**Comment by fannyBkane** [comment]
Hi @Cleop good point, I think both bullets and invision. I hope however that changes are clear enough, otherwise happy to talk through changes in more details.

Useful also to point out that for this specific tabs, the mobile will be styled differently to the desktop, see below:
![screen shot 2017-11-07 at 11 47 43](https://user-images.githubusercontent.com/20577339/32492235-806694c6-c3b1-11e7-87d2-ce4de3d50177.png)

**Comment by fannyBkane** [comment]
@Cleop I was trying to edit the post simultaneously as you 😂 

Here is the link to the static mobile mockups :  sthttps://zpl.io/bW4Prdn

**Comment by fannyBkane** [comment]
Welcome back @Cleop! Thanks, looking ace 😄 

I grouped the feedback into three parts...

**_A couple outstanding bits I noticed:_**
-----------------------------------------

**3. Masthead across all pages, except for forms**
- H1 in the mastheads are not vertically centred on desktop
- < on select tag page and the X on Add a new challenge don't seem to have margin adjusted



**_A few gaps or bits that could be adjusted slightly:_**
-----------------------------------------
**2. Filter in explore**
- Increase the padding left & right slightly

**8. Mobile check**
- keyword in tag filter has equal margin left and right but as a result looks misaligned. Could it be Left aligned instead, bringing it in line with desktop?

**'select tag' list region hover** 
- when clicking a 'mother tag' the children tags are displayed and only the top line has a grey fill background. On mobile, the region is grey on active (or is it focused?) state. It's not really confusing but I am wondering what can be done to make it look more elegant. Will ponder and add a comment later today!


**_Some other bits that feel clunky but as they are a result of oversight from my part they weren't initially scoped... Just putting this in case it's possible to estimate/update:_**
-----------------------------------------
**1. Tabs in explore**
- remove  {background-color: #002c49;} on **.togglebar__item--selected:hover** 

**3. Masthead across all pages, except for forms**
- remove {letter-spacing: 0.75px;} on **.title--dropdown**
- remove .title--filter {letter-spacing: 0.75px;} on **select filter** on mobile 
- remove {font-weight: bold} on **.title--dropdown** 

**5. Nav hover state**
- remove {background-color: #002944;} on **.navbar-top__item--desktop:hover** 

**8. Mobile check**
- tab filters are on a white background - as per the designs / could it be brought in line with desktop?

I hope that makes sense.

**Comment by fannyBkane** [comment]
> when clicking a 'mother tag' the children tags are displayed and only the top line has a grey fill background. On mobile, the region is grey on active (or is it focused?) state. It's not really confusing but I am wondering what can be done to make it look more elegant. Will ponder and add a comment later today! ---- notes: remove grey hover/active state on mobile --- to be dealt with in this issue

Could the tag select screens in Explore be brought in line with those in the forms? The only difference is that bit of padding between the highlight colour and the tags.

**Comment by fannyBkane** [comment]
Hey @cleop looks great! A few things I noticed:

- Could the text in the filter be regular weight instead of bold (as on screenshot here)
![screen shot 2017-11-30 at 12 23 45](https://user-images.githubusercontent.com/20577339/33430693-59fa1c70-d5c9-11e7-9e06-a68a830006f4.png)

- Could the hover state of list items (on people list or challenges etc) background colour be changes to #f2f2f2

- Long tags in the filter still overlap with the tabs on viewport smaller than 800px and larger than 600px (not sure if this is going to be addressed in this issue or in [#1126](https://github.com/emfoundation/ce100-app/issues/1126) ?)

- At the moment it looks like the toggle bar links have different width properties? Could the width of the tabs adapt to the word but the padding left and right be a fixed value?

Desktop 
![Desktop](https://user-images.githubusercontent.com/20577339/33430411-59711c8c-d5c8-11e7-82a2-3fddf2aa0407.png)

Mobile 
![Mobile](https://user-images.githubusercontent.com/20577339/33430413-598a1d90-d5c8-11e7-985c-16a42fc52aef.png)


**Otherwise:**
- I confirm that the wording 'challenge' will not changed to 'opportunity'.
- I confirm that the solution for 'sort by' on the people page works - cheers for that


**I will create an issue for labels on lists that will include:**
- Need to think of solution that will be consistent and work across all applicable pages: explore/people/results/orgs
- Need to clarify which current 'in table' values should be removed when column labels are added e.g. 'shared by' wording on each resource is now replaced.

**Comment by Cleop** [comment]
@fannyBkane - thanks for taking a look and the feedback 😄 

Re: bold text on the select tag, I implemented that because that's how it was in invision:
![image](https://user-images.githubusercontent.com/16775804/33431011-98d7349a-d5ca-11e7-9435-ec010f52d924.png)
Happy to remove if you wish, just thought I should double check first.

You're right that the long tags issue is being solved in #1126 👍 

Thanks for confirming the other points. 

I'll get to work on the changes 💪

**Comment by fannyBkane** [comment]
@Cleop you are right regarding the bold, that was indicated in Invision. The issue is when rendered in the browser at this font-size it is harder to read. I should know better, and will keep note for designing forward. I hope it's ok.

Note: I thought I had pointed it out in another issue this week, but either I haven't or I lost track of it 🤔 :

**Comment by fannyBkane** [comment]
@Cleop looks good to me, @asimonw fine to close the issue :)))
