### ISSUE TITLE
Interactions

### ISSUE THREAD

**Issue by fannyBkane** [emfoundation/ce100-app#1052]
**1. Comment and search fields (see examples)**

**Basic implementation:** Change the bottom border color of the comment box when a user clicks to focus on it. Need @fannyBkane to confirm the exact color to change to.

**Advanced implementation:** add a js animation like the one seen on youtube comments where the color change transitions starting in the middle of the bottom border to reach the tips where it stays as a solid color. @fannyBkane said that this would be the preferred implementation if it were to take approx less than 1/2 a day extra to implement.

- example 1 (Muzli): underline colour changes
![screen shot 2017-11-07 at 11 02 31](https://user-images.githubusercontent.com/20577339/32490601-9c085ea4-c3ab-11e7-9585-acfe28035f4d.png)
![screen shot 2017-11-07 at 11 02 42](https://user-images.githubusercontent.com/20577339/32490609-a1ccf61a-c3ab-11e7-850b-14a8c5700615.png)

- example 2 (YouTube): underline colour changes from te centre outwards
https://www.youtube.com/
![screen shot 2017-11-06 at 15 49 43](https://user-images.githubusercontent.com/20577339/32449682-271dd4e4-c30a-11e7-9b4e-c1f593aef094.png)

- [x] Search bar and bar on results page
- [x] Comments (new and edit) bar

**2. Navbar, make the whole highlighted div area of each link clickable, not just the word** ie. 'explore'. For the following:
- [x] explore
- [x] add
- [x] manifying glass
- [x] ellipsis
- [x] profile

**On the Explore Tabs**
- [x] Orgs
- [x] Challenges
- [x] Insights
@fannyBkane to confirm if there are any other transitions/interactions in the mix at this stage that should be estimated for in this issue.

**Comment by fannyBkane** [comment]
Link to preview specs: https://invis.io/F5EBBSADM#/263025829_Interactive_UI_Styleguide
![interactive ui styleguide](https://user-images.githubusercontent.com/20577339/32606106-e7a94dcc-c54b-11e7-8c36-68ab61cec877.png)

**Comment by Cleop** [comment]
@fannyBkane - assuming you'd like the interactions for the 'edit' a comment text box. What colours would you like the line before and after focus? This is the colour in comparison to the create box currently:
<img src="https://user-images.githubusercontent.com/16775804/33324740-6065f296-d448-11e7-9053-c455d23b8541.png" width=300px />
And when the create comment box is in focus:
<img src="https://user-images.githubusercontent.com/16775804/33324768-700192c8-d448-11e7-9535-cde0ce1376ed.png" width=300px/>

Would you like the edit box to have the same colours as the create box? Or perhaps the same colours as you outlined in the style guide for other form elements? Like this:
<img src="https://user-images.githubusercontent.com/16775804/33324838-a3914ab6-d448-11e7-8a2c-d73a52ec8473.png" width=250px />

**Comment by fannyBkane** [comment]
Hi @Cleop could the edit box have the same colours as the create box?

**Comment by asimonw** [comment]
@SimonLab Wasn't this closed by accident?

**Comment by SimonLab** [comment]
@asimonw yes I just merge a PR linked to this issue and Github automatically close it 😟  I don't know if there is a way to change this on github, our way to do this is to normally referecne issue with "ref:"

**Comment by asimonw** [comment]
Looks good to me overall. Like the effect on the comment box! It's less clear on the search box, but also less necessary I think.

@fannyBkane Let me know if ok to close.

**Comment by fannyBkane** [comment]
@cleop looks great! @asimonw fine to close!
