### ISSUE TITLE
Adding data to flag email on members' flagging behaviours

### ISSUE THREAD

**Issue by iteles** [emfoundation/ce100-app#1054]
As an admin for EMF 
I would like to capture data on flagging of comments 
So that I can answer questions like #1033 

## Acceptance Criteria
Email that is sent to admin email inbox when a comment is flagged (https://github.com/emfoundation/ce100-app/issues/947#issuecomment-336890686) must now contain:
+ [x] Name of the person who flagged the comment
+ [x] Organisation of the person who flagged the comment
+ [x] Name of the person who owns the _challenge_ with a flagged comment
+ [x] Organisation of the person who owns the _challenge_ with a flagged comment

**Comment by iteles** [comment]
Next steps are to investigate how much of this data can be captured in GTM.

**Comment by SimonLab** [comment]
@asimonw the email template has been updated to include the information linked to the comment flagged
