### ISSUE TITLE
Content owners should not be able to create admin users

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1060]
They should also not be able to turn themselves or other users into admin users.

**Comment by asimonw** [comment]
@SimonLab This works thanks. I just realise now though that it's possible for a content owner to turn an admin into another type of user. This would allow someone to (perhaps by accident) remove all admins from the app.

Two solutions in order of preference:
+ Don't show the edit button for admins in the People list when the logged in user is a content owner
+ Don't show the radio buttons to change the user type of an admin when logged in user is a content owner

I prefer the first solution because it offers more security.

**Comment by iteles** [comment]
@asimonw Well remembered, I didn't even think of this!

As this original issue is resolved, shall we open this as a new one and close this one?
I agree, the first option is not only more secure, but also makes more intuitive sense!

**Comment by asimonw** [comment]
@iteles Good plan. Created #1110 for that!
