### ISSUE TITLE
Incomplete UI following #1051

### ISSUE THREAD

**Issue by Cleop** [emfoundation/ce100-app#1061]
#1051 outlined some bulleted UI changes which were illustrated by the designs in invision. Some of these changes went alongside other amendments that weren't included in the bullet points but related to the same features. So that things don't look strange or out of place before the end of the sprint, the following may benefit from being addressed:

- [x] Need to make the search 'go' and magnifying glass icons bigger to match the new h1 font size on both the **search page** and the **search results page**.

**Current:**
![image](https://user-images.githubusercontent.com/16775804/32556944-bb68f9d2-c498-11e7-86ee-4393e12f4dbb.png)
**Design version:**
![image](https://user-images.githubusercontent.com/16775804/32556964-c8605072-c498-11e7-8c04-1e0d1dfa42d1.png)

- [x] **Vertically centre masthead titles** where the min height has now been set. On the following **5 pages** (and any others I may have missed!): people, explore, select tag, create a new challenge, the search results page.

**Current:** 
![image](https://user-images.githubusercontent.com/16775804/32557060-fe00083a-c498-11e7-9c7c-ad50386421fc.png)
**Design version:**
![image](https://user-images.githubusercontent.com/16775804/32557018-e54ca28a-c498-11e7-9196-8c85f54e9f37.png)

- [x] < on select tag page (in line with the logo on the nav) and the X on Add a new challenge, move their margins to be inline with the nav above

**Comment by fannyBkane** [comment]
Hey @Cleop a detail that was never addressed before: the masthead background is a radial gradient in the mockups. I believe you can render it in css. will have a look into it - if I find a satisfying value in css, would it be possible to add it in?

**Comment by Cleop** [comment]
This is the value zeplin gives:
```
 background-image: radial-gradient(circle at 46% 19%, #ffffff, #003253);
}
```
I've not tried it yet but worth a shot!

**Comment by Cleop** [comment]
@fannyBkane - I tried implementing the radial gradient values provided by invision but they don't produce what we see on invision. In my first comment above you can see what it should look like. This is what the code gives me:
![image](https://user-images.githubusercontent.com/16775804/33209884-da54a76e-d10f-11e7-8c9e-43d3deb2c062.png)

**And this is as close as I could get it to your version by playing with the values:**
![image](https://user-images.githubusercontent.com/16775804/33210097-baff58f4-d110-11e7-9739-089bd4ead5d8.png)
radial-gradient(circle at 80% -900%, #ffffff, #003253)

Perhaps you can look into how you generated the values or you could provide me with an image version as the background instead?

**Comment by fannyBkane** [comment]
Hey @Cleop thanks for checking that out. I'd rather not use an image, because the gradient will be off. Let's park this one, until css gradients improve!

**Comment by fannyBkane** [comment]
@cleop just one thing I noticed, I don't know why my machine is displaying a system font inside of the 'Go' button. Apart from that, LGTM! 
![screen shot 2017-11-27 at 10 13 21](https://user-images.githubusercontent.com/20577339/33261827-0c4b4496-d35c-11e7-9eaf-998a5de6b55c.png)

**Comment by asimonw** [comment]
@Cleop The search results page looks a bit off on mobile, especially missing padding below the button
<img width="357" alt="screen shot 2017-11-27 at 13 39 21" src="https://user-images.githubusercontent.com/15235804/33267114-9202e456-d378-11e7-94b8-44bbb6715620.png">

More generally: could the top part (search field and box) take up less vertical space on mobile? @fannyBkane do you agree? I'm also not sure the font (both on desktop and mobile) needs to be this big. Longer queries won't be completely visible in the search field. (Not a strong opinion though)

**Comment by fannyBkane** [comment]
@asimonw hadn't seen the missing padding, @cleop would be great to adjust that, thank you!

Concerning the font-size and vertical space, the initial designs had a smaller search field on the results page, but I asked Cleo to change it to have a bigger input field and text, like how it appears when you open the search box. 

The reason I asked for that change is that it was easier to deal with at the time when designing the masthead system and type scale. At the moment the longer words or strings are hidden, which may not be ideal but it is sometimes seen. Happy to review that now.

![screen shot 2017-11-27 at 15 10 04](https://user-images.githubusercontent.com/20577339/33273454-44f46c68-d385-11e7-9b77-e0edc673e79b.png)

**Comment by asimonw** [comment]
@fannyBkane If the new font-size is for a consistent type scale system, ok with me to review later. I'm a bit less sure about the field and button taking up so much vertical space, but also nothing urgent. One man's opinion ;)

**Comment by fannyBkane** [comment]
@asimonw having less space will not work so well with the bigger type...  I appreciate one does have to scroll, but I suggest we keep it as it is until we decide to use a smaller font 😬

**Comment by asimonw** [comment]
@fannyBkane Fair enough 😄 
@Cleop That leaves just the font type in the Go button and the padding underneath the button on mobile.

**Comment by Cleop** [comment]
I've fixed this one but @asimonw it's not so much the padding underneath the button on mobile but more the fact that iPhone 5 was stacking the button whereas it should have been like all other mobile views on one line like this:

**Comment by fannyBkane** [comment]
Thanks @Cleop Looks good to me :)

@asimonw fine with me to close the issue.
