### ISSUE TITLE
UI Enhancements from Invision Designs

### ISSUE THREAD

**Issue by Cleop** [emfoundation/ce100-app#1062]
**UI Enhancements from Invision:**
- [x] Ensure and check the site for 14px as the body / p text size not 16px
- [x] Make the tag categories not bold (normal) when in the modal
- [x] Consistency check that the text in all buttons (with pill outlines) are bold
- [x] Remove line/border dividing 2 sections on the challenges page
- [x] Change text colour of orgs, insights and people columns under explore tab list and resize fonts to 14px. Either see invision designs or follow: links should be blue/grey and any other text should be black.
- [x] On the adjust set tags page change the colour of the bottom borders, 'search all tags' link - change from maroon and remove the underline. Make the bottom border only cover the same width of the screen as the tags do when open.

**Comment by fannyBkane** [comment]
> Change the background of the challenges pages - check with @fannyBkane before implementing to confirm what she would like.

@Cleop this should have a a radial background with the value as follows:
 background-image: radial-gradient(circle at 46% 19%, #ffffff, #003253);

Thank you!

**Comment by Cleop** [comment]
Other enhancements requested/ picked up by @fannyBkane in #1051 but estimated for separately here:

**1. Tabs in explore**

remove {background-color: #002c49;} on .togglebar__item--selected:hover

**3. Masthead across all pages, except for forms**

remove {letter-spacing: 0.75px;} on .title--dropdown
remove .title--filter {letter-spacing: 0.75px;} on select filter on mobile
remove {font-weight: bold} on .title--dropdown --- on all navbar titles whether hovering or selected or normal

**5. Nav hover state**

remove {background-color: #002944;} on .navbar-top__item--desktop:hover

**8. Mobile check**

tab filters are on a white background - as per the designs / could it be brought in line with desktop?
Extra from call:

-  On the people page make the horizontal padding the same as the other cards ie. 1.5rem (not including the green dots) and also make sure that the people status dots are vertically aligned in the middle.

**Comment by fannyBkane** [comment]
@Cleop @asimonw LGTM :))
