### ISSUE TITLE
DAM API organisations

### ISSUE THREAD

**Issue by SimonLab** [emfoundation/ce100-app#1071]
update organisations plugin:
- [x] Delete references to tag table: https://github.com/postgres-plugin/people/blob/58c5668961cb75e9f2e87e6d5495c3bff882db57/lib/fixtures/create-tables.sql#L28
- [x] Add a type of tag in tags_organisations table as tag and location are now separated. This allow us on the server to know which api request to send:
```
CREATE TABLE IF NOT EXISTS tags_organisations (
 tags_id INTEGER,
 organisations_id INTEGER REFERENCES organisations (id),
 type VARCHAR(100) CHECK (type IN ('tag', 'location'))
);
```

- [x] update GetDetails function of org to not fetch the tags from the tag table: https://github.com/postgres-plugin/people/blob/master/lib/queries/orgs/getDetails.js
- [x] Crate function wrapper to the list of tags from the API
- [x] update the edit view org handler to with the wrapper function

**Comment by SimonLab** [comment]
@asimonw @georgemillard while trying to convert the current tags with the one provided by the API I notice that some tags are not anymore defined (ex: Global Partner). If a tag is not anymore define should we remove it from the organisations (and challenges) that already have this tag?
You can find our current list of tags here:
https://github.com/emfoundation/mock-data/blob/master/tags.json

**Comment by asimonw** [comment]
Thanks for flagging that @SimonLab. @georgemillard shall we we review this and make sure missing ones have been a conscious decision?

**Comment by asimonw** [comment]
Actually, @SimonLab those tags in the link you shared don't correspond at all to the ones that I'm seeing in the app (staging and production). Everything from category 1 was removed a long time ago (and there are other differences too). Are you sure that you're using an up to date version as mock data?

**Comment by georgemillard** [comment]
I will check with Lucy that the source I used for generating tags for the asset manager is up-to-date.

**Comment by SimonLab** [comment]
@asimonw I will check the difference between the mock data and the tags in productions :+1:

**Comment by SimonLab** [comment]
The main steps of the issue have been implemented (update postgres tabes + create functions for API). I've created a more specific issue for the mapping between the current tags and the one from the API: #1105
