### ISSUE TITLE
Limit number of matches returned

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1075]
Currently, there is no limit on the number of returned matches shown on the challenge view.
We could like to limit this to 10 items per section (Organisations, Challenges, Insights), maximum 30 in total.

**Comment by asimonw** [comment]
A more refined enhancement of this is for #1065

**Comment by asimonw** [comment]
@SimonLab The limit works on organisations. I'll assume that it works on the other types as well. Could we deploy this fix separately? (If not easily, what else would be deployed?) Then we can easily see whether it works for insights as well.

**Comment by SimonLab** [comment]
@asimonw Yes this will work with insights and challenges too, this is the code we have on master, we slice (take only the 10 first elements) the arrays of these items:
https://github.com/emfoundation/ce100-app/blob/4f4d83675b555f9246de4d68ff8f5c5cb8505d63/server/handlers/challenges/challenge-view.js#L74-L75

I think we can this feature was the only one added directly to master so I think we can deploy it (after 5?)

**Comment by iteles** [comment]
It was indeed! Is #1109 a blocker for this?

**Comment by SimonLab** [comment]
@iteles I think the ranking might have been changed during the API integration. So I don't think #1109 is a blocker, @asimonw could you confirm that on staging the ranking is correct?

**Comment by asimonw** [comment]
@iteles @SimonLab My test was on staging. See comment in #1109. I think it's ok to deploy this fix tonight. We'll need a bit longer to figure out what the bug is (if there is one).
