### ISSUE TITLE
User profile pictures on the org profile page not aligned to the left

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1077]
When the email in the user details is too long, the profile picture is not positioned next to the user details anymore, but picture and user details are stacked. 
<img width="209" alt="screen shot 2017-11-15 at 11 30 25" src="https://user-images.githubusercontent.com/15235804/32831592-1a833b34-c9f9-11e7-9008-aaf011c09e76.png">
instead of
<img width="205" alt="screen shot 2017-11-15 at 11 36 10" src="https://user-images.githubusercontent.com/15235804/32831638-3a939a0e-c9f9-11e7-86b6-14f066f4dd92.png">

Possible solution:
+ Reduce the padding on the left of the profile picture
+ For emails that are still too long, use text-overflow: ellipses

**Comment by iteles** [comment]
This may no longer be an issues, @asimonw to check.

**Comment by asimonw** [comment]
This is indeed no longer an issue with the org profile redesign!
