### ISSUE TITLE
link comment with comma

### ISSUE THREAD

**Issue by SimonLab** [emfoundation/ce100-app#1079]
on challenges/20
![image](https://user-images.githubusercontent.com/6057298/32832382-288fcca2-c9f3-11e7-88bf-e647a1e55502.png)

The comma at the end of the link should not be part of the link

**Comment by SimonLab** [comment]
We could have a simple check that test if a url ends with a comma and remove it in this case. The only issue with this logic is that query string could also contains comma, ex: ```https://www.google.co.uk/search?q=ellen+macarthur,``` 
I don't think this case will happen often and maybe for a fist version it's ok to just remove the comma instead of spending time trying to find a way to distinguish if a comma is a normal "text comma" or if it belongs to a query string

**Comment by asimonw** [comment]
@SimonLab I think it's ok for now to check for a final comma and remove it from the link. I think the case where the query string ends with a trailing comma won't happen very often.
