### ISSUE TITLE
minimise number of environment variables

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#108]
We should create cookie in tests when needed

**Comment by nelsonic** [comment]
@JMurphyWeb updated the title of this issue to reflect the technical requirement. 
we want to have the _bare minimum_ of environment variables which need to be updated. 👍

**Comment by JMurphyWeb** [comment]
Will implement hapi-auth-jwt and remove env variables

**Comment by JMurphyWeb** [comment]
@nelsonic i think we are as minimised as we can get. Can we close this issue?

**Comment by nelsonic** [comment]
@JMurphyWeb the Google Doc (_which I am treating as my "single source of truth" because it's the only place I can securely store all the DEV .env and copy-paste it locally when I am reviewing/testing a branch_) currently has _two_ extraneous entries: `COOKIE_PASSWORD` and `CODECOV_TOKEN` do we still _need_ them?

**Comment by JMurphyWeb** [comment]
Absolutely. I will check the project for possible extraneousness once the current conflicts are resolved.

**Comment by JMurphyWeb** [comment]
@mk4111 @nelsonic there is now a 

`NODE_ENV=true`

environment variable to be set locally only. I have updated google doc but wanted to make sure you see it.  This may change depending on feedback from Nelson re #126

**Comment by JMurphyWeb** [comment]
I am not sure if we need code_cov token?

Cookie_password can be removed but not high priority. I will issue.

**Comment by JMurphyWeb** [comment]
doc is currently up to date and we have the minimum number of env variables possible.
