### ISSUE TITLE
mapping category and locations tag

### ISSUE THREAD

**Issue by SimonLab** [emfoundation/ce100-app#1085]
For adding tags we are creating a mapping between each tag id and their category:
https://github.com/emfoundation/ce100-app/blob/f59ba5b90da4b14debee07e2dec0582e03952dd4/server/handlers/challenges/edit-view.js#L69-L79

However it can happen that the id of a "normal" tag and the id of a location are the same.
We need to make sure that we are not overwriting this ids

**Comment by asimonw** [comment]
@SimonLab As discussed this morning, we've added a `display_name` property to location entries.
The way to take this into account is outlined here #1086.

We'll need to get this into production before you can adapt your code, of course.

**Comment by SimonLab** [comment]
The mapping has now been implemented. #1086 will be use as main issue for the display_name property of the locations. Closing this issue as it is a technical one and can't really be tested without looking at the code itself
