### ISSUE TITLE
Methods of Function Implementations (Refactoring Redis Functionality?)

### ISSUE THREAD

**Issue by mk4111** [emfoundation/ce100-app#110]
Hi @nelsonic, at current we're sharing the same (if not similar) redis functionality across a number of our [handler functions](https://github.com/emfoundation/ce100-app/blob/7aa2ac73434ce741eb2b89168447a89bf9bae219/server/handlers.js). We've thought of a way that _might_ help improve our code, but were wondering if we could (pretty please) ask for your opinions on it before we implemented it?

We will use the [viewAllUsers function](https://github.com/emfoundation/ce100-app/blob/7aa2ac73434ce741eb2b89168447a89bf9bae219/server/handlers.js#L65) (for its simplicity) as an example to help us explain our ideas - hope that's ok!
#### Right now, our viewAllUsers function is...

```
handlers.viewAllUsers = (request, reply) => {
  const redis = request.redis;
  redis.LRANGE('people', 0, -1, (error, stringifiedUsers) => {
    if (error) console.log(error);
    const allUsers = {allUsers: stringifiedUsers.map(element => JSON.parse(element))};
    reply.view('people/view', allUsers);
  });
};
```

The following are the ways that we are thinking of making the redis.LRANGE function more reusable/chainable.
#### (1) Use a re-usable helper function

```
handlers.viewAllUsers = (request, reply) =>
  getAll('people', request.redis, (error, users) =>
    error ? reply(error) : reply.view('users/view', users));
```

```
function getAll (listName, redis, callback) {
  redis.LRANGE(listName, 0, -1, (error, items) => {
    const all = {[listName]: items.map(element => JSON.parse(element))};
    callback(error, all);
  });
}
```
##### Positives:
- The redis functions would be packaged up for re-use.
- When chaining the functions, we could use a function to execute multiple async functions, where the errors/responses from those async functions could be returned as arrays...?
##### Negatives:
- Not sure if this is much less in terms of characters typed (- might even be more...).
- I'm not sure how we feel about passing in request.redis as an argument... I felt like it might be a little odd because we are in essence passing the helper function, the bulk of the functionality that we wanted to execute...? I know it's useful because it means we're not opening new redis instances every time but still... Please correct me if I am wrong!
- We use the ternary `error ? reply(error) : reply(with-whatever-is-needed);` for pretty much every handlers - this method doesn't really 'solve' that (if that's something that would be good to solve?). To add to this point, we did consider passing in reply() to the helper function, but it then creates the issue where you can't chain the redis-commands (and (for me at least) it felt a little awkward doing so too)... (which might just be because I'm not used to passing reply as an argument and executing it somewhere other than the 'mother' handler function).

If you could please help us out, that would be epic! Thank you @nelsonic ! :)

**Comment by nelsonic** [comment]
@mk4111 this is a _good_ idea/plan. having this kind of re-useable method will be good.
the only thing I would say is: do you _want_ to be replying with a "_raw_" Database Error?
Or do you want to "feed" that error into a user-friendly template: https://github.com/dwyl/hapi-error 😉

**Comment by JMurphyWeb** [comment]
see #114 for error-handling issue

**Comment by mk4111** [comment]
Hi @nelsonic, thank you for your reply! I've just made a [PR](https://github.com/emfoundation/ce100-app/pull/112) with the relevant changes to handlers - would it please be possible to ask you to have a review of this and let me know what you think of it? If you are happy with the changes, I will split the handlers functions out into files! :)

**Comment by SimonLab** [comment]
We have now reusable Postgres plugins (https://github.com/postgres-plugin)! @mk4111 can we close this issue?

**Comment by mk4111** [comment]
Yup!
