### ISSUE TITLE
Ranking of matches doesn't seem to work

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1109]
I tagged 
+ a challenge with 2 tags `a` and `b`
+ an org `X` with 2 tags `a` and `b`
+ an org `Y` with 1 tag `a`

Org `Y` appears above org `X` in the list of matches, even though `Y` has less overlapping tags.

**Comment by SimonLab** [comment]
@asimonw did you test this on staging or on the test app with the API integration?

**Comment by asimonw** [comment]
@SimonLab On staging. I had a test on Challenge 2 prepared, but now the db has already been reset. Attempting to recreate the conditions, but it seems to do what it's supposed to now :/

**Comment by SimonLab** [comment]
I've created a PR to use the specific endpoint to only get matching insights (not all assets) and insights are now sorted by the most tags matched.
I need now to:
- [ ] update the sorting for the challenges
- [ ]  update the sorting for the organisations
