### ISSUE TITLE
Profile pictures which are not square are distorted 

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1112]
Profile pictures are forced into a square even when the uploaded picture is not square. This causes the picture to be distorted.

Two short term options:
+ Very short term: Add some extra text advising to use a square image
+ Medium term: look into a way to do an automatic crop (e.g. largest possible square from the centre of the image). At the same time an overall resize could be performed or better performance.

**Comment by iteles** [comment]
The short-term solution here will be dealt with in Sprint 11, with the medium term to be split out into a separate issue and moved to a future sprint.

**Comment by Cleop** [comment]
@asimonw - would you like the message both on the org profile photo upload location as well as the user profile photo upload location?

**Comment by asimonw** [comment]
@Cleop That's a good idea. Org logos are only uploaded by admins and content owners, but it doesn't hurt to remind them.

Thanks for your suggestion for the text, but could we make it a bit stronger than just a recommendation, like "Please use a square image"?

**Comment by asimonw** [comment]
@Cleop I don't see any change on staging.. maybe not deployed yet?

**Comment by Cleop** [comment]
![image](https://user-images.githubusercontent.com/16775804/33549776-96a8cdd4-d8e3-11e7-8f4e-9445d7db002d.png)
This is what's on staging now... maybe try testing again @asimonw

**Comment by asimonw** [comment]
Sorry @Cleop I still don't see it. Also, the image you're sharing doesn't correspond to either a setting page a primary/secondary user would see, nor an org edit page an admin/content owner would see. So, I'm a bit confused :)

**Comment by asimonw** [comment]
@Cleop I understand now, that what you shared is what you see when adding a new org.
There would thus be two more places where it's required. The user settings page is the most important one.

**Comment by Cleop** [comment]
Thanks @asimonw - I had missed that space and put it in the adding contexts. Thanks for pointing it out 👍

**Comment by asimonw** [comment]
I think we've got them all now 👍
