### ISSUE TITLE
Create test app with production database

### ISSUE THREAD

**Issue by SimonLab** [emfoundation/ce100-app#1117]
To run tests for the integration of the DAM API it might be worth to have a duplicate of the production app. This will allow us to run scripts ( #1105 #1104 ) and make sure that everything is working correctly with the "real" data. Once all the process has been verified on this app we can run it on the production application.

- [x] create an Heroku app with the data loaded from one of the postgres backup of the production app

**Comment by SimonLab** [comment]
The steps to duplicate a database on Heroku are similar to the ones describe here: https://github.com/emfoundation/ce100-app/issues/879#issuecomment-334475698

**Comment by SimonLab** [comment]
@asimonw @georgemillard I'm trying to connect a new Heroku app to the application repository on Github but I think I don't have the correct permissions anymore:
![image](https://user-images.githubusercontent.com/6057298/33168033-5c5d8818-d037-11e7-9ba7-a1d86edd3c38.png)

 Do you know if you change the configuration of the repo?
Could you connect the application? On Heroku the app is called "ce100-dam-api". Let me know if you need more infomration

**Comment by asimonw** [comment]
@SimonLab I don't really see what's missing. I use the same heroku account as you, so it also fails for me. Heroku dashboard has team access to emfoundation, so I'm not sure what else I can do. Any ideas?

**Comment by SimonLab** [comment]
I think it might be on the configuration of Github that we might allow access for Heroku : https://devcenter.heroku.com/articles/github-integration

I will try to find what needs to be changed on Github

**Comment by asimonw** [comment]
In the "Third-party access" part of the organization settings, Heroku is still approved.

**Comment by asimonw** [comment]
@SimonLab Ok I think that you need admin access because it's your account which is used to connect to GitHub. I wonder how this worked before if you've never had Admin access..

I'll have a look at giving you admin access to the repo. We could also use my Github account to connect Heroku, but I'm not sure what other implications this might have. It might break some existing permissions?

**Comment by asimonw** [comment]
@SimonLab I've made you admin for the repo for now. We'll see what we do later.
This fixed the problem. The app is connected now.

**Comment by SimonLab** [comment]
a duplicate of the production app is now ready. The data is inserted with:
```pg_restore -h host -p port -U user -W -d database --no-owner --role=user -v downloaded_backup```
The option ```-W``` force a prompt to let us enter the password for the database

**Comment by asimonw** [comment]
@SimonLab Is there anything to test here? Or just the fact that the app still works properly is a test?

**Comment by SimonLab** [comment]
This step is more a technical step for me to test, however you can see that the app at https://ce100-dam-api.herokuapp.com is now running and is a duplicate of the production app. The next step if for me to tests all the convert data script on this app before running them on production

**Comment by SimonLab** [comment]
The application is now deployed on production. We can reopen this issue if we need to create another duplicate of the production heroku app
