### ISSUE TITLE
Section headers in search results look a bit off

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1121]
The font size of the headers is smaller then that of the text below it. There could be some padding underneath the header text.
<img width="693" alt="screen shot 2017-11-24 at 15 54 04" src="https://user-images.githubusercontent.com/15235804/33215606-c41f7f98-d130-11e7-85de-c5faa178ac4d.png">

@fannyBkane wdyt?

**Comment by fannyBkane** [comment]
@asimonw indeed there could be some padding underneath the header text. The challenge link font-size should be brought in line with the items on the explore>challenge page https://staging-ce100-emf.herokuapp.com/challenges

**Comment by asimonw** [comment]
@Cleop @iteles If estimates work out to have issue #1128 in sprint 11, I'll close this one.

**Comment by asimonw** [comment]
Actually, @Cleop we moved #1128 to sprint 12, because it's better to wait until we have user profiles, so that we can have less items per line for people, which will help to limit the width.

This means, that this issue will stay open, but only includes adapting the padding underneath section headers.
