### ISSUE TITLE
Bring styles of search results in line with Explore pages

### ISSUE THREAD

**Issue by fannyBkane** [emfoundation/ce100-app#1128]
- [x] Could the **content width** be brought in line with other lists (explore>organisations, explore>challenge, explore>insights)
- [x] Also, could the margin be adjusted between `<h1 class="results"> `and corresponding` <div class="results_card">`, to be closer to the mockup
- [x] can `<div class="results_card">` have similar default padding

[Link to Invision](https://projects.invisionapp.com/d/main#/console/12499385/262294096/preview)

![screen shot 2017-11-27 at 12 21 26](https://user-images.githubusercontent.com/20577339/33266426-813ef908-d36d-11e7-878f-601a190d4297.png)

**Comment by iteles** [comment]
Most important portion: Bring widths inline.

**Comment by fannyBkane** [comment]
@Cleop lgtm

@asimonw the font-colour of the text, the hover states aren't in line with the explore section, but that should go into a separate issue as it was not pointed out in this one.

**Comment by asimonw** [comment]
@fannyBkane Ok to follow this up in separate issue
