### ISSUE TITLE
testing environment

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#113]
We need to implement a testing environment so our tests don't interact with a production database.

**Comment by JMurphyWeb** [comment]
look into redis connection and how we can manipulate the room it uses.

**Comment by JMurphyWeb** [comment]
Neither Marie or I have much experience with setting up a dev/testing/production environment.

At the moment things which should depend on the config:
- [ ] Which redis DB we are using

**Comment by nelsonic** [comment]
@JMurphyWeb using environment variables _solves_ this issue. let's pick up tomorrow. 👍

**Comment by JMurphyWeb** [comment]
This issue can be parked for now. I will reopen if we have any questions on environments
