### ISSUE TITLE
Limit locations tags

### ISSUE THREAD

**Issue by SimonLab** [emfoundation/ce100-app#1130]
In the explore section we'll simply limit the location tags to the ones which are actually being used for existing orgs, challenges and insights.

**Comment by SimonLab** [comment]
@asimonw this issue is ready to be tested on ce100-test app

**Comment by asimonw** [comment]
@SimonLab It works well for orgs and challenges, but it doesn't seem to pick up locations attached to Insights. This could also happen.

**Comment by SimonLab** [comment]
@asimonw sorry I might have missed one part of the requirement. Currently the location shown are the one that are already attached to organisations, challenges or insights:
![image](https://user-images.githubusercontent.com/6057298/33481756-c986fa26-d68d-11e7-90b5-a92f60cc2dec.png)

Do you want to filter this list of locations a bit more and only show the ones that are linked only to organisations when the user is on the organisation tab (and same for challenges and insights)?

**Comment by asimonw** [comment]
@SimonLab No, that's totally fine. What I mean is that for example asset0 has locations Egypt and Iran, but they are not appearing in the location selection list.

**Comment by SimonLab** [comment]
@asimonw ready on ce100-test heroku app to be tested

**Comment by asimonw** [comment]
Works now!
