### ISSUE TITLE
On Insights/Resources different contributors should be separated by a middle dot

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1131]
When integrated with the DAM, the author field in Insights/Resources gets populated by possibly several contributors. Currently, the different contributors are separated by an ordinary dot:
<img width="941" alt="screen shot 2017-11-28 at 11 28 34" src="https://user-images.githubusercontent.com/15235804/33315228-5d426ba2-d430-11e7-95a1-9f75a0fa4ef1.png">

Two things:
+ The separator should instead be a middle dot (e.g. `&middot;` or `&bull;`)
+ There should not be a trailing dot at the end, only in between different contributors

**Comment by SimonLab** [comment]
@asimonw ready to be tested on ce100-test
