### ISSUE TITLE
Glitchy look for a few long tags on the Explore filter

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1135]
For a few of the bigger tags, the filter box on Explore goes to two lines, which breaks a few of the layout elements (like the tag selectors no longer lining up with the top of the tab content correctly):
<img width="621" alt="screen shot 2017-11-27 at 16 49 56" src="https://user-images.githubusercontent.com/15235804/33328466-5c5abcec-d45a-11e7-807d-2a731ac7c464.png">

A few options:
+ Display the selected tag as the main title, and keep the text "Select tag" in the filter button, as we were planning to do at some point anyway #1126. Only issue with that is that on mobile, we don't display that title, so we'd need to keep displaying the current tag in the filter button on mobile, but not on desktop, which is not ideal for a responsive solution.
+ We simply make the filter select button wider, maybe adapt the with to the length of the text. Currently, if it works for "Enablers and system conditions," it should be fine. The main hurdle here is that on smaller screen sizes, the tag will overlap more quickly with the tab selectors on its left. A solution for this would be to increase the breakpoint between mobile and desktop to around 850px. This is quite wide for a mobile design, but would look better than the current solution for most views. This could be a first step on the way to #1078.

**Comment by asimonw** [comment]
@fannyBkane If you have any further thoughts on this, please add then here.

**Comment by fannyBkane** [comment]
@Cleop @asimonw lgtm!
