### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#114]
We need a system in place for error handling. 

take a look at hapi-error and read boom docs/tutorial

**Comment by JMurphyWeb** [comment]
Don't know if you have any input other than hapi-error @neslon?

**Comment by nelsonic** [comment]
@JMurphyWeb yes, I tried to make https://github.com/dwyl/hapi-error as _re-useable_ as possible.

**Comment by JMurphyWeb** [comment]
errorFunc in https://github.com/dwyl/hapi-auth-jwt2 is specifically called when there was an error in validating the jwt?

I am struggling to figure out how and if i should use Hoek.assert in our auth.js hapi-auth-jwt2 plugin registration.

Also, at the moment within `validateFunc` we have 2 different 'routes' which lead to the same outcome: `cb(null, false);` which doesn't seem great. Those two:
- check to see whether the user has ever logged in before (ie checking if they activated their account with a password). 
- A users id may also not be recognised by the db (ie they do not have an account.)

**Comment by nelsonic** [comment]
@JMurphyWeb yeah, you should not _need_ an `errorFunc` if you are using `hapi-error` to handle `401` (_invalid JWT_) errors. 

What are you _checking_ for in your `validateFunc` ? 
You're checking that the person is _authorised_ to access the endpoint in the app that they are requesting.The two possible scenarios are:

1. Person has _never_ logged in before and is _verifying_ their account. 

2. Person is just accessing a page that requires a valid JWT. 

Both of these will work fine with the auth code we wrote today. 👍
