### ISSUE TITLE
Update organisation profile

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1149]
Given #1147 the organisation profile will need two modifications.

Challenges tab:
+ [x] The list of challenges will now be an aggregate of challenges shared by people belonging to the organisation
+ [x] Every item in the list will not only show the title of the challenge, but also the name of the person who shared it, this will be a link to their personal profile
+ [x] No add challenge button
+ [x] No link to Archived Challenges needed anymore on this page

People tab:
+ [x] Every item in the list will now be a link to a personal profile where the person is not an admin
+ [x] We will display less information per person (same as in #1151 but no need to display org name)

Further changes:
+ [x] Change font size of header title
+ [x] Align tabs to the left
+ [x] Move the company logo to above the name, not side by side on desktop

**Comment by fannyBkane** [comment]
[Link to Invision - Desktop](https://projects.invisionapp.com/d/main#/console/12767821/267419068/preview)
![screen shot 2017-12-05 at 09 39 05](https://user-images.githubusercontent.com/20577339/33600115-3784e4ce-d9a0-11e7-9fb4-cf7107938d6d.png)

[Link to Invision - Desktop](https://projects.invisionapp.com/d/main#/console/12767821/267419067/preview)
![screen shot 2017-12-05 at 09 41 40](https://user-images.githubusercontent.com/20577339/33600226-886af1d0-d9a0-11e7-9a6f-75461a0838e8.png)

**Comment by Cleop** [comment]
Time estimate subject to changes from #1151 once people list display decided.

**Comment by fannyBkane** [comment]
[Link to Invision - Mobile]([Link to Invision - Mobile](https://projects.invisionapp.com/d/main#/console/12795181/268152498/preview#project_console) shot 2017-12-07 at 12 09 17](https://user-images.githubusercontent.com/20577339/33714610-80dd752a-db47-11e7-8d82-ccd66aa01c56.png)
)
![screen shot 2017-12-07 at 12 09 17](https://user-images.githubusercontent.com/20577339/33714679-b5111892-db47-11e7-9386-e53080ad4797.png)

**Comment by Cleop** [comment]
@fannyBkane - would you like us to include putting the logo above (not next to) the company name in this issue for desktop mode? I noticed it in the designs but not the acceptance criteria.

**Comment by fannyBkane** [comment]
@Cleop yes please.

**Comment by Cleop** [comment]
Is this look ok for where the challenge author should go on mobile?
<img src="https://user-images.githubusercontent.com/16775804/33774004-c5088308-dc31-11e7-8f31-d81f24c3f58c.png" width=350px />

**Comment by Cleop** [comment]
![image](https://user-images.githubusercontent.com/16775804/34100119-5fb76460-e3d9-11e7-9de6-0ffa63325a9b.png)

Should the people's names here be in denim if they are links to their profile pages? Based on our comments in:
https://github.com/emfoundation/ce100-app/issues/1151#issuecomment-352083693

**Comment by asimonw** [comment]
@Cleop Looks pretty good! I do have some small points. Roughly in descending order of priority.

+ On mobile, would it be possible to let the challenge titles span the whole width of the viewport? Currently there is a width set of 50%, which doesn't seem to serve a purpose (anymore?)
<img width="312" alt="screen shot 2017-12-18 at 15 47 24" src="https://user-images.githubusercontent.com/15235804/34111725-d95778e2-e40a-11e7-9f92-bd3bcbe917b6.png">

+ The About us tab is nicely aligned with the tab navigation, could you do the same for the Challenges and People tabs? (see prototype)
+ Would it be possible to increase the size of the email icons in the People tab a bit, to closer resemble the prototype?
+ I think we could just remove the title "Challenges" within the tab, as it's already the selected tab in the tab navigation. This would make it more consistent with the People tab (and might make point 2 more straight forward)
+ A tiny one, but on mobile there are tiny white lines around the phone and email icons
<img width="295" alt="screen shot 2017-12-18 at 15 50 15" src="https://user-images.githubusercontent.com/15235804/34111893-499a8a9a-e40b-11e7-81a3-a553873aa72d.png">

+ Not urgent, but as an admin, I don't see the user type. It might be worth having that in this view as well, so that this list is brought more in line with the People list.

**Comment by Cleop** [comment]
@asimonw - thanks for your feedback, I will set to work on these. The only one which I wanted to double check with you before proceeding is the width of the sections being in line with the tabs. This was something @fannyBkane and I discussed and the reason why we decided on these widths is because although the About Us section may not be the same width as the challenges and people sections, the reason is so that they match the width of the other white space on the Explore tabs (for orgs/challenges and insights). The only reason why About Us isn't the same width as them all is because it has more content and a 2 column structure and so we were concerned that there wouldn't be enough space. I'm happy to broaden these to match the same width but I thought I should mention the context of our discussions behind this. Also, if I do go ahead and make them wider, would you like me to make them wider in Explore view too?

**Comment by asimonw** [comment]
@Cleop If you've had a conversation with Fanny about this and decided the widths based on that, then no need to change them. The reason I flagged it is because the left hand sides don't line up nicely, while they do in the mockups.

But I also notice now that the width of the Explore view tabs is not the same as on the org profile page. I think bringing all of this is in line might be the best way forward, but since that's a bigger decision which should involve Fanny, skip that one in the list ;)

Thanks for flagging it!

**Comment by Cleop** [comment]
@asimonw - The tiny white borders on the icons appear to be part of the svgs, see here when I put a border around the image how you can still see the white?
![image](https://user-images.githubusercontent.com/16775804/34116444-93deafe6-e410-11e7-9ad8-b975cc665026.png)

**Comment by asimonw** [comment]
@Cleop Ah interesting.. Ideally the background of this svgs would be transparent, so that it'd just take the colour of the element behind it. Can you manipulate the svg code directly or is that a bit tricky (given that they were generated by a drawing tool, I assume)? If not, let's leave this as it is for now. It's a tiny issue anyway.

**Comment by asimonw** [comment]
@Cleop Or just removing those white lines of course (just realising that you need to use the email icon on desktop as well with same background, so maybe that's easier). If it takes longer than 15mins don't worry about it.

**Comment by asimonw** [comment]
Thanks @Cleop already looks much better. I do have a few more things.
+ Looking at the mockups again, there are no lines between challenges and people in the list anymore. Did you agree with Fanny to not follow the mockups there? If not I'd remove the lines, as it does look nicer without I think.
+ Sorry to be a pain, but the email icon still looks rather small, easy to miss. See https://projects.invisionapp.com/d/main#/console/12767821/267419067/preview

Also, now that the title "Challenges" is removed from the Challenges tab, there is top padding for challenges, but not for people. I think there should actually be a bit more padding for people and a bit less for challenges, bringing both in line. Could you reduce the top padding for the challenges tab to 2rem and add the same to the people tab? (I'm taking a risk here, playing designer..)

**Comment by asimonw** [comment]
@Cleop I now see that there are still lines for the same lists in Explore, so not sure where Fanny wanted this to go. So ignore the first item in my comment. I'll leave that call to @fannyBkane.

**Comment by Cleop** [comment]
I've reduced the padding on both tabs so they have the same, this shows the spacing when hovered on and when not:
![image](https://user-images.githubusercontent.com/16775804/34250059-9e91fedc-e633-11e7-960f-2a387fa33a19.png)
![image](https://user-images.githubusercontent.com/16775804/34250091-b04c50aa-e633-11e7-8c24-fed361ffd75c.png)

**Comment by fannyBkane** [comment]
@Cleop @asimonw  the container width on the org profile and the org page could be made the same to be consistent across.

**Comment by asimonw** [comment]
@fannyBkane Since we made the call before the break to leave things as they are and there is a rationale for the About us tab to be a bit wider (two columns instead of one), I suggest we close this issue and potentially follow up on consistency tweaks in a later sprint, in order to manage the amount of work for next week. Is that ok?

**Comment by fannyBkane** [comment]
@asimonw that's fine
