### ISSUE TITLE
Update challenge list in Explore

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1150]
- [x] Every item in the list should now also contain a link to the person who shared it.
- [x] The wording of 'shared by' should change to 'at'

**Comment by fannyBkane** [comment]
[Link to Invision - Desktop](https://projects.invisionapp.com/d/main#/console/12767821/267419075/preview)
![screen shot 2017-12-05 at 09 42 53](https://user-images.githubusercontent.com/20577339/33600292-badd41f4-d9a0-11e7-8cf4-e2c7e21d42ac.png)

**Comment by fannyBkane** [comment]
[Link to Invision - Mobile](https://projects.invisionapp.com/d/main#/console/12795181/268152492/comments#project_console)
![screen shot 2017-12-07 at 12 12 37](https://user-images.githubusercontent.com/20577339/33714741-f309976e-db47-11e7-8e5a-bbe3e13186f5.png)

**Comment by asimonw** [comment]
@fannyBkane How should this behave? Link to different things (challenge title, person, org) depending on what people click on like on desktop? At the moment it looks like one big link, suggesting one action for the whole thing (link to challenge I presume).

**Comment by fannyBkane** [comment]
Hey @asimonw It is confusing because when you hover on Invision your cursor always stays the same 😕 

If you click on different items (on the challenge card) on the prototype they will take you to the corresponding page: challenge, user profile or organisation.

**Comment by asimonw** [comment]
@fannyBkane The only issue is that on mobile, you don't have hover states, so it might really all look like the same link. We can go ahead with this and then see how it feels on actual devices?

**Comment by fannyBkane** [comment]
@asimonw good point! let me update it :)

**Comment by Cleop** [comment]
@fannyBkane - so the italics for the creator name is only on mobile, is that right? On desktop it will be the hover state that will differentiate between the two links.
<img src="https://user-images.githubusercontent.com/16775804/33831936-f4131e28-de71-11e7-97fc-17dd4ee7f507.png" width=150px />

**Comment by fannyBkane** [comment]
@Cleop that is right!

**Comment by Cleop** [comment]
Still to do:
--- Change 'shared by' to saying 'at'
--- Remove 'shared by Apple' on user profile

**Comment by asimonw** [comment]
@Cleop A similar issue as one of the remarks I just made in #1149 

The title of the challenge title could span more of the viewport
<img width="260" alt="screen shot 2017-12-18 at 16 05 32" src="https://user-images.githubusercontent.com/15235804/34112697-af831cb2-e40d-11e7-9cc2-8e67d1f8de7c.png">

I appreciate that you need to leave some space for the edit button, but
+ First of all, could the padding around the whole list be decreased significantly. This can be much more like the challenge list on the org profile.
+ Could the title span more of the container, like my remark in #1149 

The first point actually applies to all tabs in explore. There is really no need for so much padding around the lists on mobile. This will create much more space for the content. (see prototype)
