### ISSUE TITLE
Demo flow Sprint 11

### ISSUE THREAD

**Issue by iteles** [emfoundation/ce100-app#1154]
@Cleop As discussed, could you please add in your proposed demo flow for all the UI work you have been doing? No one knows it like you do!

We'll then need to fill this in with #1112, #1101, #1065, #1110, #892,  #1106

**Comment by Cleop** [comment]
**- Org profile layout**
- Tab based structure
- page layouts inline with other pages across the site
**- Interactions -**
- Challenge page - show interaction on comments box, then matching UI - see more/less, new section titles, new colours, shows up to 10, starts with 4, won't show if 0 values.
- Search page - show interaction on search box, search box also been made bigger, font made consistent
- Explore - Make filter fit all tags, new filter colour scheme, all headings now clickable everywhere, removed the shadow from hover state (and in main nav)
**- Consistency throughout -**
- body text now 14px, checked hover states, flat design removing drop shadows, removing bold, masthead consistent height across all pages now, h1 font weight/height, padding consistency

**Comment by iteles** [comment]
+ Set up challenge with lots of matches

Final demo flow:

- Log in as an admin

**Org profile layout**
- Tab based structure
- page layouts inline with other pages across the site

**Consistency throughout**
- body text now 14px, checked hover states, flat design removing drop shadows, removing bold, masthead consistent height across all pages now, h1 font weight/height, padding consistency

**Explore page**
+ Show removed shadows on hover
+ Clickable headings
+ Select tag has changed
  + Largest of labels now fits well, both on mobile and iPad

**Challenge page**
+ Create a comment and show interaction - on edit too
+  Go to challenge 9 to show see more/less. show interaction on comments box, then matching UI - see more/less, new section titles, new colours, shows up to 10, starts with 4, won't show if 0 values

**Search page**
+ Show interaction on search box - search for `a`
  + Note no bug ;) #1106
+ Search box also been made bigger
+ Font made consistent


**Square profile photo message** #1112 
- Click 'Add' and 'user' to show new message



Notes:
+ Masthead on organisation page is taller than in other views
+ Change placement of text for adding a new organisation
+ Add photo text on

**Comment by iteles** [comment]
Completed yesterday 👍
