### ISSUE TITLE
Name of person who created a comment should link to user profile

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1162]
Now that we'll have user profiles, the name of the commenter can be a link to the person's profile.

This can only work for primary and secondary users, because internal roles (admin, content owner, view only) won't have a profile page.

This won't affect comments by internal users, but could we change the org displayed above their comments from "EMF" to "Ellen MacArthur Foundation"?

**Comment by asimonw** [comment]
@Cleop I don't see the change from "EMF" to "Ellen MacArthur Foundation" when an internal/backend user comments. I just commented as Admin and get this:
<img width="616" alt="screen shot 2017-12-18 at 16 17 03" src="https://user-images.githubusercontent.com/15235804/34113165-19df90ee-e40f-11e7-9432-f5ee0493254d.png">

**Comment by SimonLab** [comment]
@asimonw sorry we spotted that this morning, I think @Cleop is going to create a PR to fix this.

**Comment by asimonw** [comment]
@SimonLab That's why I asked @Cleop because I noticed the commit, but I guess it's not yet merged in 👍

**Comment by Cleop** [comment]
@asimonw - yes that's spot on. Will be merged shortly...
