### ISSUE TITLE
Content owner and view only users should not be visible to primary and secondary users

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1164]
Currently, in the People list, admins are correctly hidden from primary and secondary users, but content owners and view only users are not. This is incorrect.

Admins, content owners and view only users should be regarded as "back-end" users, not visible to other members of the platform. There are some other inconsistencies at the moment, but this issue is only about the behaviour of the People list.

**More precisely**:
+ Primary and secondary users can only see primary and secondary users
+ Admins, content owners and view only users can see all user types
+ Subtlety: Only admins can edit other admins, so even though content owners and view only users can see admins in the list, they won't see the edit button and will get an authorisation issue when navigating directly to the admin's edit page

**Comment by Cleop** [comment]
Initial implementation done using handlebars helper, could later be refactored by editing the plugin query once the plugins are all aligned with master.

**Comment by asimonw** [comment]
@Cleop I've made this more explicit in the top comment. Does that clarify everything?

Side note: there are no "superadmins," that's what we simply call admins these days 😉

**Comment by Cleop** [comment]
Note to self: now need to remove the except for admin's part here on the plugin:
![image](https://user-images.githubusercontent.com/16775804/33775926-c91d1a5c-dc37-11e7-8282-cf4697904f1b.png)

**Comment by SimonLab** [comment]
@Cleop I've now updated the plugin to not filter the list of user on the plugin itself but let the application do it depending on the type of users logged in: https://github.com/postgres-plugin/people/pull/83

I've also updated your PR linked to this issue to make sure that the "frontend" users (primary and secondary) can't see inactive users

**Comment by asimonw** [comment]
@Cleop @SimonLab Something implicit in the requirements was that content owners should still be able to edit users. Only for admins, they shouldn't see the edit button. Currently, they can't edit any users anymore. This used to work fine (there's a previous issue to remove the edit buttons only for admin users, which worked well at some point). 

The problem is also occurring in production, so this regression must have happened in the previous sprint and wasn't caught by tests. I've turned a few people in production back into admins to mitigate this temporarily.

**Comment by asimonw** [comment]
@SimonLab There still a few things missing which used to be there for content owners:
+ Content owners should also see the user type and the status dots on the left for users of all users
+ Content owners should be able to change user type in user settings (remember that they shouldn't be able to make any user an admin)

The second one is not strictly speaking on the people list, but related to permissions.
