### ISSUE TITLE
Content owners and secondary users should see matches

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1173]
Currently, only admins and primary users can see matches. The intention was for a broader group to see matches. (I wonder if this changed during the update of the permission model?)

In order to fix this and simplify matters going forward, we've decided that everyone should now be able to see matches on challenges.

This means that all roles can see the matches of the challenges independent of which org the user or the challenge is linked to.

**Comment by SimonLab** [comment]
linked to : https://github.com/emfoundation/ce100-app/issues/378
![image](https://user-images.githubusercontent.com/6057298/33942077-bb60c7dc-e00c-11e7-9755-3ae0c3b0fce2.png)

@asimonw I'll remove all the permissions restrictions for the suggested matches 👍

**Comment by asimonw** [comment]
@SimonLab I think that'll be easier to maintain and the business seems to be happy with that. 

It's slightly confusing that we refer to admins and content owners, while in the code you seem to refer to superadmins and admins.

Is it correct to conclude that there is a mapping?
+ admin in UI <-> superadmin in code
+ content owner in UI <-> admin in code

Wouldn't it be less confusing to change the naming in the code to match UI conventions?
