### ISSUE TITLE
Navigation bar - UI enhancements

### ISSUE THREAD

**Issue by Cleop** [emfoundation/ce100-app#1178]
#1152 is a large issue and for the sake of more accurately prioritising it amongst the sprint, these UI amendments will be separated out into this issue to distinguish them from the raw practical changes. The following changes are desired:

**MOBILE VIEW**
- [x] Replace the ellipsis with a horizontal ellipsis (new asset required)
- [x] The dividing line between Settings and logout on the full page mobile menu
<img src="https://user-images.githubusercontent.com/16775804/34107174-1f4b3874-e3f3-11e7-91d0-88eee939e160.png" width=200px />

- [x] Restyling the dropdown menus on desktop to be white with blue text, left align the text, giving them round edges and a different border colour.
<img src="https://user-images.githubusercontent.com/16775804/34101206-dd84da3c-e3dc-11e7-98ea-11b4644bd1ff.png" width=150px />

~- [ ] Insert the user's name for the full navy menu (using the plugin - backend prep step)~
~- [ ] Putting the user's name on the full page menu on mobile when it's open and moving the profile photo to the left~
<img src="https://user-images.githubusercontent.com/16775804/34098494-7b187de8-e3d4-11e7-8c17-6378db144269.png" width=300px />

**Comment by Cleop** [comment]
@fannyBkane - please could you provide the horizontal ellipsis asset for this one?

**Comment by fannyBkane** [comment]
@Cleop sent by email.

**Comment by asimonw** [comment]
@Cleop Could you clarify item number 2 in your list? Or is that part of (or prep for) item number 4? I think item number 4 is the least high priority in this list as it's different behaviour from how it works on desktop and can be regarded as an additional feature. (Also, moving the icon from right to left might be a bit confusing without an animation, hard to tell without some testing.)

**Comment by Cleop** [comment]
@asimonw - according to the designs I'm only replacing the top ellipsis with a horizontal one, I just wanted to check on the grounds on consistency that you're happy with the ellipsis still being vertical for comments on challenges?
<img src="https://user-images.githubusercontent.com/16775804/34106595-b1788a9c-e3f0-11e7-86a9-1ef7d425a7a3.png" width=350px />

![image](https://user-images.githubusercontent.com/16775804/34106586-aae61834-e3f0-11e7-95c6-a28f434ceadb.png)

**Comment by asimonw** [comment]
@Cleop Thanks for checking, but please keep the ellipsis vertical as they are now for comments.

And it's indeed fine that the dropdown styling is different on desktop and mobile, thanks.

**Comment by iteles** [comment]
Agreed with @asimonw That we would split these last 2 items into a separate issue.
