### ISSUE TITLE
Update challenge view

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1191]
Currently, underneath the challenge title it says "Shared by <org name>". Could this be updated to "Shared by <creator name> at <org name>", where the creator name links to the user profile and the org name links to the org profile?
+ [x] Add 'at' 
+ [x] Add link to user's profile
+ [x] Only make the link words go darker on hover
+ [x] Add user's name (amend query from the plugin)
+ [x] Amend the query so that prim/secondary users can see the edit icon on archived challenges (PR open on challenges plugin) - NEW
+ [x] Amend the query so that when a challenge is either archived/unarchived that you get access to the creator's id so that you can be redirected to their profile - the app's code then needs updating once this PR has been sorted. - NEW
+ [x] Enable secondary users the rights to be able to archive their own challenges - NEW see #1226 
+ [x] The My org link should no longer be highlighted for any challenge views
<img width="1094" alt="screen shot 2017-12-19 at 15 35 28" src="https://user-images.githubusercontent.com/15235804/34161962-79372fe8-e4d2-11e7-80d9-538c50b0a725.png">

**Comment by asimonw** [comment]
Currently, the "Shared by" also changes colour when hovered. This shouldn't happen because it's not a link.

**Comment by asimonw** [comment]
@iteles I added another related issue to the top comment. Hope that's ok.

**Comment by Cleop** [comment]
@asimonw - also the 'back' button currently takes you back to the org page, would you like this to take you back to a user's profile page?

**Comment by asimonw** [comment]
@Cleop Good point, but could this actually depend on where you come from?

Currently, if you come from `/challenges` is takes you back to `/challenges`, if you come from the org challenges tab it takes you back there, could we add the case that when you come from the person's profile it takes you back there?

It might be easier to keep track of that in a query string or something (maybe for later).
