### ISSUE TITLE
The challenge list in Explore is sorted backward

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1192]
This is a regression because it used to be correctly sorted, from most recent to oldest. At the moment, the most recent challenge gets added to the end of the list, which is incorrect.

The ordering is correct on the org profile list, so this bug is only about the Explore view.

**Comment by SimonLab** [comment]
The challenges are now sorted via the query in the plugin ```ORDER BY chal_date DESC, chal_title ASC```:
https://github.com/postgres-plugin/challenges/blob/28556d17d67fa3f1989b14cd9389b02d436ebae8/lib/queries/getByTagsAndLocations.js#L60
