### ISSUE TITLE
Vertical Alignment on explore tabs is off

### ISSUE THREAD

**Issue by Cleop** [emfoundation/ce100-app#1195]
<img src="https://user-images.githubusercontent.com/16775804/34118893-25aee7fe-e418-11e7-90c9-8533ee780dea.png" width=350px />

- Insights is too high

- Challenges needs mb0 adding

- The org logos have too much top margin

Need to also check tabs on org page for vertical alignment and people's profiles

**Comment by fannyBkane** [comment]
@Cleop @asimonw The desktop view looks good to me.  There is an overlap of the tabs, as well as an extra padding below the blue underline on viewports under 1030px wide. 

![screen shot 2018-01-03 at 11 16 53](https://user-images.githubusercontent.com/20577339/34518641-214247a8-f078-11e7-9417-ee30c81da8d8.png)

**Comment by asimonw** [comment]
We should maybe incorporate this into #1078. I'll leave this open for now and prioritise when I've gone through the whole list.

**Comment by asimonw** [comment]
I added @fannyBkane 's comment to #1078 and closing this one.
