### ISSUE TITLE
Ensure Intercom doesn't cover 'more' menu

### ISSUE THREAD

**Issue by iteles** [emfoundation/ce100-app#1199]
As a user of the application
I would like to be able to click on the menu items in the More menu which are currently covered by the Intercom icon
So I can use these options.

@Cleop You suggested a pragmatic solution, @asimonw suggested: Adding padding to bottom of the More menu so that the menu items sit above the intercom icon.

Which one are we going to go with?

![screen shot 2017-12-19 at 10 29 32](https://user-images.githubusercontent.com/4185328/34162761-bcb84c62-e4cc-11e7-8c5a-ff7238ca8f73.png)

**Comment by asimonw** [comment]
@iteles @Cleop We discussed something like this:
<img width="462" alt="screen shot 2017-12-19 at 16 02 50" src="https://user-images.githubusercontent.com/15235804/34163111-234ae8dc-e4d6-11e7-8b1a-29b9618c5278.png">
I'm happy with that solution. Basically just adding some padding-bottom to the containing div.

Could you also lowercase the 'u' in "Up" and put a non-breaking space in between "Contact" and "us"?

**Comment by fannyBkane** [comment]
@SimonLab @asimonw Works for me on the Chrome inspector tool, but not working on iphone 5

![img_0789](https://user-images.githubusercontent.com/20577339/34518274-a0e7d40c-f076-11e7-8637-b782ea617e2c.PNG)

**Comment by asimonw** [comment]
@Cleop @SimonLab It also doesn't seem to be working for me when logged in as an admin (also not in the dev tools). Could it be that this was only implemented for primary/secondary users?
