### ISSUE TITLE
Challenge card creation

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#12]
As a primary user, I can add any number of challenge cards containing a title, description and set of tags to my profile, so that I can share all my challenges with the community and I’m not limited on how many challenges I can share.

Should "description" be part of the MVP?
Limit the number of tags allowed to be selected?

**Comment by LucyJW** [comment]
I think description is important for making useful matches as tags and title alone can be a bit limited for users to describe the nature of their challenge. Reviewing the  challenge description is possibly a key action after receiving a notification of a potential match.

**Comment by asimonw** [comment]
Question: should we make tags mandatory? I.e. should every card have at least one tag?

**Comment by mk4111** [comment]
tasks to add/remove and view tags are covered in #61 and #105.

The _remaining_ challenge card is composed of 
- [ ] input fields for the *title* and *description*
