### ISSUE TITLE
create new user should check that email doesn't exist

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#120]
At the moment no check is in place.

If the email is already registered, we should notify the user.

**Comment by mk4111** [comment]
We have a new issue and PR for this https://github.com/emfoundation/ce100-app/issues/475 and https://github.com/emfoundation/ce100-app/pull/499 respectively, so I think this is fine to close.

@JMurphyWeb could you please check and confirm that this is ok? Thank you! <3
