### ISSUE TITLE
Add in 'Add Challenge' button on mobile

### ISSUE THREAD

**Issue by iteles** [emfoundation/ce100-app#1200]
As a member 
I would like to have a button to allow me to add challenges
So that I can add new challenges from an obvious place in the page

### Acceptance Criteria
+ [x] 'Add Challenge' button appears between list of challenges and the Archived challenges banner

<img width="230" alt="after 1128 before spacing" src="https://user-images.githubusercontent.com/4185328/34162964-58c9ade4-e4cd-11e7-904c-35dcbdbefa95.png">

**Comment by fannyBkane** [comment]
@Cleop @asimonw LGTM
