### ISSUE TITLE
Spacing between name and role in people profiles

### ISSUE THREAD

**Issue by iteles** [emfoundation/ce100-app#1201]
Increase the spacing between name and role in people profiles.

![after 1128](https://user-images.githubusercontent.com/4185328/34163405-8b104028-e4ce-11e7-956d-dd458decdd76.png)

**Comment by Cleop** [comment]
This is what I've done, I think the difficulty is that Sally's name hangs lower than someone like Ben's. I've tried to do the spacing on the basis of someone like Ben but let me know what you think:

<img src="https://user-images.githubusercontent.com/16775804/34202183-e6a996aa-e56e-11e7-9155-62e7a4acd4e2.png" width=250px />
<img src="https://user-images.githubusercontent.com/16775804/34202207-f9403436-e56e-11e7-94ba-49e319b75815.png" width=250px />

**Comment by asimonw** [comment]
@Cleop As this is a minor issue, I don't think you need to spend more time on it if there are other issues that can still benefit from your attention today.

**Comment by fannyBkane** [comment]
@Cleop to increase the spacing between name and role in people profiles, without making changes to the height of the container, would it be possible to make the person's name smaller?

**Comment by asimonw** [comment]
@fannyBkane That would make this header font size smaller than the one on the org profile. Are you happy with that?

**Comment by fannyBkane** [comment]
@asimonw I know, and I suggest we try that as a solution.

**Comment by Cleop** [comment]
How's this?
![image](https://user-images.githubusercontent.com/16775804/34725819-02b365ac-f54a-11e7-9fda-167e99a36199.png)
![image](https://user-images.githubusercontent.com/16775804/34725837-116206f8-f54a-11e7-9d94-0af79aecc99a.png)

**Comment by asimonw** [comment]
@Cleop I'm happy with this. @fannyBkane you too?

The feel of it might change a bit after new colours have been applied, so we could raise another issue if there's still an issue then and close this one.
