### ISSUE TITLE
Challenges of disabled organisations/people still visible to external users in Explore

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1219]
Challenges shared by users which are inactive should not be shown to primary and secondary users. Since users linked to a disabled org are made inactive automatically, this should imply the same challenges from all users of a disabled org. This means that for primary and secondary users we should:
- [x] remove challenges of inactive people in Explore
- [x] remove challenges of inactive people on the challenges tab of the org profile
- [x] deny access to the challenge view of challenges shared by inactive people
- [x] remove challenges of inactive people in the search results

The challenges also appear on the people profile, but because the user is inactive, primary and secondary users should not have access to that view anyway.

---

Current mitigation: archive all challenges of disabled org.

A problem will occur when we want to deactivate a user who has shared challenges. If at that point, the user and the organisation agree that they want to keep the challenge, we should build in a way to transfer the ownership of the challenge (through the UI).

**Comment by Cleop** [comment]
@asimonw - you suggested:

> Current mitigation: archive all challenges of disabled org.

However I think this may be a more complicated way of achieving your goal. If we were to archive all of the challenges of an inactive org, would that not make it difficult if you were then to reactivate the organisation? In that situation how could we remember the archived/unarchived statuses of the orgs before we applied the blanket archiving?

Would you be happy for us to simply create a query that filters the list of challenges and removes any with an org_id that corresponds to an inactive org id for primary and secondary users whilst leaving things as they currently are for admins so they can still see them?

**Comment by asimonw** [comment]
@Cleop Don't worry about my mitigation. This is only until this issue is fixed and was only necessary for one challenge. I mentioned it to give some context (maybe confusingly so).

So yes, this issue is about filtering the list of challenges so that only challenges of active users are shown to primary and secondary users. I would only check the associated user (as challenges are now owned by users). Users linked to an inactive org would be inactive themselves anyway as well.

**Comment by asimonw** [comment]
@Cleop I updated the top comment to put things a bit more straight forwardly. The important information for this issue is above the horizontal line. Hope it helps.

**Comment by SimonLab** [comment]
When an organisation is deactivated, all the users linked to this organisation become also inactive. This is done on Postgres with `trigger`: https://www.postgresql.org/docs/9.1/static/sql-createtrigger.html

The trigger is only fired when the organistaion become inactive (not when the organisation become active):
https://github.com/postgres-plugin/people/blob/c17d6dbcb5a1ec38043cce86805b8f6e17a29935/lib/fixtures/set-triggers.sql#L23

The trigger definition can be found here:
https://github.com/postgres-plugin/people/blob/master/lib/fixtures/set-triggers.sql

**Comment by asimonw** [comment]
@SimonLab The checked-off items all work. But I forgot one in the list! A challenge belonging to an inactive user still shows up in Search. I've added that one to the top comment. Apologies for missing that in the original criteria.
