### ISSUE TITLE
New branding | UI changes part 2

### ISSUE THREAD

**Issue by fannyBkane** [emfoundation/ce100-app#1230]
## Login page
- [x] Change input fields style
- [x] Change input fields layout
- [x] Change sub header font-family, size and colour
- [x] Change sub header copy
- [x] style links at the bottom 
- [x] Add new copy of links at the bottom
- [x] Make mobile changes
- [x] Check and make change on the password reset page to echo above changes
- [x] Same for the activation page

## Landing
- [x] Change background to Blue-purple gradient
- [x] Change buttons colour to Pink
- [ ] Remove background of landing cards
- [ ] **Desktop only** Change alignment of landing card 

## User profile
- [ ] Change masthead colour to Blue/purple gradient
- [ ] Change H1 to white
- [ ] Change email and call icons
- [ ] Change email and phone number text to white
- [ ] Change primary label font-colour and background
- [ ] Add solid border to profile photo
- [ ] Change fallback picture

## Search page
- [x] Change background colour to Blue/purple gradient - translucent bg an issue on mobile user photo menu and also search on desktop but not on search on mobile - spot the difference
- [x] Change 'Go' button colour to Pink

## Search result
- [x] Change masthead colour to Blue/purple gradient
- [x] Change 'Go' button colour to Pink

## Forms
- [ ] Change H1 colour to blue and background colour of masthead to white
- [ ] Change the colour of the 'X' buttons so they're no longer white
- [ ] Note: forms fields will reviewed in a later sprint

**Comment by Cleop** [comment]
- Capitalise Login to be LOGIN
- Add a no entry symbol next to filter not available on people tab

**Comment by asimonw** [comment]
@Cleop If there's still any time, it might be worth playing around with this to get rid of the autofill styling on the form fields in Chrome: https://stackoverflow.com/questions/2781549/removing-input-background-colour-for-chrome-autocomplete (the obvious choice, transparent, doesn't seem to work). If not, we can keep it in a separate issue for later.

**Comment by Cleop** [comment]
@fannyBkane @asimonw I've just made a PR for the first stage of 'please-test' on this issue. It's for the login page. I have not yet however made the changes for the forgotten password/ activate account pages to do with login so please don't look at those.

So once this PR has built and been merged and the please-test label is on then that's what to expect.

**Comment by fannyBkane** [comment]
> ## Login page
>  - [ ] style links at the bottom

Can we change the links back to white on desktop like shown here:
![screen shot 2018-01-11 at 15 48 35](https://user-images.githubusercontent.com/20577339/34833417-3d9901d8-f6e7-11e7-9d88-49300b33540b.png)

**Comment by fannyBkane** [comment]
@Cleop 
> ## Landing
> - [ ] Change buttons colour to Pink


The buttons aren't Pink at the moment

**Comment by Cleop** [comment]
Cool, just keeping the colour contrast on mobile?
![image](https://user-images.githubusercontent.com/16775804/34833563-a535b278-f6e7-11e7-82b8-b32b371a84bd.png)


--- Sorry the pink buttons are in a PR that is not merge yet

**Comment by asimonw** [comment]
@Cleop I know that you'll still add a colour for the from headers (now invisible), but don't forget to also provide a colour for the close button (now also white on white). @fannyBkane did you specify a colour for that? They seem to be missing from the mockups.

**Comment by Cleop** [comment]
@asimonw - which form headers are you referring to? For today I think the form headers will be staying lavender and therefore the 'X' buttons will still be visible if that's what you mean:
![image](https://user-images.githubusercontent.com/16775804/34835473-d4be41a4-f6ec-11e7-9bc3-42d1d90b4a0a.png)

As we suggested around 2pm, I'm now not working on anything new but instead working on making sure any changes I have already made do not make anything else look broken or wrong.

**Comment by asimonw** [comment]
@Cleop Oh I thought you had decided in the end to do it anyway. I was talking about the challenge edit view. This one needs the lavender background then. I'll let you know if I spot more.

**Comment by asimonw** [comment]
@Cleop @iteles I've reviewed this with @fannyBkane and we're happy to stop here with this issue for the Monday launch. It's in a stable state now and we'll pick up the missing bits in future sprints 👍 

I'll extract the remaining checkboxes into a new issue and close this one, if you're happy with that.

**Comment by iteles** [comment]
Sounds like a plan @asimonw, thanks.

**Comment by asimonw** [comment]
@fannyBkane New issue #1251 created to follow up on remaining items. Hope I captured all of it.

Closing this one.
