### ISSUE TITLE
Permissions access for inactive people profile page

### ISSUE THREAD

**Issue by SimonLab** [emfoundation/ce100-app#1233]
Only backend user should be able to access the people profile view of inactive users. Frontend user should be redirected to a 403 page when trying to access an inactive user profile page

**Comment by SimonLab** [comment]
@asimonw can a content owner access the profile page of an inactive user or only admin have this right?

**Comment by asimonw** [comment]
@SimonLab Content owners should also have this access. They can edit and create users, so this is part of that "user management".

The main part where content owners and admins differ is the challenges. For other aspects of user management, they are pretty much the same (apart from the fact that content owners cannot create or edit admins).
