### ISSUE TITLE
Content owners can no longer see inactive orgs, they can also no longer see status dots

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1236]
Content owners should have exactly the same access as admins for orgs (remember they used to be the admins! None of the old rights of used-to-be-admins should disappear.). This means that they should be able to see inactive orgs, see status dots, have access to inactive orgs and see edit buttons for them.

**Comment by SimonLab** [comment]
@asimonw I've created a PR for this issue and I've started to add some documentation around the permissions. I'm not sure about the permissions for the view-only role linked to the inactive organisation, could you check this Readme to see if there are any mistakes, thanks: 
https://github.com/emfoundation/ce100-app/pull/1238/files#diff-c7e0d06875ebafff2049a85784d68ba0

**Comment by asimonw** [comment]
@SimonLab That's broadly correct. The only mistake I can see is that primary users cannot add their own organisation, only edit it.
