### ISSUE TITLE
Inactive users get activated again when disabling the org they belong to

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1244]
This is a funny one. To reproduce:
+ Disable a user belonging to an active org
+ Check that the user does not appear in the people list anymore on the org profile
+ Now disable the org
+ The active users of the org got disabled (this is good!)
+ But the inactive user(s) got activated again!
+ Also note that they do appear in the people list in the org, but in their settings they are actually not linked to any org (I assume that the user id is still in the org model, but the org id is no longer in the user model --> they are out of sync)

**What should happen**: Inactive users should stay inactive.

Side note: re-activating the org should not re-activate the people who used to be part of that org (this already works as expected).

**Comment by SimonLab** [comment]
The work to fix this issue is on the people plugin:
The trigger when an organisation become inactive should be:
```
$BODY$
  BEGIN
    UPDATE people
    SET active = false
    WHERE org_id = OLD.id;

    RETURN NEW;
  END;
$BODY$
```
where active is set to false instead of negating the value
