### ISSUE TITLE
Travis Failing

### ISSUE THREAD

**Issue by mk4111** [emfoundation/ce100-app#125]
[Travis](https://travis-ci.org/emfoundation/ce100-app/builds/159271554) is failing at trying to access the /people/add route (which _does_ exist in [routes.js](https://github.com/emfoundation/ce100-app/blob/master/server/routes.js#L17))

On localhost, a different error message is being received:

![screenshot from 2016-09-12 11 33 42](https://cloud.githubusercontent.com/assets/13470325/18432956/dc27b4f0-78dc-11e6-9e61-7e042f4ec4c8.png)

**Comment by mk4111** [comment]
@nelsonic could you please help us debug this issue please?

**Comment by nelsonic** [comment]
This error message points to this line:
[`sendemail/lib/index.js#L16`](https://github.com/dwyl/sendemail/blob/471087f95dd1ac88186d4af21a3829546ec37fc9/lib/index.js#L16)
which informs you that you need a `process.env.TEMPLATE_DIRECTORY` i.e. an Environment Variable for `TEMPLATE_DIRECTORY` which is in the Google Doc 

Please see: https://github.com/emfoundation/ce100-app/issues/108 and https://github.com/emfoundation/ce100-app/issues/123

**Comment by mk4111** [comment]
@nelsonic - changing it to .env fixed that! Sorry I missed #123! Done now though, thank you for pointing it  out and helping me! :D
