### ISSUE TITLE
Nav drop-downs should collapse when the users clicks anywhere else on the page

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1259]
Another solution could be to show/hide the drop-downs on hover in/out, instead of on click.

![screen shot 2018-05-24 at 10 26 30](https://user-images.githubusercontent.com/36198201/40480025-2e45de60-5f45-11e8-8b8a-8d3480084fb0.png)

**Comment by asimonw** [comment]
@Danwhy Works well, but just a tiny request: currently clicking on the avatar or three dots a second time doesn't close the menu, could you change the behaviour so that clicking those elements toggles (not only opens) the menu?

**Comment by asimonw** [comment]
@sophielevens this seems to be fixed on staging now. Should it be in please test?

**Comment by fannyBkane** [comment]
@sophielevens @asimonw LGTM :))
