### ISSUE TITLE
login flow bug

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#126]
Unable to login with new auth system.

`/login`

email: ja@mu.co
password: Hello1

**Comment by iteles** [comment]
@JMurphyWeb If you are assigning this to @nelsonic for help, could you please detail what you have already tried and preferably push up your branch?

**Comment by JMurphyWeb** [comment]
At time of writing I am not actively working on this issue as i was awaiting response from nelson on gitter. 

I have only tried to login, but no cookie is being set (visibly) in the browser dev tools. The reply is being called, but the .state() doesn't seem to be having the desired effect. 
According to the tests, the cookie is being set after login.

@nelsonic made some additions last night before merging so was hoping he would have an idea of what is causing it.

**Comment by nelsonic** [comment]
@JMurphyWeb what have you done so far to debug this, what is in your console when you print out the response from redis and bcrypt?

**Comment by JMurphyWeb** [comment]
Currently working on deploy task-list. I wasn't getting any useful logs as the reply that should be setting the cookie is being called, but the cookie is not there. I don't know how i can log this?

**Comment by iteles** [comment]
@JMurphyWeb Are you working through this as a time boxed task with @mk4111 first as suggested?

**Comment by JMurphyWeb** [comment]
Made a new route which should set a cookie:

```
  {
    method: 'GET',
    path: '/set',
    handler: (req, reply) => 
      reply('cookie set>').state('token', 'token', {path: '/'}),
    config: { auth: false }
  }
```

But it has no effect on the cookie-> localhost on dev tools. Seems like there has been a change to some default setting as i cannot set a cookie anywhere in the app. 

Branch -> waiting to hear how to disable pre-commit hook

**Comment by JMurphyWeb** [comment]
Think this is solved now. Just making sure. Will update once I am done.

**Comment by JMurphyWeb** [comment]
Hapi has changed the default settings with the latest update (which we now have). 

isSecure -> now defaults to true
isHttpOnly -> now defaults to true

From my investigating (limited knowledge) isHttpOnly doesn't affect how a user interacts with the app as we are not interpreting the cookie client side, so we can leave that as `true`.

`isSecure: true` doesn't administer a cookie on local host with current setup. I wonder if is ok to set to false for now. Maybe something like this:
```
isSecure: process.env.NODE_ENV ? false : true
```

Then only keep NODE_ENV environment variable locally?  Maybe there is a better way..

**Comment by JMurphyWeb** [comment]
https://github.com/emfoundation/ce100-app/commit/28e991e65e4d3c611a1be7fd852da62088063758

I just pushed up a fix.
