### ISSUE TITLE
All user types should see the display name for location tags

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1260]
When logged in as a primary user, I still see the full name of location tags:
![screen shot 2018-01-22 at 16 21 19](https://user-images.githubusercontent.com/15235804/35232085-d5e73854-ff9a-11e7-8432-a15aefe247f9.png)

This does not seem to happen with admin users. Please make sure users of all types consistently only see display names in location tags (in selection screens, on org profiles and on challenge pages).

**Comment by Cleop** [comment]
**Notes on testing:**
The correct version is showing in these circumstances:

- Staging, primary, secondary and admins
- local,

**Comment by SimonLab** [comment]
@asimonw I just had a look on staging with a primary user and I can't reproduce the error either. Could you test again on your side, maybe updating the api resolve this issue too. Otherwise could you indicate some steps that could help us detect this issue, thanks

**Comment by SimonLab** [comment]
Thanks for the details @asimonw . Since now the staging api is the same as the production one it's strange the the error only occurs on production. I spot any logic error on the displayName tag, see https://github.com/emfoundation/ce100-app/blob/master/templates/helpers/displayTagName.js
Maybe this feature wasn't deploy properly on production?

**Comment by Cleop** [comment]
On production logged in as an admin it works fine for orgs ie. Apple - USA not United States of America.

However on production logged in as an admin I on this challenge: https://cello.community/challenges/32 USA is not abbreviated.

**Comment by iteles** [comment]
As there was some trouble reproducing this bug, it's currently on hold until we have carried out another deployment.
At this point @asimonw will check the bug can be reproduced and we'll go from there.

**Comment by asimonw** [comment]
@iteles I've just encountered it again on staging. Shall I move it into sprint 15 as well?

url: https://staging-ce100-emf.herokuapp.com/challenges/12
user: sa@ro.co

<img width="299" alt="screen shot 2018-06-08 at 14 54 15" src="https://user-images.githubusercontent.com/15235804/41159272-414b6f50-6b2c-11e8-98bb-176693ade917.png">

The display name is "United Kingdom" so that's what should appear.
