### ISSUE TITLE
Use the DAM staging API for cello staging

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1267]
It seems that currently, the staging app is using the API provided by the live DAM API. This makes it hard to test any changes to the way the DAM works.

There should be a test or staging environment in which we can test the latest cello version with the staging version of the DAM API.

**Comment by asimonw** [comment]
The config var `DAM_API` needs to be set to `http://staging.circulareconomy.space`.
On its own, this would break some other data, because the DAM tags are currently not the same on staging and production. We will address this here https://github.com/emfoundation/asset-manager/issues/208.

Another solution would be to use a different tag mapping on staging, but I think going forward, I think it's more elegant to keep the systems in sync.

**Comment by iteles** [comment]
Thanks @asimonw, we'll wait until Friday to tackle this so that the data copying can happen tomorrow 👍

**Comment by asimonw** [comment]
@Cleop The database has been copied on our side, so this one is good to go!
I moved it up one position in the priorities ;)

**Comment by Cleop** [comment]
@asimonw - I've updated this and everything seems to be working fine but I'm not exactly sure what is best to test. Perhaps you can take a look?

**Comment by asimonw** [comment]
@Cleop It looks all lined up perfectly again, thanks!
