### ISSUE TITLE
Use the "link" value when non-empty for Insights and Resources

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1268]
Currently, Insights and Resources always use the `file` field for the url. This is not correct for entries which are not links to S3, but links to somewhere else. In that case, the `link` value should be used from the API.

More precisely: use the `link` value if non-empty, otherwise use the `file` value.

**Comment by Cleop** [comment]
"Bundles - delivering household appliances as a service" is an example of a link
"Remanufacturing for Jaguar Land Rover" is an example of a file
