### ISSUE TITLE
Add a Hotjar snippet in the head tag of every page

### ISSUE THREAD

**Issue by fannyBkane** [emfoundation/ce100-app#1277]
Copy and paste the snippet of code below into the <head> tag on every page. So that we can track users' activity (recordings) when we need.

```
<!-- Hotjar Tracking Code for https://cello.community/ -->
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:751064,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>
```

**Comment by asimonw** [comment]
@iteles @Cleop Let me know if anything's unclear for this one.

**Comment by asimonw** [comment]
@Cleop Let's leave the GTM issue #1269  for now. We'll first see how much use we can get out of Hotjar, thanks.

**Comment by asimonw** [comment]
We'll only be able to test this properly once in production. If there's an issue, I'll open a new issue for it.
