### ISSUE TITLE
Add a maintenance mode switch for the library

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1288]
This would allow us keep the user experience acceptable during DAM updates and maintenance.

The simplest option might be to implement it as a Heroku config var.

Another (maybe longer-term) option is a new general app settings page, only accessible to admins. For now, it would only have this one checkbox on it.

When in maintenance mode:
- [ ] The Insights and Resources views show a message "Insights/Resources currently unavailable due to maintenance. Please check back soon!"
- [ ] In the list of matches on challenge views, the Insights section is simply not shown.

**Comment by Danwhy** [comment]
Of the two options, the functionality for first (Heroku env var) would mostly be logic that would need to be implemented for the second option, (checking if maintenance mode is on, then returning the correct data/pages) so we can definitely start with that. My estimate for that is about 3 hours. 

After that, the functionality for turning it on via a settings page would be about another 2 hours.

**Comment by sophielevens** [comment]
**To activate to the maintenance mode:**

- Log in as an admin user
- Go to the menu, select Admin Settings
- Check the "on" checkbox and then click the "apply" button

**To disable the maintenance mode:** 
- Go to the menu, select Admin Settings
- Check the "off" checkbox and then click the "apply" button

**Comment by asimonw** [comment]
LGTM!
