### ISSUE TITLE
Main navigation improvements - part 1

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1294]
On mobile, what is currently the "Home" item in the bottom nav, becomes a "My matches" item.

On desktop, the "My organisation" link in the top nav is replaced with a link to "My matches."

The home icon in the top left corner will also link to the "My matches" page. (to be confirmed)

**Comment by asimonw** [comment]
@fannyBkane @Kimberley-Heath last item in the top comment to be confirmed. Alternative would be the "Explore" section as home.

@fannyBkane Any other changes to the nav for this first iteration?

**Comment by fannyBkane** [comment]
@asimonw "Settings' become 'My personal settings' in the burger menu on mobile and the drop down on desktop, and the header of the settings page is changed to 'My personal settings' instead of edit user details

But that perhaps relate to copy changes @asimonw

**Comment by asimonw** [comment]
@fannyBkane As this also involves a change to the settings page itself, it sounds like a good idea to group this in with the copy changes instead. Cheers!

**Comment by sophielevens** [comment]
Hi @fannyBkane, are the icons in the mobile navbar changing (as "My Matches" on mobile now has a house icon).

If so, could you send the assets to us? 

Thanks! 😄

**Comment by Kimberley-Heath** [comment]
Hey, so for a secondary and primary user the cello logo links to their 'My Matches' page, as an Admin the cello logo links to error 403 - should this just link to Explore @asimonw ?

**Comment by asimonw** [comment]
@Kimberley-Heath Indeed!
@sophielevens Could the cello logo still link to the Explore page for Admins, Content Owners and View Only's please? Only for primary and secondary users should it link to My Matches.

**Comment by Kimberley-Heath** [comment]
I have tested all five user types - LGTM!
