### ISSUE TITLE
Back link on tag selection screen in Explore not working properly

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1296]
In the Explore section, the back link on the tag selection screen always takes you back to the org list with filter removed, even if the user was on a different list in Explore and had a filter selected.

**Comment by asimonw** [comment]
The back icon is positioned on the left of the top banner on both mobile and desktop
<img width="361" alt="screen shot 2018-05-23 at 11 30 23" src="https://user-images.githubusercontent.com/15235804/40416142-d741cb92-5e7c-11e8-8a24-46290b3c65a5.png">

**Comment by Danwhy** [comment]
@asimonw This turned out to be pretty simple so I went ahead and implemented it

**Comment by Kimberley-Heath** [comment]
Works for me :) @asimonw

**Comment by Danwhy** [comment]
@Kimberley-Heath Sorry, this should be fixed now!

**Comment by Kimberley-Heath** [comment]
@Danwhy Sorry didn't realise I didn't reply, it works!
