### ISSUE TITLE
Review data hosting

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1299]
Make sure all personal data is hosted in the EU.

**Comment by Danwhy** [comment]
Both the postgres and redis instances on heroku are hosted in Europe:
<img width="381" alt="screen shot 2018-05-24 at 11 29 35" src="https://user-images.githubusercontent.com/8939909/40480268-cb5b75a2-5f45-11e8-91a5-cc10570017e8.png">
<img width="272" alt="screen shot 2018-05-24 at 11 30 13" src="https://user-images.githubusercontent.com/8939909/40480283-d940859a-5f45-11e8-9d88-e95218490f7c.png">

**Comment by asimonw** [comment]
Thanks for checking @Danwhy !
