### ISSUE TITLE
Challenge card management of existing cards

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#13]
As a primary user, I can edit or delete existing challenge cards on my profile, So that I have the flexibility to change or remove  challenges based on their status or changes to my focus areas.

Archive instead of delete?

**Comment by LucyJW** [comment]
Or archive as well as delete? i.e. archive if challenge is solved?

**Comment by asimonw** [comment]
I think an archive option (in addition to a permanent delete) would be useful. Another option which has been mentioned was to be able to disable/enable cards (a kind of "publish" to the rest of the community). Possibly not for the MVP though.

**Comment by mk4111** [comment]
As we're currently uncertain of _how_ we would access archived options ( #103 ), this is not included in the time estimates provided.

A time estimate to create the functionality to add/remove and view tags has been provided in ( #61 and #105)

Thus time estimates will be focussing on _editting_ existing challenge cards:
- [ ] *title* and *description*

**Comment by asimonw** [comment]
@mk4111 @JMurphyWeb How are you currently handling the "delete" option? We realised that it would be important to have a prompt pop up, asking the user whether they are sure they want to delete. For archive/unarchive this is less important, because the action is reversible.

**Comment by iteles** [comment]
@asimonw I would strongly suggest that we don't actually delete anything at this stage - even if we show the users a 'delete' button, we'll want to _archive_ for now and see how many calls/emails you get saying things were deleted by mistake.

**Comment by asimonw** [comment]
@iteles I didn't mean delete it from the database, we could (should) definitely keep records around, at least for a certain period. But for users, archive would mean that they can easily retrieve it themselves without our help, while delete would remove it from _their_ history.

On the other hand, at this stage, if there is only archive functionality that's totally fine and would simplify things a bit. This would mean that we don't even show them a delete option, only archive (the design currently shows both.)
