### ISSUE TITLE
Change placeholder text field on the create password screen

### ISSUE THREAD

**Issue by fannyBkane** [emfoundation/ce100-app#1300]
To say 'Choose password' instead of 'Enter password'

 
![screen shot 2018-05-23 at 11 08 36](https://user-images.githubusercontent.com/20577339/40418232-abd0cdb2-5e79-11e8-8333-097f7edb1557.png)

**Comment by Kimberley-Heath** [comment]
LGTM! (When I created my new user this morning I saw this was changed) @asimonw
