### ISSUE TITLE
Filter people by topic in Explore

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1302]
Now that people will be able to tag themselves, we can allow users to filter people by topic in exactly the same way that we're allowing orgs, challenges and insights to be filtered.

**Comment by fannyBkane** [comment]
Hey @Danwhy looks good!

Just seeing that the message when there aren't results is aligned to the left edge of the viewport. 
![screen shot 2018-06-08 at 11 26 54](https://user-images.githubusercontent.com/20577339/41153597-177513ba-6b0f-11e8-94ee-6d7c4f314c22.png)
Could it be styled like the other messages (here how it's displayed for orgs) 
![screen shot 2018-06-08 at 11 27 00](https://user-images.githubusercontent.com/20577339/41153607-1d3dda48-6b0f-11e8-9d27-2e544e23569a.png)

**Comment by fannyBkane** [comment]
That's fine @asimonw 👍

**Comment by fannyBkane** [comment]
@sophielevens @asimonw  LGTM!
