### ISSUE TITLE
List the person who posted the challenge in search

### ISSUE THREAD

**Issue by Kimberley-Heath** [emfoundation/ce100-app#1306]
Now we are shifting the focus on people on cello, challenges that come up in search should have the person listed who posted it as it does in the list view
![screen shot 2018-05-24 at 11 35 22](https://user-images.githubusercontent.com/36198201/40480514-ad81317e-5f46-11e8-8b8d-18d3ae5d8535.png)

**Comment by fannyBkane** [comment]
@asimonw priority-3 label sounds good
