### ISSUE TITLE
Update profile page to show interests

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1314]
"As a CE100 contact, I want to display my interests to the network, so that other people know at a glance what I'd like to know more about, collaborate on or can help them with."

The interests tags are displayed on personal profiles.

[Mockup](https://projects.invisionapp.com/share/3DEU1V0A6#/screens/268152495)

[EDIT]
[Desktop mockup](https://invis.io/DYESHUZW7#/300141925_User_Profile)

**Comment by sophielevens** [comment]
Hi @fannyBkane, would you like the mockups provided in this issue to be implemented? I started doing this yesterday but on hangouts this morning Alex mentioned that these might be for another sprint. Please bear in mind there are still some slight changes to be made, such as the icons.

![image](https://user-images.githubusercontent.com/25961258/40967504-0c222860-68ab-11e8-859b-f179677d47c7.png)

@asimonw, there are some more instances where the header will need to change if it is going to be consistent throughout the site (see below), so I will wait for your confirmation as to whether I should continue making the design changes or not.
 
![image](https://user-images.githubusercontent.com/25961258/40967210-6a8cc6fe-68aa-11e8-8197-345925e630a3.png)

Thanks 😄

**Comment by asimonw** [comment]
@sophielevens I've discussed this (related to the personal profile page) with @fannyBkane and it's fine to add the changes to the banner as shown in the mockup.

The change is a bit more tricky when it comes to the org profile page, because most logos won't work on that background. If you look at the latest mockups, you'll see that the banner is still white for org profile pages. @fannyBkane do you agree that we want to keep the white background in that case?

**Comment by fannyBkane** [comment]
Seconding @asimonw 's point: 

> The change is a bit more tricky when it comes to the org profile page, because most logos won't work on that background. If you look at the latest mockups, you'll see that the banner is still white for org profile pages. @fannyBkane do you agree that we want to keep the white background in that case?

Please keep the org header background white @sophielevens 

Thank you 😃

**Comment by sophielevens** [comment]
Thanks for getting back to me @fannyBkane and @SimonLab ✨

**Comment by fannyBkane** [comment]
Hey @Danwhy @sophielevens the header background doesn't seem to have been changed to a gradient?

I wonder if the explanation above was clear... To clarify: it makes sense to have a gradient on user profile header backgrounds, but not on organisation profiles (because the logos don't work well against a coloured fill).

**Comment by fannyBkane** [comment]
On another note.. I realise this wasn't specified in this issue, or on the prototype... 

Would be great if the Interests tags behave like the 'topics' on the organisation page (default/hover state and link to Explore people with the corresponding tag selected).
![screen shot 2018-06-08 at 11 05 14](https://user-images.githubusercontent.com/20577339/41152799-ac7228ac-6b0c-11e8-9f08-e37589999cc4.png)

Happy to consider this as an iteration and open a new issue @asimonw

**Comment by fannyBkane** [comment]
@sophielevens LGTM! 👍
