### ISSUE TITLE
Make People the first tab in Explore

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1316]
To reflect that we'd like the app more people-centric, we'd like the People tab to be the first/default one that appears when users to to Explore.

**Comment by asimonw** [comment]
@Danwhy This one seems ready for testing as well, right?

**Comment by Danwhy** [comment]
@asimonw It wasn't quite ready, as we'd moved it, but the default page after coming through from matches was still `/orgs` . It is ready to test now though!
