### ISSUE TITLE
Improvements to topic tag selection

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1317]
Based on user research, we'd like to add some improvements to the topic tag selection process.

**Acceptance criteria**: 
- [x] Indicate how many tags are selected, and how many can maximally be selected
- [x] Show selected tags at a glance at the top of the screen (position fixed)
- [x] Clicking the cross on the right of a selected tag (displayed at the top) deletes the tag from the selection
- [x] On mobile, the "Cancel" button appears at the top left and the "Add/Edit" button appears at the top right
- [x] On desktop, the cancel icon (cross) appears at the top right, the "Add/Edit" button appears underneath the rest of the content (also fixed position). The functionality of add/edit and cancel buttons does not change.

**Mobile prototypes/flows:**
Onboarding>Choose interests>Modal>My matches [Link](https://invis.io/3DEU1V0A6#/298354399_Onboarding)
Matches>Go to Settings>Settings>Edit interests>Save settings>My matches [Link](https://invis.io/3DEU1V0A6#/298354397_Matches)
My menu>My personal settings> Edit interests>Save settings>My profile [Link](https://invis.io/3DEU1V0A6#/267955515_My_menu-primary_user)
My menu>New challenge>Add tags>Modal>Save&Publish challenge>Challenge [Link](https://invis.io/3DEU1V0A6#/267955515_My_menu-primary_user)
Challenge>Edit challenge>Edit tags>Save & publish challenge>Challenge [Link](https://invis.io/3DEU1V0A6#/268152494_Challenge)

**Comment by sophielevens** [comment]
Hi @fannyBkane, @Danwhy and I are having a look through the mockups and we are wondering if you could draw up some desktop designs to replicate how you imagine the new tag selection looking on a bigger screen?

We are particularly interested in finding out if the selected tags will be displayed within the modal itself. 

Thanks 👍

**Comment by fannyBkane** [comment]
Desktop mockups 
![my interests](https://user-images.githubusercontent.com/20577339/41296196-52524c80-6e54-11e8-9ecc-6521042134b2.jpg)
![our expertise](https://user-images.githubusercontent.com/20577339/41296197-527498a8-6e54-11e8-92c5-3523c58205b4.jpg)
![tags](https://user-images.githubusercontent.com/20577339/41296198-5290977e-6e54-11e8-858b-95cbd575daac.jpg)

**Comment by asimonw** [comment]
@Danwhy Spotted a few issues:
- If I add or remove some tags and then press cancel, the selection on the form is indeed not updated (correct), but if I then open the selection modal again, the changes are still there. Canceling should undo the operation completely.
- The "Add" button doesn't work on desktop
- Could the "Add" button/link on both desktop and mobile actually say "Edit" if the user didn't have any tags for that object (profile/challenge/org profile) yet?
- Could the cross on the selected tags be lower case and a bit further apart from the text in the tag (see mockups)?

**Comment by Danwhy** [comment]
@asimonw I'm a little confused regarding point 3 above: If a user has no tags selected, they should see the 'Add' button, right? And if they already have some tags selected, they should see an 'Edit' button?

**Comment by asimonw** [comment]
@Danwhy whoops, I said it the wrong way! What you suggest is what I meant, thanks for checking 😄 

I'll update that comment to avoid further confusion.

**Comment by asimonw** [comment]
@Danwhy Works well now!

@fannyBkane @Kimberley-Heath could you also test this a bit, as it's a pervasive new feature.

**Comment by fannyBkane** [comment]
@asimonw 

**In the modal**, it does not actually make sense to have the button say 'Edit'... I suggest to use one of the following instead:  _Add_, _Done_ or _Save_ 

![screen shot 2018-06-21 at 13 39 48](https://user-images.githubusercontent.com/20577339/41719723-ca87c274-7558-11e8-8fac-9638abf4952f.png)

**On mobile:** 
- the cancel and add aren't showing (using Chrome)
- Could the selected tags be aligned to the left, and the '10 out of 10' to the right and pink (see [invision](https://invis.io/3DEU1V0A6#/302385245_Challenge-Add_New_Challenge-Add_Tags)? 
![screen shot 2018-06-21 at 13 48 17](https://user-images.githubusercontent.com/20577339/41720133-fdede19c-7559-11e8-9e5a-9ecc66bad7cc.png)

**Comment by asimonw** [comment]
@fannyBkane why can’t the word used not be the same on mobile and desktop? Save doesn’t work for most cases as no tags are saved yet at that stage. Add doesn’t work when there were already tags. For example, the user could actually be deleting tags. I think Edit is a good choice that’s generic enough. Done could also work. Do you prefer that over a combination of Add/Edit as we have now?

Funny that you can’t see the buttons on mobile, I can. What browser are you using?

**Comment by fannyBkane** [comment]
@asimonw I didn't mean to use different words on mobile and desktop (sorry if that was not clear)! The issue is that, when you have selected tags, it doesn't make sense to press 'Edit' (see screenshot. When I see Edit in the button i think that it'll edit my selection.

That's why I suggested other words...

'Save' or 'Add' may not work in every case. 'Done' would work, with the risk that people may not understand it - as Ines mentioned in the kickoff. 

I would prefer to have a simpler solution that works across the different case, simply becasue it's simpler to implement, and we'll have more time to test and iterate later on.

wdyt?

**Comment by fannyBkane** [comment]
>@fannyBkane so you mean use Done for all cases? Happy to try that.

@asimonw That's right

**Comment by Kimberley-Heath** [comment]
Have tested in over time, in a few different user types/ places on the site, and it all seems to work fine. Also think having 'Done' definitely works in all cases :)

**Comment by asimonw** [comment]
LGTM. @fannyBkane Is the buttons not showing up on mobile now fixed for you?

**Comment by fannyBkane** [comment]
Yes @asimonw the links are showing now! can @Danwhy can u confirm that the size and colour of the text links are like on the mockup? ( it was 14px and white with 0.75 opacity ). Thank you!

**Comment by asimonw** [comment]
@Danwhy @sophielevens Indeed, could the font size be 14px instead of 11px and a 0.75 opacity be added to the top left and right links on mobile?

**Comment by fannyBkane** [comment]
@sophielevens I can't see those changes on staging :/

>could the font size be 14px instead of 11px and a 0.75 opacity be added to the top left and right links on mobile?

**Comment by asimonw** [comment]
@sophielevens Same here.. #1451 didn't make it onto staging I think.

**Comment by sophielevens** [comment]
@asimonw and @fannyBkane, I may have labelled this as please test too early - it is now on staging and ready to test 😄

**Comment by fannyBkane** [comment]
@sophielevens noticed on ios that the margin left on Cancel is really tiny, compared to teh margin right on Done. Can this be adjusted so that both spaces are equal?

![image from ios](https://user-images.githubusercontent.com/20577339/41966708-bee2a6b6-79f7-11e8-914b-a7a45ec809c6.png)

**Comment by asimonw** [comment]
Looks good now!
