### ISSUE TITLE
View/Flow for onboarding question

### ISSUE THREAD

**Issue by sophielevens** [emfoundation/ce100-app#1324]
Create the html for the onboarding question "What are you interested in?"

Part of #1292 

[Initial state](https://projects.invisionapp.com/share/3DEU1V0A6#/screens/298354399)
[After selection](https://projects.invisionapp.com/share/3DEU1V0A6#/screens/298537769)

[EDIT]
**Desktop**
[Initial state](https://invis.io/DYESHUZW7#/300141937_Onboarding)
[After selection](https://invis.io/DYESHUZW7#/300141934_Onboarding-Tags-Selected)

**Comment by Danwhy** [comment]
Being tested as part of #1292
