### ISSUE TITLE
Front end for matches page

### ISSUE THREAD

**Issue by sophielevens** [emfoundation/ce100-app#1325]
Create a view which lists people, orgs, challenges and insights (max of 10)

Part of #1293 

**Mockups**
[With matches](https://projects.invisionapp.com/share/3DEU1V0A6#/screens/298354397)
[Without matches](https://projects.invisionapp.com/share/3DEU1V0A6#/screens/299074280)

**Comment by Danwhy** [comment]
Being tested as part of #1293
