### ISSUE TITLE
DAM maintenance mode - part 2

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1327]
Topic tags are also unavailable when DAM is in maintenance.
How does cello behave when tags are not available from the DAM API currently and what can we do to make the app as useable as possible when that's the case.

**Comment by asimonw** [comment]
@Danwhy As suggested during the standup, it would be great if you could simulate what would happen to cello if the DAM API is not available (e.g. during DAM maintenance). 

One solution is to have a "local" cashed version on the cello server which could be synced through a weekly (?) cron job? The tags don't change that often, so that seems enough to me for what would be a fallback anyway.

**Comment by Danwhy** [comment]
When maintenance mode is on, the tags should now still be available, as they are being cached in Redis. (searching using individual tags may not be available straight away, as it requires a first request to the api to be made before caching, but the list of tags will be)

**Comment by asimonw** [comment]
LGTM @Danwhy
