### ISSUE TITLE
Secondary contacts do not have a 'notifications' tickbox

### ISSUE THREAD

**Issue by Kimberley-Heath** [emfoundation/ce100-app#1344]
Primary contacts have the option to tick whether they want to  receive notifications when someone comments on their challenges. However secondary contacts do not have this and therefore receive no notifications... 

![screen shot 2018-06-05 at 14 48 21](https://user-images.githubusercontent.com/36198201/40980618-c187d964-68d0-11e8-8f5f-bc8364b6bb2d.png)

**Comment by asimonw** [comment]
@iteles This one is added to the end of the sprint in case there is some time left. We forgot to enable notifications for secondary users when we moved from org-level challenges to user-level challenges.

**Comment by Kimberley-Heath** [comment]
LGTM! @asimonw
