### ISSUE TITLE
Use the "link" value when non-empty for Insights in challenge matches

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1345]
This is the same bug that was just fixed on the search results page #1282.

If an insight that appears in the list of matches for a challenge (on the challenge view) has a non-empty "link" value, please use that one instead of the "file" value.

**Comment by asimonw** [comment]
@iteles Another "buffer" issue for this sprint.

**Comment by Kimberley-Heath** [comment]
Hi @Danwhy this doesn't work for me... I opened this challenge: https://staging-ce100-emf.herokuapp.com/challenges/12,  and clicked 'Toast Ale - brewing beer from surplus bread'

@asimonw FYI

**Comment by asimonw** [comment]
@sophielevens I think this one's for you

**Comment by Danwhy** [comment]
Thanks @Kimberley-Heath, was this after clicking the "see more" link? (The data on the staging site was reset before I had a chance to look at that challenge)

**Comment by Kimberley-Heath** [comment]
@Danwhy yes it was after I clicked the "see more" link...

**Comment by Kimberley-Heath** [comment]
LGTM
