### ISSUE TITLE
Archive Users not working for new Orgs with _no Primary User_

### ISSUE THREAD

**Issue by mk4111** [emfoundation/ce100-app#136]
toggle-archive function is replying with a 500 error when applied to new organisations with no primary users. On adding a user to that organisation though, we see that the archiving _did_ work, so we need to figure out why it's replying with an error page/message.

**Comment by mk4111** [comment]
Likely related to #135

**Comment by JMurphyWeb** [comment]
This appears to be fixed in next PR

**Comment by JMurphyWeb** [comment]
Now fixed on next PR
