### ISSUE TITLE
Remove "N/A Admin" dropdown option

### ISSUE THREAD

**Issue by mk4111** [emfoundation/ce100-app#137]
Remove "N/A Admin" dropdown option from edit-user-details view.
Add a value of "-1" to the "Please select option" default option.
Primary Users being detached from organisations, and admins who are not affiliated with any organisation can use this option.

**Comment by iteles** [comment]
@mk4111 This looks like multiple issues in one and also requires some reasons around why you are making this decision in the form of a user story (please remove the technical label when done).

I would suggest 'No organisation' makes more sense from the user's perspective than '-1'.

**Comment by JMurphyWeb** [comment]
@iteles -1 represents the value of the dropdown behind the scenes. It is linked to the `Please Select` dropdown option.

The issue was raised as @mk4111 spotted a bug which crashed the app when we edited and selected admin.

**Comment by JMurphyWeb** [comment]
Should be fixed in next PR
