### ISSUE TITLE
Admin notification when a new challenge is posted

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1378]
When a new challenge is posted, a notification email should be sent to an address which is set as a variable in Heroku (email address to be communicated).

To be added: list of fields which need to be included in the email, copy and mockup of email (including title)

**Comment by fannyBkane** [comment]
Fields to include in the notification email:

**Email:** info@cello.community
**Name of sender:** cello

**Subject line:** New challenge...(text TBC @Kimberley-Heath)

**Body of email:**

name of person who receives the email
name person who created the challenge
organisation the person who commented are from (TBC @Kimberley-Heath ?)
challenge title + link

**Email footer**
text: why they’re receiving the email
link to their personal settings

**Comment by sophielevens** [comment]
Hi @fannyBkane, do you or @Kimberley-Heath have the correct copy for the admin notification email? 
Thanks 👍

**Comment by Kimberley-Heath** [comment]
Hi @sophielevens here is the email text in a similar style to the other notification emails, @fannyBkane FYI I have changed the layout slightly from the mock up so now it is more similar to the other notifications. 

![screen shot 2018-06-18 at 13 46 39](https://user-images.githubusercontent.com/36198201/41536690-37f74788-72fe-11e8-853b-9db820a92779.png)
