### ISSUE TITLE
Admin notification when a new comment is posted

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1379]
When a new comment is posted, a notification email should be sent to the same address as in #1378.

To be added: list of fields which need to be included in the email, copy and mockup of email (including title)

**Comment by fannyBkane** [comment]
Fields to include in the notification email:

**Email:** info@cello.community
**Name of sender:** cello

**Subject line:** New comment on...(text TBC @Kimberley-Heath)

**Body of email:**

name of person who receives the email
name person who commented
organisation the person who commented are from
challenge title + link
full comment text
link to the corresponding challenge
**Email footer:**
text: why they’re receiving the email
link to their personal settings

**Comment by Kimberley-Heath** [comment]
![screen shot 2018-06-18 at 13 47 01](https://user-images.githubusercontent.com/36198201/41542990-f24658f4-730d-11e8-91a3-2add075bd34c.png)
@sophielevens
