### ISSUE TITLE
Copy on profile when no interests are shared yet

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1383]
On a profile of someone who hasn't shared any interests yet.
- [x] Underneath the Interests header, replace the copy with: "No interests shared yet."
- [x] If it's your own profile, add the text: "Go to "your settings" to add some."

**Comment by fannyBkane** [comment]
Hey @asimonw is it ok, for consistency to update to the following?

![screen shot 2018-06-12 at 09 47 57](https://user-images.githubusercontent.com/20577339/41279966-b9c42bec-6e25-11e8-87e7-8e47e41cdcbb.png)

Change 'You have no interests set yet' to: 'No interest shared yet'
Add button [+Interests] (style to be consistent with [+ Challenge] button underneath)

**Comment by asimonw** [comment]
@fannyBkane Would that button be a link to the personal settings? In that case, wouldn't a link style and different copy be clearer?

**Comment by fannyBkane** [comment]
Hey @asimonw good point! I've reviewed and updated. Note, there could be copy saying 'edit tags' when there are tags selected.

![screen shot 2018-06-13 at 09 52 15](https://user-images.githubusercontent.com/20577339/41340586-a35f6e96-6eef-11e8-9ac7-23209587b82e.png)
![screen shot 2018-06-13 at 09 52 22](https://user-images.githubusercontent.com/20577339/41340587-a37c0d08-6eef-11e8-81d6-fb703f961c0a.png)

**Comment by fannyBkane** [comment]
@asimonw Although it works, technically and hierarchically, it makes for a complicated UI.... Feels that this could be improved. Created issue  #1396 for that.

**Comment by asimonw** [comment]
@fannyBkane That looks fine to me. But happy to discuss issues with this solution and other option in #1396.

**Comment by sophielevens** [comment]
At the moment, is this issue complete if: 

A user without interests sees the following:

<img width="453" alt="screen shot 2018-06-19 at 16 27 10" src="https://user-images.githubusercontent.com/25961258/41607317-aa4abace-73dd-11e8-89ea-08b85f2caf4e.png">

A user with interests sees the following:

<img width="503" alt="screen shot 2018-06-19 at 16 26 09" src="https://user-images.githubusercontent.com/25961258/41607318-aa649fb6-73dd-11e8-87b0-a2beea03b9ec.png">

Thanks 😄

**Comment by asimonw** [comment]
@sophielevens that looks perfect!

To make things clear, that would be when looking at your own profile. For other people's profiles, leave off the second line in both case 👍

**Comment by fannyBkane** [comment]
@sophielevens Looks great! The challenges, tags and text displayed when there is no content should be indented slightly - is there a simple way to have the same indent for all of those?

**Comment by fannyBkane** [comment]
@sophielevens @Danwhy @asimonw LGTM

**Comment by fannyBkane** [comment]
Hey @asimonw my bad — something escaped my attention:  the indent is different on each element.

![screen shot 2018-06-25 at 14 03 51](https://user-images.githubusercontent.com/20577339/41851815-10a0ed96-7881-11e8-93c8-1220bc1520f9.png)

Would it be possible to update the margin left in order for all the text and buttons below the headers to be left aligned nicely?
![screen shot 2018-06-25 at 13 59 37](https://user-images.githubusercontent.com/20577339/41851864-3dfe3bb8-7881-11e8-8ac8-a76cf294e2b8.png)

It would make a more pleasant page and clearer hierarchy.

 It's ok to create a new issue now this one is closed.

**Comment by asimonw** [comment]
@fannyBkane You're right. A new issue would be better as it's a different issue from the original. I'll add it to the sprint so we can prioritise accordingly.

**Comment by fannyBkane** [comment]
@asimonw sounds good!
