### ISSUE TITLE
Copy amends

### ISSUE THREAD

**Issue by fannyBkane** [emfoundation/ce100-app#1388]
Menu> New challenge:
'Add new challenge' header changes to ‘New challenge’

**Comment by fannyBkane** [comment]
@Danwhy I can't seem to be able to login to the staging site, could you advise?

**Comment by Danwhy** [comment]
@fannyBkane Looks like there might have been an issue resetting the data, I'll get it fixed and let you know when it works

**Comment by Danwhy** [comment]
@fannyBkane Should be working now

**Comment by fannyBkane** [comment]
@Danwhy it does, thank you!

**Comment by fannyBkane** [comment]
@asimonw @Danwhy LGTM :)
