### ISSUE TITLE
Style & text update - Comment notifications

### ISSUE THREAD

**Issue by Kimberley-Heath** [emfoundation/ce100-app#1398]
To keep everything consistent, we have decided to update the notification for comments on challenges to be aligned with the new notification in issue #1380  

**OLD Text:**
![screen shot 2018-06-13 at 10 52 06](https://user-images.githubusercontent.com/36198201/41343953-d6978ff2-6ef7-11e8-874f-cfe4d3f5a969.png)

Please note that I underlined words that are merge fields, although they do not need to be underlined in the final email. The pinks are links and if they could be shown in the cello pink #FA3265 (not underlined) in the final email that would be great! Although the last line "Too many emails? Change notification settings here" - please can this be the lavender grey #585667 and for the "here" link underlined. Thanks!

**NEW Text:**
![screen shot 2018-06-13 at 10 52 37](https://user-images.githubusercontent.com/36198201/41343987-edfb1f56-6ef7-11e8-9225-afcb23872280.png)

**Comment by asimonw** [comment]
@iteles Sorry to be adding to the scope, but it would be great to do this in tandem with #1380.
That way the existing notifications are consistent with the new ones.

**Comment by sophielevens** [comment]
Hi @Kimberley-Heath, what colour would you like the main copy of the email to be? It is currently #222222. 

With changes in place: 
<img width="643" alt="screen shot 2018-06-15 at 14 37 20" src="https://user-images.githubusercontent.com/25961258/41470799-a655cbac-70a9-11e8-82be-9f4ce98818f8.png">

**Comment by Kimberley-Heath** [comment]
Hi @sophielevens, if this was the colour used in previous notifications then yes let's continue with that. Thanks!

**Comment by sophielevens** [comment]
Hi @Kimberley-Heath , 
I know you specified that the merge fields don't need to be underlined but would you like the challenge title and comments italicised, as they are in this mock up? 
Thanks 👍

**Comment by Kimberley-Heath** [comment]
Yes, italicised please with quote marks for the challenge, and speech marks for the comment. Thanks @sophielevens!

**Comment by Kimberley-Heath** [comment]
Hey @sophielevens, a couple of changes please! 

- [ ] Can the subject line say 'your challenge' rather than 'a challenge'.
- [ ] Can 'Respond to Ben' be underlined
- [ ] Can there be a comma after the 'Dear Kimberley' 
- [ ] Can the comment be on the line underneath or is this not possible?

Thanks!

**Comment by Kimberley-Heath** [comment]
Thanks for changes! @sophielevens The last thing is the update I expressed in this issue https://github.com/emfoundation/ce100-app/issues/1380, which was to update the subject line so the challenge name is in italics without speech marks. Thanks!

**Comment by asimonw** [comment]
@sophielevens Let us know if it's actually not possible to display text in italics in the subject line. In that case, it might still be better to keep the quotation marks.

I'll close this issue as the only remaining things is also handled in #1380
