### ISSUE TITLE
Match challenge with profiles

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#14]
As a primary user, I get recommendations on which organisations may be able to help me, related to a specific challenge and based on how I tagged it, so that I can get help solving my challenge and find potential collaborators.

**Comment by LucyJW** [comment]
The recommendations are not necessarily based on who to contact but who may be able to help you with a challenge. Contact is one (of a few) actions a user might take. A small difference but might be worth updating.

**Comment by asimonw** [comment]
Done.

**Comment by JMurphyWeb** [comment]
@asimonw slightly struggling to 'picture' this view, is it in the wireframes?

**Comment by asimonw** [comment]
@JMurphyWeb it's not a separate view per se. After a user has created a challenge, underneath that challenge card on the profile page, he would see a list of orgs with matching expertise tags. We haven't mocked it up yet, because we pictured it would be part of the second sprint, but we can send through some lo-fi drawings to make it clearer.

The same applies to #15 and #16. They both appear on an org profile, but only the user related to the org can see this. In general, you have a "public view" without edit buttons and no match info and a "private view" only for users linked to the org.

**Comment by JMurphyWeb** [comment]
ok, i think that is clear. Could we add a brief description to new wireframes indicating who is logged in at the time, as in #34

**Comment by asimonw** [comment]
![fullsizerender_3](https://cloud.githubusercontent.com/assets/15235804/17745292/38523122-64a3-11e6-8670-1b64ad3662a0.jpg)

List of recommendation appears underneath a challenge card. Initially, we'll go for a simple matching "algorithm": show all orgs which have an expertise tag which matches one of the tags of the challenge. To be fine tuned at a later stage.

**Comment by asimonw** [comment]
@JMurphyWeb @mk4111 See "Profile (private view) editable" in Zeplin https://zpl.io/Z1IjRwn
Underneath every existing challenge card, you see a list of matching orgs (based on overlapping tag sets).
