### ISSUE TITLE
navbar logic can be extracted into a function

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#141]
I am not sure of a good way of solving this issue with handlebars, but at the moment we are passing an 'alternate' navbar to our views in the handlers that want them.

**Comment by JMurphyWeb** [comment]
This is what we have at the bottom of viewAllUsers handler:

```
      // TODO: Can this navbar logic go somewhere else?
      var allUsers = {
        allUsers: users,
        alternate: [{
          path: '/people/add',
          name: '+'
        }, {
          path: '/orgs',
          name: 'Orgs'
        }]
      };
      reply.view('people/view', allUsers);
```

**Comment by mk4111** [comment]
@JMurphyWeb - this navbar was implemented for the Sprint 1 demo; I think we should be able to remove that from the handlers in our next iteration.

**Comment by JMurphyWeb** [comment]
Ideally yeah. I just wasn't sure of a good way of removing that logic from individual handlers?

**Comment by JMurphyWeb** [comment]
Moved main argument into #56
