### ISSUE TITLE
My Profile - Organisation name colour change

### ISSUE THREAD

**Issue by Kimberley-Heath** [emfoundation/ce100-app#1413]
I have noticed that on 'My Profile' the organisation name under the person name is barely visible in the colour it is now. Please can this be updated to white (@fannyBkane to confirm this is the right colour). 
![screen shot 2018-06-18 at 15 21 37](https://user-images.githubusercontent.com/36198201/41544269-310c4a2e-7310-11e8-8890-0790ab109b49.png)

**Comment by fannyBkane** [comment]
I confirm white is fine :) cheers @Kimberley-Heath @sophielevens

**Comment by asimonw** [comment]
@sophielevens The bug only occurs for users without a job title.

One way to reproduce:
- Visit a profile with job title. The org name is white as it should be
- Remove the job title from that profile
- Return to the profile and note that the org name is now gray

**Comment by sophielevens** [comment]
Thanks for this! 

@fannyBkane, would you like the organisation to behave as the phone and email do with an underline on hover?

**Comment by fannyBkane** [comment]
@sophielevens yes please make the organisation behave as the phone and email. Thank you!

**Comment by Kimberley-Heath** [comment]
LGTM!
