### ISSUE TITLE
'Search' word placement on safari 

### ISSUE THREAD

**Issue by Kimberley-Heath** [emfoundation/ce100-app#1429]
@asimonw One thing I have noticed is on a Safari browser (but not in Chrome) the 'Search' word placement is higher than usual and chops the top of the S off...

![screen shot 2018-06-25 at 10 18 33](https://user-images.githubusercontent.com/36198201/41841801-22372fe0-7861-11e8-86f1-052c0f8f1842.png)

**Comment by asimonw** [comment]
Good spot @Kimberley-Heath !
@sophielevens could you look at why the placeholder text is not placed the same on Safari, please?
Something else I noticed: it's cosmetic, but the pink line at the bottom on the focused state of the Search box is not quite covering the white line underneath. This also only seems to be happening on Safari, not other browsers..

**Comment by Kimberley-Heath** [comment]
LGTM!
