### ISSUE TITLE
Improve styling of the Resources page

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1432]
The Resources page could use a bit of work to be brought a bit more in line with other pages.

**Comment by asimonw** [comment]
@fannyBkane I'm thinking at least adding left and right margins on desktop, same as on Explore?

**Comment by fannyBkane** [comment]
@asimonw indeed. The header could also be restyled to follow the same as on Explore.

**Comment by sophielevens** [comment]
I think these guidelines are clear enough, thanks @asimonw  and @fannyBkane ✨

**Comment by fannyBkane** [comment]
@asimonw @sophielevens I have cleared my caches but not seeing changes on the resources page fyi
![screen shot 2018-06-27 at 10 04 21](https://user-images.githubusercontent.com/20577339/41964292-1e98a696-79e9-11e8-88cf-2c63fb3b5418.png)

**Comment by asimonw** [comment]
@sophielevens I don't think #1451 actually made it onto staging!?

**Comment by sophielevens** [comment]
Hey @asimonw, I don't think it had deployed by this point, sorry. 
I just checked staging and it is there now

**Comment by fannyBkane** [comment]
Nw @sophielevens it is now indeed and it looks good to me :) @asimonw

**Comment by fannyBkane** [comment]
Wait... @sophielevens I have just realised :/ that the header on mobile screens is the same as before. So changes were made only on desktop. Not a biggie, we can log that as a separate issue and add it to the backlog @asimonw

**Comment by asimonw** [comment]
@fannyBkane On mobile it seems less of an issue to me too, so a new issue for it sounds good!
