### ISSUE TITLE
The "choose interests" url

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1433]
@Danwhy @sophielevens I noticed that the "Choose interests" screen during onboarding is still `/choose-interests` while the same page is available at `/` (as long as the user hasn't shared interests yet). Is there a reason for that?

The goal was to only use `/`. The benefit of that is that people can never navigate back to the "Choose interests" page once they've shared interests. And it also avoids duplicating code/functionality. Wdyt?

**Comment by Danwhy** [comment]
You're right @asimonw, I think we just missed removing this endpoint when we made the onboarding changes

**Comment by asimonw** [comment]
Great, thanks @Danwhy. I did land on it in the onboarding flow, so make sure it's not linked to from the consent pages anymore either. The second form should just link to `/`.
