### ISSUE TITLE
Activation email - update email address

### ISSUE THREAD

**Issue by Kimberley-Heath** [emfoundation/ce100-app#1434]
We should update the email address within the activation email to 'info@cello.community' rather than ce100@ellenmacarthurfoudnation.org.

![screen shot 2018-06-25 at 11 28 09](https://user-images.githubusercontent.com/36198201/41845358-20c36502-786b-11e8-9181-16d8558cdc35.png)

**Comment by Kimberley-Heath** [comment]
@asimonw @fannyBkane. 

Is there anywhere else the c100@ email is displayed we should also update?

Also is there any other changes we may as well update now along with this one? One for me would be to remove 'Best' before 'From cello'.

**Comment by asimonw** [comment]
@Kimberley-Heath Now that you mention it, the "Contact us"!

@Danwhy @sophielevens Could the email address be changed as Kimberly instructed, both in the activation email and the "Contact us" link in the nav?

**Comment by fannyBkane** [comment]
@Kimberley-Heath I can't think of another instance where ce100@ is used.
