### ISSUE TITLE
Filter by location not working for People

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1436]
Because currently people cannot add a location to their profile, filtering by location in Explore doesn't work for people. The whole list of people is shown.

Question to @fannyBkane and @Kimberley-Heath:

I think it's less confusing to show no results and a "No results" message rather than a list of all people.
This would of course be a temporary fix. We should enable people to add a location to their profile in a later sprint. wdyt?

**Comment by Kimberley-Heath** [comment]
@asimonw Yes it might be confusing if everyone is displayed, but I wonder whether 'no results' is the right message? Could we use 'Currently unable to filter by location' so people know that there is not the feature yet?

**Comment by asimonw** [comment]
@Kimberley-Heath that sounds good.
@sophielevens would it be possible to do as Kimberly suggested: don't show any people when a location is selected in Explore and just display "Currently unable to filter by location" in the same stile as other "No results" messages in Explore?
