### ISSUE TITLE
Challenge 62 will not filter...

### ISSUE THREAD

**Issue by Kimberley-Heath** [emfoundation/ce100-app#1461]
@asimonw Just noticed on the live site that there is a challenge that does not filter. It says it is from March 7th so is not the newest or oldest but remains at the top... 

https://cello.community/challenges/62

**Comment by asimonw** [comment]
Thanks for flagging that @Kimberley-Heath.
@Danwhy will look into what it is about this challenge that keeps it at the top no matter how you sort the list.

**Comment by Danwhy** [comment]
This was a problem with the challenges sorting in general, not just the one. It's the same issue we had with the insights before, there just weren't enough challenges locally/on staging to notice it
