### ISSUE TITLE
Users can tag more than 10 interests

### ISSUE THREAD

**Issue by Kimberley-Heath** [emfoundation/ce100-app#1464]
@asimonw This user has somehow managed to tag more than 10 interests... 

https://cello.community/people/483

**Comment by asimonw** [comment]
@Kimberley-Heath Try to find out how they managed to do that.

Even if for some reason the JavaScript didn't load (for example) it should still not be possible to save more than 10 tags per person to the database. So depending on what you find out, I'll create a new issue for that or track it here. Thanks!

**Comment by asimonw** [comment]
As a first solution, we should at least make sure that no more than 10 tags are allowed server-side.
If somehow the user has managed to select more than 10 (by messing with the HTML and/or JS?), the form should return with an error message saying "Too many tags were selected. Please select up to ten."

**Comment by asimonw** [comment]
@sophielevens @Danwhy I manually changed the HTML to try and save more than 10 and it got rejected. So from what I can tell that's fixed 👍
