### ISSUE TITLE
The Explore section sometimes displays JSON when using the back button

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1465]
On any of the tabs in the Explore section, clicking in the search filter field triggers an extra Ajax request to load the list in JSON format. Clicking on any of the list items (for example) and then clicking on the browser back button causes the browser to display the JSON rather than the actual page (as if a History.replaceState has been used).

**Comment by asimonw** [comment]
LGTM. @Kimberley-Heath happy?

**Comment by Kimberley-Heath** [comment]
LGTM! @asimonw
