### ISSUE TITLE
archived challenges showing in matches

### ISSUE THREAD

**Issue by fannyBkane** [emfoundation/ce100-app#1466]
Even though not showing in explore or profiles... It needs to be removed.

![screen shot 2018-07-03 at 09 26 44](https://user-images.githubusercontent.com/20577339/42208170-72984a94-7ea3-11e8-9f49-6dae0e98b80a.png)

**Comment by asimonw** [comment]
@fannyBkane I think this might only be visible to admins / content owners. I'll look into it.
Good spot!

**Comment by Kimberley-Heath** [comment]
In my user test he came across it too so not just admins :(  If it is not a easy fix, I could just permanently delete the challenges but not ideal...

**Comment by asimonw** [comment]
@Kimberley-Heath Easy mitigation for now is to remove tags from archived challenges. (I've already done this now for some EMF test challenges.)
Should be fixed somewhere next week.

**Comment by Kimberley-Heath** [comment]
Oh yes good idea! I will do this, thanks

**Comment by asimonw** [comment]
LGTM. @fannyBkane wdyt ?

**Comment by fannyBkane** [comment]
LGTM @asimonw

**Comment by asimonw** [comment]
@sophielevens Actually, the same is happening for people, orgs and insights. You're not supposed to see inactive ones in matches.

And a second related issue is that challenges posted by the person themselves also show up in matches.

So could you fix 2 additional things:
- No inactive people, orgs or insights should show up
- No challenges posted by the user should show up

**Comment by asimonw** [comment]
This should apply equally to the matches that show up on challenges pages. The same logic should be used.

**Comment by asimonw** [comment]
@sophielevens if there's only time to look at one of these, the last point "No challenges posted by the user should show up" is the most urgent one :)

**Comment by Danwhy** [comment]
@asimonw Do you have an example of a challenge showing up in the matches of the user that created it? I can't seem to get it to happen, and looking at the query we're using, it should have already been accounted for

**Comment by asimonw** [comment]
@Danwhy You're right.. in the confusion of testing different options I must have fooled myself.

In that case, nothing's too urgent anymore in this issue. How much time would the first point take? It must be very similar to filtering out inactive challenges. Same for people, orgs and insights.

**Comment by Danwhy** [comment]
@asimonw It should be quick enough that I can get it done now. Although insights will be different as they come from the DAM API, so I'm not sure how to check if they're inactive

**Comment by asimonw** [comment]
@Danwhy I think you do that already for the insights in Explore, If not, we should create an issue for that 😉 

I can tell you which field to track. On the other hand, just doing it for people and orgs for now would already help a lot. We can deal with insights in another way for now, by simply removing them from the cello collection on our DAM.

**Comment by asimonw** [comment]
@Danwhy For insights there's a field called `enabled`. But happy to create a new issue for that and make sure those are filtered out everywhere (matches, explore, search) at a later time.

**Comment by asimonw** [comment]
@Danwhy from the commit it seems that this does not include insights at the moment right?

Are we currently filtering out insights with `enabled=false` in Explore?

**Comment by asimonw** [comment]
Apart from that LGTM!
