### ISSUE TITLE
Selecting "Choose interests" on IE11 not working

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1467]
Several users have reported that clicking on "Choose interests" on the screen after consent has no effect on IE11. It's likely that this means that the modal doesn't activate in other places either.

A very similar issue has popped up before (#875 in case it's related).

**Comment by Kimberley-Heath** [comment]
Sorry, still doesn't seem to work... @asimonw @sophielevens 

I tested Choose interests/ edit interests/ edit tags on challenges...
