### ISSUE TITLE
NODE_ENV - what's it for and is it needed?

### ISSUE THREAD

**Issue by mk4111** [emfoundation/ce100-app#152]
NODE_ENV has been used so that the [tests don't interact with the production environment](https://github.com/emfoundation/ce100-app/issues/113). But is this needed?

I thought that on deploy, the tests were only run in Travis - which has its stand alone testing environment - which means that it is separate from the Heroku Redis DB?

It would be great to get some clarification on this and to know what best practises there might be, and what people do in general when testing in development and production :)

**Comment by JMurphyWeb** [comment]
@mk4111  
I explained the use of the node_env here: https://github.com/emfoundation/ce100-app/issues/126

**Comment by JMurphyWeb** [comment]
more specifically : https://github.com/emfoundation/ce100-app/issues/126#issuecomment-246716201

**Comment by JMurphyWeb** [comment]
> Hapi has changed the default settings with the latest update (which we now have).

isSecure -> now defaults to true
isHttpOnly -> now defaults to true

From my investigating (limited knowledge) isHttpOnly doesn't affect how a user interacts with the app as we are not interpreting the cookie client side, so we can leave that as true.

isSecure: true doesn't administer a cookie on local host with current setup. I wonder if is ok to set to false for now. Maybe something like this:

isSecure: process.env.NODE_ENV ? false : true
Then only keep NODE_ENV environment variable locally? Maybe there is a better way..

**Comment by mk4111** [comment]
@JMurphyWeb - that makes a lot more sense to me now - I thought it was more to do with databases! I remember that issue now, and have made the link in my mind :) Thanks @JMurphyWeb!
