### ISSUE TITLE
Implement system which allows views to adapt to different scopes and permissions

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#157]
To clarify: 
 - scopes: ['admin', 'primary']
 - permissions: eg primary has logged in and views their own org (editable) or views a different org(non-editable)

At the moment i have modelled it in handlers: 

When viewing an organisations details: 
```
      var editable = { editable: organisation_id === orgId || request.auth.credentials.scope === 'admin' };
```

Then pass the view the above object.

I was hoping to pass down the scope to each view and let handlebars deal with the logic, but with handlebars' limited operations it would have had make use of helpers.

What do you think of above implementation @mk4111 @nelsonic ?

**Comment by JMurphyWeb** [comment]
Linked to #57 #48

**Comment by JMurphyWeb** [comment]
I have changed the auth.js file. We now have access to the logged in users id, scope, organisation_id via:
```
  var loggedIn = request.auth.credentials;
  loggedIn.userId,  loggedIn.scope,   loggedIn.organisation_id,  
```
Which i am using:
```
var editable = { editable: loggedIn.organisation_id === orgId || loggedIn.scope === 'admin' };

```

**Comment by mk4111** [comment]
Cool - this looks good! :D

**Comment by JMurphyWeb** [comment]
Having looked a bit more at the edit org view, I was wondering if we could always send some info to handlebars:

if it is a primary user that is logged in viewing their own org:
```{ permissions: {scopePrimary: true, editable: true } } ```

if it is a primary user that is viewing a different org
```{ permissions: {scopePrimary: true, editable: false } } ```

**Comment by mk4111** [comment]
That's true - we could use that to determine whether to display the edit buttons too (public and private view)

**Comment by JMurphyWeb** [comment]
ye and could help determine which navbar..

**Comment by JMurphyWeb** [comment]
I have decided on a method and will look at how it works when implementing #48
