### ISSUE TITLE
Match challenges with challenges

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#16]
As a primary user, I get an overview of which of my challenges matches other member’s challenges, So that I can see how many other members share a related challenge and may be potential collaborators in solving it.

**Comment by iteles** [comment]
+ Logic for matching challenges with challenges
+ Styling for matched challenges (desktop & mobile)
+ Making sure back button still working correctly

**Comment by iteles** [comment]
@fannyBkane to confirm final icons

**Comment by iteles** [comment]
@asimonw For now do we want to limit the number of challenges we display?
In future sprints we can add a 'see all matching challenges' section as well.

**Comment by asimonw** [comment]
@iteles Good suggestion. The same limit as for orgs would be fine for now, thanks.

**Comment by SimonLab** [comment]
@asimonw @iteles I quickly check if there was a limit when we match the organisations but I can't see any at the moment, do you know if there is one at the moment?
I will check with more detail just in case I missed something.

**Comment by asimonw** [comment]
@SimonLab I think there was a limit set, but I can't find a reference to it in a previous issue at the moment.. I think the code would be the ultimate judge :)

**Comment by Cleop** [comment]
@asimonw - in the user story for this issue it only explicitly mentions primary user's being able to see matches, is this still the case? Or can admins also see matches?

Meaning: secondary users can never see matches and primary users cannot see matches for challenges linked to organisations apart from their own.

**Comment by asimonw** [comment]
@Cleop As discussed, admins and content owners should also see matches for all organisations, as they already do. Could you let me know how it's set up for secondary users for now?

Keep the behaviour for secondary users as it is for this issue.

**Comment by asimonw** [comment]
@SimonLab Similar issues to #919 

Challenges matching with Challenges doesn't seem to return the results I expect, eg:
+ Ch1 Biochem + Anaerobic, Ch2 Biochem, no match found. 
+ If I then add Bioenergy to Ch2, Ch2 matches with Ch1 but Ch1 still shows no match for Ch2. 
It's as if certain tags are needed to get the matching to work.

**Comment by SimonLab** [comment]
Thanks for spotting this @asimonw . I think the issue is linked not directly of the way we match elements but on the way we display them. The following file: https://github.com/emfoundation/ce100-app/blob/master/templates/helpers/hasMatches.js is used to know if there are any matches and to display or not the results. The way the condition is currently done is not right and I've just created a PR for that which will check in more details if we have any results

**Comment by asimonw** [comment]
@SimonLab Another issue: it looks like challenges by the same organisation are also being returned as matches. This was not made explicit in the requirements, but could we exclude matches from the same organisation? On staging, you can see that "Challenge Number 2" and "Challenge Number 3" appear in each other's match list.

**Comment by iteles** [comment]
Adding an extra hour for https://github.com/emfoundation/ce100-app/issues/16#issuecomment-338697964
