### ISSUE TITLE
Dynamic joi validation models for same endpoints for admin and primary

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#162]
for `/orgs/id/edit` post request.

Admin can edit name(required) and mission_statement
Primary can edit mission_statement

Is there a way we can use a different model depending on who has made the request?

Admin model:
```
  payload: {
    name: Joi.string().min(1).required(),
    mission_statement: Joi.any().optional()
  }
```
Primary model
```
  payload: {
    mission_statement: Joi.any().optional()
  }
```

**Comment by JMurphyWeb** [comment]
uneditable inputs is not really an option/

**Comment by mk4111** [comment]
Hi @JMurphyWeb - I see the issue here... Do you think Hapi's [''Route Pre-requisite"](http://hapijs.com/api#route-prerequisites) could help us solve this issue?

**Comment by JMurphyWeb** [comment]
@mk4111 thanks for looking into! i was just going through the docs myself. I will check your link after but i think that sounds good. Will keep you updated 👍

**Comment by mk4111** [comment]
@JMurphyWeb thank _you_ :D

**Comment by JMurphyWeb** [comment]
eventually worked out how to pass validate an object with functions as values:

```javascript
var Joi = require('joi');

module.exports = {
  payload: (value, options, next) => {
    var scope = options.context.auth.credentials.scope;
    return Joi.validate(value, schema[scope], next);
  }
};

var schema = {
  admin: {
    name: Joi.string().min(1).required(),
    mission_statement: Joi.any().optional()
  },
  primary: {
    mission_statement: Joi.any().optional()
  }
};
```

**Comment by JMurphyWeb** [comment]
I will add it to the relevant pr

**Comment by JMurphyWeb** [comment]
#163 should resolve this issue
