### ISSUE TITLE
Change Password implementation

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#166]
When a primary user changes their password, they must confirm their `old_password`, then type their new password **twice** `new_password` & `confirm_new_password`.

validation will take care of:
new_password min 6 characters and
identical new_password and confirm_new_password

In the handler I was planning on:
Getting the user from redis
bcrypt comparing old_password with the existing password
  throw if error
  reply if  incorrect old password
bcrypt hash new_password
  throw if error
  store new password to redis
  reply with 'updated your details'

I wasn't planning on changing/updating their session token.

**Comment by JMurphyWeb** [comment]
@nelsonic could you check over my planned implementation please?

**Comment by nelsonic** [comment]
@JMurphyWeb firstly, my _understanding_ is that _changing_ password is not an MVP requirement ... 
(_or at least I cannot find it in the backlog ..._ https://github.com/emfoundation/ce100-app/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20password )
I know this `old password`, `new password` + `repeat new password` approach is used by quite a _few_ sites but I'm _not_ a fan of this approach ... it does not add "_security_" ... it just forces people to type more ... 
I think updating your password should use the same "_flow_" as re-setting it 
i.e. an email is sent to their email address, they click on a link and are able to re-set their password. 
which _is_ a feature in our backlog: https://github.com/emfoundation/ce100-app/issues/7

So... implement password reset then make the feature available inside the app for people who want to update/change their password they have to access their email to complete the action. 

Thoughts?

**Comment by JMurphyWeb** [comment]
I think I got a bit carried away with the wireframes, I think you are right in that the change password isn't part of backlog so I won't put any work into it and closing this issue.

Wireframes do contain a reset password feature:
https://app.zeplin.io/project.html#pid=57ac9b5692d0c316520caeca&sid=57cdad1cc8057a6c67aa66a3
