### ISSUE TITLE
Copy updates

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#176]
You can find some copy updates here. Images only serve to indicate where the copy should go, but are not "designed."

[Google doc](https://docs.google.com/a/ellenmacarthurfoundation.org/document/d/1581gfeX6cyrbOJjuqDq_Ds6vcyH4qO1alzJ5wUw1m54/edit?usp=sharing)

@JMurphyWeb do you have a gmail account? Otherwise we'll need to share the doc with you in a different way.

**Comment by mk4111** [comment]
@asimonw - could I ask where the user should be linked to (from the login page), to access the 'mobile app for the event'?

**Comment by asimonw** [comment]
@mk4111 See the [wireframe](https://zpl.io/ZnMkwr). It's at the bottom right.

Looking at the copy updates again, there is no need to remove the text underneath the logo on the login screen anymore (apologies if you already did this..). We did this because we didn't expect matchmaking functionality yet, but now that it's there, the text makes sense 😉

**Comment by mk4111** [comment]
Hi @asimonw - sorry I don't think I explained myself very well - could you please tell me the url to which you would like to user to be linked to, on clicking that piece of text?

Ok, I'll reapply this :)

**Comment by mk4111** [comment]
@asimonw - as the userflow for adding tags is a little different, I wonder if some of the text prompts are still as relevant to the new userflow... I've added a few comments and suggestions to the docs - could you please have a look if possible and let me know what you think? Thank you!

**Comment by asimonw** [comment]
@mk4111 Sorry, re-reading your question, that was clear actually.. I'll check and let you know asap.
And I'll go through the doc this afternoon as well, thanks!

**Comment by mk4111** [comment]
@asimonw - thank you!

**Comment by asimonw** [comment]
@mk4111 The previous link I provided in the google doc is no longer used, as I expected. This is the new one https://ce100events.zerista.com

**Comment by mk4111** [comment]
Hi @asimonw thank you!

**Comment by mk4111** [comment]
I think all the relevant copy updates have been made and are now merged into master
