### ISSUE TITLE
Remove 'cancel' buttons and replace with 'x' in header

### ISSUE THREAD

**Issue by iteles** [emfoundation/ce100-app#187]
As a user, I don't want to have a 'cancel' button right next to the 'Save' button as I may click this accidentally and lose all my data.

This should be a 'x' near the top of the page:
https://app.zeplin.io/project.html#pid=57ac9b5692d0c316520caeca&sid=57cdad239561cc384a69e7de
<img width="330" alt="emf-ce100-cancel-button-cross" src="https://cloud.githubusercontent.com/assets/4185328/18795172/2ae7c954-81bb-11e6-9e77-d23430207620.png">

**Comment by JMurphyWeb** [comment]
This is resolved in #194
