### ISSUE TITLE
Make general capitalisation across the application consistent

### ISSUE THREAD

**Issue by iteles** [emfoundation/ce100-app#190]
The EMF convention is for the first letter of a phrase or menu item to be capitalised and the rest not: e.g. `Add challenge` and not `Add Challenge`.

**Comment by asimonw** [comment]
I don't see a change

**Comment by asimonw** [comment]
@iteles Could you clarify what has changed here? I still see places where not only the first word is capitalised. The tags for instance. Although, we will send you an update of the list of tags soon, so we could just send them over with correct capitalisation.
