### ISSUE TITLE
Browse orgs and challenges using tags as filters

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#20]
As a primary user, I can browse organisations and challenges from a central interface, with tags as a filtering option, so that I can see and explore all the members, challenges and opportunities in one place.

---

Update as requested by @fannyBkane 
View on Zeplin: https://zpl.io/Z1A9eFl

A couple of things:
- [x] Can you change tags to lowercase, EXCEPT for parent tags on the 'select tag view' ( legibility is improved in lower case, especially for longer tags)
- [ ] Browse challenge view: can you hide the challenge description on the card? (in the design we hid the description on the challenge cards in the list view as they may end up being very long https://zpl.io/ZEOhGN)
- [x] Add challenges created by that users own organisation to the list of challenges.

**Comment by LucyJW** [comment]
How is this different to #20? I think we could clarify the difference in the user story more clearly.

**Comment by asimonw** [comment]
The difference is the starting point. In this story, you start by navigating to a "directory," in #21 you start by clicking on a tag in someone else's profile or a challenge. Once this story is implemented, #21 should be quite straight forward, but still useful to keep it as a separate story, I think.

**Comment by asimonw** [comment]
![fullsizerender_2](https://cloud.githubusercontent.com/assets/15235804/17744851/6dccc102-64a1-11e6-8df6-42def9e7df7e.jpg)

Clicking on Explore (used to be Browse) shows a screen with broadly three options. Either show all orgs (alphabetically, lazy load on scroll if necessary), all challenges (latest first) or select a tag. They all lead to the same view in a different state. The view has a tag drop down at the top (default is no filter selected, i.e. "All") and a drop down to choose between orgs or challenges (default is orgs). I'll call the second drop down the type selector

More precisely (action -> state):
* All challenges -> Tag filter: default (All), type selector: challenges
* All orgs -> Tag filter: default (All), type selector: orgs
* Select tag -> Tag filter: selected tag, type selector: default (orgs)

Hope that makes sense.
