### ISSUE TITLE
add challenge card with no tags bug

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#200]
if we add a challenge card, but don't add tags, then click on profile, we get an error.

**Comment by mk4111** [comment]
@JMurphyWeb - I'm going to work on this now. Can I have the go ahead please? Thanks!

**Comment by JMurphyWeb** [comment]
ok

**Comment by mk4111** [comment]
Couldn't simulate this issue - will revisit once #199 is merged in.

**Comment by JMurphyWeb** [comment]
We never found this bug again so was fixed either intentionally or unintentionally .
