### ISSUE TITLE
Populating db happening twice

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#207]
In our server.js we run our initialise function which sets up the db with some mock data. This is handy for development and for now useful for the client to quickly test what we have built.

However when running the tests, we require server.js as well as calling our pre test setup function. Basically the data is injected twice when running tests.

For now i have split the starting of the server and the initialising of the DB back into a start.js file.

Happy to change this if/when a better solution is recommended.

**Comment by nelsonic** [comment]
Apologies for not _seeing_ this issue yesterday. (_too many github notifications..._)

In [`/test/helpers/set-up.js#L8`](https://github.com/emfoundation/ce100-app/blob/d0df7c6654e52978d02bbdededc24e90e2a837f7/test/helpers/set-up.js#L8)
Simply add a _check_ before running the script ...
```js
if(process.env.DB_INIT) { // see: https://github.com/emfoundation/ce100-app/issues/207
  // run the init steps

  // then set the DB_INIT value to ensure it only gets run once
  process.env.DB_INIT = 'done';
}
```
This _prevents_ the `dbSetup.initialiseDB` from being run multiple times without "_hiding_" the issue in the `start.js` file which has no inline comments justifying it's existence.

**Comment by SimonLab** [comment]
@JMurphyWeb I think this issue is not relevant anymore as we use mock-data to populate our database, could we close this issue?
