### ISSUE TITLE
"Select Tags" view - existing tags not displayed correctly

### ISSUE THREAD

**Issue by mk4111** [emfoundation/ce100-app#208]
In the userflow:
- Add/Edit challenge card tags
- Save challenge card tags
- Edit organisation tags
- Save tags

When we display the edit (add/remove) existing organisation tags view, the existing tags for _challenges_ is displayed instead of those for _organisations_. Seems to be saving correctly, although this needs to be checked.

**Comment by mk4111** [comment]
@JMurphyWeb - I'm going to look into this issue next!

**Comment by mk4111** [comment]
Happens in another userflow:
- add a challenge card (with tags)
- add a second challenge card (with tags)
- edit second challenge card
- edit first challenge card --> tags from second challenge card also displays.

Unless 'unchecked' the displayed challenge cards are also saving.

**Comment by mk4111** [comment]
Following on with the userflow above, we find that the tag from the tags that _aren't supposed to be there_, are the tags that are selected when editing the second challenge card _first time around_ .

Tags that are added when editing that challenge are _not_ displayed.

**Comment by mk4111** [comment]
N.B. Google Chrome is used in the above examples.

Now going to try and debug with Firefox.

**Comment by mk4111** [comment]
This issue persists with Firefox too.

**Comment by mk4111** [comment]
Update - the tags displayed on adding a _new_ challenge (challenge 3) are the accumulate of the previous two --> the same tags object is being referenced every time.

**Comment by mk4111** [comment]
tags.json was being 'required' into our .js files as 'require('path-to-tags.json')' --> a copy is required in _once_ and shared across different .js files _globally_.

**Comment by mk4111** [comment]
Fixed by switching out require for fs.readFile! :tada:

**Comment by JMurphyWeb** [comment]
Interesting.

**Comment by JMurphyWeb** [comment]
This is as good as in review, @mk4111 can you please add the label once the conflicts are fixed and i am assigned?

**Comment by mk4111** [comment]
Closing issue - has been merged in.
