### ISSUE TITLE
Use tags to explore more

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#21]
As a primary user, I can click on a tag in a profile page or challenge to see all profiles or challenges related to that tag respectively, so that I can see all the other members (and challenges) that are active in the areas I’m searching and make my own matches.

Related to #20

**Comment by asimonw** [comment]
Should probably be broken down into two stories, one for organisations and one for challenges.

**Comment by asimonw** [comment]
@JMurphyWeb This seems to work fine for challenges, but when clicking on a tag which belongs to a profile, I also get sent to the list of challenges with that tag. This should be the list of orgs with that tag.

**Comment by SimonLab** [comment]
Thanks @asimonw for spotting this! The new version is now deployed. At the moment not a lot of organisation share the same tag, but there is "design for disassembly" tag which is share by multiple organisations
