### ISSUE TITLE
'requiring' in mockData files --> fs.readFile(Sync)?

### ISSUE THREAD

**Issue by mk4111** [emfoundation/ce100-app#210]
In light of #208, it _might_ be a good idea to switch out the way that we are currently reading in mockData files (```var fileName = require('path-to-file')```) to ```var fileName = readFileSync(path.join(__dirname, 'relative-path-to-file'))```

@JMurphyWeb, what are your thoughts on this?

**Comment by JMurphyWeb** [comment]
Sounds good indeed.

**Comment by mk4111** [comment]
Closed in favour of #211
