### ISSUE TITLE
tags.json --> save to redis!

### ISSUE THREAD

**Issue by mk4111** [emfoundation/ce100-app#211]
edit csv-to-json.js to save the object to redis (instead of a .json file)

-------------

TODOs:

- [x] ~~edit csv-to-json.js file so that we're saving tags state to redis instead of to a .json file.~~
- [x] edit csv-to-json --> rename file to save-tags.js (read in .json, and save to redis)

**Comment by mk4111** [comment]
I'm going to have a :eyes: at this :sunny:

**Comment by mk4111** [comment]
@JMurphyWeb - I've just updated the top description with my thoughts on saving the tags to the db. I've got it working as saving as a list, but I'm wondering what the benefits of keeping/not keeping a history of tag 'updates' in redis might be... Can I pick your brains on this please? Thank you <3

**Comment by JMurphyWeb** [comment]
Personally i'd say not to worry about storing a history just yet. It is a nice feature but maybe not MVP?

**Comment by mk4111** [comment]
@JMurphy, cool - I'll go with that then :) Thanks!
