### ISSUE TITLE
Apply for AWS SES (Email Sending) Limits Increase

### ISSUE THREAD

**Issue by nelsonic** [emfoundation/ce100-app#212]
When an account is _first_ registered for AWS SES https://aws.amazon.com/ses/ it is placed in a "sandbox" to avoid people sending _too_ many emails (_i.e. "spam"_) in order to send _more_ than the daily sandbox limit we need to send a _request_ to AWS support stating how many outbound emails we expect to send per day/month. this only takes 5 mins to do.

Required for: https://github.com/emfoundation/ce100-app/issues/42
and to avoid: https://github.com/emfoundation/ce100-app/pull/194#issuecomment-249827198

See: https://aws.amazon.com/ses/faqs/  (_search for "apply" in section 4 and click the link_)

**Comment by mk4111** [comment]
@nelsonic  and @JMurphyWeb am :eyes: now <3

**Comment by mk4111** [comment]
So the daily quota 200 emails ([see here!](http://docs.aws.amazon.com/ses/latest/DeveloperGuide/request-production-access.html))

In [this link](http://docs.aws.amazon.com/ses/latest/DeveloperGuide/manage-sending-limits.html), there's an example with an arbitrary(?!) limit of 50,000 so I'm thinking of requesting for an increase to this amount...

@nelsonic do you think that's enough? :blush:

**Comment by mk4111** [comment]
I've made a request for our quota to be raised to 50,000 but would be happy to submit a new request if needed! Hope that's ok!

**Comment by mk4111** [comment]
I'll unassign myself when we are granted the request

**Comment by mk4111** [comment]
Sending quota has been updated to 50,000! Woohooo! :tada:

@nelsonic is this issue ok to be closed?

**Comment by nelsonic** [comment]
@mk4111 would you mind adding a sub-section with a paragraph explaining why you had to do this and how you did it to: https://github.com/dwyl/sendemail#which-email-service-provider (_please/thanks_!)

**Comment by mk4111** [comment]
I've just made a PR on this, ([#48](https://github.com/dwyl/sendemail/pull/48))
If you could have a look and let me know what you think, I'd really appreciate it! Thank you @nelsonic !!
