### ISSUE TITLE
confirm password validation

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#214]
```
module.exports = {
  payload: {
    password: Joi.string().min(1).required(),
    confirmPassword: Joi.string().min(1).required()
    // TODO: make min 6 & password match confirmPassword
  }
};
```

This task is still outstanding

**Comment by iteles** [comment]
@jmurphyweb This is pretty impenetrable to anyone outside the project. Where does the requirement to have a minimum number of characters come from? What does `password match confirmPassword` mean?

**Comment by JMurphyWeb** [comment]
ensure that the user's password is the same as their confirmPassword.

No requirement for minimum characters, but it is literally changing that '1' to a '6' so it is no work and we presumed it would be nice to have. Can remove min characters?

**Comment by iteles** [comment]
If we already have intelligent error handling for it, let's keep them in 👍
