### ISSUE TITLE
Change from challenge.archived to challenge.active

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#217]
When the change was made: https://github.com/emfoundation/ce100-app/pull/199/files#diff-b00b2426ea4c5569a2f693c13130c545R10

I think the data booleans were not replaced with their opposite.  May need updating on your local branch @mk4111. Also wiki needs updating.

**Comment by JMurphyWeb** [comment]
Update: i think challenge number 4 was correctly change, but the rest weren't.

**Comment by mk4111** [comment]
@JMurphyWeb - what do you mean by the booleans being updated?

**Comment by JMurphyWeb** [comment]
Sorry it's not very clear but we discussed this on the day. I think it was just a small mistake when you changed the `archived` key to `active` the values were not changed.  

ie something that was `archived: true` should have been changed to `active: false`, but the keys were not updated to represent the new data structure, so we were left with `active: true` which isn't what you intended, except for challenge with `id: 4` which was updated.

This should be fixed in the later PRs and maybe even master now so i have added an in-review label.

**Comment by mk4111** [comment]
@JMurphyWeb - ah yes I understand now! I'll have a look into how this wording affects the structure of our code this morning

**Comment by JMurphyWeb** [comment]
this is already done @mk4111

**Comment by mk4111** [comment]
@JMurphyWeb - so we _don't_ need to fix this in the later PRs?

**Comment by JMurphyWeb** [comment]
It should already be fixed
