### ISSUE TITLE
Main feedback widget

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#22]
As a primary user, I should be able to send feedback from every page, so that I can easily tell the team how well the features are working or if I think something could be improved.

**Comment by asimonw** [comment]
![fullsizerender](https://cloud.githubusercontent.com/assets/15235804/17744553/1ae9f8ca-64a0-11e6-8bc8-936b57669faf.jpg)

Feedback widget on every screen. One text field. Should send email with sender email address and name pre-populated. Ideally, it would also indicate the page the user was on.

**Comment by iteles** [comment]
As discussed, the MVP of this is a simple `mailto` link

**Comment by JMurphyWeb** [comment]
This is very soon to be in review. @mk4111 can you push up and change the label when you assign me to look over please?
