### ISSUE TITLE
bugs and todos

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#220]
Will flesh this issue out but I have noted down some todos as a result of the work i did this morning:

Some things to do that I will go onto address in the next PR:

- [x] add tests
- [x] check tagsData change whether it should be added elsewhere
- [x] put reusable browse functions in helpers
- [x] remove active and contact from primary user contact view

~~- [ ] check outstanding todos in the project~~
~~- [ ] add filter to browse orgs, click organisations, filter disappears~~ --> see #226
~~- [ ] add query validation on new browse routes --> see #225~~

**Comment by iteles** [comment]
@JMurphyWeb All of the checklist items here are closed. Is this `in-review`?

**Comment by JMurphyWeb** [comment]
is now 👍
