### ISSUE TITLE
Protecting against script injections

### ISSUE THREAD

**Issue by mk4111** [emfoundation/ce100-app#228]
Related to #32

This is something we're lacking in all of our input fields and something we should probably implement. Should this be in future enhancements? Seems like a fundamental to-do too...

**Comment by SimonLab** [comment]
We are now using [pg-escape](https://www.npmjs.com/package/pg-escape) to escape the values from the forms. @mk4111 can we close this issue?

**Comment by mk4111** [comment]
Yup!
