### ISSUE TITLE
Permissions on edit challenge view

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#230]
every primary user can GET the challenges/id/edit view by manually typing in challenges/number/edit

Only a primary who created the challenge can edit the challenge card.  In other handlers we have used the getPermissions function to work out if the user can GET a view, so that might be an option when it comes to fixing.

**Comment by mk4111** [comment]
:eyes:

**Comment by mk4111** [comment]
Problem: non-primary users can view a challenge's edit page + also submit an edit to the challenge.

**Comment by mk4111** [comment]
closing issue as fix has been merged into master
