### ISSUE TITLE
admin cannot edit tags on an existing challenge card

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#239]
This issue may have arisen since me adding error-handling and possibly updating the validation models.

error:
`403 - Sorry, something went wrong, please retrace your steps.`

**Comment by mk4111** [comment]
:eyes:

**Comment by JMurphyWeb** [comment]
@mk4111 also the edit challenge view doesn't show the admins top navbar

**Comment by mk4111** [comment]
still? I'll look into it...
