### ISSUE TITLE
add new user, leading zero of phone number is dropped

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#242]
I think it at some stage it is being changed to a number as opposed to a string.

**Comment by mk4111** [comment]
:eyes:

**Comment by mk4111** [comment]
Seems that this happens only when the first digit is a 0.

**Comment by mk4111** [comment]
Error message doesn't seem to recognise that the input should be a phone number (spec: 11+ random digits between 0 and 9) 

![screenshot from 2016-10-06 14-06-41](https://cloud.githubusercontent.com/assets/13470325/19153365/2a5e4e28-8bce-11e6-93ac-cdf44dd56510.png)

**Comment by mk4111** [comment]
Looking at if Joi has a .phone() schema, like they do for email.

**Comment by mk4111** [comment]
https://github.com/hapijs/joi/issues/863

Link above explains that this problem can be solved with regex.

**Comment by mk4111** [comment]
Fixed!

Displays numbers starting with ```+44``` too
