### ISSUE TITLE
Admin creates new admin, gets attached to a user

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#244]
I did not select an org, but got attached to Fanta. It must be due to organisation_id being -1 and the user gets attached to the last org or something?

```
Hi Jack Murphy

Welcome to CE100! You've been added as a user of Fanta.

Click here to log in.

Alternatively, copy and paste the following link to access our log in page

Link: localhost:3000/people/activate/[hashed link]

Love, EMF
```

**Comment by mk4111** [comment]
:eyes:

**Comment by mk4111** [comment]
Seems that ```redis.LINDEX('organisations', orgId, (error, response) => ...``` where ```orgId === -1``` returns the Fanta organisation...

Strange because Fanta's id === 7

**Comment by mk4111** [comment]
organisations are now being queried for _only if_ orgId !== -1.

**Comment by JMurphyWeb** [comment]
is this in review?

**Comment by mk4111** [comment]
@JMurphyWeb - I've just finished testing, and am about to commit. I'll put an 'in-review' label once I've pushed up. Need to find out about method of creating PRs first though!

**Comment by JMurphyWeb** [comment]
Ahh ok nice!
