### ISSUE TITLE
Browse: Still says "Select tags" even after tag has been selected

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#249]
The selected tag should be shown at the top.
(Initially, it might be better to say "Showing all tags" like in mockups)

[See mockup](https://zpl.io/Z1nsDsm)

**Comment by mk4111** [comment]
Ties in with #250

**Comment by mk4111** [comment]
Ties in with #241 and #250

**Comment by JMurphyWeb** [comment]
This is fixed locally
