### ISSUE TITLE
Browse: toggling between orgs and challenges clears the tag filter. 

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#250]
Once a tag selection has been made, toggling between orgs and challenges clears the tag filter. The tag filter should be preserved.

User flow should be: select a filter --> see orgs for that tag --> click on challenges to see those for same tag
Appreciate that this might not have been clear from the info we've provided, hence not marked as bug.

**Comment by mk4111** [comment]
Related to #241
