### ISSUE TITLE
Profile: only (roughly) first two lines of challenge description should be shown

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#256]
Character count to be tested..
Tapping the challenge opens a new view which shows the full description.
See [here](https://zpl.io/ZEOhGN) and [here](https://zpl.io/Z2kmBO6).

**Comment by JMurphyWeb** [comment]
should be closed with the new slimmed down challenge card.

**Comment by asimonw** [comment]
@JMurphyWeb What's the implemented behaviour exactly? It looks like no description is shown at all on the profile and full description in the card itself, which is fine.

There is no view which only contains part of the description, right? This is not as described in this issue, but would be fine for now actually.

**Comment by JMurphyWeb** [comment]
@asimonw sorry i missed this. Yup you are right, this challenge preview doesn't exist anymore.
