### ISSUE TITLE
More user friendly 401 screen

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#257]
The 401 screen has title "401" and has admin nav. Should be more user friendly (with at least a title). No nav needed, just link to login.

**Comment by nelsonic** [comment]
@asimonw would you consider simply _redirecting_ to the `/login` page ?
(_or do you prefer to display an error page with a link to the login page_?)

**Comment by asimonw** [comment]
@nelsonic yes that would be fine for now. Some form of feedback (potentially a flash message) could be nice, but lower priority.

**Comment by SimonLab** [comment]
The redirection to the login page is been implemented with #485
