### ISSUE TITLE
Not possible to access archived challenges

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#268]
Currently, it's possible to archive a challenge, but there is no way to access the list archived challenged.

No delete button/functionality needed.

![screen shot 2016-11-14 at 12 28 28](https://cloud.githubusercontent.com/assets/12638261/20264935/ee68a420-aa65-11e6-8363-23687e90eaa1.png)

**Comment by JMurphyWeb** [comment]
@asimonw - Can we please ask you the following?

- How do we access the above view? 
- Can we clarify that this view is only accessed by primary users, for challenges that they or any previous primary users of their organisation, have created?
- Should admin have a similar view for all challenges? (We couldn't find a view which suggested so)
- Should admin have a view for _deleted_ challenges too?
- Should the following views be displayed for primary and/or admin users?

Thank you!

**Comment by asimonw** [comment]
In same order as the questions:

* Archived challenges can be accessed from the [profile page](https://zpl.io/Z231EN8). See link at the bottom.
* Exactly as you state it
* Admins don't need access to this
* Deleting a challenge removes it from the db, so no-one, not even admins, can have access to it, BUT, we decided that "delete" is not necessary at this stage, we'll demote this to priority 3. So please build the view *without* the delete functionality for now
* This would only be for primary users, but as above, not a priority 2

Hope that clarifies things. I'll create another issue for the delete functionality.

**Comment by JMurphyWeb** [comment]
Firstly I want to add the navigation to this view into the org profile view:
![screen shot 2017-01-09 at 12 08 04](https://cloud.githubusercontent.com/assets/12638261/21766104/606621ea-d664-11e6-994d-07adb920c496.png)


This should only be viewable by primary users of that org. 

I am thinking that the URL could be:
`/orgs/id/challenges?archived=true`
or 
`/orgs/id/archived-challenges`

**Comment by JMurphyWeb** [comment]
I have implemented a basic navigation card in the org details view. It needs a bit of tweaking, specifically the height and the colour of the anchor text.

**Comment by JMurphyWeb** [comment]
We need a new query on the challenge plugin which must return all inactive challenges that are linked to a given org.

**Comment by JMurphyWeb** [comment]
https://github.com/postgres-plugin/challenges/pull/69

**Comment by JMurphyWeb** [comment]
@asimonw do you want the archived challenges to look as they do in the wireframe (with the tags and description) or like they do in the app without the extra info.

I guess your answer may also answer the next question: 
Should the challenges be clickable so that the primary user can see it in the challenge details view?

**Comment by asimonw** [comment]
@JMurphyWeb They can indeed be like the other challenges, without the extra info (the mockups weren't updated to reflect this).

No need to give an extra indication that it's not active for now. The card will just have an "Unarchive" rather than an "Archive" button.
Also no need to show suggested matches, as the challenge is likely not relevant anymore to the organisation, but if it's easier to show them, that's fine too.
Keep this feature simple: the most important point here is that users still have access to archived challenges and re-activate them if necessary.

**Comment by JMurphyWeb** [comment]
Ok thanks@asimonw so do the views above look ok? is there anything to change?

**Comment by JMurphyWeb** [comment]
No archived challenges:

<img width="325" alt="screen shot 2017-01-19 at 16 16 14" src="https://cloud.githubusercontent.com/assets/12638261/22114811/a92dd30e-de62-11e6-8508-a68e8d6192b1.png">

**Comment by asimonw** [comment]
@JMurphyWeb Yes for now that looks fine.

**Comment by asimonw** [comment]
@JMurphyWeb After archiving or unarchiving a challenge, the user is taken to the Explore challenges page. Could this be the profile instead please?
