### ISSUE TITLE
Not possible to log out

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#269]
We were thinking that this could be a link on the [Settings page](https://zpl.io/2a86OV).

**Comment by JMurphyWeb** [comment]
Link: https://app.zeplin.io/project.html#pid=589c772f8ad534321d652f04&sid=589c8a9581d4a5831f1889a5

**Comment by JMurphyWeb** [comment]
- [ ] Add logout link to user settings
- [ ] Delete cookie
- [ ] Redirect to Login
- [ ] Possibly remove session from Redis (probably not necessary)

**Comment by JMurphyWeb** [comment]
This was added in #715
