### ISSUE TITLE
Quick contact list

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#27]
As a primary user, I can see a list of other users with corresponding contact details, so that I can quickly get in touch with people that I’m interested in collaborating with

**Comment by jo3murphy** [comment]
@asimonw do we somewhere define 'primary user' at least for now? Given conversations around user / org profiles this could be helpful especially as MVP evolves

**Comment by jo3murphy** [comment]
Contact details:
- First name
- Surname
- Preferred email address 
- Job title (?)
- Preferred contact number (?)

**Comment by asimonw** [comment]
@jo3murphy I'll add some context to the idea of a primary user in #2 where it is first mentioned.

**Comment by LucyJW** [comment]
@jo3murphy @asimonw Having quick access to phone numbers came out as a key piece of feedback from user research so I would suggest including it if possible

**Comment by asimonw** [comment]
Agreed @LucyJW

**Comment by mk4111** [comment]
Hi @/all! Will this be a list of _all_ primary users? i.e. with no filters applied?
Will the expertise tags of each primary user be displayed along with their contact details?
If not, how would a primary user know whether they might be interested in talking to another primary user?

**Comment by asimonw** [comment]
@mk4111 Since the expertise tags characterise organisations and not the primary users themselves, this list will be a simple contact list without tags. This might be a bit confusing at first because there will be one user per org. In a future iteration, we will probably allow users to tag themselves with expertise/interests as well and then it will make sense to also filter users by tags.

**Comment by mk4111** [comment]
@asimonw that makes a lot of sense!! Thank you!! :)

**Comment by asimonw** [comment]
![fullsizerender_1](https://cloud.githubusercontent.com/assets/15235804/17744775/18e2d9ba-64a1-11e6-81fc-e6f08088142e.jpg)

List of users: first name, last name, job title and org displayed by default. Items expand on click/tap revealing email and phone number as well.
