### ISSUE TITLE
First screen after login

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#28]
As a primary user, the first screen I see after logging in signposts and explains the main things I can do on the platform (share a challenge, browse or go to profile), so that I understand what the platform is about and I have quick access to its main features.

[link](https://zpl.io/2nidYL)

**Comment by mk4111** [comment]
@asimonw could you explain in a little more detail what you mean by signposts?
Should they be like a 'step-by-step' guide on navigating and using the platform?
Should they display every time a user logs in, or only on the very first time that they enter the platform?

**Comment by asimonw** [comment]
@mk4111 Have a look at the wireframes as well. By signpost we just mean a title and some description of the feature. These would then link to the different relevant screens (so, much less than a step-by-step guide at this point, although it might be a nice idea once the features get richer).

We would show this screen every time someone logs in. It's kind of a simple home screen, highlighting the most important items in the nav. We might replace this by a "dashboard" once more features exist. Especially on first login it makes sure people don't land on an empty profile with no context.

**Comment by mk4111** [comment]
Got it, thank you @asimonw!

**Comment by mk4111** [comment]
Redirect to landing page from:
- /activate
- /login
- on click of logo on top left of top-nav

**Comment by mk4111** [comment]
@asimonw - am I correct in assuming that this /landing page is specifically for primary and secondary users?

When an admin logs in, would you like them to have the same view, or would you like them to go straight to '/orgs' as it currently does? Or maybe another view?

**Comment by mk4111** [comment]
Also @asimonw, just to clarify, do we want to bottom nav to only show when the users have scrolled the whole length? Or would we want it to be a 'sticky' footer, so it is stuck to the bottom of the user's view as we scroll (as is the case for challenges list and orgs list right now)? 

Thank you!

**Comment by mk4111** [comment]
Got the route, handler and html file working right.

Now applying CSS!

**Comment by asimonw** [comment]
@mk4111 This screen is indeed not for admins. Behaviour for admins can stay as it is.

The bottom nav should always be sticky, as it currently is on other pages. Thanks!

**Comment by mk4111** [comment]
@asimonw yay! Thank you!

**Comment by mk4111** [comment]
The wireframes seem to have just been updated.

**Comment by asimonw** [comment]
@fannyBkane Could you have a look at this? Without the down arrows, people might not know that there's more further down the page.

**Comment by asimonw** [comment]
Also @mk4111, the first link to "Fill in your profile" should link to the org profile, not to the user's settings. For secondary users, the text should be slightly different. Or we don't show this section at all.

**Comment by fannyBkane** [comment]
@LucyJW could we have a look at this?

**Comment by asimonw** [comment]
@mk4111 The screen looks fine for primary users, but as mentioned above, the first button should go to the org profile (no need to add down arrows in at the moment, to be reviewed later). 

For secondary users, could you just remove the sections "Tell us about you" and "Share a challenge"?

Also, the CE100 logo at the top left should be a link to this home screen on other pages (I thought that this was working before, but not anymore). Thanks!

**Comment by JMurphyWeb** [comment]
Logo in nav covered in #637
