### ISSUE TITLE
User settings

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#29]
As a primary user, I can easily navigate to my user settings where I can manage my first name, last name, title, phone number and notification preferences, so that I can update my personal information and personalise my experience of the platform.

**Comment by JMurphyWeb** [comment]
Navigation covered in #56 

Timebox excludes edit password and logout functionality.

Primary user can edit their details. 

<img width="366" alt="screen shot 2016-09-07 at 18 42 11" src="https://cloud.githubusercontent.com/assets/12638261/18322494/e44524c0-752a-11e6-9693-314550ee08ce.png">

**Comment by asimonw** [comment]
@iteles For change pwd, we had decided to provide a link (like a forgotten pwd link), but that's currently not present. 

Also logout is missing. Turns out that that's a quite handy thing to have for testing..

**Comment by JMurphyWeb** [comment]
@asimonw as we said in the other issue, I believe the forgot password is covered in #7 ?

**Comment by asimonw** [comment]
@JMurphyWeb #7 technically only covers resetting pwd from the login screen. Would you prefer to handle both pwd reset from login and user settings in #7?

**Comment by JMurphyWeb** [comment]
Sorry I must have misunderstood. I thought from your comment above that you wanted to remove the change password in user settings functionality, and only have 'forgot password' functionality.  

So assuming I am incorrect, it is best to keep the 2 issues.

**Comment by JMurphyWeb** [comment]
From the description and my first comment on this issue, I think the change password in user settings functionality only ever came up in the wireframes.

I don't think they are covered by this issue, but there is no other issue covering it.. If you would like that functionality to be added, would it be ok to add a new issue, link it to this one, and then we can test this issue, and close or bug fix if necessary. Thanks

**Comment by asimonw** [comment]
@JMurphyWeb I remember seeing a conversation between you and @nelsonic about this in another issue. Unfortunately, I can't seem to find it anymore.

You were thinking about building in the change password functionality as in the mockups, and @nelsonic suggested simply reusing the forgotten password functionality. I'm happy with @nelsonic's suggestion. We should keep it in both places (login and user settings), because we don't want people to have to log out just so they can change their password.

**Comment by JMurphyWeb** [comment]
@asimonw with password reset covered in #7 I will add please test to this.
