### ISSUE TITLE
Remove /browse from routes

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#293]
Following on from [@nelsonic](https://github.com/emfoundation/ce100-app/issues/202#issuecomment-252148242)s comment in #202, we need to remove the `/browse` from all routes.

I have an open question to @nelsonic: 

In the add tags to browse view, we currently have the url /browse/{whatever we are browsing}/tags

Would you suggest we change the URL to /orgs/tags and challenges/tags or something else?

**Comment by JMurphyWeb** [comment]
@nelsonic says:
@JMurphyWeb good question. ideally this should be discussed with @asimonw 
But that sounds sensible. 
a followup question is: how are we then going to filter for certain tags?

**Comment by JMurphyWeb** [comment]
If i understand the question, I don't understand the need to change the way we filter by certain tags

Currently we have `browse/orgs?filter=1,1` which would become `/orgs?filter=1,1` which would represent filtering by a certain tag.

**Comment by iteles** [comment]
@JMurphyWeb I would suggest the format would be `/orgs?tags=` rather than `/orgs?filter=`

**Comment by JMurphyWeb** [comment]
@iteles OK I can change that.

@nelsonic When changing my old `/browse/{view}/tags` to `/{view}/tags`, it now conflicts with  `/orgs/{id}` or `challenges/{id}` routes.  

Even when i hard code the orgs or challenges in for the {view} it still causes route conflicts.

**Comment by JMurphyWeb** [comment]
I'm getting some slightly strange behaviour, going to look into now. will reassign if still have a question.

**Comment by JMurphyWeb** [comment]
All good. I hardcoded the routes and moved them above the `/orgs/{id}`  & `/challenges/{id}` routes .
