### ISSUE TITLE
addSharedBy function fix

### ISSUE THREAD

**Issue by mk4111** [emfoundation/ce100-app#295]
As @JMurphyWeb mentioned in #274, ''we filter out the inactive orgs, but any challenge created by an inactive org will still be looked for in the addSharedBy function.''

In #274, we switch out the ```browsableOrgs``` for ```challenges```. By doing this, we're removing the check for 'active' organisations.
If we instead keep browsableOrgs and do ```browsableOrgs.filter(org => org.id === chal.org_id )``` we could return with 'false' which would still display the challengeCard.

We need to: filter out inactive challenges, filter out challenges associated to inactive organisations, then add shared_by.name.

We could:
- add shared_by.name for all 
- then check if organisation is active --> challenges.filter(chal => allOrgs[chal.org_id].active)

**Comment by JMurphyWeb** [comment]
@mk4111 I haven't looked at the file in detail today, but there was a TODO in there to avoid the repetition. I think we can 'get all tags' before the if/else, so move the if/else logic into the callback, would simplify things a bit.

**Comment by mk4111** [comment]
@JMurphyWeb - yeah there is and that still needs to be fixed - that's something I'm planning on doing in the way we discussed before, but it won't fix this issue for challenges.

**Comment by mk4111** [comment]
_UPDATE_ helpers.getChallengeIds only returns challengeDetails of challenges associated with _active_ organisations, so the issue that I thought existed was prevented before this step.
