### ISSUE TITLE
Management of existing users

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#3]
As an EMF admin, I can browse, edit and delete existing users, So that I can manage incoming and outgoing members to the platform in concordance with the programme and make any necessary changes to users as I need to.

**Comment by asimonw** [comment]
@JMurphyWeb All good, but after saving or canceling, we get redirected to browse, while it would make more sense to stay on the People page.

**Comment by asimonw** [comment]
@JMurphyWeb another issue. Telephone number should not be a required field.

**Comment by JMurphyWeb** [comment]
- [ ]  Change joi
- [ ]  Check for required on html form
- [ ] Check tests

**Comment by asimonw** [comment]
Correction. Save is fine, but after Cancel or Archive/Unarchive, the user should be directed to People.

**Comment by JMurphyWeb** [comment]
@asimonw can i ask about the differences between admin edit user, and primary edits their own details:
if admin editing:
Cancel, Save & toggle archive should redirect to the  all people view

if user editing their own settings:
Cancel & Save should redirect to their organisation's profile or the all people view?

Also the button currently says 'Submit', would you prefer 'Save'?

**Comment by asimonw** [comment]
@JMurphyWeb I think it makes sense to redirect admins to the all people view and primary/secondary users to their organisation's profile. Even more natural would be to return to whichever view the user came from, but if that's more complicated to implement at this point, use the former guidelines. 

I prefer the word "Save", which is also what is used in the mockups as far as I'm aware.

**Comment by asimonw** [comment]
Final bits are now resolved.
