### ISSUE TITLE
Redirect `/` endpoint to `/login`

### ISSUE THREAD

**Issue by iteles** [emfoundation/ce100-app#307]
Currently when we go here: https://ce100-emf.herokuapp.com, we get a 401 error. 
Redirecthttps://ce100-emf.herokuapp.com/ to https://ce100-emf.herokuapp.com/login as this is the correct first page.

**Comment by JMurphyWeb** [comment]
- [ ] need to check if logged in, redirect appropriately
- [ ] add tests

**Comment by SimonLab** [comment]
[hapi-error](https://github.com/dwyl/hapi-error#redirectredirecting-to-another-endpoint) can accept a redirect url for specific status codes. So when the authentication validation failed hapi-auth-jwt2 throws a 401 that we can redirect with the options:

```
{ statusCodes: { 401: { redirect: '/login' } } }
```

**Comment by SimonLab** [comment]
resolved with #485

**Comment by SimonLab** [comment]
This redirection is working on localhost but the staging on heroku seems to not get the configuration file for hapi-error. By creating another heroku application and by updating the version of hapi-error the issue seems to be resolved, just need to check on the staging area now

**Comment by SimonLab** [comment]
resolved with #539
