### ISSUE TITLE
Production app currently down

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#317]
At http://ce100-emf.herokuapp.com/login

**Comment by JMurphyWeb** [comment]
I am taking a look at this now. 

Login page showing, login itself is taking a while, then application crash.

**Comment by JMurphyWeb** [comment]
Working locally. Will add some logs and redeploy to try to isolate the error.

**Comment by JMurphyWeb** [comment]
@SimonLab suggested that it could be a problem with corrupted redis data on Heroku. I redeployed to reset the db to it's initial state and it seems to be working ok.

**Comment by iteles** [comment]
@asimonw We've seen a recent issue with Redis data on heroku. If you're able to test again, we can check whether this might be the case here or whether it will require further investigation.

**Comment by asimonw** [comment]
@iteles @JMurphyWeb Site's indeed up again, thanks! Are you implying that the data loss in #318 and this issue might be related? I think this issue can be closed now, keeping the Redis issue in #318. You agree?

**Comment by SimonLab** [comment]
Thanks @asimonw for checking this issue. Postgres will resolve this issue as the data will be more consistent and persistent
