### ISSUE TITLE
Newly created org and user disappear from database

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#318]
It's not completely clear what caused this, but here's the flow:
* As admin, create a new org (I used the name "Alex Foundation")
* As admin, create new (primary) user and link to above org
* Log in with user (after receiving activation email) --> works fine
* As admin, disable user to see what happens to profile contact info
* As admin, enable user again
* A bit later, try to access app with new primary user again --> not possible
* As admin, notice that both new user and org are no longer listed

I don't know if the disable/enable of the user is part of the cause, but mentioned for completeness.

-------------------

Tasks:

- [ ] Identify problem area by recreating locally and investigating database.
- [ ] Review tests to ensure this scenario is being covered
- [ ] Update documentation (covered in #330)

**Comment by JMurphyWeb** [comment]
@asimonw I think we need to attempt to recreate this problem locally. We will take a look early next week.

Did you say that it had happened before? I worry that it is related to redis issue mentioned in #317 but if it has happened before then that isn't the case.

**Comment by asimonw** [comment]
@JMurphyWeb It didn't happen before that I'm aware of, but it has happened again since.

**Comment by JMurphyWeb** [comment]
hhmmmm ok thanks @asimonw we will investigate. We need to recreate this locally to see what is happening with the DB.

Also in the gitter chat, you did not mention 'deactivating' the org or user, is this a separate issue from that one?

Extended on a problem that may be causing this and other issues in #330

**Comment by asimonw** [comment]
@JMurphyWeb The archiving functionality seems fine in itself, but I mentioned it as a possible cause, because maybe archiving a user has undesired side effects (although deleting both user and related org from db would be quite extreme as a side effect).

**Comment by JMurphyWeb** [comment]
I am very hopeful that this will have been resolved with the postgres migration. Difficult to prove as we could not recreate the issue.

**Comment by asimonw** [comment]
@JMurphyWeb I assigned this to myself. I will close this after the postgres migration has been deployed and if this issue doesn't appear anymore for us.

**Comment by asimonw** [comment]
@JMurphyWeb We created a new org and user last Wednesday and they seem to have disappeared from staging. Did you guys re-seed the database since then? Otherwise the problem might still be there.

**Comment by mk4111** [comment]
Hi @asimonw, we've redeployed to master a good number of times since Wednesday (it's on automatic deploy every time we merge into master), so I think that would be why... Would you prefer it if we disenabled automatic deploy so that it doesn't update with our most recent changes every time?

**Comment by asimonw** [comment]
@mk4111 Does this need to reset the database each time? In principal I don't mind, we can keep using the test users you created for us, but it makes it hard to test this particular issue.

Are you doing another deploy today?

**Comment by mk4111** [comment]
Hello @asimonw ! We've set it so that the database is indeed reset each time we deploy. We could take this off, but I think with the introduction of secondary users, it would be helpful to keep this setting... I think we will be deploying today too - maybe it's best if we remove auto-deploy for now so testing is possible?

**Comment by asimonw** [comment]
@iteles what do you think? It would be useful to know that the database is not reset for (for instance) a full day, so that we can close this issue with some confidence. But I also don't want to obstruct the development process. Maybe we can agree on a day to do this?

**Comment by JMurphyWeb** [comment]
Will hopefully deploy to production either tonight or early tomorrow and send @asimonw the login info

**Comment by iteles** [comment]
@asimonw When the secondary users have been deployed to staging tomorrow (Thursday), let's hold off deploying to staging again until Monday (once you've tested this again). 

@jmurphyweb @mk4111 Can we remove the auto-deploy to staging once secondary users are in? Cheers!

**Comment by asimonw** [comment]
@iteles Actually, @JMurphyWeb suggested yesterday to deploy to production so that we can test this one on production. That sounded like a good plan to me, as it doesn't interfere with your workflow.

**Comment by iteles** [comment]
@asimonw Yes, I'd forgotten that you weren't actually using production and @simonlab raised that with me this morning too. Great plan 👍

**Comment by asimonw** [comment]
@JMurphyWeb @mk4111 As mentioned during the call, last Friday I created a user called "Alex Test" attached to a new org "Test Org", and today both user and org have disappeared.

**Comment by SimonLab** [comment]
@asimonw thanks for the details. Do you remember when and what time you've created the user and organisation we will check that we haven't redeployed or resetting the database after you've created them.

**Comment by asimonw** [comment]
@SimonLab I received the activation email on the 20th at 17:21.

**Comment by mk4111** [comment]
Update: @SimonLab found that when Heroku dynos sleep (due to inactivity), and restart (when someone accesses the app), the database gets restarted. We need to revisit the way that we reset the tables.

**Comment by JMurphyWeb** [comment]
I have set all of the `RESET_plugin-name` to `false` locally and the data persists after restarting the server. That suggests it is not a problem with our resetting of the tables.

I was wondering if travis has the real database url: https://travis-ci.org/emfoundation/ce100-app/settings

Annoyingly they won't let me see the current env variables so I want to do a manual test. (make a change on production, then rebuild a travis branch to see if the data persists)

**Comment by SimonLab** [comment]
I think travis is using its own postgress database,  I still think it's an issue with our config reset on heroku,  maybe NODE_ENV?

**Comment by JMurphyWeb** [comment]
Yeah after manual testing I think we can rule out travis 😞

**Comment by JMurphyWeb** [comment]
I'll look into setting up a new production config as there is an open issue on this.

**Comment by JMurphyWeb** [comment]
Think I have it. Down to using ` Boolean(env.RESET_TAGS)` as it always coerces to true 😢

**Comment by JMurphyWeb** [comment]
It works

@asimonw adding please test as the issue should now be resolved.

**Comment by iteles** [comment]
@JMurphyWeb That's useful information to add to a `learn-heroku` repo, no? :blush:

**Comment by SimonLab** [comment]
@JMurphyWeb well spotted! sorry for the Boolean('false') we might need to find a better way to convert this values

**Comment by asimonw** [comment]
Seems solved now indeed, thanks!

**Comment by JMurphyWeb** [comment]
@iteles that sounds like a good shout!
