### ISSUE TITLE
Secondary user group

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#319]
As an EMF admin, I can assign users to a "Secondary" user group, so that more than one contact per organisation can use the app.

Every secondary user is linked to an organisation. An organisation can hold multiple (or no) secondary users. A third radio button should be added next to "Admin" and "Primary" on the user creation/edit screen.

**Comment by JMurphyWeb** [comment]
From our understanding a secondary user can:

**Comment by JMurphyWeb** [comment]
https://github.com/emfoundation/ce100-app/issues/577#issuecomment-272816305 -> ideally there would be some validation. Before saving a primary or secondary user, check that the org field is populated, thanks!
