### ISSUE TITLE
Secondary user permissions

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#320]
As a secondary user, I can view everything a primary user can view, with no edit permissions except for my own settings, so that I can have access to profiles, challenges and insights as soon as possible.

* Permissions for Explore, People and Settings are exactly as for Primary users. 
* There is no "Add Challenge" option, so that item cannot appear for Secondary users in the navigation.
* Profile and challenges on the profile don't have edit buttons
* Archived challenges cannot be accessed, so that link doesn't appear on the org profile

**Comment by JMurphyWeb** [comment]
Tasks:
- [ ] Ensure secondary user cannot 'GET' primary only views and cannot 'POST' to primary and admin only views -> Add to documentation covering routes and who can post/get from all
- [ ] May need tweaking and probably better not to access it by `permissions.permissions` in the handlers
- [ ] Ensure handlebars applies permissions logic as listed above
- [ ] Test for all of above, add integration tests for secondary user flows

**Comment by JMurphyWeb** [comment]
@asimonw what should the secondary user's bottom nav contain? and if a secondary user is looking at a challenge from their own org, should they see the suggested matches?

**Comment by asimonw** [comment]
@JMurphyWeb Good question, it would show two items rather than three: "Explore" and "Profile".

And they can also see suggested matches for challenges of their own org.

**Comment by JMurphyWeb** [comment]
add secondary users to mock data
check plugins still passing tests
check main app still passing tests
add permissions tests to all routes for secondary users
log in as a primary user and admin to ensure nothing has changed
log in as a secondary user. Hit each endpoint, update handler permissions checking
add tests for secondary user flows and user stories

**Comment by JMurphyWeb** [comment]
An example of some of the endpoints we are testing: 
```js
  {
    method: 'GET',
    url: '/challenges/3/tags',
    expectedStatusCode: 403
  },
  {
    method: 'POST',
    url: '/challenges/3/tags',
    payload: '1',
    expectedStatusCode: 403
  },
  {
    method: 'GET',
    url: '/challenges/add',
    expectedStatusCode: 403
  },
  {
    method: 'POST',
    url: '/challenges/add',
    payload: { name: 'H', description: 'h' },
    expectedStatusCode: 403
  },
  {
    method: 'GET',
    url: '/challenges/3/edit',
    expectedStatusCode: 403
  },
  {
    method: 'POST',
    url: '/challenges/3/edit',
    payload: { name: 'H', description: 'h' },
    expectedStatusCode: 403
  },
```
which I was hoping to shorten using: 
```js
{
  method: ['GET', 'POST'],
  url: '/challenges/{id}/tags',
  payload: '1',
  expectedStatusCode: [401, 401]
},
{
  method: ['GET', 'POST'],
  url: '/challenges/add',
  payload: { name: 'H', description: 'h' },
  expectedStatusCode: [401, 401]
},
{
  method: ['GET', 'POST'],
  url: '/challenges/{id}/edit',
  payload: { name: 'H', description: 'h' },
  expectedStatusCode: [401, 401]
}
```

**Comment by JMurphyWeb** [comment]
Rather than change the check editable function. for now I have just changed a few of the handlers to check if it is a secondary user:

```js
  if (loggedIn.organisation_id !== orgId && loggedIn.scope !== 'admin' || loggedIn.scope === 'secondary') {

```

**Comment by JMurphyWeb** [comment]
Having logged in as a secondary user, I can see the following issues:
- [ ] no nav bar
- [ ] edit icon on challenges and my own org even though I do not have edit rights
- [ ] suggested matches should not show up on any challenge
- [ ] user settings: email address doesn't show

![screen shot 2017-01-17 at 12 20 22](https://cloud.githubusercontent.com/assets/12638261/22020302/7c997866-dcaf-11e6-93e4-be498e5cc617.png)
