### ISSUE TITLE
Library folder structure

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#321]
As an EMF admin, I want to be able to have a centralised space to keep all CE100 resources so that we can keep everything together and in one place and organise things flexibly in folders.

Library content will be hosted on Amazon S3, and an FTP client or external app will be used to manage those files on S3.

**Comment by JMurphyWeb** [comment]
We cannot remember how an admin can add tags to 'Insights', are there any wireframes for this?

**Comment by JMurphyWeb** [comment]
We want to read further into these tasks before time boxing them.

**Comment by iteles** [comment]
@asimonw My understanding from our conversations is that this is something that the EMF team will be creating this in S3 and this is not something that will be dealt with in the app.

Is this correct?

**Comment by asimonw** [comment]
@iteles Indeed, as stated in the first comment, we'll use an FTP client or similar to mange the files themselves on S3. Tags and other meta data are handled through the app though, see #324.

**Comment by iteles** [comment]
Agreed, just wanted to double check as this is a high priority issue! Thanks @asimonw

**Comment by JMurphyWeb** [comment]
@iteles please confirm that we do not need to do anything for this task and therefore no time estimate needed?

**Comment by JMurphyWeb** [comment]
@iteles I am unsure what to do with this issue. Can you please advise?

**Comment by iteles** [comment]
@JMurphyWeb This is something that will be done manually by the EMF team, with the URL added to our 'insights creation' form #324 
No further development work needed.

The only thing required here is for @nelsonic to have a chat with @asimonw and the team to make sure he is able to pass on his knowledge around how this can best be achieved.

**Comment by asimonw** [comment]
@iteles We've set up our own interface to manage files on S3 for this using a CMS EMF is familiar with. Nothing left to do from your side.
