### ISSUE TITLE
Browse insights by topic

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#322]
As a CE100 user I want to be able to filter content according to my topics of interest so that I can find everything available on certain key subjects. Sorted by creation date/time when no tag is selected.

This will result in a third type of content that can be browsed under "Explore" which will now have:
* Organisations
* Challenges
* Insights

For each item, we display title, author, type and file size. For admins, a green or red dot shows whether the item is enabled or disabled, respectively.
[link](https://zpl.io/Z13nsGC)
![screen shot 2017-01-10 at 13 11 27](https://cloud.githubusercontent.com/assets/12638261/21807398/66fdcdf0-d736-11e6-8106-dacce369435c.png)

The same views will be used by an admin.

**Comment by asimonw** [comment]
Ideally the file size would be determined automatically.

**Comment by JMurphyWeb** [comment]
We are not sure if we will have an 'insights' table, if not, how will the tags be store..

**Comment by asimonw** [comment]
When no topic is selected (default view), the results should be sorted by creation date/time, descending order.

**Comment by JMurphyWeb** [comment]
@asimonw if a tag is selected, assuming more than one result, do you also want them to be sorted by date?

**Comment by asimonw** [comment]
@JMurphyWeb Yes, do that for now.

**Comment by JMurphyWeb** [comment]
Reminder - we still need to add the red/green dot for insights

**Comment by JMurphyWeb** [comment]
View is very similar to the resources view #323

**Comment by JMurphyWeb** [comment]
![screen shot 2017-01-10 at 13 03 56](https://cloud.githubusercontent.com/assets/12638261/21807363/439aa860-d736-11e6-8a78-522fed9d36b4.png)

**Comment by JMurphyWeb** [comment]
Firstly I want to fix the insights card that can be reused for resources

**Comment by JMurphyWeb** [comment]
I am happy with how that is looking now:

<img width="378" alt="screen shot 2017-01-10 at 14 28 09" src="https://cloud.githubusercontent.com/assets/12638261/21809793/12bdf430-d741-11e6-880a-0a0f7abe5f93.png">

**Comment by JMurphyWeb** [comment]
I am going to split the navigation bar into a partial. The relevant issue is here https://github.com/emfoundation/ce100-app/issues/522

**Comment by asimonw** [comment]
@JMurphyWeb When a filter is selected, the document type disappears. It's there when viewing all tags.

**Comment by asimonw** [comment]
@JMurphyWeb Something else. Could you also set target="_blank" on the resource/insight link so that it opens in a new window? Thanks!

**Comment by JMurphyWeb** [comment]
`target="_blank"` done

**Comment by JMurphyWeb** [comment]
All done.
