### ISSUE TITLE
Extra resources screen

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#323]
As a CE100 user, I can access extra practical resources, which can not naturally be classified by a topic, in a separate place on the app, so that I have quick access to more practical documents for my day to day work.

These extra resources can be accessed from the top burger nav. An admin will determine which resources and up there by using a checkbox in the resource creation/edit view.

![screen shot 2017-01-06 at 10 14 32](https://cloud.githubusercontent.com/assets/12638261/21714832/f28a24b8-d3f8-11e6-8605-cd64b215b3b5.png)

[link](https://zpl.io/A3NI9)
[location in nav](https://zpl.io/jcEYg)

**Comment by mk4111** [comment]
Starting with tests, covering the following:
- access `/resources` as admin, primary, secondary --> all users 200; active resources only.
  --> how do admin access inactive resources/insights
- admin can add insight as a resource --> resource displays in `/resources`
- admin can edit insight: edit link/title + edit to unmark them as a resource

**Comment by mk4111** [comment]
Need to update `pg-insights` plugin to include `getResources` query. 
https://github.com/postgres-plugin/insights/issues/17

**Comment by JMurphyWeb** [comment]
@mk4111 thisis now please tests right?

**Comment by asimonw** [comment]
@mk4111 Looks good, but could you also make it possible to edit items from the resources screen, just like on the explore insights screen?

**Comment by asimonw** [comment]
@mk4111 Thanks for adding those edit buttons! I missed your question before about showing inactive insights/resources. It's correct to show both active and inactive items to admins, as is the case now, but could you add a red/green button next to them to indicate which ones are active/inactive? Left of the title would work.

**Comment by iteles** [comment]
@asimonw I don't think we'll have time to add this in now that the sprint has ended, but could we create a separate issue to capture the requirement with the red/green circle for admins?

**Comment by asimonw** [comment]
@iteles It's fine not to have this in time for the demo. I'll create a new issue because this regards both the resources and admin screen. 

It's technically speaking not a new requirement though. I know that it's not in the wireframe (which is for primary users), but it was understood that the admin screen was the same with edit buttons and green/red dots added.
