### ISSUE TITLE
Create or edit library content

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#324]
As an EMF admin, I can create or edit assets and link them to S3 assets, so that I can provide further context (meta data) to the asset which will determine where and how it will be accessed on the app.

Fields are:
* Title (text, required)
* Url (text, reference to location on S3, required)
* Type (dropdown, items TBD)
* Author (text)
* Show in Resources (checkbox)
* Tags (as for orgs and challenges)
* Enable/disable (as for orgs, people)
(Other fields, e.g. relating the asset to an organisation, might be needed, but with a lower priority)

![screen shot 2016-11-14 at 14 26 20](https://cloud.githubusercontent.com/assets/12638261/20268269/59971b68-aa76-11e6-9e68-37ec84cd4cd0.png)

*Type dropdown fields:*
* Case Study
* Paper
* Presentation
* Report
* Video
* Workshop Summary

[link](https://zpl.io/ZjyNTg)

**Comment by JMurphyWeb** [comment]
Do resources show up in explore insights even though they don't have tags attached?

**Comment by asimonw** [comment]
@JMurphyWeb Only title and url are required. First comment updated to reflect that.

Resources can show up in the Explore default view when no topic filter is selected (order by latest first). In general resources can also have tags and in that case, they would appear when the relevant topic is selected as a filter in Explore.

**Comment by asimonw** [comment]
By the way, I'm assuming that fields such as created_by and created_at will also be stored on the asset object, even though they won't be displayed to the user (potentially to the admin at a later stage).

**Comment by asimonw** [comment]
@JMurphyWeb The way tags are added is not mocked up, because it ill be exactly the same as the way tags are added to orgs or challenges.

**Comment by JMurphyWeb** [comment]
@asimonw Ok thanks for updating the description. Thanks for reminding about created_at and created_by. We will write up our proposed data structure before implementing it so you can have a chance to review what we are putting in.

**Comment by mk4111** [comment]
@JMurphyWeb and I had a chat about how we were thinking of implementing this.
Given our new modular data structure, we will be creating an Insights plugin, which (like all our other plugins) will host the main table 'insights', and the lookup table 'tags-insights'.

The methods we think we will need are: getById, getAll, add and edit.

In order to create these 'create' and 'edit' views, I plan on starting by creating the plugin.

@SimonLab - does this sound about right to you? Please let me know your thoughts! :tanabata_tree:

**Comment by SimonLab** [comment]
@mk4111 yes sounds good, the structure of the plugin will be very similar to the existing one so it should be easy now to create the new one.

**Comment by JMurphyWeb** [comment]
@asimonw does type refer to the Article/Report/... ? It would be great to get the possible entries for the dropdown.

![screen shot 2017-01-05 at 11 49 13](https://cloud.githubusercontent.com/assets/12638261/21680559/5fae5e36-d342-11e6-8b82-f9bf53add3d0.png)


Also I was wondering if the size of the file is an important feature right now? I think we will either need to make a request upon the admin adding/updating an insight, or ask the admin to enter the size of file manually?

**Comment by asimonw** [comment]
@JMurphyWeb Yes, those are examples of possible Types. I'll see if we can get you a full list asap. 

Regarding the size, we could de-prioritise that. Automating it would be better than asking admins to do it manually, but appreciate that this would take longer to build. I'll double-check with the team and create a separate priority 3 issue for this if confirmed.

**Comment by JMurphyWeb** [comment]
@asimonw @fannyBkane we were not sure how an admin navigates into this view. It seems to make sense to have it as an menu option after the admin presses the `+` button on their bottom nav, but it is not indicated in the wireframes.

What are your thoughts?

**Comment by fannyBkane** [comment]
That is what we expect. Thanks @JMurphyWeb

**Comment by JMurphyWeb** [comment]
re-opening as it is a user story

**Comment by JMurphyWeb** [comment]
![screen shot 2017-01-10 at 16 33 19](https://cloud.githubusercontent.com/assets/12638261/21814840/88fab7b2-d752-11e6-84e8-4384c200391d.png)

Styling is pretty close. Still need to:
- [ ] update the `doctype` field to `type`, and
- [ ] offer the enabled/disabled checkbox

**Comment by JMurphyWeb** [comment]
I have got it working for add insight, but it has caused an issue with the edit view.

I need to update the edit function so that it can accept an active value

**Comment by asimonw** [comment]
@JMurphyWeb here's a list of types:
* Case Study
* Paper
* Presentation
* Report
* Video
* Workshop Summary

This could still change a bit when we start uploading content, but I assume that that won't be too hard.

**Comment by JMurphyWeb** [comment]
Thanks. I will put them into the description and hopefully get them into the app today.
