### ISSUE TITLE
Free text search

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#326]
As a CE100 user I want to be able to search the app by whatever keywords I choose so that I can find everything that relates to my interests or find information that I can't find by browsing

https://zpl.io/bll1LMe
https://zpl.io/aRMoGGr

Search results should reflect permissions in the Explore and People sections.
Content Owners/Admins can see inactive people, organisations and insights as well, but no-one can see archived challenges in search results, not even primary users who created them.

**Comment by JMurphyWeb** [comment]
From the wireframe a search should return results from People, Organisations, Insights, Challenges and News.

It is not clear what the conditions are for an item to show up in any of the above categories. 

@asimonw I imagine it is just mock data in the wireframe, but it would be good to know how searching for a word (eg. `sound`) should return results in each of the above categories.

**Comment by asimonw** [comment]
@JMurphyWeb It was suggested by @SimonLab to limit the results to exact matches for now. Ideally, a match with any textual piece of content stored as a direct property of a resource would return that resource. The display would be the same as the one used in the different listing views of the different resources (as the mockup suggests). Which pice of text was matched exactly does not need to be highlighted for now.

**Comment by iteles** [comment]
+ Add search icon to nav
+ Search modal
+ Search results page:
  + Search nav bar
    + Retains search term
    + Also allows you to make new searches
  + 'We've found x results for x'
  + Tags
    + Show only the tags that contain the word searched for
    + Show all partial matches too 'outlet' should show 'outlets'
    + Clicking on tags takes to a filtered view
    + For now, no particular order of tags
    + If there are no matches in tags, do not show 'tags' block

**Comment by iteles** [comment]
## Decision required from EMF

For @asimonw @georgemillard and the EMF team to look into: Order of the blocks in the search results page, particularly that of tags.

@georgemillard and Lucy raised users might expect that clicking on the tags filters the _search results_ page rather than taking them to the 'Explore' view.

**Comment by asimonw** [comment]
@georgemillard @LucyJW the only reason tags even appear in the search results is because I thought it could be interesting to add. It sounds like there are too many questions (hence assumptions) around this, so I suggest we leave it out completely for now.

**Comment by SimonLab** [comment]
My first idea for a full text search was to use [Elasticsearch](https://www.elastic.co/products/elasticsearch). This implies creating a specific database to index all the data that need to be searched (people, organisations, challenges, tags), this also means that we will need to duplicate our data, save in postgres + elasticsearch. Elasticsearch is a powerful tool but it requires quiet a bit of tinkering and configuration to get the search result expected.

Postgres offers some simple search features:
- https://www.postgresql.org/docs/9.5/static/textsearch.html
- https://www.postgresql.org/docs/8.3/static/functions-matching.html

 I think having a limited type of items to search on (people, organisation...) and knowing which elements for each type to search on (ex: job title for user, description of an org,...), and also having define the type of the search as an "AND" it will easier/quicker to use Postgres.

So my to recap I will tend to use Postgres with patern matching and regex to search for elements containing a substring of the term searched. We can then evaluate the relevance of the searches and determine if we need a more complex search engine (ie Elasticsearch) but at this stage I don't think so.

**Comment by asimonw** [comment]
@SimonLab That sounds very sensible. Agreed to not overcomplicate things until we have clear needs/use-cases for it 👍

**Comment by iteles** [comment]
Time estimate: 4 days, to be broken down into sub-issues.

**Comment by Cleop** [comment]
@fannyBkane - please can you provide us with the magnifying glass icon? You mentioned we should already have it in the nav in #887, however, this is yet to be built (as outlined in this issue) and so we don't have it yet...

**Comment by fannyBkane** [comment]
Hey @Cleop I've sent them to email address. I've replaced the arrow by chevrons, and updated teh mockups/prototype accordingly.
