### ISSUE TITLE
Desktop views

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#327]
As a CE100 member, I can easily access the app from my desktop or laptop.

**Comment by JMurphyWeb** [comment]
I will discuss this with @harrygfox , aiming to get an accurate estimate of this.

**Comment by iteles** [comment]
@fannyBkane Thank you!

@asimonw You mentioned some of these were higher priorities than others? Or is this the subgroup of screens which is most important?

**Comment by asimonw** [comment]
@iteles Explore and Profile have the highest priority.

**Comment by JMurphyWeb** [comment]
@iteles should we arrange a sit down with @harrygfox for a chat? not sure if you will arrange that or us?

**Comment by JMurphyWeb** [comment]
@asimonw @fannyBkane a quick question about the select tags view: https://app.zeplin.io/project.html#pid=57ac9b5692d0c316520caeca&sid=5880f439bdd1e1a776b86e0d

It contains a back icon and a cancel button. I just wanted to double check that you wanted both in desktop view and neither in mobile view?

**Comment by JMurphyWeb** [comment]
Explore views: https://app.zeplin.io/project.html#pid=57ac9b5692d0c316520caeca&sid=58766dad869eace02c822fd3

News view:
https://app.zeplin.io/project.html#pid=57ac9b5692d0c316520caeca&sid=5878fec4a22372c36f3e3c15

splash page: 
https://app.zeplin.io/project.html#pid=57ac9b5692d0c316520caeca&sid=5880f020591a596709280da8

@asimonw @fannyBkane quick question about the explore, org details, people list seem to stretch the entire screen, but most of the other views have a container around the main content. We wanted to check if that is how you wanted it or if it was something to do with wider/narrower screens?

**Comment by asimonw** [comment]
@JMurphyWeb Regarding your first question: the cancel button performs the same function as the cross on mobile, but we thought that a cancel button would be more 'desktop-y'. We did notice that the select tags screen never has a cross icon, which should be there. It should take you to the same screen as the save.

The back arrow is new and should also appear on mobile. I'll create a new issue for that as it's a new requirement.

**Comment by asimonw** [comment]
The second question: laptop or 'narrow' desktop screens have no "HD" in the title. The mockups with HD in the title are for wide screens and typically just put all content in a max-width container. So those few screens for which the content spans the whole width on laptop, I think that's because the content is list-based with several rows, to make optimal use of space. @fannyBkane can you confirm that?

@JMurphyWeb Is it ok to have two 'templates' for this with slightly different behaviour of the container?

**Comment by fannyBkane** [comment]
' I think that's because the content is list-based with several rows, to make optimal use of space. '

@asimonw @JMurphyWeb that's right.

**Comment by JMurphyWeb** [comment]
@asimonw sure that shouldn't be a problem. 

Thanks @fannyBkane got it.

**Comment by asimonw** [comment]
The updated designs can be found in the new Zeplin project [here](https://zpl.io/ZOkmLW).

The links shared by @fannyBkane above are no longer valid. We can provide a detailed list of links if it's helpful, but the new Zeplin project will be easier to navigate as it only contains latest designs.

The priorities are still: Explore, profile, walkthrough, people, forms.

**Comment by mk4111** [comment]
As all the sub-issues for each of the designs now have the `please-test` label, I thought it would make sense to add it to this epic, so that we would be able to close it if/when happy :)

**Comment by fannyBkane** [comment]
Hey @mk4111 it all looks good, just wondering if we could center and add a max width to the form as see on this mockup https://zpl.io/u0QgI

**Comment by JMurphyWeb** [comment]
```
{
    max-width: 50rem;
    margin: 2rem auto;
}
```

**Comment by fannyBkane** [comment]
Ace @JMurphyWeb 

@asimonw fine to close.
