### ISSUE TITLE
Redirect after editing existing user

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#328]
As requested in #3 

Edit user from people list, press cancel -> get taken to browse, should be taken to people list

We are a little unsure of the existing behaviour when adding a user.
- For 'cancel' we need to change redirect in handlebars

We have seen that when pressing cancel, we get redirected to 'browse'.

Check archive/unarchive redirect location.

**Comment by asimonw** [comment]
@JMurphyWeb You're right, it actually does take you back to People after Save. It happens on Cancel and Archive/Unarchive, but save is fine. I'll correct that in #3.

**Comment by JMurphyWeb** [comment]
This issue is covered in #3
