### ISSUE TITLE
Tech Stack (WIP)

### ISSUE THREAD

**Issue by mk4111** [emfoundation/ce100-app#33]
Some preliminary thoughts on tech stack...
### Front End

Things to think about: 
- Will the app be dynamic? Do we need it to be real time? (The options below are suggestions made on the assumption that this will be a relatively dynamic app)
- How 'mobile' do we need the app to be?
- Will there be a disadvantage/an advantage if the app is Client-side heavy? Is a single-page app a good idea?
- Do we want the app to work offline too?
##### _Advantages:_
- The UI is neat; e.g. re-renders every time the page gets updated (so we'd be able to see the most recent challenge/comment/etc. posted. 
- (I might be skipping too many steps ahead but just as a thought:) If we do decide to go native with the app at some point, a large proportion of the code from React Vanilla would be transferable. In addition, the user experience will be 'native', so the issues that some people report when using Cordova/PhoneGap on their mobiles won't be an issue. Push notifications will be possible.
##### _Disadvantages:_
- We'd need two code bases - ReactJS for web, and React Native for mobile.
#### (2) PhoneGap:
- General: I'm not sure how dynamic the app is.
##### _Advantages:_
- Same code base for web and mobile.
- Can get push notifications (see Push Plugin for PhoneGap).
##### _Disadvantages:_
- Some complaints that the app's feel on a mobile isn't 'native'
##### _Advantages:_
- Browser compatibility good - simple and basic so I don't think there will be issues for loading, etc.
##### _Disadvantages:_
- Will need extra work to get it to render 'nicely', in terms of loading order and media type (desktop/mobile/etc).
### Back End
- NodeJS, with HapiJS (?) for our server
### Database

Quite stuck on this. Current thoughts below:
- **_ElasticSearch_** Seems like it would be useful for them in future phases of development, but I'm not sure if they have fixed the issue where the callback is returned before the cluster is set. In which case, **_Redis_** seems like a nice alternative, but we're limited to exact matches (unless we use regex), and given that, maybe **_PostGres_** is a better idea - but the disadvantages of that is that structuring the database will be less flexible/we would need to know exactly what fields they want before working with it. It's also not horizontally scalable, and considering potential future developments, all in all, I don't think that's a great idea... 
- Possible solution - maybe instead of using just one type of database, we could mix and match depending on what we want to save - need a more thorough think through on this. Something to discuss with Jack on Friday for sure, and hopefully ask for some advice from @nelsonic too...!!
- I don't know if this is all in my head, but I think Alex may have at some point mentioned MongoDB? (Or was that Django (python)?) I don't really have a clue about either of those, but I'll look into them with Jack on Friday.
### Notifications
- Mailgun and Twilio? 
- If we're using React Native or PhoneGap, it'd be cool to look into push notifications too!
### Authentication
- I'm not sure what Alex's thoughts are on 3rd party authentication like LinkedIn, and how disruptive that might be for the app we're trying to create - i.e. whether people will find it easier to communicate via in-app messages on LinkedIn instead.

**Comment by asimonw** [comment]
Some thoughts on this below.

### Frontend

* We definitely have a dynamic app in mind. None of the features we're considering for the first sprints would require real-time, but we can definitely see a good use for it for later features (messaging/chat, user activity on the platform etc)
* Regarding hybrid app options: I think it might make a lot of sense to first focus on a responsive web app solution and only consider building a separate mobile solution at a later point if we think it adds value. E.g. if you choose to use React, keeping state management nicely separated from the view rendering layer, should make it less painful to build a mobile version with React Native (don't know how well that actually works in practice, though). That might be a reason to consider React.
* A significant part of our audience will use this app on desktop, so even though we're designing this mobile first, I don't think we should prioritise mobile use especially.
* Push notifications would be nice, but we don't actually know yet how much we'll really need it at this point. (By the time we really need it, they might finally also work in the browser on iOS???) A simple text notification feature might be enough for now?

### Database

I didn't mention MongoDB, I think, but you're right that the database structure might need to change a lot over time, so for this sort of thing MongoDB is pretty good. Nelson probably has a more informed opinion, but I'd definitely vote for a flexible solution.

### Authentication

I'll need to check with the business team, but I think that we can't rely on everyone being willing to use LinkedIn to log in. If that's the case we'll need a "non-OAuth" solution anyway, so I think we can avoid the additional complexity of having several authentication methods for now. 
Related to this, for the MVP there won't be a regular registration option. We set up the users (primary contacts) and send them a link to authenticate their account.

**Comment by nelsonic** [comment]
https://github.com/dwyl/technology-stack

**Comment by asimonw** [comment]
Your comments make a lot of sense to me @nelsonic. 

I really don't see the need to build a Native version at this point (and foreseeable future). In any case, having to worry about two code bases before understanding and testing core features makes no sense. (I also really like the Progressive Web App idea.) Happy to go with your "default" tech stack (Redis etc). We didn't include free text search yet, just because of a simple prioritisation of features, but it will need to be added in a next phase.

Real-time will definitely add value, and is one of the reasons why building something bespoke makes sense. We didn't include real-time features in the MVP, again just so that we can focus on core ideas first, but if there is enough time, it would be very interesting to consider a "showcase" feature already now.

I indeed don't think Push notifications are important at this point, but notifications in general would be part of sprint 2. How we do it exactly is tbd. Auth with simple email+pwd is a perfect way to start.

**Comment by iteles** [comment]
Closing this issue as it was agreed we would move forward with the current stack.
