### ISSUE TITLE
Documenting side effects of archiving/unarchiving

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#330]
Preface:
I think in general we have some uncertainty when an admin deactivating something (say an organisation) and what effect we want that to have on the linked users & challenges.  Similarly, when an admin reactivates something what effect does that have on the linked items? 
It is one thing that I think it would be really great to have explicitly laid out for us, so that we know exactly the functionality to build in.

Actionable tasks (for Jack and Marie)
- [ ] We need to unify the documentation current side effects when archiving users, orgs, challenges
- [ ] Ask Alex if these flows are ok
- [ ] Update README with the expected outcomes

**Comment by asimonw** [comment]
@JMurphyWeb That's a very good idea. I'll let you guys look into it so that it's technically foolproof, happy to feed into the discussion if needed.

**Comment by JMurphyWeb** [comment]
This is covered in #378
