### ISSUE TITLE
Wireframes additional info

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#34]
Thanks for great [wireframes](https://zpl.io/1NP3uu) @fannyBkane, it would really help to add a brief description in zeplin to the views with info like:

- who is logged in and a little bit more detail about the view they are in (eg. Laura (primary user) logged in on her personal profile page) 

- might also be helpful to know how the user got to that view (eg: my profile > edit)

**Comment by asimonw** [comment]
@JMurphyWeb I sort of answered this question in #37. All wireframes shared so far are for primary users. Are the new titles and added descriptions helpful?

**Comment by JMurphyWeb** [comment]
great thanks
