### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by mk4111** [emfoundation/ce100-app#35]
Hi @emfoundation/dwyl could we ask you for the pool of tags please? We thought it would be better to ask for them up front! Hope that's ok!

**Comment by LucyJW** [comment]
Hi I have just shared this with @emfoundation/dwyl via Google Sheets. I couldn't share it with Jack's Founders & Coders email as it is not a Gmail account. If you have another address I can update. Thanks.

**Comment by LucyJW** [comment]
These tags are a work in progress as we are currently refining a Foundation-wide topic taxonomy for EMF which will feed into this - certain tags will change. Let me know if there is a deadline you need for a more "final" version. Although we will always need admin rights to change these.

**Comment by mk4111** [comment]
Hi @LucyJW, thank you for sharing this with us! Jack's google email address is [jmurphy.web@gmail.com](jmurphy.web@gmail.com) - if you could add him too, that'd really help us! Thank you very much again!

**Comment by LucyJW** [comment]
Hi @mk4111  and @JMurphyWeb  - I have now shared it with you. Thanks.

**Comment by mk4111** [comment]
@LucyJW Thank you!!! :)
