### ISSUE TITLE
integrate getAllActiveTags function into the application

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#362]
Currently the get all active function is used in the following endpoints:
/challenges/{id}/tags (GET)
/orgs/{id}/tags (GET)

I think these should both be using the same handler which sits in the new 'shared' folder.

Also affected will be the handlebars views, and possibly the joi validation on the corresponding POST routes.

Once this is implemented, I think it will break the POST handler as the format of the tag ids will have changed.

**Comment by JMurphyWeb** [comment]
I am first going to integrate add-tags-to-challenge.js

**Comment by JMurphyWeb** [comment]
We need 2 functions to help us re-write the handler:

Get tags attached to a particular challenge, so that we know which tags have already been attached to the challenge (in the case that we are editing an existing challenge):
`request.pg.tags.getTagsAttachedTo(tableName, challengeId, cb);`
@SimonLab do you think this function should sit in the tags plugin?

Get all active tags, which we already have:
`request.pg.tags.getAllActive(cb);`

**Comment by SimonLab** [comment]
Can we create a specific issue for adding tags to a challenge where you describe you previous comments to recap the issue, if you can add a reference to the file or the lines of code to change it would be great too :+1: , it will make it much easier to get the context of the issue, thanks.

**Comment by SimonLab** [comment]
@JMurphyWeb I think we can close this issue now, no?
