### ISSUE TITLE
Migrate Data from Redis to Postgres

### ISSUE THREAD

**Issue by mk4111** [emfoundation/ce100-app#368]
Why? 
- Our data has become more relational than we originally saw it to be. Whilst Redis was a good choice for an MVP, we've realised that the amount of 'maintenance' required to 'upkeep' the relationship when one thing gets changed is _significant_ in terms of keeping it bug-free and the number of database queries we needed to make; by migrating our existing data to postgres, we hope to utilise its 'relational' quality, to allow a change to a single dataset, to propagate through to all related datasets.

How?
Split the data into the following 'main' tables:
- People (id, firstname, lastname, user type, email, phone, password, job title, org-id, last login, active/inactive)
- Organisations (id, name, logo_url, mission statement, active/inactive)
- Challenges (id, title, description, date, creator_id, org_id, active/inactive)
- Tags (id, name, category array, active/inactive)
- Categories (id, name, active/inactive)
...and create 'look up tables', which store the relationship between the above tables:
- Tags - Organisations (id_tags, id_orgs)
- Tags - Challenges (id_tags, id_challenges)
- Tags - Categories (id_tags, id_cat)

**Comment by SimonLab** [comment]
these epic issues recap all the endpoints and permissions: #366 #378
