### ISSUE TITLE
browse challenges - filter challenges by tag query

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#369]
To filter challenges by a tag, we need to expose a function on the tags plugin:

`challenges.getChalByTag(tagId, function (error, challenges){ ... }`

Will be applied here: https://github.com/emfoundation/ce100-app/blob/master/server/handlers/browse-view.js#L24

See description here https://github.com/postgres-plugin/challenges/issues/9

---------------

Update referred to in [this comment](https://github.com/emfoundation/ce100-app/issues/369#issuecomment-263883812) :

This issue requires that:
- [x] challenges.getAll (now a part of .getByTag) is integrated into this app ( #372 _created_ the functionality in the _challenges_ plugin ) >> This returns all challenges (unfiltered)
- [x] challenges.getByTag (just the filtering part of the plugin method) is also integrated into this app.

For the latter to work, we need the endpoint /challenges/tags to be functional too ( I think this is #355 ).

**Comment by JMurphyWeb** [comment]
Still needed: the filter tag being sent back in the object from the plugin.

**Comment by JMurphyWeb** [comment]
This query has been written, but is not yet fully merged.

**Comment by mk4111** [comment]
Updating the main description of this issue, because I've realised it encompasses two tasks!

**Comment by mk4111** [comment]
My misunderstanding! Found that the necessary groundwork had been laid!

**Comment by SimonLab** [comment]
resolved with #387
