### ISSUE TITLE
pg transition: challenges.getAll

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#372]
For browse challenges view (no filter tag selected):
![screen shot 2016-11-24 at 09 42 38](https://cloud.githubusercontent.com/assets/12638261/20593441/61f4c182-b22a-11e6-9350-6debdffa6c59.png)

To be applied in this handler
https://github.com/emfoundation/ce100-app/blob/master/server/handlers/browse-view.js#L23

Will return a similar object to #369, I am wondering if we can even expose the same function with some different arguments, telling the function not to filter by any tags if none are given.

**Comment by SimonLab** [comment]
fixed with #387
