### ISSUE TITLE
Show related org when listing challenges in "Explore"

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#377]
Currently, when browsing challenges, it is not clear who shared the challenge. We would like to add this to the bottom of the challenge [like this](https://zpl.io/Z2tV4qQ).

Note that this isn't necessary when showing a challenge on someones profile, because in that case it is clear who is sharing the challenge.

**Comment by JMurphyWeb** [comment]
This was fixed during the postgres migration and is in master.

**Comment by JMurphyWeb** [comment]
@iteles I made this change during the postgres switch. I wasn't sure what to do with the issues now as the 'Shared By' feature is in, but the browse styling is still old, and not like the new version.
