### ISSUE TITLE
Data structure

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#38]
Not yet formatted as you requested @nelsonic but we have been thinking:

```
People:
  { id: number
  , user_type: string// [ admin, primary, secondary ]
  , password: string
  , first_name: string
  , last_name: string
  , email: string
  , job_title: string
  , phone: string
  , organisation_id: number
  , challenges_created: [id1, id2, id3, …]
  , last_login: number
  , active: boolean
  }


Organisation:
  { id: number
  , name: string
  , primary_id: number
  , logo: string // will this be an image or url?
  , mission_statement: string //(validation max characters)
  , tags: [string, string, string, …]
  , people: [string, string, string, ...]
  , challenges: [id1, id2, id3, …] // this may be useful when we have multiple users creating challenges on behalf of the organisation
  , active: boolean
  }


Challenges:
  { id:  number
  , date: number
  , creator: number //primary user id
  , title:  string
  , tags: [string, string, string, …]
  , description: string
  , active:  boolean //challenges can be archived
  }

Tags:
//option 1:
ParentTags = ['energy', 'education', 'finance', ...] //set
//child tags
energy = [ 'oil', 'gas', 'electricity' ] //set
education= [ 'higher education', 'secondary', 'research' ] //set
//

//option 2:
tags =
  { energy: "[ 'oil', 'gas', 'electricity' ]"
  , education: "[ 'higher education', 'secondary', 'research' ]"
  } //hash

```

What do you think about tag data structure? we have been having a little discussion and are slightly unsure on how much data per request we should be passing to front end ( eg more client-side state management but less requests -> option 2).

**Comment by nelsonic** [comment]
@JMurphyWeb / @mk4111 models look good.  
i would make `users` --> `people` (_being picky about how I describe people using the app_)
and I would allow people to be members of multiple organisations from the start.
so `people.orgs: Array`

data is *fairly* "relational". 
we should get some feedback from @asimonw as to how they expect to *query* the data.

**Comment by asimonw** [comment]
@JMurphyWeb I don't know how you're setting up tags, but I suggest also using ids to uniquely characterise them.  One immediate benefit is that the display name can be changed easily, without unnecessary data migrations or what not.

@nelsonic People won't ever be in multiple orgs (fingers crossed), but several people can be part of the same org. I was thinking it would be better to have `Organisation.people: Array` and no need to specify the org in People.

What would you like to know exactly about how we will query data? I tend to just get the whole tag structure and store it in a model the first time tags are used (maximum once per full page refresh). How are you thinking about approaching it: SPA-like per "screen"?

**Comment by asimonw** [comment]
Just noticed that the user model doesn't have an id. @nelsonic @JMurphyWeb do you agree with the approach to characterise every basic element (user, org, challenge, tag) uniquely with an id?

**Comment by JMurphyWeb** [comment]
@asimonw 

- agree regarding an id for each data type. Added.
- an array of users attached to each organisation will definitely be necessary once secondary users enter the fray. Have added for now but i was under the impression we were not including secondaries for now.
- left multiple orgs per person **out** as per your instruction.

@nelsonic 
- I think we have adapted to fit in with your first comment (could you briefly explain why 'people' is preferable to 'users'?)

**Comment by asimonw** [comment]
@JMurphyWeb indeed no secondary users for now, but makes sense to start treating it as an array already.

**Comment by JMurphyWeb** [comment]
There will only ever be 1 primary user right? I think it makes sense to store that user in it's own organisation field `primary_id`
Then another field on the organisation being an array which can hold all secondary_users attached to that org.
What do you think?

**Comment by asimonw** [comment]
Good question.. I think there might be scenarios where having multiple primary users will make sense (e.g. so that managing other users for the org can be done by more than one person). I think it's cleaner to determine the behaviour/access based on the user group, and not by in a way duplicating that info in the org model.

One problem might be how we specify which contact info to display on the org profile. For that, maybe it makes sense to add a `contact_id`? We might also be trying to solve a problem which doesn't yet exist. It sounds like it would be a manageable change to add the `contact_id` later if we need it and decide then whether it needs to be an array or not? I would like to get @nelsonic's view on this.

**Comment by asimonw** [comment]
@JMurphyWeb Could you also add the boolean field "Enabled" to People and Organisations, like for Tags? Apologies for missing that one. Again, this field is simply to allow for the option to make a person or org inaccessible without having to delete them from the db.

**Comment by JMurphyWeb** [comment]
Done. Tags need work still covered in #50.

**Comment by JMurphyWeb** [comment]
@asimonw sorry i missed your previous comment about contact_id. Your thoughts for an organisation:
{ contact_id: Number                  // the user that shows up on the orgs profile
, primary_ids: [ Num, Num, ... ]   // the users that have edit access of their org
, people: [ Num, Num, Num ]      // all (other?) people associated with that org
}

Please confirm that this is the jist of what you were getting at?  It feels like the users of MVP are all actually `contact`s for their org as opposed to (or as well as?) `primary`s. 

Is there a difference in permissions between a primary and a contact for an org?

And more generally, is there any advantage to 'duplicate' data and store each `contact` and `primary` also in the `people` array? I feel like it is unnecessary but interested to hear anyones thoughts

**Comment by asimonw** [comment]
@JMurphyWeb I was perhaps overly complicating things for now. The idea was that later on there might be more than one user with primary user permissions, of which only one would be displayed as contact person. This would not affect permissions at all, only determine which one we display on the profile.

But since how this will work is not entirely clear yet, maybe it's simpler to ignore the contact_id property for now. Does that sound good?

**Comment by JMurphyWeb** [comment]
sounds good 👍

**Comment by JMurphyWeb** [comment]
@nelsonic should we store `primary_id` into `people` array for a given organisation?

At the moment we have the latter, which I was thinking is unnecessary but wanted to check before changing.

```javascript
//org
{ name: 'Apple'
, primary_id: 2
, people: [ 3, 4 ] //representing the people attached to the org
```

```javascript
//org
{ name: 'Apple'
, primary_id: 2
, people: [ 2, 3, 4 ] //representing the people attached to the org
```

**Comment by JMurphyWeb** [comment]
updated data structure on the wiki: https://github.com/emfoundation/ce100-app/wiki/Data-structure

**Comment by JMurphyWeb** [comment]
@asimonw i think this has come up before, but i cannot find it, sorry.

Is the challenge card created on behalf of the organisation or the user? Or will it eventually be both? We were just wondering where we should store the challenge cards - in the people or organisation data set.

Thanks

**Comment by JMurphyWeb** [comment]
Alex responded with challenge cards are attached to an org.

**Comment by JMurphyWeb** [comment]
updated data structure: https://github.com/emfoundation/ce100-app/wiki/Data-structure
