### ISSUE TITLE
Add account_activated key to data structure

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#381]
We want to determine whether a user has activated their account. If they have, we can set the `account_activated: true`

Remember to update the [datastructure](https://github.com/emfoundation/ce100-app/wiki/Data-structure) when this change is made

**Comment by SimonLab** [comment]
We also need to add the "account_activated" property in the [people data](https://github.com/emfoundation/ce100-app/blob/master/data/people.json)
