### ISSUE TITLE
intialise redis client in server.js

### ISSUE THREAD

**Issue by SimonLab** [emfoundation/ce100-app#388]
The application is using [hapi-redis-connection](https://github.com/dwyl/hapi-redis-connection) to attached a redis client to the request object. However I think this plugin might need [some updates](https://github.com/dwyl/hapi-redis-connection/issues/3) so until the next version of the plugin I think we should create manually the redis client and attached it to the [server.app](http://hapijs.com/api#serverapp) object. server.app "Provides a safe place to store server-specific run-time application data".
This will also make it easier to manage the redis connections in our tests.

**Comment by JMurphyWeb** [comment]
@SimonLab this is closeable?

**Comment by SimonLab** [comment]
resolved with #375
