### ISSUE TITLE
need to catch undefined 'ss' in add-sessions.js

### ISSUE THREAD

**Issue by mk4111** [emfoundation/ce100-app#397]
When run locally, the tests pass fine. Even if redis returns undefined [from the callback on this line](https://github.com/emfoundation/ce100-app/blob/master/test/helpers/add-sessions.js), if passes.

However, it seems that this is not the case, when run online, as can be seen [from this report](https://travis-ci.org/emfoundation/ce100-app/builds/180105180)

We need to catch the undefined argument 'ss' from the callback defined in the link above, so that Travis doesn't error in this way

**Comment by SimonLab** [comment]
The error comes from the fact that Travis try to get all keys of an empty hset (no values yet) and Object.keys try to convert the undefined keys to an array. We should first check what is the return value of the get keys function, I'm surprised that it doesn't return an empty array but it's possible.

**Comment by mk4111** [comment]
I agree - I'm going to start working on this now

**Comment by mk4111** [comment]
Tracked the issue down!

- The issue manifested _now_ instead of earlier because challenge.test.js was run, prior to login.test.js, where sessions are being stored in the database.
- when the database is empty from an hget request, it returns a 'null'.

**Comment by JMurphyWeb** [comment]
Good to find this issue!
