### ISSUE TITLE
database populating scripts broken (redis & pg)

### ISSUE THREAD

**Issue by mk4111** [emfoundation/ce100-app#400]
To debug #398, I flushed the database locally. I am now having trouble repopulating the database; it seems that a file which existed at the time of creating the script no longer exists, and that the registration of the plugins is failing.

![screenshot from 2016-12-01 10-50-41](https://cloud.githubusercontent.com/assets/13470325/20791272/0e739616-b7b4-11e6-8aba-a96e2ec945ab.png)

**Comment by mk4111** [comment]
Looking into fixing this issue now.

**Comment by mk4111** [comment]
Issue was that:

- populateDB script used an old config file, which had not been updated >> removed in favour of the new one.
- pgMockData script is no longer required to populate pg database because it's all done in the server, at the time of registering the plugins.

**Comment by SimonLab** [comment]
We don't use the populating script as the plugins are doing this automatically
