### ISSUE TITLE
Add suggested matches to org details view

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#402]
Relates to the org details view: #395

![screen shot 2016-12-15 at 12 29 49](https://cloud.githubusercontent.com/assets/12638261/21224064/3afdf708-c2c2-11e6-8683-06f61e5a5380.png)

Preface:
I am struggling to find the relevant issue right now, but when challenges have their own view (priority 3?), I am pretty sure the suggested matches will get moved over to that view.

Problem:
adding suggested matches to a list of challenges makes the query quite complex. @SimonLab is this right? I could be over complicating in my head so would be good to get your input.

Potential mvp solution:
write the query for only one challenge, and make that query multiple times using async module, then in the handler format the suggested matches for each challenge into the challenges array and send to handlebars.
This solution could be useful when we move the 'suggested matches' query into a single 'challenge' view (not yet built) then we will be able to just use the exact same query.

Possible alternative:
Build the 'single challenge' view, as it is something that shouldn't be hard to build, is ultimately desirable and would make this issue easier to solve.

@iteles after thinking about it I am leaving this question internal,  because we do not yet have a single challenge view yet, our only option is to work out a way of implementing it into the org details view (as in the wireframe above) even though it may not be desired long term. Please let me know if assumptions are wrong.

Link to wireframes: https://app.zeplin.io/project.html#pid=57ac9b5692d0c316520caeca&sid=57d9907a3b1cfd1b11eb9d91

**Comment by JMurphyWeb** [comment]
I have had a think about this query and feel like given an array of challenge ids, it shouldn't be too hard to write.  

Something like this takes the array of challenge ids, and returns all the organisations that match each tag on each challenge:

```
SELECT
tags_challenges.challenges_id as ch_id, 
tags_organisations.organisations_id as or_id
FROM
tags_challenges
JOIN tags_organisations
ON tags_challenges.tags_id = tags_organisations.tags_id
where tags_challenges.challenges_id IN (4, 5, 6, 7)
ORDER BY ch_id
;
```

**Comment by iteles** [comment]
I had a quick catch up with @asimonw on Friday and we discussed this briefly. The conclusion was that we will absolutely need to have separate challenge cards for future functionality, as in future the plan will be to attach a lot more information to it (e.g. suggested reading materials and suggested similar challenges). This means it will get too cluttered if the suggestions stay in the organisation view.

Let's time estimate each of the 2 cases.

There is a very clear directive here that there are higher priority items in our backlog in terms of new functionality for now, so if in this sprint the suggested matches need to stay in the org view, this is not an issue.

**Comment by JMurphyWeb** [comment]
likely to be moving back onto this via #500 tomorrow

**Comment by JMurphyWeb** [comment]
This feature is now in the Single challenge view.
