### ISSUE TITLE
pg transition: Edit org view

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#405]
![screen shot 2016-12-02 at 08 58 23](https://cloud.githubusercontent.com/assets/12638261/20828055/84341db2-b86d-11e6-810e-6bdcddf1267b.png)

Edit Organisation View
[Primary View](https://app.zeplin.io/project.html#pid=57ac9b5692d0c316520caeca&sid=57cdad229561cc384a69e792)
Admin View not provided.

Permissions:
Admin and Primary can edit: Mission statement, and Add tags
Admin can also edit: Org name, Logo url, enable/disable org, view primary user if linked and see a link to edit that user.

Data needed for this view:
Org: name, Mission statement, logo url, active, active tags linked.
linked primary user: first, last, id, active

@asimonw I wanted to check if we display the user to the admin in this view if the primary user is disabled?

**Comment by asimonw** [comment]
@JMurphyWeb We hadn't foreseen to show the primary user attached to the org in this view (or at least, this was changed when we decided to select the org from "Add user" rather than select the user from "Add org").

Having said that, it does sound like a nice idea to show the primary user here, with a blue dot if active and a red dot if not. This is a nice to have at this stage, though. So if it adds more work, this can be done with prio 3.

**Comment by JMurphyWeb** [comment]
Ok for the time being I will show the user here, active or not.

I think we will take a look at the coloured indicators for enabled/disabled all in one go.

**Comment by JMurphyWeb** [comment]
Admin View:

![screen shot 2016-12-02 at 12 35 09](https://cloud.githubusercontent.com/assets/12638261/20834185/daae92f8-b88b-11e6-90ce-22f1f20317aa.png)
![screen shot 2016-12-02 at 12 35 19](https://cloud.githubusercontent.com/assets/12638261/20834188/df662f9a-b88b-11e6-80cd-09db6637c76f.png)

Primary
![screen shot 2016-12-02 at 12 37 31](https://cloud.githubusercontent.com/assets/12638261/20834242/34e2c3d4-b88c-11e6-8edd-a6660af65a77.png)
![screen shot 2016-12-02 at 12 37 46](https://cloud.githubusercontent.com/assets/12638261/20834249/38746476-b88c-11e6-92b6-3e2a801d8948.png)


Added some better styling and the tags section.

**Comment by JMurphyWeb** [comment]
All seems to be working as expected. Need to now add tests.

**Comment by JMurphyWeb** [comment]
tests added

**Comment by SimonLab** [comment]
@JMurphyWeb this issue seems to be resolved, can it be closed?

**Comment by JMurphyWeb** [comment]
yup
