### ISSUE TITLE
pg transition: edit org POST endpoint

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#408]
Edit Organisation Post Route. 

pg.orgs.update(id, orgObj)

Need to check the fail action is still working if the admin/user fails validation on the edit org fields.

Permissions:
Admin:
Name, logo url, mission statement
Payload: `{ name: 'Apple', mission_statement: 'Change the economy' }`

Primary:
mission statement
Payload: `{ mission_statement: 'Change the economy' }`

**Comment by SimonLab** [comment]
resolved with #423
