### ISSUE TITLE
Admin can create new user

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#41]
technical tasks related to #1 
- [x] basic interface
- [x] first_name, last_name, user_type, organisation
- [x] validate request
- [x] create route
- [x] addUser db function
- [x] save to db
- [x] add 'admin' auth scheme

**Comment by asimonw** [comment]
@JMurphyWeb see my comment in #38. I think it's better to set users as a property of an org rather than the other way round. That way you can easily capture all users belonging to an org as an array in one place. (Although at this point there will only be one user per org.)

**Comment by JMurphyWeb** [comment]
Yes thanks i will ammend data structure now.

**Comment by mk4111** [comment]
@asimonw, we have made a note to include primary users as a property of an organisation, but would it be helpful for you, if we include the organisation name as a property of the primary user too? 

We can see this being helpful when displaying/sharing primary user's profiles.

**Comment by asimonw** [comment]
@mk4111 This might be relevant for #27 (for example), where we'll want to display the org along with every user on the platform. It would indeed be more performant to have the org id stored as a property of the user as well.

The only trade-off there is that I do want to avoid admins having to do this duplication manually. Could you make sure that every time a user is assigned to an org by an admin, the org id in the user model itself is updated automatically to reflect this change? If that's not a problem, then it's a good idea.

**Comment by JMurphyWeb** [comment]
Yeah that is how we are hoping the flow to be. No extra work for the admin...

**Comment by asimonw** [comment]
Perfect!

**Comment by JMurphyWeb** [comment]
closing as deployed
