### ISSUE TITLE
pg-transition endpoint: toggle active organisation

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#418]
Function needed to toggle the activity status of an organisation. 

![screen shot 2016-12-05 at 14 21 05](https://cloud.githubusercontent.com/assets/12638261/20888355/6dde7824-baf6-11e6-83a2-816a46024baa.png)

We are referring this functionality to enable/disable as opposed to archive/unarchive.

Disabling an org when:
The organisation has an active primary user linked -> Also disable the linked user AND disable their sessions.

The organisation has an inactive primary user linked -> Disable org only.

The organisation has no primary user linked -> Disable org only.

Enabling an org:
Enable org only, do not touch the primary user.

**Comment by JMurphyWeb** [comment]
`UPDATE organisations SET active = NOT organisations.active WHERE id = 1;`

**Comment by JMurphyWeb** [comment]
Having a bit of trouble:

If I update an org that exists, we get an empty array, which is expected.

If i update an org that doesn't exist, we again get an empty array.

this means there is no way to tell if the update was successful or not.

I am going to log the full response from node-postgres and check the docs to see if we are missing something in our query function.

**Comment by JMurphyWeb** [comment]
In the end we realised that we need the full object from node-pg. 

the key `rowCount: 0` indicates that no row was updated.

**Comment by JMurphyWeb** [comment]
Pr now open. Not covering disabling a linked primary user if there is one.

**Comment by SimonLab** [comment]
resolved with #421
