### ISSUE TITLE
Send notification email to new user

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#42]
Linked to #1 & #41 

- [x] ~~sign up to mailgun~~ --> swapped out for sendEmail npm module
- [x] make api call 
- [x] make sure url has userId

@asimonw can we have notification email content?

**Comment by asimonw** [comment]
@JMurphyWeb we'll get a temporary text over to you soon, but it might still change.
How will it work? Will the email contain a link to an activation page? Ideally, that page would immediately ask the user to create a password.

**Comment by JMurphyWeb** [comment]
Yes that is what we are aiming for. See #43. Changing content not a problem.

**Comment by LucyJW** [comment]
Hi @JMurphyWeb and @asimonw 

Please find some temporary text below, let me know if you have any feedback:


Welcome to the CE100 matchmaking app.

We want to help you make the connections that can accelerate your progress in the programme and help you collaboratively solve your circular economy challenges.

To get started, please reset your password using the link below to enable your account.

***LINK***

We know that it’s hard to solve some of these challenges alone and that the right connections aren’t always obvious, so this app will help you identify new business opportunities and solve problems faster. You no longer have to wait to attend an event to be able to network and collaborate effectively.

Your feedback is important and we encourage you to get in touch with us with your thoughts and suggestions. If something isn’t working, tell us and we’ll work to make it better. You can reach us at digital@ellenmacarthurfoundation.org.

Thanks,

The CE100 team

**Comment by LucyJW** [comment]
A name for the app is yet to be defined so is referred to internally as a 'matchmaking app' for now.

**Comment by JMurphyWeb** [comment]
Need to link up send email with new email addresses

**Comment by mk4111** [comment]
@JMurphyWeb and @iteles can we close this issue? 
It's part of #1 and can be tested there methinks :)

**Comment by JMurphyWeb** [comment]
Closeable
