### ISSUE TITLE
To regex or not... (in tests)

### ISSUE THREAD

**Issue by mk4111** [emfoundation/ce100-app#427]
Linked to #424 

As part of enhancing our tests, should we (not) use regex in our tests? Why?

Question originally posited in [this PR](https://github.com/emfoundation/ce100-app/pull/404#pullrequestreview-11562166)

**Comment by JMurphyWeb** [comment]
- I don't see the need for regex in tests as it is being used atm. indexOf is less to write and less to think about and has the same result.

**Comment by JMurphyWeb** [comment]
@mk4111 I may be wrong, but I think you introduced the idea of using regex in the tests (unless it was simon?) 

I think in the interest of this issue getting anywhere, you should briefly say why using regex is better. Open ended issues tend to hang around for a bit too long.

**Comment by mk4111** [comment]
Hi @JMurphyWeb - nope you're right, it was me!

I decided to use regex because I wanted to not only check that the words displayed, but also because I wanted to know how many occurrences of that word there were. I predominantly used them to use .match(), which also takes a string, but with regex you're able to ensure that you look _only_ for those words, so that, for example, .match does not match word x with words that _contain_ word x; e.g. 'boo' and 'boolean'. Would be happy to switch out .match(regex) to .match(string) though.

I think .indexOf is good if you want to just check that the word (whether or not it is contained by another word) exists, but I don't think it tells us anything beyond that because it only returns the index of the word in the string, which isn't very informative on the whole. I also think that .match reads more naturally than .indexOf, but that's a personal preference. On the other hand, .indexOf _is_ faster than regex though so if we're having or are concerned about performance issues (which I don't think we really are right now...) I think .indexOf should be chosen.

Just wondering, is it an issue to be using regex in tests? A little confused about why this might be an issue, although I am generally fine with it being brought up!

**Comment by JMurphyWeb** [comment]
@mk4111 I think match does work in the same way as indexOf with regards to matching with a part of a word or a whole word.  
![screen shot 2016-12-06 at 15 44 48](https://cloud.githubusercontent.com/assets/12638261/20932050/33a82f12-bbcb-11e6-9d22-0d0b36e500f9.png)


I think i first brought the regex up when reviewing your PR because it seemed a bit more complicated than just indexOf and different to how we do it in all our other tests. 

I don't know why it is issued, maybe @SimonLab asked you to?

**Comment by mk4111** [comment]
Yeah, match(string) works in the same way as indexOf, but match(regex) can be used to match whole words only - I'm not sure I've done it correctly though, so it probably/very well may partially match words.

Definitely agree that it's better to unify the way we test - sorry for disrupting the consistency! Just thought our tests could do with some whole word matching and counting too!

Keen to hear @SimonLab 's opinion on regex

**Comment by JMurphyWeb** [comment]
@mk4111 If you want to match a whole word, couldnt you just do indexOf(' hello ')?

**Comment by mk4111** [comment]
@JMurphyWeb, say you have the string 'This is a sentence about phellogens', .indexOf('hello') will pick up on that, and will return the index of the letter 'h' in the string.

If you have the right regex, it won't pick up on that because it will recognise that `hello` is not the same as `phellogens`, so regex would be useful to ensure that we're not picking up on a random word which just includes (/partially matches) the word we're searching for.

**Comment by JMurphyWeb** [comment]
Ok I agree in that I think regex can be good to use in very specific use-cases, but don't think we actually have any of those at the moment.

indexOf(' hello ') would also not match your sentence.

**Comment by mk4111** [comment]
I think I'm using some at the moment.

It does, check out http://jsbin.com/cijegazume/edit?js,console

**Comment by JMurphyWeb** [comment]
http://jsbin.com/bodaxiqeqa/edit?js,console

I don't want to you to remove it really, as i said in my pr comment. I just think that in future tests we should avoid using it unless it gives us some real benefit, or we decide to use regex app-wide and change all our old tests, which I would prefer not to do, at least now.

**Comment by mk4111** [comment]
The problem with _manually_ adding spaces on either side of the word to fully match the words is that it won't match HTML --> the majority of things we're looking for have tags around them, e.g. `<h1>hello</h1>`

In that case, .indexOf(' hello ') will fail...

We can avoid it, but I think it's helpful when you want to know how many times something has displayed so that we know it's displayed correctly.

**Comment by JMurphyWeb** [comment]
But my main point being, in the interest of keeping tests consistent, simple and easy to understand, indexOf is generally my preference.

I think if there is a justifiable use case and it is not too complicated, then regex is great.

**Comment by JMurphyWeb** [comment]
I think my aversion to regex is knowing how hard they can be to understand to someone who didn't write it.

**Comment by SimonLab** [comment]
I think the tests should be easy to read as they help the developers to understand the feature which is tested. Regex are powerful but can be hard to understand and become quickly cryptic. If possible I would prefer to avoid regex in tests.
@mk4111 do you think we can close this issue?

**Comment by mk4111** [comment]
@JMurphyWeb and @SimonLab yep! Goodbye Regex ( :'( ) !!
