### ISSUE TITLE
Storing date/time

### ISSUE THREAD

**Issue by mk4111** [emfoundation/ce100-app#433]
Now that we are using postgres, there are a couple of options in the way that we store date and time:

- On server-side, in the handlers we could use Date.now() and attach it to the payload object (which includes title and description)
- Could do the same thing but in the challenges plugin
- Could set  date to have the format `TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()` when initialising the table, so that we wouldn't have to pass anything in/write extra lines of code to get the date/time.

Do you guys have a preference or opinion @SimonLab and @JMurphyWeb ?

I think the last option might be the nicest, because if we do ever want to display the date/time on the front end, it has already been formatted for us. 

-----

More date types to choose from in Postgres if you prefer something that's not the above:

https://www.postgresql.org/docs/9.1/static/datatype-datetime.html

**Comment by JMurphyWeb** [comment]
I cant think of a reason why we wouldn't let PG do the work. We do need to ensure that it is of a format that we want though.

I have a couple questions though:
How does the one you mentioned format the date? 
and does it default to the date at the time the row was entered, or the date the time the table was created? 
What is the `TIMESTAMP WITH TIME ZONE NOT NULL` ??? it looks strange!

**Comment by mk4111** [comment]
Yeah, I agree!

The one I mentioned gives back the date, time and time zone in this format:  `2016-12-07 14:19:10.561159+00` (too much?)
It defaults to the time that the row is entered into the database
`TIMESTAMP WITH TIME ZONE` is the data type and looks like the one above.
`TIMESTAMP` and `TIMESTAMP WITHOUT TIME ZONE` are the same, and just don't include the `+00` bit at the end, `2016-12-07 14:19:10.561159`
`NOT NULL` is not null and works in the same way we've used it before... It does look strange doesn't it... :scream:

**Comment by JMurphyWeb** [comment]
I am not sure which is best. But think the default postgres is the way to go.

**Comment by mk4111** [comment]
@JMurphyWeb - cool, I'll keep it with the time zone - better more data than less right?
