### ISSUE TITLE
admin managing existing users

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#44]
view linked to #3 and #4

- [x] list basic info all members on db
- [x] admin clicks on a member, show new view for details of that member
- [x] display all admin-editable fields 
 - First name (req)
 - Last name (req)
 - Email (req)
 - Job Title
 - Phone Number
 - User Group (Admin or Primary) (req)
- [x] submit / delete/ cancel buttons
- [x] submit route
- [x] delete route
- [x] submit db call
- [x] delete db call
- [ ] notify admin (success/error)

**Comment by asimonw** [comment]
@JMurphyWeb Editable fields for user admin

* First name (req)
* Last name (req)
* Email (req)
* Job Title
* Phone Number
* User Group (Admin or Primary) (req)

Notes: we decided to make all user fields editable by admins. Only the ones with (req) are essential for the admin edit view. Those are the ones which should be required in the user model in general. But do add the other ones as well if it's easy enough to set up.

**Comment by JMurphyWeb** [comment]
Need to respond to the user if success/error

Linked to #177
