### ISSUE TITLE
Function to check if primary has permissions to edit a challenge

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#441]
Related issue: https://github.com/emfoundation/ce100-app/issues/439#issuecomment-265714204
PR #440 

We do not have any way of telling if a primary user belongs to the correct organisation that created a challenge.

We want a function exposed on the people plugin which takes the user id and challenge id and returns whether that user has permission to edit that given challenge.

people.checkEditable(userId, chalId, cb)

@SimonLab does this sound too specific? it could get all challenges that the user can edit?
and should it sit on the challenges or people plugin?

challenges.checkEditable(userId, chalId, cb) ??

**Comment by JMurphyWeb** [comment]
I am going to write the query now. would be great to have some input on the above questions before i start writing into the plugin..

**Comment by SimonLab** [comment]
@JMurphyWeb  The logic sounds good. This function is linked to the permission feature so my first thought would be to add it to the people plugin as we want to allow people to access or not specific feature. But again it's also link to the challenges and it might be easier to write the query on the challenge plugin as we might have to do less join on the tables. So I'm not 100% sure where to put this function (both are fine I think), challenges.checkEditable sounds ok, do you think of a better name?

**Comment by JMurphyWeb** [comment]
Number of joins is the same. I think that at the moment it is to do with challenges so I will put it there. But assuming we will use it in the handler and not in the plugin, it is likely to become more general so we could end up moving it to the people plugin in the future.

Actually for now I am wondering if it is easier if the challenges plugin does this check before going ahead with the query that it was asked to do.

I will write the query up and have a think over lunch.

### Query

```sql
SELECT
challenges.id as chid, challenges.title as chal_title,
people.first_name
FROM people
JOIN challenges
  ON people.org_id = challenges.org_id
 where people.id = 3
 and challenges.id = 3
;

```

Returns 1 row --> it is editable so go ahead with the query
```
 chid |     chal_title     | first_name
------+--------------------+------------
    3 | Challenge Number 3 | Sally
```


Then uneditable example:
```sql
SELECT
challenges.id as chid, challenges.title as chal_title,
people.first_name
FROM people
JOIN challenges
  ON people.org_id = challenges.org_id
 where people.id = 3
 and challenges.id = 4
;
```

returns 0 rows 
```
 chid | chal_title | first_name
------+------------+------------
(0 rows)
```
