### ISSUE TITLE
pg transition: /people/add 'GET' endpoint

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#442]
endpoint: /people/add 'GET'

view:
<img width="310" alt="screen shot 2016-12-08 at 17 32 55" src="https://cloud.githubusercontent.com/assets/12638261/21020451/73325fb6-bd6c-11e6-8aa1-4f0f67bd0966.png">
<img width="309" alt="screen shot 2016-12-08 at 17 33 03" src="https://cloud.githubusercontent.com/assets/12638261/21020455/762db260-bd6c-11e6-8311-0f9bd644fbbf.png">

When adding a primary user we want to display an organisations dropdown.  In the dropdown, we want to display different options depending on the user:
- primary user: active orgs, without linked primary users
- secondary user: active orgs

@asimonw is that correct?

**Comment by asimonw** [comment]
@JMurphyWeb Good question. It does sound like this would make it more complicated. Wouldn't it be easier to build this if we allow for more than one primary user to be attached to an org, so we don't have to worry about filtering out orgs?

The downside is that we currently don't have a good way to treat more than one primary user in the UI (only one "contact" is shown), but the upside is that there is a chance that we'll want the ability to attach more than one primary user to an org in the future anyway (as we've always said).

So, it depends. If it's quicker to build in the filter with some client-side JS for you, fine, if it's easier to allow for more than one primary user per org, go for that. We can work with both options for now.

**Comment by asimonw** [comment]
@JMurphyWeb Another thing I've been wondering about: wouldn't it be easier to turn the enable/disabled feature as a simple checkbox? It could say "Enabled" and be checked by default. As it is, you have to worry about both the "Save" and "Disable" endpoint. If it's a checkbox, you only have to worry about "Save". And it actually makes it more transparent to admins that they can create a user without "activating" it.

Same comment would apply to orgs and insights. What do you think? If this complicates things, ignore this comment for now.

**Comment by JMurphyWeb** [comment]
@asimonw we will have a think about the implications of allowing more than one primary user per organisation tomorrow. If it is not going to cause any problems then I think it will be easier so we can go down that route.

Regarding the checkbox, I know this was discussed when we first went about building this feature, but I cannot remember why we decided on an anchor (maybe wireframes or some other reason?). We agree it makes more sense from a UI perspective to have a checkbox.

One question I have that is slightly linked to this, if you want to create a user that is disabled, presumably that means they should not receive an account activation email? Which can add a bit of complexity as we need to give the admin the chance to send the email and maybe check whether an email has been sent already.

**Comment by asimonw** [comment]
@JMurphyWeb Good point. One option is to send an activation email only when the `enabled` checkbox is checked. But then you'd indeed have to track internally whether an email was already sent or not. The ability to resend an activation email would also be a nice feature to add in later.

How does it work at the moment? You simply don't have the option to disable a user at creation time, only afterwards when editing? If that's the case and it works fine, stick to that and we can possibly change to a checkbox solution later (based on user feedback).

**Comment by JMurphyWeb** [comment]
I think for users this makes sense to keep it as it is as long as you don't mind every user you create being sent an activation email. But for orgs/insights we could look into using a checkbox?

**Comment by JMurphyWeb** [comment]
I have not started work on this endpoint due to being unsure how we will approach it.

**Comment by JMurphyWeb** [comment]
I have made the query that will give only available and active organisations on the drop down. I think for now we can leave multiple primary users per org, as it will take a bit more work and testing that is not top priority right now.

**Comment by JMurphyWeb** [comment]
Need to update the query. Here is the version that only gets unlinked active orgs, which isn't quite what we want:
		 +module.exports = [
 +  'SELECT name, id',
 +  'FROM organisations',
 +  'WHERE id NOT IN',
 +  '(SELECT org_id',
 +  'FROM people',
 +  'WHERE org_id IS NOT NULL',
 +  'AND active = TRUE',
 +  // prevent duplicates if there is more than one user per org
 +  'GROUP BY org_id)',
 +  'AND active = TRUE;'].join(' ');

**Comment by JMurphyWeb** [comment]
The aim is to get back all active orgs, with some indicator of whether they have an active primary linked already or not.

We want to order alphabetically. 

On the front end, we can filter the orgs depending on whether the admin has selected primary or secondary.

**Comment by JMurphyWeb** [comment]
@SimonLab can i close this isssue now?

**Comment by SimonLab** [comment]
resolved with #453
