### ISSUE TITLE
Mockdata and Lookup Tables

### ISSUE THREAD

**Issue by mk4111** [emfoundation/ce100-app#446]
Creating this issue, in order to help us make our tests more rigorous, and so that we can add to/edit the mockdata without disturbing a certain relationship:

I'm not sure this is the best way to display the data so please let me know if you might recommend a different way of doing so!

##### /challenges

Active chal from Active org (with tags) --> Challenge 2
Active chal from Active org (without tags) --> Challenge 5
Active chal from Inactive org --> Challenge 1
Inactive chal from Active org --> Challenge 9 (_this is new_) `>>` chal_id = 9, org_id = 4, user id = 6 
Inactive chal from Inactive org --> Challenge (_this is new_) `>>` chal_id = 10, org_id = 8, user id = 11

Does this clash with any of your endpoints? Can we update the relationships that we want to maintain here so that we can keep track somehow, and improve our mockdata and tests?

**Comment by SimonLab** [comment]
I think our data is unified now, @mk4111 do you still need this issue?

**Comment by mk4111** [comment]
@SimonLab - I think it might be a good idea to keep this open for the time being as I think we will be need to be checking this again when we start integrating new features and users. It would be good to get information of the relationships that @JMurphyWeb relies on, on his tests for `/people/add` so that we don't accidentally change anything

**Comment by JMurphyWeb** [comment]
Honestly I think moving forward, we need to:
- add a load of new mock data.  
- only add that data in one place if possible (not 4)
- work out a way for us to unit test without relying on the mock data where appropriate.

**Comment by mk4111** [comment]
@JMurphyWeb - that would be ideal, except I'm not sure how we can do that without any further delays to the project D:

**Comment by mk4111** [comment]
I think we need to document which specific relationships - between challenges, orgs and people - we need to maintain, so that we know _how_ we can tweak them (instead of adding new mock chal/orgs/people every time we have something new to test)

Closing this issue because I think we need to document this in a technical readme or wiki or something!
