### ISSUE TITLE
pg transition: /people/activate/hashedId POST

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#449]
Post endpoint  /people/activate/hashedId 

In this handler we need to:
- [x] use jwt to decrypt the user id from the url
- [x] use bcrypt to hash the password given
- [x] add the password to the user table
- [x] query should return the user that they just updated
- [x] if no error, add a session 
- [x] redirect to that users org if they have one, or to the /orgs page if they don't
- [x] test that our validation is working and pointing to the correct handler

`.pg.people.addPassword(userId, hashedPassword, function (pgErr, res) {`
Should check:
- user is active: true
- user has account_activated: false

**Comment by JMurphyWeb** [comment]
I decided not to perform this check:
- user has account_activated: false

as if we leave it open, this query can be used for resetting of password as well.

**Comment by SimonLab** [comment]
resolved with #450
