### ISSUE TITLE
user log in view

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#45]
a user can log in to the app #5 

- [x] route
- [ ] if cookie there, redirect to landing page --> see #307
- [x] else serve login page
- [x] inputs: email, password, submit
- [x] route
- [x] db functions
- [x] redirect or respond with error

**Comment by mk4111** [comment]
Admin label has been added to make note of the fact that both primary and admin users will be entering the app through this log in view.

**Comment by JMurphyWeb** [comment]
@iteles I think at the time that we wrote this we were slightly confused of the benefit and thought it would be good to try to write a basic login ourselves.  I think we are missing some features that the plugin provides, but we felt that our requirements for the time being were met, so decided to stick to not using it for the time being.

On a side note, we don't really like the thought of a route being registered outside our routes.js file given that is where all our routes currently exist.

**Comment by mk4111** [comment]
@JMurphyWeb  and @iteles, can we close this issue too?
@iteles has created a specific issue ( #307 ) for the unticked checkbox.

**Comment by JMurphyWeb** [comment]
I think this is closable.
