### ISSUE TITLE
admin managing existing organisations

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#47]
linked to #9 

front end similar to #44 - reuse?

- [x] admin clicks on a member, show new view for details of that member
- [x] list basic info all members on db
- [x] display all admin-editable fields 
 - Title (req)
 - Logo
 - Primary User (req)
 - Description
- [x] submit / delete/ cancel buttons
- [x] submit route
- [x] joi validation
- [x] delete route
- [x] submit db call
- [x] delete db call
- [ ] notify admin (success/error)

**Comment by asimonw** [comment]
@JMurphyWeb Editable fields are 

* Title (req)
* Logo
* Primary User (req)
* Description

I added the description (mission statement) -> nice to have but not essential

**Comment by JMurphyWeb** [comment]
Updated. Thanks.

**Comment by JMurphyWeb** [comment]
@asimonw if an admin 'archives' an organisation, what should happen to the linked primary user?

**Comment by asimonw** [comment]
@JMurphyWeb In general, it's rather 'disable' than archive. For instance, we imagine this option to be useful when an org is initially being set up, but we don't want it in the org list yet. A bit like a draft version.

But if there are users linked to it, the only logical thing to do is to also disable all the linked primary contacts. In this case, it's better to see it as 'archiving' before we eventually delete the org and its primary users.

**Comment by JMurphyWeb** [comment]
@asimonw thanks for feedback and sorry for double post. I wanted to document in an issue.

**Comment by asimonw** [comment]
@JMurphyWeb No worries. Happy to adapt to your flow.

**Comment by JMurphyWeb** [comment]
Need to notify admin on success/failure.
linked to #177
