### ISSUE TITLE
Edit-org layout incorrect

### ISSUE THREAD

**Issue by mk4111** [emfoundation/ce100-app#473]
Expected layout is different to what we had before:

![expected-layout-of-edit-org](https://cloud.githubusercontent.com/assets/13470325/21189795/badcde90-c217-11e6-9033-ead69f1c6eab.png)

Our current layout is:

_admin view:_
![incorrect-layout-edit-chal](https://cloud.githubusercontent.com/assets/13470325/21189806/c246fbac-c217-11e6-8030-2e290262690d.png)

_primary view:_
![primary-edit-org-view](https://cloud.githubusercontent.com/assets/13470325/21189937/1af66ba2-c218-11e6-822b-cded5e57a872.png)

But according to our latest Zeplin wireframes we want:

![edit-profile](https://cloud.githubusercontent.com/assets/13470325/21189740/95115790-c217-11e6-97bb-db162a7ac4cc.png)

Should we confirm with clients that they _do not_ want to display the tags they previously selected?

**Comment by JMurphyWeb** [comment]
https://github.com/emfoundation/ce100-app/issues/405

This is the wireframe that i was following whilst building this view. 

@asimonw can you let us know if would not like to show the tags on this view? if you are happy showing the tags then feel free to close this. thanks

**Comment by asimonw** [comment]
@JMurphyWeb Showing existing tags in this view is fine.
