### ISSUE TITLE
Edit User Details - radio button not selected correctly

### ISSUE THREAD

**Issue by mk4111** [emfoundation/ce100-app#478]
On Edit User Details view (for any user), the radio button specifying your usertype is not selected correctly, and is displayed as Primary.

![bug-wrong-radio](https://cloud.githubusercontent.com/assets/13470325/21191056/da19f2da-c21b-11e6-9659-b7f7bf64727f.png)

We need to fix this so that we display the radio button selecting the correct user type.

Similarly the organisation is not pre selected if the user has one.

**Comment by JMurphyWeb** [comment]
The old handler seems to have been removed so I cannot easily see how it was done before.  This is a case for not removing old handlers until we are happy with our current functionality @SimonLab @mk4111

**Comment by JMurphyWeb** [comment]
fixed bug but now failing tests.

Also spotted that the organisaiton is not selected when editing user.

**Comment by JMurphyWeb** [comment]
PR covers the user_type and org dropdown pre-population

**Comment by SimonLab** [comment]
resolved with #484
