### ISSUE TITLE
primary user can view and edit their organisation

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#48]
linked to #10 

View:
- [x] route
- [x] query db
- [x] serve basic page with edit buttons showing
- [x] display tags
- ~~[ ] link to edit tags~~
- ~~[ ] add tags button~~
- [x] create challenge card button
https://app.zeplin.io/project.html#pid=57ac9b5692d0c316520caeca&sid=57d985d9895d1e04118eff10
... todo check with zeplin

Edit:
- [x] route
- [x] query db
- [x] serve basic page with populated form
- [x] editable field: mission statement 
- ~~[ ] display currently saved tags with 'x' delete buttons~~
- ~~[ ] route for remove tag~~
- ~~[ ] db remove tag from organisation~~
- [ ] re render page if successful error if not #177 
- ~~[ ] add tags button~~
https://app.zeplin.io/project.html#pid=57ac9b5692d0c316520caeca&sid=57cdad229561cc384a69e792

**Comment by mk4111** [comment]
Removed from Sprint 1 for the time being, as we are still unsure on how to host the tagging system in the database

**Comment by asimonw** [comment]
@mk4111 It might make sense to create a separate task for tag management by primary users. It's exactly the same for profiles and challenges, and it allows you to go ahead with other parts of this story. It will also be easier to estimate these things separately.

**Comment by JMurphyWeb** [comment]
I am putting some of the groundwork of this issue in PR #163. Mainly the logic of what a primary user can see/do vs an admin, it will not cover tags or challenge cards.

I don't think this story can be finished until we have challenge cards and tags finished.

**Comment by mk4111** [comment]
@JMurphyWeb can we close this issue? :) I've put the please-test label on issue57

**Comment by JMurphyWeb** [comment]
Sounds good!
