### ISSUE TITLE
Admins now show up in /people view

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#486]
![screen shot 2016-12-15 at 11 57 18](https://cloud.githubusercontent.com/assets/12638261/21223161/ab36d71a-c2bd-11e6-9184-651ea6a756d2.png)

I think primary users are only supposed to be able to see active primary users in the /people view. Although I could be wrong. Can you confirm @mk4111 ?

**Comment by mk4111** [comment]
@JMurphyWeb - I think so!
