### ISSUE TITLE
Fail action will break application

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#490]
[This line](https://github.com/emfoundation/ce100-app/blob/master/server/models/max-allowed-tags.js#L11) represents a handler that we no longer want to use. I think this model validates the add tags to org and add tags to challenge view, so we need to work out which view is being used in order to know which handler to point to.

**Comment by JMurphyWeb** [comment]
@mk4111 is this fixed now?

**Comment by mk4111** [comment]
@JMurphyWeb, yes should be! #488 - I think it's been merged in already too...

**Comment by mk4111** [comment]
I think we have fail action in a number of other places too though, we should probably check that those don't break too?

**Comment by JMurphyWeb** [comment]
have already checked that
