### ISSUE TITLE
Unify mock data

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#503]
We are having an issue with introducing new mock data. 

Currently we use a single 'batch' of mock data, which is useful as we can use it in all of our tests and when we are manually testing the application.  However this 'batch' of mock data is in 3 plugins and the main app. Now that we will be introducing new features with new tables (eg insights), it is going to be very time consuming to introduce and maintain this in 4 different places. We need to find a way to only have our batch of mock data in a single place.

In the main application the [data/](https://github.com/emfoundation/ce100-app/tree/master/data) folder holds all of the json files.  This is read into the plugins when the server is initialised.

At the moment, the only way I can see us using one set of mock data and use it between our separate plugins is via npm. If we were to publish the mock data we can require it into each place that it is used. 

Problems that i can see with this method: 
- it seems strange
- every time we update the mock data module, we would need to `npm update` the app and our 3 plugins.

Advice would be appreciated.

**Comment by SimonLab** [comment]
To try to clarify, we have at the moment three different modules:
- [people](https://github.com/postgres-plugin/people)
- [challenges](https://github.com/postgres-plugin/challenges)
- [tags](https://github.com/postgres-plugin/tags-system)

This three modules can be reuse in other projects as they are not directly linked to the main application. However we are using the same data for the main application and the three modules as it is simpler for us at the moment to reason and tests the features by having the mock data unified. But really the three different modules could have totally different kind of mock data.

I think at this stage it's still better to keep the mock data unified as it will be quicker to tests the new functions added to the plugins. @JMurphyWeb I had the same idea of creating a mock data npm package that we can update and include in our different project. At the moment I think it's the easy way to go.
- "It seems strange" - a bit but it's not shocking
-  "every time we update the mock data module, we would need to npm update the app and our 3 plugins" Yes we will need to update the package.json of the application and plugins but it's easy and quick, I don't see this as a big blocker.

I don't see another solution at the moment so I think creating an npm package is a good first approach. Let's review this later on but I think we should try this solution.

@JMurphyWeb any other comments or questions?

**Comment by JMurphyWeb** [comment]
Sounds good

**Comment by SimonLab** [comment]
resolved with #505
