### ISSUE TITLE
Hamburger menu in wireframes

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#52]
I don't think there is any indication as to what should happen after pressing the hamburger button in the navigation bar from the wireframes.

@fannyBkane @asimonw

**Comment by fannyBkane** [comment]
Uploaded a screen to Zeplin: Burger>open

*Fanny Breteau*
Designer ~ Digital Team

t: +44 (0) 1983 296 463
e: fanny.breteau@ellenmacarthurfoundation.org
<scs@ellenmacarthurfoundation.org>

<http://ellenmacarthurfoundation.org>

**Comment by asimonw** [comment]
@JMurphyWeb to clarify, latest is related to #31, Directory is just a contact list #27 and you already have the Settings screen #29. The wording might still change though...

**Comment by JMurphyWeb** [comment]
cool thanks! Maybe create a new issue an put a priority on it @asimonw ?

**Comment by asimonw** [comment]
Good point. The nav is not covered in any user story because I imagine you build it as you create new screens. But I'll put in a story for a "finalised" nav as priority 3.

**Comment by asimonw** [comment]
Done #56

**Comment by JMurphyWeb** [comment]
great.
