### ISSUE TITLE
update sendemail api

### ISSUE THREAD

**Issue by SimonLab** [emfoundation/ce100-app#540]
The sendemail package has just been updated with some breaking changes, we need to update the sendemail function called to the new api

see the two last PR of sendemail:
- https://github.com/dwyl/sendemail/pull/56
- https://github.com/dwyl/sendemail/pull/57

Once the change has been done we can then update the version in our package.json to the last version of sendemail which is 2.8.0

**Comment by JMurphyWeb** [comment]
Possibly use Sinon to stub our sending email tests.

Can ask to see @shouston3's code on his current project for an example.

**Comment by shouston3** [comment]
See [here](https://github.com/dwyl/sendemail#high-volume-of-emails-when-running-automated-tests) for an example for implementing this

**Comment by JMurphyWeb** [comment]
Tiny change in the api from this:
```js
sender.newUser = function (recipient, callback) {
  sendEmail('welcome', recipient, callback);
};

```

to this:

```js
sender.newUser = function (recipient, callback) {
  sendEmail.email('welcome', recipient, callback);
};
```

**Comment by iteles** [comment]
If our tests are already working without stubbing, I wouldn't spend the time stubbing them :+1:
The effect is the same at this stage.

**Comment by JMurphyWeb** [comment]
@iteles only problem is our email inbox is getting flooded with 1000s of emails... I will put a little bit of time in today to explore introducing Sinon, as it is something I haven't done before and would like to learn.

I have already implemented the new api. Will PR now.

**Comment by JMurphyWeb** [comment]
Have now stubbed the send email function using Sinon as per @shouston3's recommendation.

**Comment by SimonLab** [comment]
#579 has updated the sendemail package
