### ISSUE TITLE
Newly created challenge does not appear on profile, but does in Explore

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#542]
I created a challenge called "Test challenge" with a primary user. After creation, the challenge does not appear on the profile. I can find it when browsing using "Explore", so the data does get saved.

**Comment by JMurphyWeb** [comment]
It could be that we deployed during your testing @asimonw ?

I just tried to recreate the flow and the challenge was there. Although it appeared at the bottom of the list which needs to be fixed.

**Comment by iteles** [comment]
@JMurphyWeb Let's move this back to `please-test` when we've deployed the fix to #546 and manually tested this again.

**Comment by asimonw** [comment]
@JMurphyWeb You're right, I hadn't spotted it at the bottom. Changing the order will fix this.
