### ISSUE TITLE
Add logo to organisations

### ISSUE THREAD

**Issue by mk4111** [emfoundation/ce100-app#55]
Add logo functionality to edit org view.

I think we want to add this functionality to add org view.

Need to check if a user can edit/add their organisations logo.

**Comment by JMurphyWeb** [comment]
(added tasks to do hence increase in time estimate)

**Comment by mk4111** [comment]
Issue merged into #10.

**Comment by JMurphyWeb** [comment]
mistake on our part. Issue reopened.

**Comment by JMurphyWeb** [comment]
I am unsure how to test a file being uploaded.

**Comment by JMurphyWeb** [comment]
I was looking into nock as I thought that might be why the build was failing. Here is the response from S3:

```
{
  ETag: '"d09e2d7ebd6c4ad87a20f301fb28cdaf"',
  Location: 'https://ce100-logos.s3-eu-west-1.amazonaws.com/foxy812e3e642f09ec9f.png',
  key: 'foxy812e3e642f09ec9f.png',
  Key: 'foxy812e3e642f09ec9f.png',
  Bucket: 'ce100-logos' 
}
```

**Comment by JMurphyWeb** [comment]
but it is passing on travis now. Would be great to get it into staging for some manual testing.
