### ISSUE TITLE
Clicking 'Cancel (X)' should take us back to the previous page

### ISSUE THREAD

**Issue by mk4111** [emfoundation/ce100-app#551]
We currently have 'X' rerouting to a hard-coded path; we want to make this flexible so that - if the user clicks cancel - the user is redirected back to their previous page.

This was raised as an issue specifically for the challenge details view (/single challenge view), but this option could be considered app-wide.

**Comment by mk4111** [comment]
Time estimate has not been added yet, as we haven't thought of a good method of capturing the history/state of the visited paths.

**Comment by JMurphyWeb** [comment]
Think it would be great to have some insight from @SimonLab or @nelsonic to see if there is a standard method to follow?

**Comment by JMurphyWeb** [comment]
Having studied the request object again i found this key: 

```js
info:
   { received: 1484386851096,
     responded: 0,
     remoteAddress: '127.0.0.1',
     remotePort: 50565,
     referrer: 'http://localhost:3000/orgs/1',
     host: 'localhost:3000',
     acceptEncoding: 'gzip',
     hostname: 'localhost' 
},
```

Where referrer is the url that the user was on before making the current request.d

**Comment by JMurphyWeb** [comment]
```js
var u = 'http://localhost:3000/orgs?tags=2'
var cancelUrl = require('url').parse(u).path;
// /orgs?tags=2
```

**Comment by JMurphyWeb** [comment]
Just done some manual testing and got the following working nicely for the add challenge view:
```js
var url = require('url');
function getCancelUrl (req) {
  var cancelUrl = url.parse(req.info.referrer).path;
  return cancelUrl;
}
```

**Comment by JMurphyWeb** [comment]
Problem with the above is it doesn't work if a user clicks 'add challenge' twice as the 'cancel' url will be the same as the current url

Fix: 
Create a default case of the users home page:

```js
helpers.getCancelUrl = function (req) {
  var defaultHomePage = req.auth.credentials.organisation_id
    ? '/orgs/' + req.auth.credentials.organisation_id // non-admin default
    : '/orgs'; // admin default
  var previous = url.parse(req.info.referrer).path;
  var current = req.path;

  // if the previous path is same as current, redirect to the user's default
  return current === previous ? defaultHomePage : previous;
};

```

The default home page for a non-admin is their orgs profile and for an admin it is `/orgs`

**Comment by JMurphyWeb** [comment]
@SimonLab @mk4111 do you think we should implement this app-wide? I think it would be a 15 minute task as it is already tested and the helper function already implemented.

It would be useful to also have the dynamic cancel button after a user presses 'Settings' as they can access it from any view.

If not we should add please test to this issue.

**Comment by SimonLab** [comment]
@JMurphyWeb I would say yes to implement it on all the application, however we just need to confirm that it is the behaviour we want on all the x button, do we want to redirect to a specific page on some occasions?
@asimonw could you confirm that the user should be redirected to the previous pages for all the "x" cancel button or are there any exceptions?

**Comment by asimonw** [comment]
@SimonLab Not that I can think of. Always returning to the previous page sounds like the natural thing to do. Thanks!
