### ISSUE TITLE
Update challenge list view

### ISSUE THREAD

**Issue by mk4111** [emfoundation/ce100-app#552]
Related to this issue #255.

We just spoke about updating the challenge list (`/challenges') view, so that only the *title* and *shared by* are displayed per challenge. The organisation name (i.e. org by which the challenge has been shared) should also be hyperlinked, so when clicked, the user is redirected to the organisation profile. 

@asimonw can we please ask you to confirm that you would like description (as issued in #255) and tags removed from this view?

**Comment by asimonw** [comment]
@mk4111 Yes please, thanks. This extra information will be accessible by clicking on the card.

Question: does this affect the way challenges are shown in the profile as well, or is a different partial used for this?

**Comment by mk4111** [comment]
@asimonw thank you for your speedy reply and confirmation!! 

The challenges in browse view and the challenges displayed in organisation profile are indeed generated by the same partial, but we can change this if you would prefer different options to be displayed for the two views!

**Comment by asimonw** [comment]
@mk4111 Leave it like that for now. We can make that call based on real content and feedback after launch.

**Comment by mk4111** [comment]
Still assuming this design (but without the tags):

![screenshot from 2017-01-13 12-48-56](https://cloud.githubusercontent.com/assets/13470325/21930580/b1a5f918-d98e-11e6-8277-a63754b3199f.png)

**Comment by mk4111** [comment]
We now have:

![screenshot from 2017-01-13 12-50-56](https://cloud.githubusercontent.com/assets/13470325/21930642/f467bf66-d98e-11e6-9fa2-859329737d0a.png)

**Comment by mk4111** [comment]
Apple is a little wonky --> removing the `.anchor` class removes this:

![screenshot from 2017-01-13 12-53-37](https://cloud.githubusercontent.com/assets/13470325/21930718/50f64c84-d98f-11e6-8d3d-f354545b1120.png)

**Comment by mk4111** [comment]
Visited links have text-decoration on them - is this ok @asimonw?

**Comment by asimonw** [comment]
@mk4111 Would it be possibly to keep the original styling even for visited links? That's more app-like.

**Comment by asimonw** [comment]
@mk4111 Would it be possible to remove the awkward spacing between the challenge title and the "shared by" text before closing this issue?
