### ISSUE TITLE
Navigation for primary user

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#56]
As a primary user, I can use a persistent navigation, so that I can access the main features of the app in a consistent way.

**Comment by asimonw** [comment]
On mobile, this is separated into a bottom nav:
* Browse (we might end up calling it "Explore") -> #20 
* Add challenge -> #12 
* Profile -> #10 

And a top burger nav:
* Latest -> #31 
* Directory (might turn into "Contact list") -> #27 
* Settings -> #29

**Comment by JMurphyWeb** [comment]
```
      // TODO: Can this navbar logic go somewhere else?
      var allUsers = {
        allUsers: users,
        alternate: [{
          path: '/people/add',
          name: '+'
        }, {
          path: '/orgs',
          name: 'Orgs'
        }]
      };
      reply.view('people/view', allUsers);
```
