### ISSUE TITLE
Add/edit user organisation dropdown bug

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#560]
As an admin, if you go into the edit user view for Ben Morpheous:
<img width="773" alt="screen shot 2017-01-12 at 16 00 15" src="https://cloud.githubusercontent.com/assets/12638261/21897036/4ff68376-d8e0-11e6-9156-e58786c33d5d.png">

The org dropdown doesn't show Fanta as it is not an enabled organisation:
<img width="672" alt="screen shot 2017-01-12 at 16 04 01" src="https://cloud.githubusercontent.com/assets/12638261/21897199/cf52e146-d8e0-11e6-81de-f10a6148eaae.png">

This means that editing Ben in any way will result in him being 'unlinked' from Fanta organisation.

It seems like a bit of an edge case, I don't know how likely it is for an Admin to be editing a user linked to a disabled organisation? @asimonw could you suggest your desired functionality here? and suggest a priority for us please?

_________________________________
Additional thoughts on this org dropdown:
The org dropdown needs a bit of thought with the introduction of secondary users, we were thinking of displaying differing drop-downs depending on which user 'type' is selected:
- if an admin is being created/edited -> show no dropdown
- if a primary is being created/edited -> show all active, unlinked organisations (except the org that they belong to if we are in edit user view)
- if a secondary user is being created/edited -> show all active organisations

I have put the above thoughts here for discussion: https://github.com/emfoundation/ce100-app/issues/319

**Comment by asimonw** [comment]
@JMurphyWeb This user would anyway be inactive right? I think it's ok to unlink them in this edge case, indeed.

What you suggest for the dropdown could work, but a simpler solution would be to always show the full dropdown, i.e. never filter out linked orgs. The only downside (apart from having a rather big dropdown, which we would anyway have for secondary users) is that admins can accidentally link more than one primary user to an org. 

As I have suggested before, this could be fine as long as the model doesn't reject this. We'd just show the first user in the list as a contact on the profile. I don't think there would be any other side effects? The benefit would be that if there is a need for two people in an org to be able to edit the org profile, we could easily do that.

And it would solve the edge case above as well. The user wouldn't need to get unlinked.

**Comment by JMurphyWeb** [comment]
This is now sorted as all orgs show up in our drop down

**Comment by JMurphyWeb** [comment]
@asimonw should probably close this when he is happy
