### ISSUE TITLE
Update styling on /people list

### ISSUE THREAD

**Issue by mk4111** [emfoundation/ce100-app#563]
/people list wireframes now show active/inactive status with a green/red indicator. Admin is currently shown of a user's activity status by text in the hidden section so this needs to be updated.

![screenshot from 2017-01-12 16-35-59](https://cloud.githubusercontent.com/assets/13470325/21898596/39672200-d8e5-11e6-8c5d-70c4169337e4.png)

**Comment by mk4111** [comment]
Just looking at the styling to check for colour changes and font size changes, following review.

We currently have (in the PR)
![screenshot from 2017-01-13 09-20-11](https://cloud.githubusercontent.com/assets/13470325/21924570/a51c65d2-d971-11e6-90fd-153715c14b7e.png)

**Comment by mk4111** [comment]
Immediately we can see that:

- Title: Contact List --> People 
- Font type(?) and size is different
- Colour of indicator is different
- Indicator is not quite round in mobile view

Will now work to fix these

**Comment by JMurphyWeb** [comment]
@mk4111 could you also please capitalise the 'p' in 'primary' and 'a' in 'admin'?

**Comment by mk4111** [comment]
Having a bit of difficulty where I can't fill the background color of the whole list, when an item is toggled.

**Comment by JMurphyWeb** [comment]
@mk4111 I guess these small css issues can take a back seat for now if you don't make decent progress?

**Comment by mk4111** [comment]
@JMurphyWeb - yeah I'm thinking the same, I've just been reading about the background colour but most suggest frontend javascript. I think there might be a way with CSS but it seems pernickety because we'd have to change the order on HTML, then style it so it looks like it's in order, or we try to apply background colour in two parts...

Styling is otherwise done though I think
