### ISSUE TITLE
Profile public view

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#57]
As a primary user, I can see other organisation profiles, including contact details and enabled challenges, so that I can find out more about other organisations in the network.

**Comment by asimonw** [comment]
By clicking on a challenge you see a details view.
On the profile of your own organisation, you see edit icons which allow you to edit profile info or challenge card details.

**Comment by mk4111** [comment]
@asimonw are there wireframes for this please? I think I'm a little confused about whether you want:
- a view for the primary user, displaying all the organisations on the network + another view displaying a specific organisation's details, or,
- a view displaying a specific organisation's details, but _also_ showing an edit buttons to user's who are the primary users of that organisation.
Hope I'm making some sense...

**Comment by asimonw** [comment]
@mk4111 The corresponding wireframe is called "Profile (non editable)." 

What we have in mind is essentially your second suggestion. There is a way to browse all org profiles on the network, this is #20 (and #21)  As a primary user, this means you could be looking at either your own org's profile (by navigating to "Profile") or another one (by browsing). We call this a private and a public view, respectively. 

The main difference (at this point) is indeed that the private view has edit buttons. I would worry about this distinction only for now. In the second sprint, other things are added to the private view related to matches with other profiles (see #14 #15 and #16).

**Comment by JMurphyWeb** [comment]
I am putting some of the groundwork of this issue in PR #163 

I don't think this story can be finished until we have challenge cards and tags finished.

**Comment by asimonw** [comment]
Since challenge cards will be tackled separately at a later stage, this general issue can be closed
