### ISSUE TITLE
Readme screen shots

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#570]
From now on, can we use mobile views for our screen shots in the readme.  The app looks best in mobile view and it will lead to smaller and more consistent images making the readme more readmeable.

Thoughts @mk4111 ?

**Comment by JMurphyWeb** [comment]
@mk4111 if you are happy please close this issue, I just wanted to bring it up.

**Comment by SimonLab** [comment]
Agree however mobile can have different resolution so the dimension of the images will be different if taken from different phone. We just need to ensure that the images have the same dimensions.

**Comment by JMurphyWeb** [comment]
@SimonLab  on chrome use iphone 6?

Ok they may not be exactly the same, but they will be similar.

![screen shot 2017-01-13 at 10 08 34](https://cloud.githubusercontent.com/assets/12638261/21926104/46dc2f5a-d978-11e6-970c-d33ed3a5023c.png)



![screen shot 2017-01-13 at 10 08 28](https://cloud.githubusercontent.com/assets/12638261/21926105/4a622b48-d978-11e6-80ae-599e7d649a89.png)

**Comment by mk4111** [comment]
100% happy!! I'll close this now! ReadMe looking sho puurrrrdy!!! <3
