### ISSUE TITLE
Remove old test files

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#578]
@mk4111 @SimonLab I wanted to get your thoughts on what to do with the old test files?

We could either try to convert them by changing the id's of the mock data being used or just get rid of them? Or maybe a mixture of the two?

Either way we probably shouldn't remove a test file unless either it has been covered with our new tests, or we are back to 100 per cent coverage.

**Comment by JMurphyWeb** [comment]
I am adding this to sprint 3 as it should be done with the postgres migration as well as getting back to 100% coverage

**Comment by SimonLab** [comment]
I think I would just check what tests are missing to cover all the application and would try to implement them. You can maybe have a look at the old tests for inspiration but the structure is now different so I'm not sure if it's very efficient to try to convert the old tests.
