### ISSUE TITLE
Staging browse insights with tags bug

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#581]
Filtering a browse insights view with any tag will return a 500 error.

example url: 

https://staging-ce100-emf.herokuapp.com/insights?tags=91

Heroku logs are not showing any stack trace meaning the latest version of Hapi Error is not being used on Heroku.

**Comment by SimonLab** [comment]
I just log the postgres error from the browse function of the insight plugin:
```
error: syntax error at or near "WHERE"
```
So I guess it's a query error, do we pass the right parameter to the browse function, is there a typo in the query? Concerning the version of hapi-error it might be worth to check if the last version is published on npm and if our package.json is up to date.

**Comment by JMurphyWeb** [comment]
@SimonLab this now seems to be resolved. Any idea why?

**Comment by JMurphyWeb** [comment]
Seems to only be broken for a primary user.

**Comment by JMurphyWeb** [comment]
here is the query that is being called when a primary tries to filter an insights browse:
```sql
SELECT tags.id AS tid, tags.name AS tname, insights.id AS iid, insights.title AS title, insights.url AS url, insights.author AS author, insights.creator_id AS creator_id, insights.date AS date, insights.active AS active, 91 AS filter_id, (SELECT tags.name WHERE tags.id = 91) AS filter_name FROM tags_insights JOIN insights ON tags_insights.insights_id = insights.id RIGHT OUTER JOIN tags ON tags_insights.tags_id = tags.id WHERE tags_insights.insights_id IN ( SELECT insights_id as iid FROM tags_insights WHERE tags_insights.tags_id = 91 ) OR tags.id = 91 WHERE insights.active = true ORDER BY insights.date DESC, insights.title ASC, tags.name ASC;
```

**Comment by JMurphyWeb** [comment]
As can be seen, `where` is being used twice in the query.

**Comment by JMurphyWeb** [comment]
This has been fixed on the plugin. `where` keyword used only once:
```sql
WHERE  insights.active = true AND
 tags_insights.insights_id IN 
( SELECT insights_id as iid FROM tags_insights WHERE tags_insights.tags_id = 91 )
 OR tags.id = 91 
ORDER BY insights.date DESC, insights.title ASC, tags.name ASC;
```
