### ISSUE TITLE
Multiple primary users

### ISSUE THREAD

**Issue by mk4111** [emfoundation/ce100-app#585]
Hi @asimonw! We have a question about displaying primary user information on organisation profiles.

Linking back to #319, can I just double check the following please?

- There can be more than one primary user
- If there are multiple primary users, on the organisation profile, we display just one of the primary user's details. Or would we want to display all the primary users?
- If just one, which user details should be displayed? We will retreive a list of primary users in _alphabetical order_ from postgres, and display the details of the first user in the list.

Clarifying this will help to figure out the logic for secondary user groups and clarify what we need to do for adding/editting  users.

Thank you!!!

**Comment by asimonw** [comment]
@mk4111 We will still aim to have only one primary user per org in practice, but it's useful to keep things flexible and technically allow for more than one primary user to be created per org. This would also make it easier to implement the org dropdown in create/edit user (just show the whole list irrespective of the user).

Your suggestion is perfect: allow for more than one primary user, sort them alphabetically and display only the first one as "contact" on the org profile. Later on we might want to create a separate field to identify the id of the contact person, but first we'd like to see if we'll ever even have more than one primary user.

**Comment by mk4111** [comment]
@asimonw - epic!!! Thank you for clarifying!! :smile_cat:

**Comment by mk4111** [comment]
Hi @asimonw ! I was wondering how important it is for the primary user displayed, to be the first in a list that has been alphabetically sorted. The reason I ask is because our current app only displays one primary user as it is, but the primary user on display is that with the lowest number as an ID. If the alphabetical sorting is not an important feature, we can move onto some more important features like resources view, so just wanted to ask your preference please :)

**Comment by asimonw** [comment]
@mk4111 Definitely, displaying the user with lowest id is fine for now!

**Comment by mk4111** [comment]
Note to self - add this (multiple primary user, and how they display) to documentation

**Comment by JMurphyWeb** [comment]
@mk4111 did you remember this note to yourself?  thought i would check as issue is now closed
