### ISSUE TITLE
After creating a challenge, the close icon should redirect to profile

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#588]
I'm afraid that there is a place where the close action can't simply go to the previous page (apologies for saying that there isn't earlier). After creating a challenge, you end up on the challenge card, so that the close icon redirects to the previous page... which is the "Select tag" screen, rather than the profile page.

A quicker workaround, which is fine by me, would be to direct the user to the profile directly rather than the challenge card after creating or editing a challenge.

**Comment by SimonLab** [comment]
I think @JMurphyWeb implemented the quicker workaround. @asimonw let us know if you want to keep this issue open and we can implement the close redirection on the close action later on.
