### ISSUE TITLE
Testing format

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#598]
As of yesterday I have been following this format for tests:

```js
tape('/${route} (${method}) - ${description}: --> ${__filename}', function () {
```

Which results in:
```js
tap('/orgs/add (GET) - Admin can access add org view: --> /blah/blah/blah')
```

Any improvements/changes? 

It would be great to get a bit more consistency from our testing descriptions -  let's agree on something and close this issue when we are all happy?

**Comment by SimonLab** [comment]
Sounds good @JMurphyWeb , some tests are not applied to any specific route in this case I think we can just omit the first part

**Comment by mk4111** [comment]
@JMurphyWeb sounds good!! Having the filepaths display has definitely been super helpful!!

**Comment by JMurphyWeb** [comment]
Nice @mk4111 @SimonLab !

 ok from now on we can keep to this. And update any old test files that we end up editing with the new format.
