### ISSUE TITLE
Tag management JSON file

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#60]
As an admin I can manage the tags via a JSON file on github.

Instructions will be provided as to how this is done.

relates to tag management gui #11

**Comment by vicky-d1** [comment]
Hi @JMurphyWeb it would be great to understand a little more about the process for this to inform the design of the admin view.

**Comment by iteles** [comment]
@vicky-d1 There's a little more of our discussion with @asimonw and what we agreed in https://github.com/emfoundation/ce100-app/issues/50 but we'll talk through it on our standup tomorrow morning 😊

**Comment by JMurphyWeb** [comment]
Need to update readme on implementation.

**Comment by JMurphyWeb** [comment]
covered in #66
