### ISSUE TITLE
Inactive challenges show up when filtering by tag

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#615]
The following url shows up the 'ice bucket challenge' which is archived.

`/challenges?tags=9`

So the filtered challenge query is returning inactive challenges.

**Comment by mk4111** [comment]
So the issue roots from the use of 'OR' in the SELECT conditional statement, in getByTag.

The issue with purely removing 'OR' from the current query is that, when no challenges are found, then `null` is returned, when really we want the filter_id and filter_name to be returned.

**Comment by SimonLab** [comment]
By adding brackets around the first condition : where (__ in __ **OR** ___) **AND**... The query works. We just need to be sure that the logic of the query is correct

**Comment by mk4111** [comment]
The way we currently retreive information from the database, we:
- gather info from tags_challenges (tid), challenges (cid, date, title, desc), tags (tname), orgs (id, name) tables
- filter above (WHERE clause using IN) with conditional: challenges_id is in tags_challenges.challenges.id

but IN is used to filter the contents of table 1, but matching them against the list provided in 'table' 2.

**Comment by mk4111** [comment]
I think the actual issue here is to do with prioritising/specifying LEFT/RIGHT/FULL joins for the filter details.

**Comment by mk4111** [comment]
Unsuccessfully tried to change the joins, and put brackets to clarify conditions but I think it's now getting to the point where it would now just be best to rewrite the query. Will give this three pommies and update my progress here.

**Comment by mk4111** [comment]
getting issue about 'cross-database references not setup'...

**Comment by mk4111** [comment]
Taking a break to review PRs.

**Comment by mk4111** [comment]
So close, but it's breaking when organisation has been deactivated...

![screenshot from 2017-01-23 23-15-29](https://cloud.githubusercontent.com/assets/13470325/22227174/f50ce1e0-e1c1-11e6-99e0-dbdb613f107a.png)

**Comment by mk4111** [comment]
query now does not return tags attached to challenge (as is not in the view anymore)
