### ISSUE TITLE
'Scroll Up' icon please!

### ISSUE THREAD

**Issue by mk4111** [emfoundation/ce100-app#619]
Hi @fannyBkane, can we please have the .svg icon (screenshot next to 'Back to top') for the 'Landing Page' design? I couldn't get it off of Zeplin... 

![screenshot from 2017-01-20 10-55-40](https://cloud.githubusercontent.com/assets/13470325/22147124/1dede494-deff-11e6-878e-258d95b5ab3c.png)

Thank you!

----------------

Note to self: Once this is received and swapped out for our current .svg, need to remove the background colour on [this line](https://github.com/emfoundation/ce100-app/pull/618/files#diff-4fab20fc9b7238f5f5307386f2b163ffR146) which was added so that we could see the icon.

**Comment by fannyBkane** [comment]
Hey @mk4111 I can't attach .svg files to this thread (not supported). How can I send it to you?

**Comment by mk4111** [comment]
Hi @fannyBkane, could you please send it to the ce100 google email address that we use for log ins? I can pick it up from there! Thank you!

**Comment by fannyBkane** [comment]
Sent to ce100@gmail.com

**Comment by mk4111** [comment]
Thank you @fannyBkane ! Just checked and it's there!
