### ISSUE TITLE
Add Favicon

### ISSUE THREAD

**Issue by mk4111** [emfoundation/ce100-app#623]
Would be good to add a favicon - would reduce the number of lines printed in Heroku Logs and would remove console.log warning on front-end.

**Comment by asimonw** [comment]
@mk4111 good idea! @fannyBkane do we have something?

**Comment by fannyBkane** [comment]
Favicon sent to ce100@gmail.com

**Comment by mk4111** [comment]
@fannyBkane - just checked and confirming receipt! Thank you!

**Comment by asimonw** [comment]
@mk4111 It doesn't seem to work. https://staging-ce100-emf.herokuapp.com/favicon.ico returns a 404.

**Comment by SimonLab** [comment]
@asimonw The favicon should be displayed now, you might need to force reload the page.
