### ISSUE TITLE
Desktop view: navbar

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#628]
Desktop views show a different nav bar to the mobile views

![screen shot 2017-01-24 at 12 30 16](https://cloud.githubusercontent.com/assets/12638261/22247282/e98d4a16-e230-11e6-83ff-259dab8f0162.png)

https://zpl.io/2va9T5

**Comment by JMurphyWeb** [comment]
Had a quick discussion with Simon and agreed that creating a totally different nav bar and hiding the one we don't want using media queries is a good place to start.

**Comment by JMurphyWeb** [comment]
@asimonw a few questions/assumptions on the top nav links. Please feel free to edit this comment if it is easier:

Add:
- admin -> dropdown
- primary -> link to add challenge view
- secondary -> don't show

Update profile:
- Admin -> don't show
- primary -> link to edit organisation details view
- secondary -> don't show

Hamburger:
- Same as mobile

**Comment by JMurphyWeb** [comment]
Timing might be slightly skewed due to this being the first desktop view so need to get media queries working.

**Comment by asimonw** [comment]
@JMurphyWeb Your breakdown is correct. Just edited the naming of "Update profile". Hope it makes sense.

**Comment by JMurphyWeb** [comment]
@fannyBkane I don't seem to have the Explore icon? And our update profile icon is slightly different.

Would you mind sending them over? Thanks

<img width="1482" alt="screen shot 2017-01-25 at 10 56 20" src="https://cloud.githubusercontent.com/assets/12638261/22287995/f42c3218-e2ec-11e6-87a8-58d4177f5d92.png">

**Comment by JMurphyWeb** [comment]
<img width="387" alt="screen shot 2017-01-25 at 10 57 32" src="https://cloud.githubusercontent.com/assets/12638261/22288040/1b8abb68-e2ed-11e6-94e7-83abb073d0fc.png">

**Comment by fannyBkane** [comment]
Hi @JMurphyWeb, I have just sent the explore and the profile icons to the gmail address. 
We changed them as the magnifying glass will be used for a free search, and the profile icon was too detailed. Thanks!

**Comment by JMurphyWeb** [comment]
<img width="691" alt="screen shot 2017-01-25 at 19 24 16" src="https://cloud.githubusercontent.com/assets/12638261/22305565/e62f9f82-e333-11e6-881c-ab3820916032.png">

**Comment by JMurphyWeb** [comment]
Navbar built for primary and secondary users. not yet got the add toggle button for admins

**Comment by JMurphyWeb** [comment]
@fannyBkane I could be wrong, but the icon for the update profile seems to sit in the top half of the allotted space. I think that is why it looks slightly strange on the image above. Whilst it is fixable with css, if we are going to be using this icon in multiple places, it might help to have it repositioned in the actual file so that it sits in the centre.

**Comment by fannyBkane** [comment]
@JMurphyWeb thanks for pointing that out. I have emailed you a .svg with a bit of padding at the top. Alternatively you can try to up the size of the icon by a couple of pixels. Hope that works.

**Comment by JMurphyWeb** [comment]
![screen shot 2017-01-26 at 15 36 28](https://cloud.githubusercontent.com/assets/12638261/22337627/5877a590-e3dd-11e6-8633-3f960f378d43.png)

Desktop navbar for admins

**Comment by JMurphyWeb** [comment]
There is a slight issue with the current implementation: 
An admin can open both the hamburger and the 'add' dropdown at the same time, which looks a little strange.

**Comment by JMurphyWeb** [comment]
secondary nav bar:
![screen shot 2017-01-26 at 15 44 19](https://cloud.githubusercontent.com/assets/12638261/22338082/62c9b834-e3de-11e6-8116-4b131eead5fc.png)

**Comment by asimonw** [comment]
@JMurphyWeb You must have missed my update of the first comment. The link to profile should be exactly the same as on mobile. That's why I said that it should say "Profile", not "Update profile". And it should link to the org profile, not the edit view.

**Comment by JMurphyWeb** [comment]
Right @asimonw I did not catch that. Can you verify that the secondary navbar is as you expect?

**Comment by asimonw** [comment]
@JMurphyWeb Everything else looks perfect, thanks!

**Comment by JMurphyWeb** [comment]
Also add new svg from that Fanny has emailed to us.

**Comment by fannyBkane** [comment]
Hey @JMurphyWeb just seeing that the Explore icon is grey and the other white. Can you make all of them grey or white (whatever is the easiest)? ![screen shot 2017-02-28 at 15 18 29](https://cloud.githubusercontent.com/assets/20577339/23411113/469d1f20-fdc9-11e6-8e3c-4b48cf518685.png)

**Comment by asimonw** [comment]
@JMurphyWeb The explore icon actually looked better in production (until yesterday..), white and with a nice white fill for the bit in the middle. Hope that can be restored?
