### ISSUE TITLE
Strange styling on the login page

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#639]
Scroll to the bottom. You'll see something like this:

<img width="363" alt="screen shot 2017-01-25 at 18 37 10" src="https://cloud.githubusercontent.com/assets/15235804/22303985/844463a8-e32d-11e6-9952-c3bb04aa10e7.png">

**Comment by JMurphyWeb** [comment]
Wireframe: 

<img width="301" alt="screen shot 2017-01-26 at 17 50 15" src="https://cloud.githubusercontent.com/assets/12638261/22343448/0334537c-e3f0-11e6-9bd1-daa9a7ee2aa1.png">

**Comment by JMurphyWeb** [comment]
What we have now:

<img width="415" alt="screen shot 2017-01-26 at 18 29 41" src="https://cloud.githubusercontent.com/assets/12638261/22344796/7071412a-e3f5-11e6-8d45-3fa9b5944582.png">
