### ISSUE TITLE
password-reset email displays wrong link

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#649]
Password-reset email displays wrong link (displays activate instead of password reset link).

**Comment by asimonw** [comment]
@JMurphyWeb Not sure what I should test here? I did notice that the activation screen now also says "Reset password" in the submit button, instead of "Create password". Minor, but possibly confusing.

**Comment by JMurphyWeb** [comment]
@asimonw new issue made #658 

If you are happy that both links in the reset password email do work, then this issue is closable.
