### ISSUE TITLE
TravisCI

### ISSUE THREAD

**Issue by mk4111** [emfoundation/ce100-app#65]
Hi @emfoundation/admins , 

I've just requested for a tool called 'TravisCI' to have access to this repository (emfoundation/ce100-app).
An email should have been sent to one or more of the admins - could someone please grant us/TravisCI access? 

Thank you!

**Comment by fannyBkane** [comment]
Hey @mk4111 I'm afraid the soonest we can do this is Tuesday. I hope it's ok.

**Comment by vicky-d1** [comment]
Hi @mk4111, I don't seem to have received an e-mail referring to TravisCI would you be able to retry as both Alex and I are admins so it should come through?

**Comment by mk4111** [comment]
@fannyBkane and @vicky-d1 thank you! Just received an email confirming that TravisCI has been given access to this repo! Yay!

**Comment by iteles** [comment]
:tada:
