### ISSUE TITLE
Set up domain for production app

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#653]
This is mostly a todo for me (set up appropriate A record).
Possibly with support from dwyl to set up custom domain on Heroku

**Comment by iteles** [comment]
https://devcenter.heroku.com/articles/custom-domains

**Comment by iteles** [comment]
I'll be updating this in the next couple of days to include setting up of a custom domain: https://github.com/dwyl/learn-heroku

**Comment by asimonw** [comment]
Thanks @iteles that's in place now.
