### ISSUE TITLE
Configure Heroku for production app

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#654]
I'm thinking about:
* scaling dynos to paid plan
* do we need more than a dev plan for Postgres?
* what about Redis?
* what else?

**Comment by SimonLab** [comment]
Redis is only used now to keep track of the user sessions and to authorise the users to access the application. So I think the free Redis instance is enough as it gives 30M.

**Comment by JMurphyWeb** [comment]
Linked to setting up our config.js file https://github.com/emfoundation/ce100-app/issues/612

**Comment by JMurphyWeb** [comment]
- [ ] Research heroku costs
- [ ] Necessity for postgres or redis paid plans
- [ ] Present to Alex

**Comment by JMurphyWeb** [comment]
@asimonw 
Heroku: https://www.heroku.com/pricing (7$ / month - doesn't sleep)
Heroku Postgres: https://elements.heroku.com/addons/heroku-postgresql (50$ / month - 4 days database rollback available)
Redis: No need for paid plan.

**Comment by iteles** [comment]
@asimonw You already have our final handover document which provides you with the details you need for master access to the heroku account. 

Let me know if you need anything else here!
