### ISSUE TITLE
Update tag list and reset production database

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#655]
We will provide dwyl with a new tag list which should completely replace the old tags.
If this requires clearing out the rest of the db (as some references might get messed up), then we can do this in production only, since there the db needs to be reset before going live anyway.

The list will be shared as a google sheet. Note the following:
* the structure is exactly the same, but some parent tags have been removed/renamed
* everything is sorted alphabetically, except for the parent tag "Location" which needs to appear at the end (within the Location category, the locations themselves are sorted, though). 
* The capitalisation should be exactly as it is in the google sheet.

Also reset the database. There should be no organisation, challenges or insights. One admin user for EMF (to start with) and maybe one for dwyl (if that makes sense?).

**Comment by JMurphyWeb** [comment]
Should be done in conjunction with setting up production config.js settings: https://github.com/emfoundation/ce100-app/issues/612

**Comment by mk4111** [comment]
In the same PR where we update tags, need to remember to update the wiki/README.md, for instructions on adding/updating tags + categories

**Comment by JMurphyWeb** [comment]
Have added the new tags to this repo (not merged yet)

@asimonw there is a `tags` directory at the root, in which:
- I have added the document for Admins  (also  linked to from the README)
- added the tags.json and categories.json data

We will continue to use our old mock data locally so don't be alarmed if you continue to see the old tags and categories in our screen-shots.

**Comment by asimonw** [comment]
@JMurphyWeb This isn't in place yet, so I assume that the `please-test` label was added by mistake?

**Comment by JMurphyWeb** [comment]
@asimonw not sure if we are still testing on staging but this should be the new list of tags: https://staging-ce100-emf.herokuapp.com/orgs/tags

**Comment by asimonw** [comment]
@JMurphyWeb Tags are looking good on staging indeed. But this issue is about making sure production is ready. So I'd like to keep it open until the tags are in production _and_ the database is reset, as we agreed with @SimonLab earlier this week.

We're not doing anything in production yet, so feel free to deploy what you have already to production when you can. Add the label `please-test` back once that's done and the database is reset. Then we know everything's ready to start uploading real content next week. Thanks!

**Comment by JMurphyWeb** [comment]
@asimonw Tags should be on production now.

We have another issue relating to wiping the user/org/insight data #727

**Comment by asimonw** [comment]
Tags look good. I'll close this one and follow up on DB in #727 👍
