### ISSUE TITLE
Update profile: 500 error when saving with blank "vision" field

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#657]
On the update profile page, if the "vision" field is empty, when you click save you are sent to a page with a "sorry, something went wrong" message (500 error). It would be better to ensure the field must not be empty in the first place by adding some validation on the model.

**Comment by fannyBkane** [comment]
Can the error message be phrased as follows?
'Please add a circular economy vision to continue.'

**Comment by JMurphyWeb** [comment]
I just edited the mission statement to empty string `""` as both an admin and a primary user and did not get any error message. Do you want there to be validation on primary user editing mission statement saying it cannot be empty?

**Comment by asimonw** [comment]
@JMurphyWeb Just did another test on staging and the 500 error seems to have disappeared! The problem is still there in production, so you guys must have solved it recently?

In any case, this means that the issue is now less high priority. I'll move it down in the list, but when you get to it, indeed adding some validation so that the mission statement cannot be empty would be good.

**Comment by JMurphyWeb** [comment]
I will put in some front end validation.
