### ISSUE TITLE
Views - login screen 

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#659]
link https://app.zeplin.io/project.html#pid=589c772f8ad534321d652f04&sid=589c86b2cd8766561d2aec28

![screen shot 2017-02-13 at 12 00 26](https://cloud.githubusercontent.com/assets/12638261/22882682/33635a46-f1e4-11e6-85c4-262e1d5405e0.png)

**Comment by mk4111** [comment]
Update - font size, colour, line height, text/copy has been updated.

One issue concerning line height remains:

![screenshot from 2017-02-13 16-02-28](https://cloud.githubusercontent.com/assets/13470325/22891037/feff126e-f205-11e6-93de-19aac442c6df.png)

**Comment by mk4111** [comment]
The issue seems to have been caused by 'conflicting' conditions for line-height of the `copy--login__options` and `anchor:link`.

**Comment by mk4111** [comment]
To find 10% darker HEX colours, I used http://www.hexcolortool.com/#67dae0

**Comment by asimonw** [comment]
@mk4111 We specified it as 10% darker because that's very easy to do with pre-processors like SASS. I wouldn't hand-code these things because that's hard to maintain. Maybe something to consider in the future.

**Comment by mk4111** [comment]
@asimonw - I agree that with something like SASS this would be easy to do and so that that should be something to consider in the future! Will open a new issue so that we can have it as an enhancement!

**Comment by fannyBkane** [comment]
@mk4111 great stuff. Could you just double the text-shadow value? It looks quite strong. Thank you!

**Comment by fannyBkane** [comment]
@asimonw fine to close :)
