### ISSUE TITLE
Views - Dashboard

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#660]
Link https://app.zeplin.io/project.html#pid=589c772f8ad534321d652f04&sid=589c890f8acb475f1fcd1333

![screen shot 2017-02-13 at 12 04 19](https://cloud.githubusercontent.com/assets/12638261/22882764/a0e9610a-f1e4-11e6-951a-57f4df10a93e.png)

**Comment by JMurphyWeb** [comment]
- [ ] First Paragraph of text
- [ ] White font
- [ ] Add down arrows
- [ ] Use new font/slightly lighter font-weight

**Comment by JMurphyWeb** [comment]
I have added the next item's index to the array of landing cards in the handler so that the down arrow knows where to direct the page to:
https://github.com/emfoundation/ce100-app/pull/671/files#diff-b4731e81c0b27b7b5083ef45bbbabb6cR40

Which is used in the handlebars here:
https://github.com/emfoundation/ce100-app/pull/671/files#diff-2e4e01973df32b22e14ae978cfcc9af5R14

This works for each of the down arrows except the first one. I cannot work out why it is not working for the first one but it is for all of the others.

**Comment by JMurphyWeb** [comment]
I have tried to make the first index a `1` in case it was a problem with using `0` but it did not make a difference

**Comment by JMurphyWeb** [comment]
@mk4111 we have been having an issue with using `vh` for setting the height of the landing card. The problem arises on mobile, when you scroll down or up, the browsers url bar comes down or disappears up, which affects the viewport height and therefore the `vh` recalculates and all the elements shift a little.

After entertaining possible solutions with @harrygfox we decided JS would be best bet to calculate the viewport height on load and use that. I will hardcode a min-height incase the user has JS disabled.

**Comment by JMurphyWeb** [comment]
Also i have removed the min-height 100vh from the body class as I could not see it was doing anything (except allowing me to click on the first down arrow)

**Comment by mk4111** [comment]
That sounds like a right pain! Didn't know of that effect so it's good to know! Thanks @JMurphyWeb :airplane:

**Comment by JMurphyWeb** [comment]
```js
(function () {
  var viewportHeight = window.outerHeight;
  var cards = document.querySelectorAll('.landing-card');

  [].forEach.call(cards, function (card) {
    card.style.height = viewportHeight + 'px';
  });
})();
```

**Comment by JMurphyWeb** [comment]
<img width="243" alt="screen shot 2017-02-22 at 13 22 27" src="https://cloud.githubusercontent.com/assets/12638261/23209503/2359d722-f902-11e6-8947-1c885555ae20.png">
<img width="246" alt="screen shot 2017-02-22 at 13 22 33" src="https://cloud.githubusercontent.com/assets/12638261/23209504/235f35dc-f902-11e6-8851-933cab3a3baf.png">
<img width="242" alt="screen shot 2017-02-22 at 13 22 42" src="https://cloud.githubusercontent.com/assets/12638261/23209505/2360f78c-f902-11e6-9543-261e10087cf4.png">

**Comment by fannyBkane** [comment]
@mk4111 could you add more margin top of the h1 'Welcome Sally' so that it looks more vertically centred?

**Comment by asimonw** [comment]
@JMurphyWeb The down arrows (and consequently the different sections) are not well well spaced on mobile. The first down arrow doesn't appear above the fold. This might have been caused by improving the alignment on desktop, where everything looks fine.

**Comment by asimonw** [comment]
@JMurphyWeb In addition to my comment above, when using an actual mobile device (iPhone 5), both in Safari and Chrome the down arrows appear on top of the text and there is no proper spacing between the different sections (as if down arrows are positioned absolutely, but I didn't verify that).

**Comment by JMurphyWeb** [comment]
var viewportHeight = window.outerHeight;

does not work nicely on ios, used `innerHeight` instead and seems to work fine.

@asimonw if testing on dev tools, remember to refresh page after switching to mobile/desktop

**Comment by fannyBkane** [comment]
@JMurphyWeb could give the same button class as on the login page? Other than that, it's fine to close @asimonw
