### ISSUE TITLE
Views - Bottom Navbar

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#661]
link: https://app.zeplin.io/project.html#pid=589c772f8ad534321d652f04&sid=589c896813154c8f1fac10ef

![screen shot 2017-02-13 at 12 13 21](https://cloud.githubusercontent.com/assets/12638261/22883025/029c46c8-f1e6-11e6-993e-390c29c76f88.png)

- [x] New Icons
- [x] change color
- [x] Font size
- [x] 'active tab' highlited

**Comment by mk4111** [comment]
Started off thinking about using `if/else` or `switch` statements to map:
- '/orgs', '/challenges', '/insights' --> `explore`
- '/challenges/add', '/challenges/{id}/edit' --> `add-chal`
- '/orgs/{id}' --> `profile`

**Comment by mk4111** [comment]
Considered saving maps as object:
```js
function getViews (path) {
  var views = {
    '/orgs': 'explore',
    '/challenges': 'explore',
    '/insights': 'explore',
    '/challenges/add': 'add',
    '/people'
  };
 return { views[path] : true };
} 
```
but realised a) no catch, b) how to factor in {id}?

**Comment by mk4111** [comment]
Now thinking either regex (using wildcard - e.g. challenges/*/tags), or .split('/').indexOf() > -1.

I think the former reads better, but the latter is something we have chosen preference over in tests, so will implement using this.

**Comment by mk4111** [comment]
switch statement where:

```js
switch (path) {
  case path.indexOf('/orgs') > -1
}
```

--> i.e. conditional in the case does not seem to work.

Will use regex.

**Comment by mk4111** [comment]
we are now returning the object we want from helpers.getView(urlPath).

Now to work on styling.

**Comment by mk4111** [comment]
Facing issues with icon size and colour - will resume tomorrow.

**Comment by mk4111** [comment]
Changing icon size correctly is proving difficult - emailing for relevant icons!

**Comment by mk4111** [comment]
Opacity along navbar fixed, now only issue is the padding on the profile icon - will ask for this to be removed.

**Comment by JMurphyWeb** [comment]
@mk4111 I commented on the PR. I really like the switch statement helper. It just needs to be (unit) tested.

**Comment by mk4111** [comment]
Adding the new Profile icon

**Comment by mk4111** [comment]
Had to change stroke, stroke width and fill but otherwise worked!

**Comment by fannyBkane** [comment]
@mk4111 looks exactly like the mockups, however ideally this nav should change due to accessibility issue — can you confirm?

**Comment by fannyBkane** [comment]
@asimonw ok to close.
