### ISSUE TITLE
Views - Tag partial

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#662]
![screen shot 2017-02-13 at 12 13 29](https://cloud.githubusercontent.com/assets/12638261/22883155/acdb543a-f1e6-11e6-8515-8ece336804f1.png)

Update tag partial

**Comment by JMurphyWeb** [comment]
Just required a change to the following fields:

OLD
```css
    margin: 0 0.625rem 0.625rem 0;
    padding: 0.5625rem 1rem;
    line-height: 1.5rem;
    border-radius: 3rem;
```

NEW
```css
    margin: 0 0.125rem 0.425rem 0;
    padding: 0.5625rem 0.8rem;
    line-height: 1rem;
    border-radius: 0.6rem;
```

**Comment by JMurphyWeb** [comment]
How they look now:

![screen shot 2017-02-14 at 11 31 24](https://cloud.githubusercontent.com/assets/12638261/22927441/28046846-f2a9-11e6-94b4-20b950e3462b.png)

**Comment by fannyBkane** [comment]
Looks good. forgot to call it out but I added a text shadow to enhance legibility - could you update?
text-shadow: 0 1px 0 rgba(0, 49, 83, 0.07);

Please note:  time allowing the tags style should change due to accessibility issue — can you confirm?

**Comment by asimonw** [comment]
@JMurphyWeb To re-iterate @fannyBkane's comment, if the changes to tags outlined in #688 are implemented, this issue can be closed without adding the text shadow.

**Comment by mk4111** [comment]
@JMurphyWeb - have you included this in #688?

**Comment by mk4111** [comment]
@JMurphyWeb - okidokie! Can we have a quick catch up call in a bit?

**Comment by mk4111** [comment]
@fannyBkane, seems the shadow has been added! Will confirm when we next deploy and this is ready to test again.

**Comment by JMurphyWeb** [comment]
PR #739 should change the look of the tags and put this issue into please test

**Comment by fannyBkane** [comment]
Ok to close.
