### ISSUE TITLE
Views - Org Details

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#663]
![screen shot 2017-02-13 at 12 26 01](https://cloud.githubusercontent.com/assets/12638261/22883332/9bf1259a-f1e7-11e6-871e-4b0072ec9e21.png)

Tags and navbar not covered in this issue

**Comment by JMurphyWeb** [comment]
![screen shot 2017-02-14 at 12 00 45](https://cloud.githubusercontent.com/assets/12638261/22928280/8537709a-f2ad-11e6-9f58-c4138c9e29ae.png)
![screen shot 2017-02-14 at 12 02 31](https://cloud.githubusercontent.com/assets/12638261/22928279/85372338-f2ad-11e6-930e-2c65aafe15dc.png)

**Comment by JMurphyWeb** [comment]
Uppercase the circular economy vision, and reduce vertical padding on the card class

![screen shot 2017-02-14 at 12 22 55](https://cloud.githubusercontent.com/assets/12638261/22928848/6cfcb366-f2b0-11e6-8376-4091a9601a21.png)

**Comment by JMurphyWeb** [comment]
Have added a card seperator class that can be used to put tags in with other content on the same card. It just adds margin to the top:

![screen shot 2017-02-14 at 12 42 09](https://cloud.githubusercontent.com/assets/12638261/22929358/2b63d0e4-f2b3-11e6-9517-9a94536615ee.png)


It does not add margin to the bottom as this is provided by the outer card's padding-bottom.  I think that makes this class specifically useful for additional/separated content at the end of a card.

**Comment by JMurphyWeb** [comment]
@harrygfox I wasn't sure what to make the rest of the margin values so made them auto. It is a bit of a stab in the dark.

**Comment by JMurphyWeb** [comment]
CONTACT card:
![screen shot 2017-02-14 at 13 00 15](https://cloud.githubusercontent.com/assets/12638261/22929843/927639e6-f2b5-11e6-8871-37db6f2043d5.png)

**Comment by JMurphyWeb** [comment]
For the list of challenges at the bottom of `/orgs/1` view, they now have a background of blue on mobile but a background of white in desktop.

I created a class

```css
.card--blue {
    background-color: #003253;
    color: #ffffff;
    border: none;
}
```
to turn them blue which is only applied in org details view (this list of challenges uses a partial that is used in a few places, it is only supposed to be blue in this view.

Then in the media query I overwrote the class `.card--blue` as in desktop, the list of challenges shouldnt be blue
```css
.card--blue {
      background-color: inherit;
      color: #40667e;
      border: inherit;
  }
```


I was wondering what the best practices here were - if any other card were supposed to be blue in mobile and desktop, this wouldn't work.

**Comment by JMurphyWeb** [comment]
![screen shot 2017-02-14 at 16 19 59](https://cloud.githubusercontent.com/assets/12638261/22937767/79c40664-f2d1-11e6-8ca3-caafa4d141b1.png)

**Comment by JMurphyWeb** [comment]
In a really similar issue to the one listed above, I need to make the edit svg white only on mobile and only in this view. On desktop it should be the regular colour. Except I don't think I can change the colour of the lines of the svg using CSS. Would be great to ask @harrygfox about this.

**Comment by JMurphyWeb** [comment]
I still need to:
- fix the svg colour on desktop
- check the new font looks as it should

**Comment by JMurphyWeb** [comment]
![screen shot 2017-02-16 at 12 36 42](https://cloud.githubusercontent.com/assets/12638261/23021604/aaf000f2-f444-11e6-9a5b-1080ed5ef1ec.png)

**Comment by JMurphyWeb** [comment]
@mk4111 I have just merged with master and now have this:\

<img width="242" alt="screen shot 2017-02-22 at 16 39 23" src="https://cloud.githubusercontent.com/assets/12638261/23216125/886c4030-f91d-11e6-91c5-6cb8832e711c.png">


I was wondering if that logo was what we wanted? and if not where it has come from? Also the font of the card header is now 18px but should be 14px in these views, I wanted to check whether we can change them to 14?

**Comment by JMurphyWeb** [comment]
Also I would like to change the padding (bottom only) on the `.card` class from 
`2.75rem 1.55rem` to `2.75rem 1.55rem 1.75rem`

**Comment by mk4111** [comment]
Just had a look!
Soooo:
- I switched out the logo for Profile.svg from the old version to this one as this is what they now want for their navbar. Previously the organisation logo icons were the same as that in the nav, but this might no longer be what is desired. Shall we ask Alex what he wants there by default when an org doesn't have a logo?
- Yes this can be changed to 14px! I think I added it there and forgot to remove it when I moved it into `card__headers--challenges` class!

**Comment by JMurphyWeb** [comment]
Dont worry about the logo. I will change it back.

**Comment by mk4111** [comment]
@JMurphyWeb thanks for the updates and the pictures that helped a lot!

As before, `logo`, `card__headers` and `padding-bottom` of .card should be fine!
About the additional points:
- Updating the rem increments from 0.8 --> 0.875rem sounds good and uniform to me! 
- Changing the padding works with me, but I have a bit of a question about it. The 'Challenge' bit under the navbar (see image below) on Challenge Details should have a smaller height (48px) according to the wireframes but having had a quick scan of the rest of the views, all the other views have a height of 64px. Should only Challenges Detail look different here? I'm tempted to keep them uniform but wondered what your thoughts were.

![screenshot from 2017-02-22 15-25-35](https://cloud.githubusercontent.com/assets/13470325/23218090/31fb50c4-f913-11e6-99c3-1bfc85a473ba.png)

In the dashboard, it's quite clear that they're all the same height _but_ Challenges... hmmm

![screenshot from 2017-02-22 15-26-15](https://cloud.githubusercontent.com/assets/13470325/23218115/453b1c3c-f913-11e6-92c3-6c02f30e1a3b.png)

**Comment by JMurphyWeb** [comment]
@mk4111 I think you are probably right. Lets go with the uniform 64px. Thanks!

**Comment by fannyBkane** [comment]
Looks ace @asimonw fine to close this one

**Comment by JMurphyWeb** [comment]
@fannyBkane could you confirm that your comment is to do with the desktop view? This issue is specifically mobile view. sorry that wasn't made clear in the description.

**Comment by fannyBkane** [comment]
Hey @JMurphyWeb thanks for clarifying.  I got mixed up. 

Could you make the 'archived challenge' link grey like here (i've used #fff 75% opacity)? 

![screen shot 2017-02-27 at 14 39 04](https://cloud.githubusercontent.com/assets/20577339/23365340/a118c654-fcfa-11e6-9d8b-d90df1792a64.png)

**Comment by fannyBkane** [comment]
Hey @JMurphyWeb it looks like the body font colour has changed back to a grey, since this morning. The phone and email links are also changed back to previous colours.

**Comment by JMurphyWeb** [comment]
@fannyBkane it is in review. We will add please test to relevant issue when it is merged.

**Comment by fannyBkane** [comment]
@asimonw fine to close
