### ISSUE TITLE
Views - Explore tab partial

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#667]
Link:
https://app.zeplin.io/project.html#pid=589c772f8ad534321d652f04&sid=589c895039daf1ba0cd194ec

![screen shot 2017-02-13 at 12 45 48](https://cloud.githubusercontent.com/assets/12638261/22883967/773d9de8-f1ea-11e6-8d94-a77402357920.png)

### Before closing this issue, ensure the size of this header is the desired 64px as harry mentioned here https://github.com/emfoundation/ce100-app/pull/680#pullrequestreview-22320838

<img width="423" alt="screen shot 2017-02-17 at 14 54 50" src="https://cloud.githubusercontent.com/assets/12638261/23069892/0cd6f834-f521-11e6-9214-476337477d80.png">

**Comment by JMurphyWeb** [comment]
![screen shot 2017-02-14 at 17 23 56](https://cloud.githubusercontent.com/assets/12638261/22940612/69404664-f2da-11e6-8a73-1f17e9286edb.png)

All updates done

**Comment by fannyBkane** [comment]
@JMurphyWeb great :)

@asimonw fine to close this one!
