### ISSUE TITLE
Views - Explore Challenges

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#668]
Link: https://app.zeplin.io/project.html#pid=589c772f8ad534321d652f04&sid=589c894bb9d031891fc4e576

View:
 
![screen shot 2017-02-13 at 12 48 30](https://cloud.githubusercontent.com/assets/12638261/22884057/ce7fd56c-f1ea-11e6-8d30-49d522c905d7.png)

**Comment by mk4111** [comment]
Updated challenges browse view now looks like: 

![screenshot from 2017-02-15 15-39-12](https://cloud.githubusercontent.com/assets/13470325/22981698/fb1517da-f394-11e6-85bf-ae2a7de66c50.png)

**Comment by fannyBkane** [comment]
@asimonw Fine to close. Curtain!
