### ISSUE TITLE
Font in wireframes is not free

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#669]
@fannyBkane https://www.fonts.com/font/mark-simonson-studio/proxima-nova/regular it seems that proxima-nova is not a free font - have you guys already paid for it on another project?

**Comment by fannyBkane** [comment]
Hey @JMurphyWeb yes, we have it on our Typekit license. I just nee to add the domains we use to my kits. Can you confirm the URLs?

**Comment by JMurphyWeb** [comment]
added: 
```css
font-family: proxima-nova, 
```

**Comment by fannyBkane** [comment]
@JMurphyWeb yes it does, you should be able to use weight regular, semi bold and bold.

**Comment by JMurphyWeb** [comment]
@fannyBkane I am just doing the [org details view](https://github.com/emfoundation/ce100-app/issues/663#issuecomment-279701007) and its tough to really know how this font will look until we deploy.. Is there anyway i can get that font locally so that we can make sure it looks ok?

**Comment by iteles** [comment]
@fannyBkane We don't tend to use typekit for the MVPs, but this looks like a simple integration.

Could you either give us access to your typekit account or provide us with the javascript code we'd need to embed? These are the instructions: https://helpx.adobe.com/typekit/using/add-fonts-website.html

**Comment by asimonw** [comment]
@JMurphyWeb If you alias your localhost (in the /etc/hosts) file and tell us which local url (ce100app.dev for example) you're using, we can add that to the list as well. This does not always seem to work well, but worth a try.

**Comment by asimonw** [comment]
@iteles Our replies crossed each other. I thought the JS snippet had already been shared. @fannyBkane can do that once she's added the domains to the list in typekit.

**Comment by JMurphyWeb** [comment]
Have aliased to: ce100app

@mk4111 you probably want to do the same.

**Comment by JMurphyWeb** [comment]
@asimonw is there anything else I need to do now?

**Comment by asimonw** [comment]
@JMurphyWeb If the alias you have chosen is ce100app @fannyBkane needs to add that to our typekit and send you a js snippet to add to the site.

**Comment by fannyBkane** [comment]
Just added ce100app to our Typekit and sent you a js snippet to add to the site. Sorry didn't do that earlier...

**Comment by JMurphyWeb** [comment]
Thanks @fannyBkane  I have it working now.

**Comment by fannyBkane** [comment]
@asimonw Fine to close!
