### ISSUE TITLE
Auth on routes

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#67]
- [x] Set up auth strategy
- [x] Add auth tests
- [x] Add scopes
- [x] Pass user credentials to handler

**Comment by JMurphyWeb** [comment]
@nelsonic @iteles 
I looked at hapi-auth-jwt2 but ended up deciding to go with hapi-auth-cookie as it was a hapi module (therefore hopefully decent) and I can't remember exactly why but I felt more comfortable implementing it at the time.  I see the benefit of using a module created by dwyl, but is it ok to let me know if you guys feel there is something wrong with hapi-auth-cookie or iron (which I think nelson commented on in #68)? 

Maybe there is a discussion that you can point me to or some sort of comparison?

**Comment by nelsonic** [comment]
@JMurphyWeb you're asking the _wrong_ person about `hapi-auth-cookie` vs `hapi-auth-jwt2` ... 😆 

`iron` is _nice_ but it's not a _standard_ and has no _specification_: https://www.npmjs.com/package/iron#where-is-the-protocol-specification _granted_ the person who _maintains_ the module is _smart_ but there's simply _**no comparison**_ in the level of scrutiny and usage applied to JWT's.
JWT's are a _standard_ https://jwt.io/ widely used by _millions_ of projects.
Granted, in a "small" app/MVP it does not "_matter_" which one you chose.

> FYI: The main difference is that `iron` is _encryption_ whereas JWT is _encoding_.
If the _objective_ is to _prevent_ people from "reading" the contents of the Cookie, `iron` is a _good_ choice (_although you could achieve the same thing using Core Node.js Crypto which is what `iron` is using "under-the-hood"..._) 
JWTs are an _order of magnitude faster_ to check which makes your app _less_ prone to "DDOS".

I would appreciate it if you raised an _issue_ on the module explaining why you think `hapi-auth-cookie` is "_better_" so we know what we need to _improve_. 👍

**Comment by JMurphyWeb** [comment]
@nelsonic I did not say I thought it was better. Maybe I will be able to better judge once I have implemented jwt2. I will flag an issue if I can see a need. 

Thanks for your explanation.

**Comment by JMurphyWeb** [comment]
This issue will be resolved when #121 is merged.

**Comment by JMurphyWeb** [comment]
auth.js is in master
