### ISSUE TITLE
Different classes for 'lists'

### ISSUE THREAD

**Issue by mk4111** [emfoundation/ce100-app#681]
We have a number of 'lists': explore[orgs, chals, insights], people, resources, archived challenges.
Which generally share some similar structures + styling.

As can be seen from [this comment](https://github.com/emfoundation/ce100-app/issues/665#issuecomment-279793633) and [another comment following](https://github.com/emfoundation/ce100-app/issues/665#issuecomment-279796206) there's some overlap, although perhaps quite little.

I think it could be a good idea to try and unify our styling across all 'lists' (i.e. ) so that we only have to change one class for the changes to propagate equally and appropriately.

**Comment by mk4111** [comment]
With the updates to #705 and #685, this should (almost) be resolved. Will need to revisit to unify organisations list into a similar format though.

**Comment by mk4111** [comment]
The general structure of 'list' items in explore/lists (apart from for organisations!) are

```js
<li class="list__item **_list__item--medium_**">
  {{#if permissions.primary}}
    {{#if permissions.editable}}
      <a class="icon icon--edit icon--desktop" href="/challenges/{{id}}/edit">
        <img src="../../../public/assets/Edit.svg" alt="Edit" />
      </a>
    {{/if}}
  {{/if}}

  <div class="list__subblock">
    <a href="/challenges/{{id}}" class="card__header--challenge card__data--link">
      {{title}}
    </a>

    {{#if shared_by}}
    <p class="card__copy card__additional u-teal">Shared by
      <a href="/orgs/{{org_id}}" class="u-teal">
        {{shared_by}}
      </a>
    </p>
    {{/if}}
  </div>
</li>
```

I've highlighted `list__item--medium` because (in addition to `list__item`) it specifically applies to challenges and resources/insights.
People List only has `list__item`.
Explore Orgs has `list__item` and `list__item--big`.

**Comment by mk4111** [comment]
The above has been updated following the completion of #697 with the details below:

Explore Orgs _and_ People List use `list__item` and `list__item--big`

--> Given that the old styling on list__item (in terms of padding/margins/line heights and size) is no longer solely required, I will update list__item with the diff with list__item--medium, and remove list__item--medium as it will no longer be needed.

**Comment by asimonw** [comment]
@mk4111 or @JMurphyWeb is this something we need to test?

**Comment by iteles** [comment]
A technical issue, this is one for us @asimonw, you're right 👍
