### ISSUE TITLE
Archiving all challenges removes 'Go To Archived Challenges'

### ISSUE THREAD

**Issue by mk4111** [emfoundation/ce100-app#683]
Archiving all challenges a) removes all challenges from view, and displays: 'You haven't shared a challenge yet'. b) 'Go To Archived Challenges' options is removed.

As primary users are the only users with edit/activating permissions, this will mean that their archived challenges will become inaccessible (unless they create another challenge, so that they can access archived challenges again)

**Comment by JMurphyWeb** [comment]
This doesn't seem to be an issue anymore @mk4111
