### ISSUE TITLE
Use Intercom chat widget instead of feedback button

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#686]
We have an account and would do most of the setup.
https://www.intercom.com/live-chat

**Comment by mk4111** [comment]
Hi @asimonw, is the setup on EMF's side ready for this? If so, could you please provide us with the key/links to implement this in place of the current feedback method?

**Comment by asimonw** [comment]
@fannyBkane Could you please set this up and email the necessary to the ce100.emf address?

**Comment by mk4111** [comment]
Hi @fannyBkane and @asimonw ! Received the information through email and just wanted to let you know that we'll confirm it's working as soon as we get onto that issue! Thank you!

**Comment by mk4111** [comment]
I've added the script to `default.html` but it is not working on localhost.
On [this link](https://docs.intercom.com/install-on-your-product-or-site/other-ways-to-get-started/integrate-intercom-in-a-single-page-app) it seems that their user information needs to be registered and authenticated on yourside. Please let me know if it doesn't work once we redeploy! (Will add please-test label once merged in and redeployed!)

**Comment by asimonw** [comment]
@fannyBkane Is there still something to activate in the Intercom admin? (I think I remember something like a "show widget" setting which needs to be selected) I can see that the app is making requests to the Intercom API, but nothing is appearing.

**Comment by fannyBkane** [comment]
@asimonw You are right - I've just activated and it works! I will customise the colours and message through the Intercom app. @mk4111 Thank you it all seems to work!

**Comment by asimonw** [comment]
@mk4111 It's working now, thanks! The old feedback button is still there though.. could you please remove that before closing this issue please?
