### ISSUE TITLE
People List: contact detail overflows

### ISSUE THREAD

**Issue by mk4111** [emfoundation/ce100-app#687]
When a user's name/job title/workplace is quite long the text 'unaligns' itself to accommodate the text.

![screenshot from 2017-02-16 12-01-06](https://cloud.githubusercontent.com/assets/13470325/23020579/a0a2c76a-f43f-11e6-98e4-8cae23465548.png)

**Comment by mk4111** [comment]
On primary user view this does not happen with Anita Rose.
![screenshot from 2017-02-16 12-06-25](https://cloud.githubusercontent.com/assets/13470325/23020733/5d57eb60-f440-11e6-8bb9-ad19b2bfa785.png)

We need to check this with longer job names, etc. 
The class name to fix is `.list__subblock` - need to give it a fixed width so that it does not overflow into the toggle icon (3 dots).

**Comment by mk4111** [comment]
The text goes onto the next line when it reaches full width:
![screenshot from 2017-02-16 12-14-06](https://cloud.githubusercontent.com/assets/13470325/23020962/703aa532-f441-11e6-88b1-c9b78301ee87.png)
Need to cap width to around 90%

**Comment by mk4111** [comment]
This does however still cause issues with admin view because of the green dot...
![screenshot from 2017-02-16 12-22-57](https://cloud.githubusercontent.com/assets/13470325/23021200/abfa079c-f442-11e6-9039-cc6167390e46.png)

@asimonw, would it be ok to move the green/red dots into the margins for this view? It would look like this:

![screenshot from 2017-02-16 12-22-10](https://cloud.githubusercontent.com/assets/13470325/23021175/909c80f6-f442-11e6-9663-638f59e6d4c8.png)

**Comment by asimonw** [comment]
@mk4111 That sounds reasonable, yes.

**Comment by mk4111** [comment]
![screenshot from 2017-02-16 20-28-19](https://cloud.githubusercontent.com/assets/13470325/23039724/7da097aa-f486-11e6-8a5c-e9be0c53ed0d.png)

Having a little struggle with fixing the width of the email, which can overflow as can be seen in the example above.

anchor and span are by default inline elements so cannot have a fixed width. Need to think of something else...

**Comment by mk4111** [comment]
span cannot have line heights --> (it adopts that of the nearest block parent)[http://stackoverflow.com/questions/18151124/css-reducing-line-spacing-of-text]
  
Have switched out span for div, applied a new utilities class called `u-text-wrap` which will wrap the text and contain it within a certain width. Applied line-height and padding to make it more intuitive that it is part of the same field

**Comment by mk4111** [comment]
Now looks like:

![screenshot from 2017-02-20 13-30-24](https://cloud.githubusercontent.com/assets/13470325/23126954/ff07599a-f770-11e6-8618-2f6b90904f07.png)
![screenshot from 2017-02-20 13-30-34](https://cloud.githubusercontent.com/assets/13470325/23126957/0090b842-f771-11e6-8771-6a3d853cda8a.png)
![screenshot from 2017-02-20 13-31-15](https://cloud.githubusercontent.com/assets/13470325/23126958/029c6c08-f771-11e6-8532-34e6d856caad.png)
