### ISSUE TITLE
Views - explore insights

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#689]
Insights
https://app.zeplin.io/project.html#pid=589c772f8ad534321d652f04&sid=589c8949b9d031891fc4e4e0

Includes resources
https://app.zeplin.io/project.html#pid=589c772f8ad534321d652f04&sid=589c8a6e4a08e9d20c769a07

**Comment by mk4111** [comment]
This issue was covered in conjunction with #645

**Comment by fannyBkane** [comment]
@mk4111 All good!

@asimonw Close. Now.

**Comment by asimonw** [comment]
@fannyBkane Sir, yes Sir!
