### ISSUE TITLE
views - edit org 

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#690]
https://app.zeplin.io/project.html#pid=589c772f8ad534321d652f04&sid=589c8ad1497e265c1d5caa31

![screen shot 2017-02-16 at 15 33 10](https://cloud.githubusercontent.com/assets/12638261/23027767/4498ecba-f45d-11e6-8d15-2fc33c2e8454.png)

**Comment by JMurphyWeb** [comment]
We are going to have to change a bit of the structure in order to get the title with logo card to float left and not be stacked on top of each other. 

@asimonw can you let us know how high the priority that aspect of this view is?

**Comment by asimonw** [comment]
@JMurphyWeb Is that because you are using the same partial as for the profile public view?
Currently, they are next to each other in the app, so I'm not sure what the problem would otherwise be. Since it's an edit view, not public, another solution might be ok. It's not as important as the public view. It's very similar to how logo and title are laid out in the org list view, so maybe that can be reused?

Get @fannyBkane 's input if needed.

**Comment by JMurphyWeb** [comment]
Yes that is true @asimonw. we haven't looked into it in too much detail but perhaps we could use that partial, although that does have slightly different styles/borders attached. 

It is just a small thing that we thought might not be too important which could save us some time.

**Comment by asimonw** [comment]
@JMurphyWeb Agreed that there are higher priority things. I suggest you leave it for now and we revisit it towards the end of the sprint if there is time.

**Comment by JMurphyWeb** [comment]
Admin
<img width="247" alt="screen shot 2017-02-22 at 16 11 19" src="https://cloud.githubusercontent.com/assets/12638261/23215052/b04e1884-f919-11e6-8e0e-3b4192a342e7.png">
<img width="246" alt="screen shot 2017-02-22 at 16 11 23" src="https://cloud.githubusercontent.com/assets/12638261/23215053/b04f8f7a-f919-11e6-8609-b1feca7212c4.png">

Primary
<img width="245" alt="screen shot 2017-02-22 at 16 11 53" src="https://cloud.githubusercontent.com/assets/12638261/23215054/b0516336-f919-11e6-9bc8-0cae719fff55.png">
<img width="253" alt="screen shot 2017-02-22 at 16 12 05" src="https://cloud.githubusercontent.com/assets/12638261/23215055/b054611c-f919-11e6-9dec-1d39b621ba61.png">

**Comment by JMurphyWeb** [comment]
Now with disabled tags:
<img width="242" alt="screen shot 2017-02-22 at 16 29 25" src="https://cloud.githubusercontent.com/assets/12638261/23215749/1ea9293e-f91c-11e6-8296-48b4ae2ebe80.png">

**Comment by fannyBkane** [comment]
@asimonw ok to close.
