### ISSUE TITLE
View - Edit settings

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#691]
https://app.zeplin.io/project.html#pid=589c772f8ad534321d652f04&sid=589c8a9581d4a5831f1889a5

![screen shot 2017-02-16 at 15 40 16](https://cloud.githubusercontent.com/assets/12638261/23028117/4af8c98a-f45e-11e6-9ca0-a9c35bfecaab.png)

**Comment by JMurphyWeb** [comment]
All new features are there:

<img width="241" alt="screen shot 2017-02-20 at 19 43 59" src="https://cloud.githubusercontent.com/assets/12638261/23139570/f7d3dfde-f7a4-11e6-88cc-468f03f29511.png">


<img width="241" alt="screen shot 2017-02-20 at 19 43 54" src="https://cloud.githubusercontent.com/assets/12638261/23139574/fcf13340-f7a4-11e6-858b-0d983d3fba8d.png">

**Comment by fannyBkane** [comment]
@JMurphyWeb all good

@asimonw fine to close this one
