### ISSUE TITLE
Views - Add challenge

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#692]
https://app.zeplin.io/project.html#pid=589c772f8ad534321d652f04&sid=589c8ca3c4ac70861db57f6f

**Comment by JMurphyWeb** [comment]
From what i could see:

- Always at least 28px margin-bottom underneath a form input
- 37px between bottom of form input and the following form label

So I have added the 28px margin bottom on the input fields, and a padding-top of 9px on the input labels

![screen shot 2017-02-20 at 11 25 57](https://cloud.githubusercontent.com/assets/12638261/23123287/b29d241a-f75f-11e6-9540-a660cb4ea833.png)


![screen shot 2017-02-20 at 11 26 04](https://cloud.githubusercontent.com/assets/12638261/23123288/b2a693ec-f75f-11e6-8088-844f51e75462.png)

**Comment by fannyBkane** [comment]
@JMurphyWeb could the button say 'Save & add tags'?

**Comment by fannyBkane** [comment]
Hey @JMurphyWeb can you add the arrow in the Save & add tags button?

**Comment by JMurphyWeb** [comment]
this should be in the add challenge view already.

**Comment by JMurphyWeb** [comment]
(on staging)
