### ISSUE TITLE
View Edit challenge

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#693]
https://app.zeplin.io/project.html#pid=589c772f8ad534321d652f04&sid=589c8ca6ad7002951f549696

**Comment by JMurphyWeb** [comment]
@fannyBkane could we please get the right arrow icon from the button in the above wireframe? Thanks!

**Comment by JMurphyWeb** [comment]
I have fixed the bottom nav not showing up in this view

**Comment by JMurphyWeb** [comment]
![screen shot 2017-02-20 at 13 08 41](https://cloud.githubusercontent.com/assets/12638261/23126246/c117140c-f76d-11e6-9576-be13627c5b5b.png)

**Comment by fannyBkane** [comment]
Arrow right svg sent.

**Comment by fannyBkane** [comment]
@JMurphyWeb 

Could the small text above the button say 'Clicking 'Save' will make your challenge public to the network'

instead of 'Clicking 'Next'...'?

**Comment by JMurphyWeb** [comment]
<img width="637" alt="screen shot 2017-02-26 at 12 45 04" src="https://cloud.githubusercontent.com/assets/12638261/23339001/6ed4d45a-fc21-11e6-96d7-c2f6fc42bf15.png">

Copy changed and icon added.

**Comment by fannyBkane** [comment]
Awesome. @JMurphyWeb Would it be possible to up the size of the arrow just a bit, so that it is more legible. Thank you!

**Comment by fannyBkane** [comment]
@asimonw fine to close.
