### ISSUE TITLE
View Desktop - Add/Edit challenge error messages

### ISSUE THREAD

**Issue by mk4111** [emfoundation/ce100-app#694]
https://app.zeplin.io/project.html#pid=589c772f8ad534321d652f04&sid=589cca449e603a741d5e7b17

**Comment by JMurphyWeb** [comment]
Here is how i have attempted to update the error message from Joi, similar to how we have done it in other models:

```

var Joi = require('joi');

module.exports = {
  payload: {
    title: Joi.string().min(1).options({ language: { any: { allowOnly: 'Please add a challenge title to continue.' } } }),
    description: Joi.string().min(1).required()
  },
  failAction: require('../handlers/challenges/edit.js')
};

```

I have tried a lot of different combinations but cant seem to get it to alter the error message.

Their documentation is a bit lousy: https://github.com/hapijs/joi/blob/v10.2.2/API.md

**Comment by fannyBkane** [comment]
@asimonw ok to close.
