### ISSUE TITLE
View - Add tags

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#695]
https://app.zeplin.io/project.html#pid=589c772f8ad534321d652f04&sid=589c8cf5bc9fa54d1f79afa0

![screen shot 2017-02-16 at 15 52 37](https://cloud.githubusercontent.com/assets/12638261/23028701/092b9f58-f460-11e6-8cfc-3ad063b4f77f.png)

https://app.zeplin.io/project.html#pid=589c772f8ad534321d652f04&sid=589c8cf4bc9fa54d1f79af70

![screen shot 2017-02-16 at 15 56 02](https://cloud.githubusercontent.com/assets/12638261/23028846/732f0cc8-f460-11e6-86fa-bc9ded2cb50d.png)

**Comment by mk4111** [comment]
Views now look like:

![screenshot from 2017-02-22 10-07-09](https://cloud.githubusercontent.com/assets/13470325/23206771/dda4e8c2-f8e6-11e6-8844-9e77b3471e4e.png)

![screenshot from 2017-02-22 10-06-45](https://cloud.githubusercontent.com/assets/13470325/23206770/db555958-f8e6-11e6-9a93-3db9ad28378b.png)

The 'Back' and 'Cancel' buttons have been added to each 'add-tags-view.js'; these exist in the handlers for 'challenges', 'insights' and 'organisations' and affect the following flows:
- challenges/add
- challenges/{id}/edit
- insights/add
- insights/{id}/edit
- orgs/add
- orgs/{id}/edit

Clicking the 'Back' and 'Cancel' button have the following effects:
(1) For `challenges/{id}/tags`, 
- back: `challenges/add` or `challenges/{id}/edit` (if cid exists)
- cancel: `orgs` or `orgs/{id}` (if oid exists)
(2) For `insights/{id}/tags`
- back: `insights/add` or `insights/{id}/edit` (if cid exists)
- cancel: `orgs`
(3) For `orgs/{id}/tags`
- back: `orgs/{id}/edit`
- cancel: `orgs`

**Comment by fannyBkane** [comment]
@mk4111 Could you make the cancel button and save button a similar width?

**Comment by mk4111** [comment]
This is included in #732; Will be sure to update this issue once it has been merged in!

**Comment by mk4111** [comment]
Has been merged; Will be ready to review on staging shortly

**Comment by fannyBkane** [comment]
@mk4111 I am concerned with the legibility of the blue text on the blue background at the top. 

Would be great to change to the colour as seen on here: https://zpl.io/u0QgI

@asimonw otherwise it is fine to close.

**Comment by SimonLab** [comment]
@asimonw is this issue still happening or is it ok to close it?
