### ISSUE TITLE
View - People list

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#697]
https://app.zeplin.io/project.html#pid=589c772f8ad534321d652f04&sid=589c9023086bd77d1f87c943

![screen shot 2017-02-16 at 16 06 15](https://cloud.githubusercontent.com/assets/12638261/23029301/f48b4fe2-f461-11e6-9a8c-e1f4bf53a332.png)

**Comment by mk4111** [comment]
There is a [bug](https://github.com/emfoundation/ce100-app/issues/687) that is very much related to this issue too. Will resolve together.

**Comment by mk4111** [comment]
Have updated the icon colours, font size, etc.

Other fixes detailed in #687

**Comment by fannyBkane** [comment]
All good. @mk4111 

@asimonw can you pleeeease close this issue?
