### ISSUE TITLE
View Desktop - Login

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#698]
https://app.zeplin.io/project.html#pid=589c772f8ad534321d652f04&sid=589c94af2ae4407a1d57157a

**Comment by JMurphyWeb** [comment]
<img width="243" alt="screen shot 2017-02-20 at 22 12 21" src="https://cloud.githubusercontent.com/assets/12638261/23162348/54792dde-f836-11e6-9bab-ccd946a0bb3b.png">

**Comment by asimonw** [comment]
@JMurphyWeb Ok for now, move on to other screens first and see if we still have time for this one later on.

**Comment by fannyBkane** [comment]
The text-shadow in the button looks too strong - would be great to check if it corresponds with the mockup?

But anyway @asimonw @JMurphyWeb Fine with me, let's change to a lower priority.

**Comment by asimonw** [comment]
Remaining issue is duplicate of the one raised in #659 so closing this one.
