### ISSUE TITLE
View Desktop - Walkthrough

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#699]
https://app.zeplin.io/project.html#pid=589c772f8ad534321d652f04&sid=589c953d9e603a741d5d60b2

**Comment by JMurphyWeb** [comment]
Just put a little bit of time into getting this view look ok in Desktop view. Can revisit when there is time.

<img width="1264" alt="screen shot 2017-02-22 at 14 47 48" src="https://cloud.githubusercontent.com/assets/12638261/23212157/1c769b96-f90e-11e6-9e06-e22883ec9cdd.png">
<img width="1265" alt="screen shot 2017-02-22 at 14 47 55" src="https://cloud.githubusercontent.com/assets/12638261/23212158/1c78d41a-f90e-11e6-81cf-3c32145b96f0.png">
<img width="1263" alt="screen shot 2017-02-22 at 14 48 06" src="https://cloud.githubusercontent.com/assets/12638261/23212159/1c7c5126-f90e-11e6-95ab-81c20523a9b7.png">

**Comment by fannyBkane** [comment]
@JMurphyWeb @asimonw fine with me to keep it centred for the moment. Could you just up the size to around or at least 16px?

**Comment by fannyBkane** [comment]
Hey @JMurphyWeb could you up the paragraph 'landing-card__description' text size to 1.2rem, and add a max width of 400px?
