### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#7]
As a primary user, I can reset my password from the login screen, so that I can still access the platform if I have forgotten my password.

**Comment by asimonw** [comment]
Bumping the priority. We do want this to be built in sprint 3 or 4.

**Comment by JMurphyWeb** [comment]
Basic implementation plan:
If a user requests a password reset, we will send them an email with an encoded  query param in the url, which, when decoded will represent the users id. 

General implementation question:
A link to reset your password should expire.  @mk4111 and I were thinking the reset password link should expire when whichever comes soonest out of a) a period of time (say 2 days) and b) the link has been used to reset the users password. Is that normal practice for a password reset email?

**Comment by JMurphyWeb** [comment]
More specific to our application, I was unsure of where we should store the password request data. Possibilities include: redis (hopefully quick and easy to implement), postgres in our `people` table (i need to explore whad

**Comment by mk4111** [comment]
I think redis makes most sense, because I think it's the type of data that would be good to keep a record of, but not necessarily one that is a 'feature' of our app in terms of user experience... 

I also think it's faster to implement if we store this in redis

**Comment by JMurphyWeb** [comment]
yeah I agree with your reasoning @mk4111 👍

**Comment by JMurphyWeb** [comment]
Looking into using JWTs and no need for storing any data.

**Comment by SimonLab** [comment]
I don't think we need to store anything. From what I understand you just want to use redis to had a time validation on the url but I think JWT can have an expire time

**Comment by mk4111** [comment]
Expiry time makes sense, but would the JWT still be active after someone resets their password? Say they try to reset their password, (1) click on 'forgot password' --> (2) receive link --> (3) click on link and update password, would they then be able to repeat step two and three?

**Comment by SimonLab** [comment]
Yes it's true that a jwt token which is still valid can be reuse to reset again the password. I think for a first version instead of having another state in a database we can have a short time where the jwt is valid, for example 5mn.

**Comment by JMurphyWeb** [comment]
I am just writing up the tests for this feature now.

`password-reset` route:

![screen shot 2017-01-23 at 12 14 53](https://cloud.githubusercontent.com/assets/12638261/22203598/c77fcaaa-e165-11e6-9910-b63107ea5bf2.png)

Notify user if the email is recognised:

![screen shot 2017-01-23 at 12 15 10](https://cloud.githubusercontent.com/assets/12638261/22203599/c797be08-e165-11e6-8aa6-8058e033c598.png)

**Comment by JMurphyWeb** [comment]
Whilst writing this I realised that the class 'error' didn't exist so i removed it from a few files.

**Comment by JMurphyWeb** [comment]
Now moving onto testing the actual resetting of the password with route `/people/password-reset`:

Test:
- we can see the view when the jwt is not expired
- user is notified if the jwt is expired upon GET request
- failing validation on the post route
- Passing validation on post route and attempt to login with new credentials

**Comment by JMurphyWeb** [comment]
Tests are now written. feature is ready for reviewal.
