### ISSUE TITLE
Views Desktop - Select Tags

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#704]
https://app.zeplin.io/project.html#pid=589c772f8ad534321d652f04&sid=58a1aea86d53d90f4bf5e634

**Comment by mk4111** [comment]
This issue was covered in #717 PR (linked to mobile view, #695)

**Comment by mk4111** [comment]
Need to replace 'X' button with 'Cancel' round button

**Comment by mk4111** [comment]
Updated, now looks like:

![screenshot from 2017-02-22 12-22-35](https://cloud.githubusercontent.com/assets/13470325/23211359/aa5b2806-f8f9-11e6-89f5-7573d0e59df6.png)
![screenshot from 2017-02-22 12-22-06](https://cloud.githubusercontent.com/assets/13470325/23211360/ac1a2818-f8f9-11e6-8810-181d442ea296.png)

**Comment by mk4111** [comment]
Button text has been updated from 'Done' to 'Save'
