### ISSUE TITLE
View - Form inputs (type text)

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#707]
Form fields type text and textareas need to have some changes as per wireframes:

https://app.zeplin.io/project.html#pid=589c772f8ad534321d652f04&sid=589cc43849e6029c0cf0820d

**Comment by JMurphyWeb** [comment]
<img width="320" alt="screen shot 2017-02-17 at 14 32 07" src="https://cloud.githubusercontent.com/assets/12638261/23069060/e476b724-f51d-11e6-83ee-14b12425d5a4.png">


This is how they look now

**Comment by fannyBkane** [comment]
@JMurphyWeb Looks good. 

@asimonw fine to close this issue.
