### ISSUE TITLE
Admin user on actual mobile device: clicking "Add" button makes the whole screen inactive

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#722]
On iPhone 5, this happens in Chrome but not in Safari. It also doesn't happen in the device simulator in chrome dev tools. Not sure what's going on, but it feels like all click handlers get a preventDefault.

Reproduce by simply trying to tap the "Add" button on an actual mobile device, using Chrome. The option list will not open. Tapping anything else also has no effect.

**Comment by JMurphyWeb** [comment]
@asimonw just to let you know this is not in the milestone and therefore not part of what we will get onto today. Could you please add it to the milestone and prioritise it if you want us to look at it?

**Comment by asimonw** [comment]
@JMurphyWeb Because this is only for admins and on mobile, it's not as urgent as some other remaining issues. It might be a sign of a deeper problem though, so I'm adding it to the milestone.

**Comment by mk4111** [comment]
Just to note - This was discussed on gitter with @asimonw, and it seems as this may be an issue isolated to iPhones, as the issue has only been reported for users of this phone. When I tested on an Android device, this issue could not be replicated. We will time estimate this issue with this point in consideration.

**Comment by JMurphyWeb** [comment]
@asimonw I am also unable to re-create this issue (on ios as well). Could we ask that you check if you are still seeing this problem?

**Comment by asimonw** [comment]
@JMurphyWeb Just tried again and I also don't have the issue anymore. I would attribute it to a browser glitch, but @fannyBkane had exactly the same problem. @fannyBkane could you log in as admin on staging, press the "Add" button and see if the app still freezes on your iPhone?

**Comment by fannyBkane** [comment]
@JMurphyWeb @asimonw It works for me now :)

**Comment by asimonw** [comment]
One option: connection issue at the office, affecting us both. Potentially JS not fully loaded..

In any case, @JMurphyWeb looks like we can park this one! I'll keep it open for now, close it if it doesn't re-appear in production. Removing it from the milestone.

**Comment by JMurphyWeb** [comment]
@asimonw it relies on css only so shouldn't be a js problem (although could be to do with something else js related)
Ok, fingers crossed 🤞

**Comment by SimonLab** [comment]
@asimonw is this still an issue? I haven't an iphone 5 to test this at the moment

**Comment by asimonw** [comment]
@SimonLab Tested again and this doesn't seem to be a problem anymore. Closing the issue, thanks for the reminder.

**Comment by kamaldhariyal** [comment]
Hi... do you have script that can freeze latest version of Siri. I want it in urgent bases. please provide if any of you have..

**Comment by iteles** [comment]
@kamaldhariyal I'm afraid not. Not something our users have requested before.
