### ISSUE TITLE
Production database

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#727]
Updated DB:
Leave one admin user with unguessable password and ce100 gmail address in production db.

@asimonw please let me know if this is not desirable.

#655

**Comment by asimonw** [comment]
@JMurphyWeb That sounds good.

**Comment by JMurphyWeb** [comment]
Thought best way to do this was wipe the current database by deploying from a branch with no data except our 1 admin user, remembering to change the reset env variables to true, then back to empty string once db has been reset.

**Comment by mk4111** [comment]
@JMurphyWeb that sounds good to me! Will we do this today?

**Comment by mk4111** [comment]
I think this is complete --> we have redeployed from branch name: [redeploy-phase2](https://github.com/emfoundation/ce100-app/tree/redeploy-phase2)
