### ISSUE TITLE
Admin user interface same as primary user

### ISSUE THREAD

**Issue by vicky-d1** [emfoundation/ce100-app#73]
We’ve looked at using the same interface for an admin and primary user and think it works, we would just have an 'add organisation’ button above the organisation search view, an ‘add news item’ button above the latest news and an ‘add user’ within the directory as well as the ability to edit relevant fields. We’ll make the changes to the designs and upload to zeppelin.

**Comment by mk4111** [comment]
@vicky-d1 has this been updated?

**Comment by asimonw** [comment]
@mk4111 Zeplin has ben updated. The screens with admin in the title are either only accessible to admins or reflect additional functionality, e.g. (edit buttons).
