### ISSUE TITLE
Drop down menu linked to burger icon shouldn't scroll

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#731]
The menu behind the burger icon (with links to Settings, People, Resources) should be fixed to the viewport. At the moment, the user can scroll it up and see the content which should be hidden behind it.

It looks like this could be solved by adding `position: fixed` to the containing div.

**Comment by mk4111** [comment]
@asimonw - you're right about the position fixed. Unfortunately we can still see the landing page content as we scroll in the section where the top-navbar is.

![screenshot from 2017-02-28 14-13-53](https://cloud.githubusercontent.com/assets/13470325/23408501/2a08e636-fdc0-11e6-93bc-ac86ba522701.png)

**Comment by asimonw** [comment]
@mk4111 The top bar can be fixed as well actually. That's always been the idea, but might hot have been clear. It can stay fix at the top in the same way that the bottom nav is fixed to the bottom on mobile.

**Comment by mk4111** [comment]
@asimonw - okidokie! Will make both fixed! Thank you!
