### ISSUE TITLE
Update copy on walkthrough screen

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#736]
Nothing changes to the structure, still 5 sections, of which 4 have a button linking to parts of the app. The links in the buttons should stay as they are:

**Sally, innovation begins with collaboration.**
Get connected to the people making the circular economy happen.

**Tell us about you**
Share your circular economy vision, expertise and challenges.

Button: Update profile

**Get to know the network**
Find out what other members are working on and get in touch.

Button: See organisations

**Share a challenge**
And find the people who can help you solve it.

Button: Add challenge

**Find the latest insights**
Get access to circular economy content on the topics you’re interested in.

Button: Explore insights

**Comment by asimonw** [comment]
The updated mockup can be found [here](https://zpl.io/29JvPl)

**Comment by JMurphyWeb** [comment]
This view has been a struggle to get right with various mobile sizes and desktop screens. Copy update should be simple, but could cause more problems than we might expect.

**Comment by asimonw** [comment]
@JMurphyWeb Looks great. There was a small typo in the third section though.. `member's` should be changed to `members`. My bad.. this had been updated in the mockup, but not in this issue.
