### ISSUE TITLE
Landing Page - down arrow icon doesn't scroll again

### ISSUE THREAD

**Issue by mk4111** [emfoundation/ce100-app#737]
We have an issue where clicking on the down arrow icon does not have the expected effect past 'Get to know the network'; i.e. does not scroll down to the next card.

**Comment by mk4111** [comment]
@JMurphyWeb - can you see if this is an issue on your phone too please? Thanks

**Comment by JMurphyWeb** [comment]
my buttons work (on staging0, but the css is bad
