### ISSUE TITLE
Missing Radial background pattern

### ISSUE THREAD

**Issue by harrygfox** [emfoundation/ce100-app#743]
In PR #719 
Something that was missing from the wireframes ([select tag-small desktop](https://app.zeplin.io/project.html#pid=589c772f8ad534321d652f04&sid=58a1aea86d53d90f4bf5e634)):
the radial background on the second bar that says "select tags".
```css
background-image: radial-gradient(circle at 50% 50%, rgba(0, 49, 83, 0.89), #002944);
```

![screen shot 2017-03-01 at 10 27 48](https://cloud.githubusercontent.com/assets/7805691/23456036/c0bfe378-fe69-11e6-87a0-67c46629305c.png)

**Comment by mk4111** [comment]
@harrygfox - thank you!!! Missed this wahhn! D:

**Comment by mk4111** [comment]
![screenshot from 2017-03-01 10-58-32](https://cloud.githubusercontent.com/assets/13470325/23457055/08dbdb7c-fe6e-11e6-9cee-a5bba1681b27.png)

**Comment by mk4111** [comment]
@harrygfox - if :) could you please close ze issue? Thank you!

**Comment by fannyBkane** [comment]
@asimonw ok to close the issue.
