### ISSUE TITLE
Update copy for activation and password reset emails

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#766]
I will send an email to the ce100.emf email with all the necessary details.

**Comment by asimonw** [comment]
@iteles Email sent, but as explained in the email, this change can't go to production until we have the final url in place. I'll let you know in this issue when everything's in place.

**Comment by JMurphyWeb** [comment]
@asimonw this just requires a change in environment variables so we can get new copy in now.

**Comment by asimonw** [comment]
@JMurphyWeb That would be great, thanks! Should get the SSL working today I hope, so we can update that env variable soon.

**Comment by asimonw** [comment]
@JMurphyWeb The SSL is now working so it should be fine to update the env var as well. Make sure to use https. There is one issue though, but we should deal with that in #651

**Comment by JMurphyWeb** [comment]
env var updated. just need to redeploy.

**Comment by mk4111** [comment]
@JMurphyWeb - is this a `please-test` too then?

**Comment by asimonw** [comment]
@JMurphyWeb I know there's no please test label yet, but I just noticed that the new copy is there, but the email still comes from the ce100.emf address. Could that be changed to our ce100 address please? Same one as in the body of the text. Thanks!

**Comment by mk4111** [comment]
Hi @asimonw - I've just added the said email to the list of 'verified emails'; there should be an email from AWS SES requesting confirmation of this. Could you please check and confirm? Once that's done, I'll test locally and will push up upon checking it's successful!

**Comment by asimonw** [comment]
@mk4111 Thanks, I'll check. When you make the change, could you also change the titles of both emails as per instruction in the email I sent with the copy?

**Comment by asimonw** [comment]
@iteles I tested this again and it was all in place, actually. Closing the issue.
