### ISSUE TITLE
Add three more resource types

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#779]
Could we please add the following Types on /insights/add:
* CO.PROJECT
* IMAGE
* LINK

I hope that this can be done without affecting existing records. Note the dot in "CO.PROJECT"; this is not a typo.

**Comment by SimonLab** [comment]
At the moment there are two places that need an update:
- the frontend dropdown needs to get a new value this can be done in the helper file [here](https://github.com/emfoundation/ce100-app/blob/b9bafae1c449f3593f607bb6b1e687060350e3f7/server/handlers/helpers.js#L7)

- The constraint apply on the datbase needs to be updated on the insight plugin see [here](https://github.com/postgres-plugin/insights/blob/5485eefaed6a011e50e776e62d32e74f09be2323/lib/fixtures/create-tables.sql#L8)

The main issue is to make sure that we don't break any other constrains on the production database. So we need first to be sure that we test the migration on localhost and staging area first
