### ISSUE TITLE
Organisation profile titles should not automatically be title-cased

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#786]
Automatic title-casing doesn't work for a lot of organisation names, so this needs to be removed. The correct casing will be determined manually on a case by case basis.

**Comment by sohilpandya** [comment]
This is currently being done in the front-end with CSS classes. We will have to rummage through all the classes and views where this is being applied and make the changes accordingly. 
a. either remove the class entirely
b. modify class if it capitalizes the first character.
