### ISSUE TITLE
Unable to change assignee on issues/pull requests

### ISSUE THREAD

**Issue by nelsonic** [emfoundation/ce100-app#79]
Hi team, I am unable to modify the assignee on issues/pull requests ... kind of required to do my thing... 😉

**Comment by iteles** [comment]
@asimonw Please add  @nelsonic to the dwyl team as I don't have the permissions to 😊

**Comment by asimonw** [comment]
Must have overlooked that. @nelsonic is added now. Please close if that solves it.

**Comment by nelsonic** [comment]
Thanks.
