### ISSUE TITLE
After creating or editing a challenge, the user should be directed to the challenge view

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#790]
Currently, after creating/editing a challenge, the user is taken to the org profile. This means that the user does not see the details of what was created/edited. Instead, we should direct the user to the challenge card that was just created or updated.

**Comment by SimonLab** [comment]
This should be just a redirection.

**Comment by asimonw** [comment]
@sohilpandya The redirect works, but after landing on the challenge card after saving, I wanted to go back to the org profile view by clicking on the top right cross icon. This sent me back to the tag selection screen (the previous screen), instead of the org profile. 

Could the cross on a challenge card always take the user to their org profile. This is the current behaviour on the live app. Thanks!

**Comment by SimonLab** [comment]
@asimonw the cancel button should now redirect to the org profile page now

**Comment by asimonw** [comment]
@SimonLab I think the work on the tag selection might have recreated the bug?

If you follow the following steps:

create or edit a challenge and click save
you end up on the challenge card, which is perfect
click cancel on the challenge card
you go back to the "Edit challenge" view.
It would make more sense to direct the user to the org profile at this stage.

The redirect is a bit subtle, because you can also end up on a challenge card through the explore screen. So, could you make sure the following happens:

If the previous page was Explore: cancel challenge card -> back to Explore (already works like that)
If the previous page was org profile or edit challenge -> to org profile
Let me know if that doesn't make sense.
