### ISSUE TITLE
Desktop walkthrough page redesign

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#791]
Instead of having a long scrolling page, we would like to show all the different options at a glance, above the fold for a typical laptop/desktop browser ratio if possible.

Mockup to be added.

**Comment by fannyBkane** [comment]
Desktop: https://zpl.io/5aRSX

**Comment by SimonLab** [comment]
For the mobile view the card will go under each other

**Comment by harrygfox** [comment]
@SimonLab Completing this will require a slight change in handlebars templating. Right now each section of the 'walkthrough' (landing page) is one `landing-card` which pulls its text from the database. 
Now we need the landing-cards to be separate from the top card which says Welcome etc. 
Would you be able to help / take this on?

**Comment by SimonLab** [comment]
@asimonw @fannyBkane currently we have 4 main sections on the walkthrough page:
- Tell us about you
- Get to know the network
- Share a challenge
- Find the latest insights
![image](https://cloud.githubusercontent.com/assets/6057298/26211180/dc2c27a8-3be9-11e7-9d7d-84be0437feb0.png)

Do you still want to keep the last section (Find the latest insights) or do you want to drop it like on the design on Zeplin? If we keep it, how do you want to display the 4 cards on desktop?

**Comment by fannyBkane** [comment]
Hey @SimonLab my understanding is to keep three sections / cards. The headers and copy are likely to be updated.

**Comment by harrygfox** [comment]
@SimonLab I have made a first pass of this. Most of the styles from the wireframes have been implemented but not finished - all px numbers need to be converted to `rem` and the buttons on each landing__card must be fixed to the bottom of its container

**Comment by asimonw** [comment]
@SimonLab @harrygfox Indeed, you can drop the last section exactly as in the mockup.

**Comment by asimonw** [comment]
@harrygfox LGTM 👍 
@fannyBkane Could you also have a look, see if this can be closed?

**Comment by fannyBkane** [comment]
@harrygfox looks good @asimonw fine to close :)

**Comment by harrygfox** [comment]
Sorry, jumped the gun, over to you @asimonw
