### ISSUE TITLE
Change profile and burger icons

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#792]
The icon used for the Profile item in the navigation will be replaced. The burger icon will be changed to an icon which reflects better that it offers _more_ options, not the full navigation.

New icons to be shared.

**Comment by fannyBkane** [comment]
2 x options: 

![screen shot 2017-05-10 at 13 50 00](https://cloud.githubusercontent.com/assets/20577339/25899414/a797d338-3587-11e7-808c-e54a51b34923.png)

**Comment by fannyBkane** [comment]
![screen shot 2017-05-11 at 16 22 40](https://cloud.githubusercontent.com/assets/20577339/25957383/1b494c38-3666-11e7-8cce-88f5f71dcd93.png)

**Comment by fannyBkane** [comment]
Icons sent to gmail address :)

**Comment by sohilpandya** [comment]
@fannyBkane Thanks for sending those over, I've had a look at them and it looks like they are black by default. Do you usually send the different colored SVGs? So, in this case, send the one with a default of white?

**Comment by fannyBkane** [comment]
Hey Sohil,

I would usually send only the black (or so I try). Do you still need the
white, and should I send both black and white in the future?



*Fanny Breteau*
Designer ~ Digital Team

t: +44 (0) 1983 296 463
e: fanny.breteau@ellenmacarthurfoundation.org
<scs@ellenmacarthurfoundation.org>

<http://ellenmacarthurfoundation.org>

**Comment by sohilpandya** [comment]
@fannyBkane thanks for getting back, no need to send the white version just wanted to know what the process has been in the past. 😄 

I had one more question, would you like the profile icon to change on mobile as well or just change the hamburger menu on mobile and leave profile as is? 

Currently it is set to this: 
<img width="433" alt="screen shot 2017-05-16 at 16 38 46" src="https://cloud.githubusercontent.com/assets/2305591/26114808/376aac7e-3a56-11e7-8bf2-4f2f64c9c5be.png">

**Comment by fannyBkane** [comment]
@sohilpandya We'd like the profile icon to change on  both mobile and desktop, cheers :)

**Comment by SimonLab** [comment]
@harrygfox sorry I miss a small issue with the profile logo on the organistion list:
![image](https://cloud.githubusercontent.com/assets/6057298/26162246/1f0183a6-3b1e-11e7-99bd-347b680d1303.png)

Is it possible to get a round icon?

**Comment by harrygfox** [comment]
@SimonLab I believe the issue you have raised has been resolved

**Comment by harrygfox** [comment]
@SimonLab Realised the short-sighted nature of my changes - there is now support for a regular icon when the organisation does not have one of their own, as well as a non-regular icon for when a custom logo has been uploaded
