### ISSUE TITLE
Explore view: update to filter and tab design

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#793]
The functionality of the tag filter and different tabs in the Explore view is not sufficiently clear. The visual design will be improved.

Mockup to be shared.

**Comment by fannyBkane** [comment]
![screen shot 2017-05-09 at 17 20 51](https://cloud.githubusercontent.com/assets/20577339/25861212/ea4a74bc-34db-11e7-807b-5942a1871431.png)

**Comment by fannyBkane** [comment]
Mobile: https://zpl.io/ZyEJOe
Desktop: https://zpl.io/1Lvnx1

**Comment by sohilpandya** [comment]
The flow remains the same, the changes being made will be from the design perspective.

**Comment by asimonw** [comment]
@sohilpandya LGTM 👍 
@fannyBkane Could you also have look, see if this can be closed?

**Comment by fannyBkane** [comment]
@sohilpandya LGTM to me too :) 
@asimonw fine to close
