### ISSUE TITLE
Copy changes

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#796]
Here we'll collect some copy changes on profile forms and challenge forms and cards.

Org profile (public view):
- [x] Remove "OUR" from "OUR CIRCULAR ECONOMY VISION"
- [x] Add title: "EXPERTISE" above the tags (style can be the same as "CIRCULAR ECONOMY VISION")
- [x] If no challenges have been shared on an organisation’s profile yet:
**No challenges shared yet.**
- [x] If (in rare instances) no contact is visible, change text to:
**No contact details yet.**

Org edit view:
- [x] Title and information copy for mission statement (replaces current)
**Circular economy vision**
*What are the circular economy ambitions for your organisation?*
- [x] Title and information copy for tags (currently missing)
**Expertise** 
*Choose tags that describe what your organisation is good at and get matched with challenges that could use your expertise.*

Tag selection screen (on both org profile and challenge forms):
- [x] Simplify current text to: "We recommend adding up to 5 tags."

Challenge card
- [x] Change 'Matched with' to 'Matches'
- [x] Copy to explain why you’ve been matched when you’ve saved a challenge (should appear underneath word 'Matches'):
*These organisations have expertise that might help you with your challenge. Why not get in touch?*

Challenge edit:
- [x] Title and information copy for challenge title:
**Title**
*Add a short, descriptive title.*
- [x] Title and information copy for challenge description:
**Challenge description**
*Tell the network what you need help solving or if there are opportunities for collaboration.*
- [x] Above tags (above "Add tags" when no tags are selected yet), just some information copy:
*Choose tags that help describe your challenge and get matched with organisations that might have the expertise you need.*
- [x] Above the "Save & publish" button (replaces current):
*Clicking 'save' will make your challenge public on your profile.*

Style of titles and information copy can be same as currently used for org mission statement:
<img width="683" alt="screen shot 2017-05-19 at 18 21 05" src="https://cloud.githubusercontent.com/assets/15235804/26257233/1a2beddc-3cc0-11e7-94b1-fad88b4ae8fc.png">

**Comment by asimonw** [comment]
@SimonLab Copy changes to be made added to first comment!

**Comment by asimonw** [comment]
@SimonLab @sohilpandya The items which I have unchecked in the first column are not completely correct.
* On the org edit view, the title and description for the mission statement field are not correct. What is currently the title should be the instructions, and the title should simply be "Circular economy vision"
* The changes for the challenge form have been done for the edit challenge, but not for the create challenge view.

**Comment by sohilpandya** [comment]
@asimonw we've made the changes that you've mentioned above and ready for you to test on staging.
