### ISSUE TITLE
Pending state for users

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#798]
After a user has been sent an account activation email, but before they have activated their account, the state of the user should be pending (rather than already active). This should be indicated by an amber dot next to their name in the admin interface. This will allow the admin to know whether the user has successfully activated their account or not.

As long as a user is still pending (or inactive, of course), the user should not show up in any org profile or in the people list for non-admin users.

**Comment by SimonLab** [comment]
At the moment the status of the user is define in the database with a Boolean value on the "active" field
```
CREATE TABLE IF NOT EXISTS organisations (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  logo_url TEXT,
  mission_statement TEXT,
  active BOOLEAN NOT NULL
);
```
We need to
- update the table with a more detail field, "status"?
- update the logic when a user is created to put the status to "pending"
- update the logic when a user login for the first time to put the status to "active"
- update the logic when an admin define the user "inactive"

**Comment by sohilpandya** [comment]
**udpate** the above table should refer to `people` not organisations. 👍

**Comment by sohilpandya** [comment]
**WIP**

Following script needs to be run to add the extra column to the `people` table
`alter table people add column status VARCHAR(20) CHECK (status IN ('active', 'pending', 'inactive'))
;`

**Comment by asimonw** [comment]
@sohilpandya That seems to work, but there is a small regression. Logging in as an admin and going to Explore -> Insights, the enabled insights now have an orange dot instead of a green dot next to them. The org list still works as before, so only insights seems to be affected.

**Comment by sohilpandya** [comment]
@asimonw could you please test this out, we've updated this on staging.
