### ISSUE TITLE
Resend activation email for pending users

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#799]
An admin should be able to resend the activation email for a pending user. 

This could be done by adding a checkbox with label "Resend activation email on save" at the bottom of the user edit screen. This would be unchecked by default. On user creation, the checkbox should preferably not be there, or be checked by default if necessary.

Alternatively, we could enable the admin to copy the activation url to the clipboard.

**Comment by SimonLab** [comment]
With this flow, the admin will have to go to the edit user page, check the the checkbox and save the page to resend an email. Is the checkbox unchecked automatically after these steps?

Instead of going to the edit user page, could we have a button "resend" for pending user on the on the list of user page?

**Comment by asimonw** [comment]
@SimonLab A button would also work if that avoids having to worry about that state of that checkbox. Or a link, styled similarly to the "Disable user" at the bottom of the edit user screen. @fannyBkane what do you think?

**Comment by fannyBkane** [comment]
@SimonLab can you add a link like @asimonw  suggested? If it doesn't stand out enough we will change it to a button. Cheers.

**Comment by SimonLab** [comment]
@asimonw @fannyBkane once an admin has clicked on the "resend activation email" link should we redirect to the people list, or anywhere else?

**Comment by SimonLab** [comment]
![image](https://cloud.githubusercontent.com/assets/6057298/26305325/bff4e3fe-3ee6-11e7-902f-6c68cf6a443f.png)
At the moment the link redirect to the list of people page
