### ISSUE TITLE
Member profile creation

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#8]
As an EMF admin, I can create member profile pages with a page title **and logo** and link them to a primary user, so that primary users, once logged in, have access to the profile page of their organisation.

Note that the relationship will be one organisation to many users in the future.

**Comment by LucyJW** [comment]
EMF admins should be able to upload member logos too. We already have them available and it may be less constraining (from design and brand approval considerations) for us to upload these as part of the profile page set up for new members.

**Comment by asimonw** [comment]
User story updated to reflect @LucyJW's point.

**Comment by JMurphyWeb** [comment]
Will be finished when #55 is implemented
