### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by SimonLab** [emfoundation/ce100-app#800]
![image](https://cloud.githubusercontent.com/assets/6057298/26061355/a36eb104-397f-11e7-928e-dc10fad4feed.png)

We need to check that the new packages version won't break any features of the application

**Comment by SimonLab** [comment]
Unfortunately updating the dependencies, break our tests:
![image](https://cloud.githubusercontent.com/assets/6057298/26068167/826dbc88-3994-11e7-9053-8e12d3f06ce0.png)

This seems to be linked to tests related to admin. Instead of being redirected to the right page the tests are blocking the user with an unauthorised code 401. Need to investigate which package has some breaking changes.

**Comment by SimonLab** [comment]
Joi makes the app break with the version 10.4.2. Checking for any breaking changes on the documentation.

**Comment by SimonLab** [comment]
resolved with #805 the badges will be updated soon

**Comment by asimonw** [comment]
@SimonLab I'm assuming that this is not for me to test?

**Comment by SimonLab** [comment]
![image](https://cloud.githubusercontent.com/assets/6057298/26119730/29538eca-3a66-11e7-94ad-2628a4f397eb.png)

The devdepencies hasn't been updated yet but it is ok now if you check https://david-dm.org/emfoundation/ce100-app?type=dev

![image](https://cloud.githubusercontent.com/assets/6057298/26119762/56b24190-3a66-11e7-94dc-6b2de53768dd.png)
