### ISSUE TITLE
Improved tag selection flow design implementation - design

### ISSUE THREAD

**Issue by sohilpandya** [emfoundation/ce100-app#801]
Related to #789 

Once we are saving the state for the tags locally (cookie, local storage or session storage), we need to implement the designs for both the mobile and desktop view. 

Form/mobile: https://zpl.io/W62Dw
Explore/modal/mobile: https://zpl.io/222375

Form/modal/desktop: https://zpl.io/Z6ml4L
Explore/modal/desktop: https://zpl.io/Z1QNlvL

- Render `/orgs/11/edit` with a hidden section that contains the information related to the tags.
- When user decides to add/edit tags, show the modal

We are still discussing the rest of the flow once the tags have been selected and how we should it should be tackled.

**Comment by sohilpandya** [comment]
@asimonw just wanted to check what devices does this need to be compatible with as we'll be using some javascript on the front end and as far as I'm aware there isn't any front-end javascript being used in the app at this moment in time. 

We'll potentially have to use JavaScript for the **modal** as well as the **local storage**.

**Comment by asimonw** [comment]
@sohilpandya You can assume ES5 compatibility, but we would still like to support browsers like IE9, so no ES6/2015 features and beyond (unless you transpile of course). Using localStorage should be fine. Are there any other HTML5 API's you'd consider using?

**Comment by sohilpandya** [comment]
@asimonw I think that's all for now, just wanted to make sure everyone was on the same page and aware of it 👍, we are very likely to keep the javascript to ES5 for the front-end. 

Will be doing a spike to figure out the best possible way to tackle this.

**Comment by asimonw** [comment]
@fannyBkane Could you have a look at the design implementation of the tag selection screen for form fields?

**Comment by fannyBkane** [comment]
Hey @sohilpandya looks great. Is it just possible to do amend the tag colour to #40667e?

**Comment by fannyBkane** [comment]
Hey @sohilpandya it looks good!
Would it be possible to make a couple of amends on desktop views: 
-align tags and edit tags button to the left, 
-change edit tag colour+icon fill+border to #40667e
-align centre archive link

**Comment by sohilpandya** [comment]
Hi @fannyBkane, I've made the first two changes, but unsure about the last one, the archive link is already centered at the bottom of the page. 
<img width="353" alt="screen shot 2017-05-22 at 17 12 08" src="https://cloud.githubusercontent.com/assets/2305591/26318110/de5d1bd8-3f11-11e7-9aeb-facb81b4da9f.png">

**Comment by fannyBkane** [comment]
Hey @sohilpandya all good if the link is centred - I thought I'd seen it left aligned.
