### ISSUE TITLE
Access to Zeplin 

### ISSUE THREAD

**Issue by sohilpandya** [emfoundation/ce100-app#806]
Hi @fannyBkane, @asimonw & @iteles 

would it be possible to get access to the designs in zeppelin? both for @harrygfox & myself. 😄 

Our details:
- `sohilpandya{at}me.com`
- `harry{at}dwyl.io`

Thanks

**Comment by fannyBkane** [comment]
Hey @sohilpandya I need your email, as it's the first time I invite you...

**Comment by sohilpandya** [comment]
Hi @fannyBkane I've updated the original issue with the email details :)

**Comment by fannyBkane** [comment]
Hey @sohilpandya I've just sent an invite :)

**Comment by harrygfox** [comment]
Got it, thank you @fannyBkane ! 👍

**Comment by SimonLab** [comment]
people can access Zeplin :tada:  closing
