### ISSUE TITLE
tag selection flow for organistion

### ISSUE THREAD

**Issue by SimonLab** [emfoundation/ce100-app#815]
based on #789 

The selection of tags for the organisation should use the new modal view.
- [x] Add modal javascript for add and edit view
- [x] Update Joi validation to accept "tags" payload on post request on add and edit org
- [x] Update the handler of add and edit to allow them to save the tags directly into the database

**Comment by SimonLab** [comment]
The redirect is different for an admin or a primary user as only the admin as the right to change the logo. The redirection needs to be checked on logoSaver.submitForm function

**Comment by asimonw** [comment]
Nice work!
