### ISSUE TITLE
New tag editing flow for Insights creation 

### ISSUE THREAD

**Issue by iteles** [emfoundation/ce100-app#818]
As an EMF admin, I would like to have the same tag selection and editing workflow ( #789 ) for Insights creation so that I have the same workflow as our application's users.

@asimonw You mentioned this was a priority 3 and would be at the very bottom of sprint 6 in case we have time to get to it. Can you please confirm?

**Comment by asimonw** [comment]
@iteles Priority added and placed towards the bottom of the sprint 6 milestone.

**Comment by sohilpandya** [comment]
@asimonw this has been pushed to staging, could you please test this out. 

Thanks 👍
