### ISSUE TITLE
The Profile item in the nav shouldn't be active when the user is on someone else's profile

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#836]
When you are viewing someone else's challenge card or org profile, the Explore item should be active.

**Comment by SimonLab** [comment]
![image](https://cloud.githubusercontent.com/assets/6057298/26249168/4cc16a9c-3c9d-11e7-8acc-26d89c33cfc5.png)

**Comment by SimonLab** [comment]
@asimonw to confirm, when a user is viewing her own challenges, the profile nav item should be active?

**Comment by asimonw** [comment]
@SimonLab Good point, that could make sense, if it doesn't create too much convoluted logic in the template code? It's important that other org's challenges have state "Explore".

**Comment by SimonLab** [comment]
This should be ok to implement and I'll add the explore item active on other orgs and challenges :+1:
