### ISSUE TITLE
promisify redis

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#87]
Some of our redis queries are getting a bit long and difficult to read. We were thinking we could promisify the redis functions that we use and hopefully reduce the size and increase the readability of our queries. I also hope the db functions could be split into smaller reusable functions if we promisfy the queries.

Thought we could open a discussion here. Looking for input from @nelsonic.

**Comment by nelsonic** [comment]
"Promisifying" the query will not make it _shorter_. 
It will "_flatten_" the functions, but not do much for reducing the _size_ of queries...

**Comment by JMurphyWeb** [comment]
Mainly want to query redis multiple times, then if there was an error in one of those queries, deal with it in one place.

**Comment by JMurphyWeb** [comment]
https://github.com/emfoundation/ce100-app/blob/refactor-tests/server/handlers.js#L92

**Comment by nelsonic** [comment]
@JMurphyWeb in _this_ particular case I would prefer/suggest using `async.waterfall`  http://caolan.github.io/async/docs.html#.waterfall to "_flatten_" out the query.

**Comment by nelsonic** [comment]
Closing. if you decide to use `async.waterfall` please open another issue and detail the instances where you are simplifying the code. 👍
