### ISSUE TITLE
Org profile: long mission statement and/or many tags lead to content being cut off

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#872]
It turns out that the missions statements often end up being quite long in a production environment. This often partially or completely cuts off the tags and contact info on desktop. Mobile is fine.

The page needs to be allowed to scroll to make all content accessible.

**Comment by SimonLab** [comment]
![image](https://cloud.githubusercontent.com/assets/6057298/26579682/b5b366f8-452c-11e7-9005-d1c833def218.png)
The scroll bar is now displayed if the property "overflow-y" is defined to "visible" on the "container--desktop" class.

**Comment by asimonw** [comment]
@SimonLab I'm wondering why there is a `height: 100vh` on the `.container` class. That's what's breaking the default scroll behaviour of the page. Is there are particular reason for it? Otherwise removing that is a perfectly fine fix for now, and potentially less complicated than what you're suggesting.

**Comment by asimonw** [comment]
@SimonLab Actually, the `height: 100vh` is also breaking the walkthrough screen on certain screen sizes, see screen grab. So, unless this is doing something important that I'm missing, removing that property seems necessary.
<img width="845" alt="screen shot 2017-05-30 at 12 05 11" src="https://cloud.githubusercontent.com/assets/15235804/26580557/8a1ff8fe-4530-11e7-9d44-bd922d856c19.png">

**Comment by SimonLab** [comment]
@asimonw removing `height: 100vh` seems to indeed fix this issue. I have updated the PR.
 I think `height: 100vh` was used for the old walkthrough page (display each sections full screen). @harrygfox does this sound ok to you?

**Comment by iteles** [comment]
@SimonLab Harry's on holiday this week so we'll ask him to take a look next week.

In the meantime, please assign that issue to me instead so we can get it in for @asimonw to test this afternoon (@jbarget won't be available to review until later this afternoon).

**Comment by SimonLab** [comment]
@asimonw this is ready to test on staging. Let us know your feedback and when you want to deploy the changes on production.

**Comment by asimonw** [comment]
@SimonLab @iteles looks ok now! Thanks a lot for the quick response, really appreciate it. It can be deployed as soon as possible 👍

**Comment by SimonLab** [comment]
@asimonw the changes have now been deployed to production :+1:
