### ISSUE TITLE
Upgrade postgres in production

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#879]
We'd like to upgrade the production app to home-basic (unless a higher plan is advised). This can apparently only be done through the CLI: https://devcenter.heroku.com/articles/upgrading-heroku-postgres-databases

**Comment by iteles** [comment]
Proposed tasks for review:
+ Back up production database **(ensure this backup is working and hasn't errored)**
  + We will most likely need to take the app offline and I believe heroku has a 'holding' function to explain that the app is offline for maintenance (@naazy, I think you've used this before)
+ Read through postgres docs and link above
+ Perform upgrade
+ Ensure data is as backed up

**Comment by naazy** [comment]
You can take app offline for maintenance via Heroku settings:
<img width="975" alt="screen shot 2017-07-18 at 09 59 45" src="https://user-images.githubusercontent.com/11833296/28308998-de8c0c3a-6b9f-11e7-9cb1-29f41e0fc0bf.png">

**Comment by Cleop** [comment]
- We will do the upgrade at the end of a day as we will need to take the site offline and want to cause minimal disruption to the team.
- The new hobby-basic plan is a paid plan and we will need to ensure we have the appropriate payment details to set this up.
<img src="https://user-images.githubusercontent.com/16775804/30590534-e87e3362-9d36-11e7-8039-bdc015879996.png" width=200px />
- Having read up on the documentation, we will follow the ['pg copy'](https://devcenter.heroku.com/articles/upgrading-heroku-postgres-databases#upgrade-with-pg-copy) upgrade process.
- We will start by creating a back up of the production heroku postgres and test this by downloading it and running: `heroku pg:backups:download -a org-name` followed by `pg_restore --verbose --clean --no-acl --no-owner -d repo-name latest.dump` locally.
- Then we will turn the site onto maintenance load before following the instructions under 'pg-copy' to run the upgrade.
- Finally we take the site off maintenance mode and test everything has completed successfully.

**Comment by asimonw** [comment]
@Cleop Happy to proceed with the $9 plan!

**Comment by iteles** [comment]
Agreed with @asimonw that this would be done in the evening of Monday 2nd October.

**Comment by SimonLab** [comment]
After reading the doc and your steps Cleo I wanted to try a fake update on staging (without paying) to make sure of all the steps.
Unfortunately the Heroku guide is based on heroku-cli which doesn't work at the moment on my computer. But if I understand correctly the heroku steps they are just:
- creating a new database with the pay plan
- copy the data from the current database to the new one
- delete the old database

All this steps can also be done with ```pg_restore``` without using ```heroku-cli```.
I manage to do a copy of a database to a new one on ce100-test. I think this solution should work

**Comment by Cleop** [comment]
@asimonw - we've now made the change. Despite this being a technical issue, feel free to test the live site to make sure everything is working as usual and then close if you're happy.

**Comment by asimonw** [comment]
Thanks @Cleop ! Production app seems to be running fine.
