### ISSUE TITLE
Upgrade Node to 6.11.1

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#881]
See https://nodejs.org/en/blog/vulnerability/july-2017-security-releases/

Priority 1 to assess risk in order to set actual priority.

**Comment by SimonLab** [comment]
I just check the version with ```heroku run node -v``` it seems that we have ther version 6.11.0. I will add define the version in the package.json with
```
  "engines": {
    "node": "6.11.1"
  }
```
This should resolve this issue

**Comment by asimonw** [comment]
Thanks @SimonLab when are you planning to restart the app?

**Comment by SimonLab** [comment]
I'll take 10mn to create a PR a bit later today, once it's reviewed and merged we could deploy on production, this is quiet quick. I don't think there is any high risk for the application but let us know when is a good time for you to deploy on production (I don't want to block you if you currently doing any user testing).

**Comment by nelsonic** [comment]
@SimonLab thanks for investigating this. please assign for review when ready. 👍

**Comment by asimonw** [comment]
@SimonLab Thanks a lot! There's not that much activity on the app at the moment, as lots of people are on holiday, but if you could do it after 5pm, that would be ideal. Would that work?

**Comment by SimonLab** [comment]
@asimonw deployed with the new version on production

**Comment by asimonw** [comment]
Thanks @SimonLab !
