### ISSUE TITLE
Not possible to create a challenge with a title longer than 50 characters

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#884]
When creating or editing a challenge, entering more than 50 characters in the title field causes a server error (500). Possibly the field is not set up to accept more in Postgres?

**Comment by SimonLab** [comment]
switching the type of the column title in the challenges table from ```varchar``` to ```text``` allow user to create titles with any length.
@asimonw I've just updated the table on staging and production. This should be fix now. I've tested on staging but not on production as I don't want  to create fake data. Could you test this on your side for the production? Thanks

**Comment by asimonw** [comment]
Hi @SimonLab I still get the same error even on staging I'm afraid.

**Comment by SimonLab** [comment]
Hi @asimonw thanks for testing again. I think this is now fixed on stagging could you try again on your side? Let us know when you are happy to deploy to production, thanks

**Comment by asimonw** [comment]
@SimonLab Works now, thanks. Ready to be deployed. Preferably after 5pm.

**Comment by SimonLab** [comment]
@asimonw the production is now up to date, let us know if everything woks, thanks :+1:
