### ISSUE TITLE
New organisation profile layout

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#886]
As a CE100 user, I want to have easy access to an organisation's challenges and people, so that I can focus on networking and collaborating.

As a consequence, we're attempting to give less importance to the mission statement on desktop. The desktop layout is especially affected by the redesign, but on both mobile and desktop, the people section is changed.
Mobile: https://zpl.io/VQ0oQDx
Desktop: https://zpl.io/a7wlkBj

**Comment by fannyBkane** [comment]
Click link to see prototype https://invis.io/FHCF3VNB9#/252017917_Profile-Overview-Owner

**Comment by Cleop** [comment]
Top section
- [ ]  Move org logo to the left
- [ ]  Move org name to the left
- [ ] Move the 'vision' to sit below the org name
Challenges section
- [ ] Give heading grey background
- [ ] Create grey lines
- [ ] Reshape/position
People
- [ ] Give heading grey background
- [ ] Move section to the right
- [ ] Create space for photo (adding photos dependent on #900)

**Comment by SimonLab** [comment]
@asimonw on the current version of the application only the first primary contact of the organisation is shown. From the wireframes it seems that we want to display all the people of the organisation, primary **and** secondary, is this correct?
![image](https://user-images.githubusercontent.com/6057298/31270816-cebc3330-aa7d-11e7-9eca-66e9bee98ba5.png)

**Comment by asimonw** [comment]
@SimonLab As discussed during our standup, we would indeed like to show all people linked to the organisation now. Alphabetically on last name for now would be fine 👍

**Comment by fannyBkane** [comment]
@asimonw fine to close

**Comment by asimonw** [comment]
@Cleop Sorry for the slow reply, but I did find two issue:
+ When clicking on "See more", the link text should switch to "See less" in expanded state. Currently, it says "See more" in both collapsed and expanded state.
+ The "Archived challenges" link is there, but currently invisible on desktop (white text on white background)

**Comment by SimonLab** [comment]
@asimonw I've created a pull request to toggle the text of the button "see more" and this should be fixed on with #957 

We have spotted that the "archived challenges" link was displayed with the wrong color while working on the admin role. The pull request #956 will fix this too
