### ISSUE TITLE
Updated people list

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#887]
As a CE100 user, I want to see pictures of people on the app and be able to browse them alphabetically, so that I can more easily find people I have met at physical workshops.

The "people card" has been redesigned and now includes a profile picture and indication whether the person is a primary contact. 
It will now be possible to sort people:
* From A-Z (based on last name)
* From Z-A (based on last name)
* Latest first
Mobile: https://zpl.io/VKGpY3P
Desktop: https://zpl.io/bz8y7Jl

The "filter by name" feature on the top left in the mockup will be implemented in a future sprint.

**Comment by asimonw** [comment]
TBD: can only admins add profile pictures for now or will we allow people to upload their own. Depends on technical option for making this user friendly.
Ignore the "Filter by name" feature on the desktop design for now.

**Comment by iteles** [comment]
For now, this will not include primary/secondary contact tab.

**Comment by fannyBkane** [comment]
Click link to see prototype https://invis.io/FHCF3VNB9#/249309365_People

**Comment by Cleop** [comment]
![image](https://user-images.githubusercontent.com/16775804/30642119-7c36060a-9e01-11e7-8a34-9280390d505a.png)

**Comment by iteles** [comment]
@Cleop Let's leave the edit button in for the admin view for now, we can always adjust this once @fannyBkane has been able to respond.

**Comment by fannyBkane** [comment]
Hey @Cleop @iteles the wireframes show different elements — I realise it's a bit random. To clarify: status dots and edit buttons should show on admin views (and only on admin views).

I have emailed the call and mail buttons. As for the magnifying glass, would you be able to use the one that's already used in the nav bar?

Cheers

**Comment by asimonw** [comment]
@Cleop Just for clarity: when referring to Admin views, this is the current role which will be renamed to Content Owner. And good point: content owners should be able to see the user type of people. 

@fannyBkane maybe it's worth mocking up where the user type would be displayed for content owners given that the people card has changed?

**Comment by fannyBkane** [comment]
Updated the prototype + Zeplin (desktop and mobile)

Preview of admin desktop view here: 
![screen shot 2017-09-20 at 17 44 56](https://user-images.githubusercontent.com/20577339/30656297-86a6df86-9e2b-11e7-9088-3f5a59126298.png)

**Comment by Cleop** [comment]
@asimonw @fannyBkane - for the A-Z dropdown:
<img src="https://user-images.githubusercontent.com/16775804/30692709-9efdf54e-9ec4-11e7-8838-7e0d7d025e1e.png" width=200px />
We can build it to replicate this using javascript. For a non js alternative, would you be happy with the same drop down functionality however instead of the selected term changing between A-Z to Z-A when the dropdown is hidden (depending on which you have selected) it would only say 'Sort by' in the dropdown and it's when you click on the dropdown that you would see the A-Z options?

Do let me know if my explanation doesn't make sense too!

**Comment by fannyBkane** [comment]
Hey @Cleop that is fine by me!

**Comment by Cleop** [comment]
We've managed to implement the changing dropdown selection to work without js 😊

**Comment by SimonLab** [comment]
As the functionality is not yet implemented and the logo is not the right one for the "filter by name" feature, we are going to hide this feature.

**Comment by fannyBkane** [comment]
Hey @Cleop @SimonLab the icons seem fine in my Finder preview, as well as when I open them in Illustrator. 

On the other hand I have come across an issue once where .svg weren't displaying in Chrome because they were served by an <img> tag. On the website, other .svg icons are used using a <i> tag. Is there any chance that the html tag used could be the issue? 

Also... As .svg still don't display on some browsers, should I send you .png files?

[
![screen shot 2017-09-25 at 13 51 24](https://user-images.githubusercontent.com/20577339/30809229-ff636fb8-a1f8-11e7-8f6e-b9728ef214df.png)
](url)

**Comment by asimonw** [comment]
@fannyBkane This is ready to be tested. Could you have a look?

The only small issue I see is that some content is unnecessarily wrapped on mobile because of the `width: 23%` set on `.list__data--occupation`. I think this only needs to be there on tablet and up.
Otherwise, it looks good to me!

I also suggest that the fallback image be part of #900 where it's already being discussed.

**Comment by fannyBkane** [comment]
Looks good! And aside to issue mentioned above by @asimonw and the original chevron .svg icon not displaying correctly it is fine by me.

**Comment by asimonw** [comment]
@Cleop @SimonLab  I've created a new issue for the text filter #916 to keep that conversation separate (and for an upcoming sprint). The problem with the search icon should actually be tackled before that in #913.

**Comment by asimonw** [comment]
@fannyBkane Something else. With long emails, we'll quickly get into this situation
<img width="398" alt="screen shot 2017-09-25 at 18 02 36" src="https://user-images.githubusercontent.com/15235804/30818464-e5809abc-a21b-11e7-9d90-ccec5d263f02.png">

Maybe we could preserve less space for phone number and especially user type, thus giving a bit more space to email?

**Comment by fannyBkane** [comment]
Yes that is a good idea. Thanks for spotting this @asimonw

**Comment by asimonw** [comment]
Ok @Cleop to summarise:
+ `width: 23%` on `.list__data--occupation` causing problems on mobile
+ chevron issue could be solved by not using an `img` tag
+ could the phone number and user type be given a bit less space, and the email field more?

Thanks!!

**Comment by Cleop** [comment]
Thanks for the nice concise summary @asimonw :blush:

- I've changed the spacing for the email to make it 25% width not 20 by making the user type area smaller as this is a small field and also will only show for admin users, this is how it now looks:
![image](https://user-images.githubusercontent.com/16775804/31080377-6a013792-a780-11e7-8d41-a65e5cbf5b53.png)

- Good spot on the occupation, I've created a media query for this 👍 

- Thanks for the suggestion for the <img> tags, I've made the switch however it's not changed things. I believe that perhaps something altered the files in the upload process. When I view the files in atom it shows me a square which is what is showing on the page:
<img src="https://user-images.githubusercontent.com/16775804/31081682-8c6c885a-a784-11e7-8587-d983b8b44a51.png" width=300px />
And when I view the file in its folder I see this:
<img src="https://user-images.githubusercontent.com/16775804/31081706-a1973aae-a784-11e7-86e6-8af3c13c66d0.png" width=150px />
and this:
<img src="https://user-images.githubusercontent.com/16775804/31081728-aa655e86-a784-11e7-9a82-df9683eab3da.png" width=150px />
Whereas on the previous svg's you've shared I can see what the image is:
<img src="https://user-images.githubusercontent.com/16775804/31081741-b8f9c374-a784-11e7-87d1-0013a0fd5e45.png" width=150px />
Could it be to do with the reference to Font Awesome within the svg files? We don't currently use Font Awesome on the site and so the files may not be displaying properly. However looking at the other svgs that you've shared before there has been no reference to Font Awesome.
<img src="https://user-images.githubusercontent.com/16775804/31081944-612e8570-a785-11e7-92c8-4c20fcd24a26.png" width=200px />

The svgs are also not showing properly in the Network tab on dev tools:
<img src="https://user-images.githubusercontent.com/16775804/31082082-cb5be5f0-a785-11e7-90a3-839497024eaf.png" width=200px />

**Comment by fannyBkane** [comment]
@Cleop I have sent you a Magnifying glass icon. I converted the font to outline in my Sketch file before exporting it. Let me know if that works.

**Comment by asimonw** [comment]
@fannyBkane and @Cleop could you have future conversations about the search icon in #326 or another search related issue. Cheers.

**Comment by asimonw** [comment]
@fannyBkane This one looks good to me now. Let me know if I can close.

**Comment by fannyBkane** [comment]
@Cleop @SimonLab looks good!  Just the following bits:

- On mobile, is it possible to move the text in line with the profile picture as seen on the mockup?
![screen shot 2017-10-06 at 11 43 15](https://user-images.githubusercontent.com/20577339/31275039-87ceb6cc-aa8d-11e7-8619-8a4da9160127.png)

- the filter is meant to be centred, and I see you've used flex centre but it doesn't look centred. No biggie here, but do you have any thoughts why?

- I have sent a new .svg for the chevron, that should work (as I converted it, like the magnifying glass)

Thank you :))

**Comment by asimonw** [comment]
@fannyBkane I think it looks fine. I do think that the slightly narrower rows in the desktop prototype look stronger and are better for scrolling through long lists of people, but maybe this is good for now and we can spend some time strengthening the overall design of lists etc in a later sprint?

Looks much better on mobile now (also on org profiles) though 👍

**Comment by fannyBkane** [comment]
`I do think that the slightly narrower rows in the desktop prototype look stronger and are better for scrolling through long lists of people, but maybe this is good for now and we can spend some time strengthening the overall design of lists etc in a later sprint?

@asimonw @Cleop @SimonLab Agree. It will be also good to review the picture size, once users have uploaded their photos. So fine with me to close for now!
