### ISSUE TITLE
New admin role

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#888]
As an Admin, I want to be able to edit every piece of content that both content owners and primary users can edit, so that I can correct corrupt data in case of emergency.

Currently, the only difference with a content owner is that the new admin can also edit every organisation's challenges, which requires edit icons in the right places. This includes the ability to (un)archive challenges and view/edit archived challenges.

Acceptance criteria:
+ Creating super admin role in database
+ Permissions: Add 'edit challenges' to their permissions across _all_ organisations
+ First super admin hard coded in on db - @asimonw 
+ Other super admins are added in the same way as we create other user roles
+ Implement logging - new issue

**Comment by iteles** [comment]
Superadmin:
+ Creating super admin role in database
+ Permissions: Add 'edit challenges' to their permissions across _all_ organisations
+ First super admin hard coded in on db - @asimonw 
+ Other super admins are added in the same way as we create other user roles
+ Implement logging - new issue

**Comment by iteles** [comment]
## Decision required from EMF

Discussion to be had between @georgemillard and @asimonw on the best way to split up permissions here. Would EMF be better off with no super admin and a very tight knit group of admins for example?

**Comment by asimonw** [comment]
@iteles After a conversation with @georgemillard we've decided on the following.
1. Change the name of the current Admin role to "Content Owner" / `content-owner`
2. Create a new Admin role (rather than calling it Superadmin), which will have the superadmin permissions described above.
3. Change my personal user's permissions in production from Content Owner to Admin.

This will more closely follow our conventions on our other platforms. (And apparently, I might not be cool enough to pull off something like Superadmin...)

I suggest that we perform step 1 and steps 2/3 separately, with some tests in between.

**Comment by iteles** [comment]
@asimonw So to confirm, are we splitting this issue into 2 different issues:
A) Rename admin to 'content-owner' - possible sprint 7 issue
B) New admin role which you would have - possible sprint 8 or further down the line issue?

If so, I would recommend we:
+ Rename this issue to reflect B above
+ Add the bullets I wrote in https://github.com/emfoundation/ce100-app/issues/888#issuecomment-330192018 as acceptance criteria to the top comment
+ Open a new issue for A

**Comment by asimonw** [comment]
New issue #902 created to handle the renaming of the current admin role first.

**Comment by iteles** [comment]
+ New permission to be added:
  + See archived challenges
  + Unarchive challenges
  + Edit challenges

+ Review permissions documentation #378

**Comment by asimonw** [comment]
@Cleop Good point! Creating challenges is not essential for admins, so if hiding the button is the quickest solution, go for that. Thanks!
