### ISSUE TITLE
API: endpoint tag_id => group

### ISSUE THREAD

**Issue by SimonLab** [emfoundation/ce100-app#891]
For selecting tags for a challenge or an organisation, we are creating manually a mapping between each tag id and their group:
https://github.com/emfoundation/ce100-app/blob/49594598c36807f882d44b17fc17836aa6fa3077/server/handlers/challenges/add-view.js#L30-L35
![image](https://user-images.githubusercontent.com/6057298/30443061-3451847a-9976-11e7-98fd-256b23c1716d.png)

We can definitely recreate this mapping from the api with ```/api/tags``` and /api/tag-groups``` but I was just wondering how difficult is it for you to create a new endpoint which will return this kind of mapping. This is not needed right now but it could help us for our estimations. I will also specify in more detail the exact format.

**Comment by asimonw** [comment]
@georgemillard We could consider returning both the id and the parent id (in this case tag group) for nested objects?

**Comment by georgemillard** [comment]
@asimonw @SimonLab the /api/tags endpoint already returns both tag id and group id, so it is possible to get the group by calling /api/tag-groups/<group_id>

Would it be helpful to additionally return group name from /api/tags? 

Perhaps we can keep this in mind when we come to create some CE100 app specific endpoints in the future.

**Comment by SimonLab** [comment]
I think it makes sense for us to create the necessary structure object (containing the group and the different tags and locations) on the application side instead of creating a very specific API endpoint only use by the application
