### ISSUE TITLE
Review Location tags in tag selection screen

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#892]
The DAM API will have a lot more location tags than currently being used (and necessary) in the app.
Two options:
* We allow many more tags to be used in the app and redesign the UI for location tags
* We find a way to only expose a sub-set of the country tags in the API

TBD...

**Comment by asimonw** [comment]
@georgemillard Let's discuss this as well.

**Comment by georgemillard** [comment]
Meeting booked in with @asimonw, @fannyBkane and @LucyJW to discuss how we want to use location tags in the app - update to follow

**Comment by SimonLab** [comment]
@asimonw I think the conclusion of this issue, is to keep the locations tag and use the "display_name" property to enhance the UI by displaying shorter name for the locations, is this right @asimonw ?

**Comment by asimonw** [comment]
@SimonLab Thanks, I had lost track of this issue. This was not related to the display name. The conclusion of this conversation was that: 
+ when creating/editing an organisation or challenge (maybe using a dropdown?) we'd like to display all the country options (1)
+ in the Explore section we'd like to use the current UI but only show the locations which are actually being used n the app. Would that be possible?

(1) We would still need to figure out how to handle the UI for selection from a long list of locations in the first case above. The problem is that it should be possible to select multiple locations and a native multi-select field is not very user friendly. Any suggestions?

I'll add this issue to sprint 11. Thanks for reminding of this.

**Comment by asimonw** [comment]
@SimonLab Should this one already be in please test? I don't see any changes to the location tags.

**Comment by SimonLab** [comment]
@asimonw you are right, this issue is not ready to be tested, I forget to remove the "please-test" label after your previous comment

**Comment by georgemillard** [comment]
@asimonw @SimonLab 
Check out how locations are added to assets in the Django Admin. A list sorted by continent, with a searchable box at the top provides a nice UI solution.

**Comment by asimonw** [comment]
@georgemillard That's true, but not exactly a quick win.

**Comment by asimonw** [comment]
@SimonLab We've decided that we want to separate out the location selection from the tag selection. See the mockups below for an indication how. The rest of the tags would work as before, but when creating or editing an org or challenge, there would be a separate input element to select locations. Because the list of locations is very long, we'll need another UI mechanism for doing it.

The grey box which says "Add a location" is a placeholder for whatever solution we implement. We suggest the following as a first iteration:
+ A native input of type `select` with attribute `multiple`. I know that this might not consistently display as a scrollable list box on all devices, but let's try and see what happens
+ We should set the `size` property, but it's not clear until we try what size would be best. Let's start with 5 and @fannyBkane can help us decide on a final size once we see what it looks like on different devices
+ We'll need some small text saying something like "To select multiple location press and hold the ctrl key"

![screen shot 2017-11-24 at 11 02 19](https://user-images.githubusercontent.com/15235804/33208739-0ba44196-d113-11e7-8326-ccef75ae31e5.png)
![screen shot 2017-11-24 at 11 02 45](https://user-images.githubusercontent.com/15235804/33208748-143958b4-d113-11e7-9c39-f3aa11ebe64e.png)

How does that sound? Note that this does not apply to the Explore section. In that section, we'll simply limit the location tags to the ones which are actually being used for existing orgs, challenges and insights.

**Comment by SimonLab** [comment]
@asimonw ready to be tested on ce100-test
![image](https://user-images.githubusercontent.com/6057298/33475146-3da7af9a-d675-11e7-9fb4-db7a54f2c52c.png)

**Comment by asimonw** [comment]
@SimonLab Works! If you could just make a few tweaks to the UI, I think it's shippable as a first iteration:
+ Add a title "Tags" above the EDIT TAGS button (and above the already selected tags if there are any)
+ Reduce the margin between the EDIT TAGS button and the already selected tags (again, if there are any)
+ Add title "Locations" above the location selector and instruction text.
+ Also change the instruction text to "Hold the cmd (on Mac) or the ctrl (on Windows) key to select multiple locations."

That should group things a bit more clearly. Thanks!

**Comment by SimonLab** [comment]
@asimonw ready to be tested on ce100-test heroku app

**Comment by asimonw** [comment]
Thanks for the tweaks!
