### ISSUE TITLE
Comments on challenges

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#893]
As a CE100 member, I want to be able to post a public reaction on a challenge shared by another member so that I have an opportunity to share insights or start a conversation with the person who shared the challenge and also the other users who come across it.

Admins and content owners will also be able to comment. 

Comments should show for inactive users, still showing their name and org (if the org is inactive, this shouldn't be a link) and a message "No longer active". See #992 
When a user is deleted (future functionality), all his comments should be deleted as well.

**Comment by iteles** [comment]
This issue deals with the **creation** of comments.

+ New table to database - save timestamp, author, text and challenge ID
+ UI for creating comment (buttons can display in first iteration - to be estimated)
+ Reverse chronological order showing on challenge page
+ Number of comments need to show
+ UI for comments themselves (including author, org, timestamp and text)
+ Admins and content-owners should display 'Ellen MacArthur Foundation' as their organisation

Let's add separate issue on character limitations and UI for next iteration

**Comment by asimonw** [comment]
@SimonLab @iteles I've added a line in the top comment about comments of inactive/deleted users.

**Comment by Cleop** [comment]
For this element of the design there are [accessibility constraints for using a placeholder instead of a label](https://www.nngroup.com/articles/form-design-placeholders/) for a form element:
<img src="https://user-images.githubusercontent.com/16775804/31659682-e03bdeaa-b32c-11e7-8821-afb9ae0c244d.png" width=500px />
The 2 most relevant for the context of the form we're using are:
- Not all screen readers will recognise placeholder text, this means it wont be read aloud, causing blind and visually impaired users to miss the content.
- Users with cognitive or motor impairments are more heavily burdened (to memorise what the placeholder text said)

A potential solution for screen readers might be to create a label that the screen reader reads but is not visible to other users. This wouldn't be a solution for users affected by the second bullet point though...

**Comment by fannyBkane** [comment]
@Cleop Thanks for raising that. 

I noticed that this pattern is used by services like Disqus and YouTube (screenshots below). 

I presume they use the label you refer to for screen readers. As for users with cognitive or motor impairments, I wonder if that is partly the function of the header that says 'Comments' above, to help recognition of what should go in the text field?

Is it fair to say that, based on this, keeping the UI as it is, and implementing a label as per your suggestion could work?

![screen shot 2017-10-17 at 17 38 03](https://user-images.githubusercontent.com/20577339/31677250-1174b34a-b362-11e7-83de-03361bd98884.png)
![screen shot 2017-10-17 at 17 38 41](https://user-images.githubusercontent.com/20577339/31677251-118a0e16-b362-11e7-9383-34ef104d5098.png)

**Comment by asimonw** [comment]
Copying @fannyBkane 's comment from #946 below:

Looking good :)) 

@cleop @SimonLab 

Would it be ok to bring the line closer to the label here (see mockup)?
On this one, looks like the padding is smaller than on most buttons. Could you confirm that it is a button style that's already used somewhere else? 
![screen shot 2017-10-23 at 13 41 28](https://user-images.githubusercontent.com/20577339/31894295-edaf81ee-b805-11e7-8d5c-99956be381e7.png)

Can you confirm Edit and Delete use the same font-size?
On this one, is is possible to increase the padding top and bottom in this element as well?
![screen shot 2017-10-23 at 13 43 19](https://user-images.githubusercontent.com/20577339/31894368-2933b37a-b806-11e7-901e-89470c7703bb.png)

**Comment by asimonw** [comment]
@Cleop @iteles After a chat with @fannyBkane we decided that we do think that it's worth improving the UX by implementing some JS solutions, if the time estimates are reasonable.

This would involve:
* Expanding the comment box using JavaScript as the user is typing. This would allow the textarea field to be only one line high at the start
* We would like to keep the cancel button in the comment creation scenario, but to make the action clearer, we would:
    + Hide the Cancel and Comment buttons when the comment field is empty.
    + Show both buttons once the user starts typing
    + Hide both buttons and empty the comment field when the user clicks either button (the Comment button would in addition also create a comment of course)

**Comment by iteles** [comment]
@asimonw Thanks for this.
Can we please add those as two separate issues so we can go ahead and ask questions/add estimates without getting lost in the other comments here?

**Comment by asimonw** [comment]
@iteles issues #977 and #978 created to track these separately.

**Comment by iteles** [comment]
In this case, the only piece of this issue left is fixing the size (font-family) of the 'Edit' menu button as mentioned by Fanny in https://github.com/emfoundation/ce100-app/issues/893#issuecomment-338723508

**Comment by asimonw** [comment]
@SimonLab I just remembered that this question came up during our planning meeting: are you also handling inactive users (and orgs) as described in the last paragraph of the top comment?

**Comment by iteles** [comment]
Ah, we're very much not. Can we add this as a separate requirement please @asimonw as this one is getting quite long and I'm keen for it to not be lost?

**Comment by asimonw** [comment]
Makes sense @iteles. I've created #992 for it.

**Comment by asimonw** [comment]
@fannyBkane Does this look good to you? This issue is only about the items outlined in https://github.com/emfoundation/ce100-app/issues/893#issuecomment-335422993.

I think maybe the comments could be a bit closer together, but that's a minor point.

**Comment by fannyBkane** [comment]
@asimonw it looks good, thanks @Cleop
