### ISSUE TITLE
Google events

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#896]
Set up Google analytics events for key user actions.
+ [x] Clicks on Log out button
+ [x] Clicks on contact email address (from org profile and people page)
+ [x] Clicks on contact phone number (from org profile and people page)
+ [x] Clicks on Add challenge (button) (from org profile)
+ [x] all three buttons on the landing page
+ [x] Clicks on Cancel button when choosing tags (for orgs mission statement & challenges) 
+ [x] Clicks on all items in the top nav (Explore, + challenge, People, and the dots)
+ [x] Clicks on contact us (from three dots expanded menu)

**Data layer**
+ [x] Clicks on individual insights (record name of insight) from insight page
+ [x] Clicks on individual resources (record name of resource) from resources page

+ Clicks on intercom? Can we do this?

**Comment by iteles** [comment]
Our initial understanding is that we can't work with intercom as our tags can't catch the events. We'll look into it further.

**Comment by asimonw** [comment]
@iteles Based on your previous experience, do you have any recommendations on how to organise events into categories and actions, and how to use labels/values?

**Comment by iteles** [comment]
@danwhy I'll leave this one to your expertise! Any suggestions on the above from Alex? 
Might be one to review with @cleop when we get to this issue in the backlog 👍

**Comment by iteles** [comment]
Moving to sprint 9 for the data layer portion of this.

**Comment by Cleop** [comment]
Unfortunately it won't be possible for us to measure clicks on intercom.

When it comes to how we name the triggers and tags in GTM we follow Google's recommended structure of: 'GA - Event - PageOfEvent - WhatIsClicked' for tags and 'PageOfEvent - WhatIsClicked' for triggers.

We use labels for events involving the data layer where the label indicates what variable the data layer is presenting for the given event e.g. {{DLV - Insight Name}}. For the events done so far we've not used values as a value has to be a numeric value and this has not been relevant for what we've been measuring thus far.

**Comment by Cleop** [comment]
This issue is now ready to test, to test:

- Go to the staging site and perform the behaviours listed above that will trigger events
- Go to Google Analytics and using the options on the lefthand side go to REAL-TIME followed by Events. You should see something similar to this:
<img width="1235" alt="screen shot 2017-10-26 at 14 23 49" src="https://user-images.githubusercontent.com/16775804/32055338-6e460d46-ba59-11e7-87b5-2d7743b6bbf7.png">

Now when you click on something that should trigger an event you should be able to see the event listed as occurring on the analytics screen.

**Comment by asimonw** [comment]
@Cleop I've started testing this and it looks good! A question: did you somehow set it up to track events on staging while other analytics is still tracking the production app? Do you set that up in the tag manager? Thanks!

**Comment by Cleop** [comment]
@asimonw - this has not yet been deployed to production, sorry I forget to mention that in my testing advice above! So yes, currently production will be gathering the preexisting analytics but you can test this using staging. Staging has the tag manager scripts in whereas production doesn't. Hope that clarifies things!

**Comment by asimonw** [comment]
@Cleop Thanks, no need to help any further on this. The event data seems to be coming in fine from staging. Will check again once it's deployed, but I see no reason why it wouldn't work for production events as well.
