### ISSUE TITLE
Reporting/Auditing tools part 1: data dump

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#897]
We will trial https://redash.io for this. See details below.

**Comment by iteles** [comment]
Agreed in mid-sprint planning: We will take 2 hours to implement [Redash](https://redash.io/) and construct a simple query to pull all of the information out of the Insights table.

This will allow @asimonw @georgemillard to take a look at Redash already hooked up to the EMF postgres database and determine whether this is a more versatile temporary solution than a CSV download (in the long term we will be looking to implement dashboards #671) .

**Comment by iteles** [comment]
For future sprints/scope: 
+ Report containing user's first nam, last name, their organisation and last logged in time (dependency on #1005)
+ Report containing all challenges and their _matches_
  + This will need additional reporting logic as the matches themselves are calculated rather than being stored in the database

**Comment by Cleop** [comment]
To test, @asimonw @georgemillard should have received invites to the Redash account via email (let me know if you've not received these). Once logged in go to queries:
![image](https://user-images.githubusercontent.com/16775804/32288450-e38fbc06-bf2b-11e7-9a41-7da024fdc78b.png)
From here select the query I have made for the insights table: 
![image](https://user-images.githubusercontent.com/16775804/32288480-f95ce23e-bf2b-11e7-8a73-07e57f9cc504.png)
You should here be able to see the query and to 'rerun' the query to get the latest data or to download the data as a .csv or excel file should you wish. 
![image](https://user-images.githubusercontent.com/16775804/32288555-310a809c-bf2c-11e7-8059-43a66246f181.png)

**Comment by Cleop** [comment]
I won't put the `please-test` labels on until I've added a little into the README on how to create a new query...

**Comment by SimonLab** [comment]
@asimonw @georgemillard At the moment Redash is connected to the staging database so there is no danger to break the datbase. However you can create sql queries via Redash so you can also insert and delete data so you need to be careful of the actions executed via Redash. We will investigate if there is a "read only" option in the config of Redash

**Comment by Cleop** [comment]
@SimonLab - there is a read-only but I don't think you can write new queries with it, you can only rerun existing ones.

**Comment by SimonLab** [comment]
@asimonw the Readme is now completed with the Redash instructions: https://github.com/emfoundation/ce100-app#redash-the-data-management-dashboard

**Comment by asimonw** [comment]
@Cleop I've played around with redash a bit (created new query, viz and a dashboard). It's clear enough for now, thanks!
