### ISSUE TITLE
Add terms and conditions

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#899]
As a primary/secondary user, I want to be able to opt in to the Terms and Conditions, so that I know under what terms I can use the app and how my personal data will be treated and protected.

This only applies to primary and secondary users, but to existing users as well as new ones. This is why the are several flows which will now contain a "consent step".

- [x] Existing users will see the consent form after logging in. They will not actually be authorised to see any other views/endpoints until they've agreed to the T&Cs (see image 1 below for flow)
- [x] New users will first be sent to the consent form (from the activation email). After the consent step, they will see the password creation screen. Only after performing both of these steps, will they have access to other views/endpoints (see image 1 below for flow)
- [x] Question for dwyl: can the flow for new users also more or less be used for existing users who want to reset their password (and haven't consented yet)?
- [x] The consent form itself is comprised of two steps, one for agreeing to T&Cs, one for opting in to further marketing (see image 2 below). The first consent is required to be able to access the app, the second one is not.
- [x] From the first consent form, there will be links to a T&Cs and a privacy policy screen (these links should always open in a new tab). Those two links will also be accessible from the "three dots" menu (in top nav on desktop, bottom nav on mobile)
- [x] There will also be a new checkbox in the user settings to alter the marketing consent. For the time being it won't be possible to change consent to the privacy and terms (to be reviewed if necessary for GDPR)
- [x] Extra: T&C consent checkbox visible only to admins / content owners for testing purposes (allowing us to toggle consent given by test user)

Image 1:
<img width="398" alt="screen shot 2018-01-23 at 15 21 00" src="https://user-images.githubusercontent.com/15235804/35281280-d0420510-0052-11e8-828e-b102a0162dfa.png">

Image 2:
**Notes**: 
+ Disregard the "display error message." If the user presses "Cancel" on the first consent screen, they will be sent to the login screen
+ The second form is not a pop-up, but a new screen
<img width="426" alt="screen shot 2018-01-23 at 15 22 07" src="https://user-images.githubusercontent.com/15235804/35281310-e3fabe26-0052-11e8-805f-930846bc1ec4.png">

**Mockups:**
[Consent Mobile](https://invis.io/HCFIVL1BZT8)
[Consent Desktop](https://invis.io/5AFHR9ANVP4) 

**HTML:**
- Privacy and terms (Consent form) 
- Terms and conditions
- Privacy Policy
- Marketing

**Comment by iteles** [comment]
TBC whether this can be an opt in checkbox or whether we need to put the full Ts & Cs in front of users. We may not have all the information we need by this sprint.

**Comment by asimonw** [comment]
@fannyBkane This is ready for mockups to be added at the end of the top comment. 
@iteles The new top comment should help with estimates. Let me know if there are any questions or concerns.

**Comment by Cleop** [comment]
### Notes to self:
- [ ] Set up the 4 pages and routes to them
- [ ] Style the 4 pages (mob too)
- [ ] Connect routes to the pages
- [ ] Connect routes from the pages
- [ ] Permissions work

**Comment by Cleop** [comment]
Testing guidance for @asimonw once PR #1265 is merged in....

Once this PR has been merged you will be able to test the ability of a primary or secondary user who is already signed up to Cello. Try logging in and then you will be given a consent page followed by a marketing page, with links available to the privacy and full terms and conditions pages.

The flow is not yet complete for new users activating their accounts. Admins can log in as usual but cannot yet toggle whether someone has consented or not. User do not yet have the ability to change their marketing preference after the initial flow. Users are blocked from accessing pages

**Comment by Cleop** [comment]
@asimonw - I've just been talking more with @SimonLab about the new user sign up flow. We feel that it will be quick to implement the sign up flow in the order: activation email -> password -> consent but will take longer to do email -> consent -> password. This is due to the process for setting up a user and the values we need to use which are used in the activation email. Given that users may already be familiar with sign up flows like the this one:
![image](https://user-images.githubusercontent.com/16775804/35915059-6b7a3f7e-0bfd-11e8-961e-93528b0b1279.png)

Where you enter your password and then agree with the Ts and Cs, would you be happy for us to do this flow with password before consent?

**Comment by asimonw** [comment]
@Cleop I suspected that that would be the case. We thought that our suggestion would be slightly preferable from a UX point of view, but given that we don't expect many people to create a password and then choose not to agree with the Ts&Cs, I think what you suggest is fine.

Would the flow then be the same for password resets as well? First reset screen, then consent (if not already given).

**Comment by Cleop** [comment]
Yes the that's what we were thinking for the password reset flow for users who are yet to consent. Thanks for getting back to us 👍

**Comment by asimonw** [comment]
@Cleop On the `/consent` page, could the link at the end of the "Your Rights" section open in a new tab please?

**Comment by Cleop** [comment]
This issue is now complete and awaiting review #1273, once it has been merged in it will be ready for testing by @georgemillard and @fannyBkane. 

The only thing that can be changed on Friday is that as we discussed with @asimonw - currently admins *and* content owners can edit a user's consent but on gitter (as we've not had time to implement the env variable staging only solution) @asimonw requested that these permissions only apply to admins. As we won't be deploying to production before Friday there is no risk imposed in the meantime.

**Comment by asimonw** [comment]
@Cleop Sounds good. That won't be a problem for now, so we'll start testing, thanks.

**Comment by asimonw** [comment]
@Cleop It's all working really well! A few tiny copy changes on the `/marketing` page:
- First bullet point:
  - Second dash should be a long dash, like the first one
  - Should end in a full stop, not a semicolon
- Second bullet point:
  - Remove the "and" after the first semicolon 
  - Full stop after "be interested in" should be a semicolon

And then on the people edit page, could you add some padding underneath each light switch, so that the different elements are grouped a bit more clearly?
<img width="668" alt="screen shot 2018-02-09 at 12 32 30" src="https://user-images.githubusercontent.com/15235804/36026002-842f6db6-0d95-11e8-9700-3693df9cb5da.png">
@fannyBkane can provide some padding values if you'd like some help.

Apart from those small changes, I'll leave this issue open until you've made the "Privacy and terms" switch accessible to admins only as well.

**Comment by Cleop** [comment]
@asimonw @fannyBkane - how's this for padding?
![image](https://user-images.githubusercontent.com/16775804/36026566-a631b410-0d8f-11e8-8304-450eec97c827.png)

**Comment by fannyBkane** [comment]
@Cleop works a treat! Could you check that the padding between 'User type' and the radio buttons underneath is consistent with the padding between The headers and toggles above?

**Comment by fannyBkane** [comment]
@cleop Looks good! A couple of things:
- On the article pages: The vertical spacing could be tweaked a bit to improve reading experience. Could the space after paragraphs and next heading be increased slightly?
- The toggle: could the padding around the text be increased ever so slightly to match the hi fi mockup?
![screen shot 2018-02-09 at 16 37 10](https://user-images.githubusercontent.com/20577339/36038419-90dc1b0a-0db7-11e8-8384-6d5a07b518fd.png)
![screen shot 2018-02-09 at 16 37 26](https://user-images.githubusercontent.com/20577339/36038420-90f3370e-0db7-11e8-8e47-b5216304b5dc.png)

**Comment by asimonw** [comment]
@fannyBkane I assume that you mean on the `/terms` and '/privacy' pages? And do you mean just the space between paragraphs and headings?

**Comment by asimonw** [comment]
@Cleop If still possible, it would be great to still get those tweaks in.

**Comment by Cleop** [comment]
@asimonw - on the case now - just hoping that my interpretation of the padding ones is going to be right!

**Comment by fannyBkane** [comment]
Hey @cleop I saw they were rems, is that correct? In that case could you try to make them 2x what they are now?

**Comment by Cleop** [comment]
How's this for the switch? @fannyBkane 

<img src="https://user-images.githubusercontent.com/16775804/36043313-d6093f00-0dc6-11e8-8485-2599a46e874f.png" width=80px />

**Comment by fannyBkane** [comment]
@Cleop it's great!

**Comment by asimonw** [comment]
@Cleop @SimonLab Looking good!
