### ISSUE TITLE
Member profile management by admin

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#9]
As an EMF admin, I can browse and edit existing profile pages, so that I can make essential changes without having to go through the primary user.

**Comment by asimonw** [comment]
This is especially for org name, logo and linked primary user. Things which can't be managed (except for logo?) by the primary user.

**Comment by iteles** [comment]
@asimonw This can be fully tested apart from the addition of the logo, which is functionality still in review

**Comment by asimonw** [comment]
@iteles When will logos be available? Until then, this issue can't be closed.

**Comment by asimonw** [comment]
Also, the spacing of input boxes is managed by setting a large line height, but this has an unfortunate effect on text areas:

<img width="340" alt="screen shot 2016-11-09 at 16 39 19" src="https://cloud.githubusercontent.com/assets/15235804/20146347/6f712908-a69b-11e6-9004-c7e8ae8e2441.png">

**Comment by JMurphyWeb** [comment]
Need to fix styling 

Logo is covered in #55

**Comment by JMurphyWeb** [comment]
Need to fix styling 

Logo is covered in #55

**Comment by JMurphyWeb** [comment]
Need to fix styling 

Logo is covered in #55

**Comment by JMurphyWeb** [comment]
To fix the styling on the text area i added a new modifier to the form__input element:

```css
     .form__input--text-area {
        line-height: 1.5;
        height: 8rem
      }
```

**Comment by JMurphyWeb** [comment]
Which translates to this in "ipad view":
![screen shot 2016-12-19 at 14 05 21](https://cloud.githubusercontent.com/assets/12638261/21315485/4f2be106-c5f4-11e6-96a4-8d97e02b86ff.png)


![screen shot 2016-12-19 at 14 05 04](https://cloud.githubusercontent.com/assets/12638261/21315465/394e6584-c5f4-11e6-94a4-8ab058975309.png)

and this in mobile view:
