### ISSUE TITLE
Add tests for Redis

### ISSUE THREAD

**Issue by mk4111** [emfoundation/ce100-app#90]
Need to write tests that will test our catches when redis throws an error

**Comment by JMurphyWeb** [comment]
@nelsonic yesterday we spoke about abstracting some redis functions that we do regularly out. For example getting a user adding some info and re setting that user into redis. Can be applied to Challenge cards as well as orgs as well. Extracting it isn't much of a problem,

**Comment by JMurphyWeb** [comment]
This should be fixed now. Hoek.assert solved a lot of our problems.
