### ISSUE TITLE
Profile picture upload

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#900]
As a CE100 user, I want to be able to upload a profile picture, so that people who have met me at events can more easily recognise me and interactions on the platform are more personal.

**Comment by Cleop** [comment]
**Research findings into this have helped create the folllowin:**
- [ ] Replicate
Currently the ability to upload images for organisations is done using [aws-sdk](https://www.npmjs.com/package/aws-sdk)
- [ ] Check for file size - size tbc
- [ ] Check for file type - types tbc

**Comment by iteles** [comment]
@fannyBkane to provide a default image for a profile picture when one has not been uploaded by the user yet.

**Comment by fannyBkane** [comment]
Sent to gmail address.
[
![people-fallback](https://user-images.githubusercontent.com/20577339/30595143-456111c4-9d48-11e7-9bba-a2d423b615c9.png)
](url)

**Comment by SimonLab** [comment]
- [ ] add ```logo_url``` field on the people table - see https://github.com/postgres-plugin/people/blob/6117e9832457b701455c9cdfea1a3861a0be6249/lib/fixtures/create-tables.sql#L11
- [ ] run migration to update the people database on staging and production

**Comment by SimonLab** [comment]
@asimonw a first version of the image upload is now ready to be tested on staging

**Comment by iteles** [comment]
@SimonLab Can we please also update the readme with this new functionality and technical changes made as well?

**Comment by fannyBkane** [comment]
@Cleop @SimonLab spotted a couple of things:

In my settings, a message saying 'no file chosen' appeared after I uploaded a picture ![screen shot 2017-10-06 at 12 33 27 2](https://user-images.githubusercontent.com/20577339/31276236-b0f35d1e-aa92-11e7-9a96-40191e73a1cd.png)

On the People list, the picture shows as a square, whereas I would expect it to be within a circle mask ![screen shot 2017-10-06 at 12 33 48](https://user-images.githubusercontent.com/20577339/31276264-e32a63fe-aa92-11e7-8ca8-359a629c0465.png)

**Comment by SimonLab** [comment]
@fannyBkane thanks for spotting this. Concerning the  'no file chosen' I haven't manage to reproduce the error. I thought it was because the name of the file was a bit long but I'v just tested on my side and it looks fine. Could you try on Safari to see if it's your chrome version the origin of the issue?
@asimonw could you also try on your side to check if you have the same error, thanks :+1:

**Comment by asimonw** [comment]
@SimonLab @fannyBkane I also cannot reproduce this on Chrome.

**Comment by fannyBkane** [comment]
Hey @SimonLab I tried again this morning. I uploaded a picture in my settings. No problem until then. The picture appear in the people list. When I go back to my settings, this is what shows:
![screen shot 2017-10-09 at 09 26 28](https://user-images.githubusercontent.com/20577339/31329933-2d277a4e-acd4-11e7-91f0-4f8c2262f73e.png)

**Comment by fannyBkane** [comment]
And this shows on Safari 'no file selected'
![screen shot 2017-10-09 at 09 29 46](https://user-images.githubusercontent.com/20577339/31329989-75a32822-acd4-11e7-9edd-3c06b722b682.png)

**Comment by SimonLab** [comment]
On the edit page, we don't display the file name previously selected ( this is the same logic for an organisation picture). We could display the url of the current image somewhere on the page but it will be a "cryptic" url format from amazon s3 (for example: https://ce100-logos.s3-eu-west-1.amazonaws.com/catd37268ebd92af9cf.jpg).
Otherwise we could also display the current image itself on the page
@asimonw @fannyBkane let me know your thougths

**Comment by fannyBkane** [comment]
@SimonLab it would be great to display something, otherwise one may think there is a bug and their image had disappeared. My preferred option would be to display the current image because it requires no extra click - and therefore less effort!

**Comment by asimonw** [comment]
@SimonLab As discussed, if we add a message saying "The image cannot exceed 250kB", we can close this issue and handle future iterations elsewhere.

**Comment by SimonLab** [comment]
Warning message:
![image](https://user-images.githubusercontent.com/6057298/31427532-87c802d4-ae5f-11e7-9188-d58e18d1a949.png)

**Comment by asimonw** [comment]
@SimonLab Thanks, this will do for this feature for now 👍
