### ISSUE TITLE
Update Hapi to version 16.6.0

### ISSUE THREAD

**Issue by SimonLab** [emfoundation/ce100-app#901]
![image](https://user-images.githubusercontent.com/6057298/30551017-1254e11e-9c91-11e7-8a87-997b0cebc622.png)

As a developer I want to update the version of all the packages used in the application as I want to be sure that the application is secure

I've added a 2h time estimation, I think updating Hapi should take less time but I want to be sure that it won't break anything

**Comment by SimonLab** [comment]
@asimonw the new version of Hapi has been updated now and deployed on staging. I've done some test and haven't spotted any bugs or errors but if you could test on your side that would be great too, thanks

**Comment by asimonw** [comment]
After testing a few other things, I think this is very likely ok.
