### ISSUE TITLE
New "View Only" internal role

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#903]
As a "view only" user, I can see everything a secondary user can see, but without being attached to an organisation, so that as a member of the EMF team I can learn about the network through the content that is created.

The only extra bit of content that should be visible is the matches on challenge cards for all organisations. Secondary users can only see the matches for their own organisation.

**Comment by iteles** [comment]
Time estimate for adding this role with our _current_ permissions system. To be revised if we move forward with #935

**Comment by SimonLab** [comment]
@asimonw do we want the view only role to be able to add comments to the challenges?

**Comment by asimonw** [comment]
@SimonLab No, would it be possible to show them the existing comments, but not the comment box, or any options?

**Comment by SimonLab** [comment]
Yes I think it's possible to create a condition in the template to only display the menu options for the non view-only user: https://github.com/emfoundation/ce100-app/blob/d39908212d40566590ea89417559c85975d4f828/templates/partials/comments/comment.html#L42-L52

and are they allow to flag a comment?

**Comment by iteles** [comment]
@asimonw I understand we wouldn't want this role to edit or delete comments, but would we not want them to have the same privileges as normal member users other than that? Is there a use case for keeping EMF 'view only' role people from being able to comment altogether (i.e. by removing the comment box?

**Comment by asimonw** [comment]
@iteles The use case I was thinking of (happened recently) is for auditors / EMF advisory panel.
But you're right that for other people it would even be useful.

So if it's actually a bit of a hassle, I'm happy for the view only role to be able to create comments. We'll just have to tell auditors to resist the urge ;)
