### ISSUE TITLE
Create links to organisation pages from People page

### ISSUE THREAD

**Issue by Cleop** [emfoundation/ce100-app#906]
Relates #887 
The new UI for the people page features a link to the organisation a person belongs to next to their job title:
<img src="https://user-images.githubusercontent.com/16775804/30704398-8a8ab270-9eea-11e7-91d9-f38749d32c84.png" width=250px />
In order to access this information and to link to the appropriate page we need to amend the db data that is loaded for this page by the plugin.
The proposed name for linking to the org page (and the needed url structure) is:
![image](https://user-images.githubusercontent.com/16775804/30704450-ad61b258-9eea-11e7-9a1b-55b631dcad9c.png)
In order for this to work and actually go somewhere we now need to add this info in the plugin.

**Comment by SimonLab** [comment]
The org_id is now returned. Based on https://www.npmjs.com/package/pg-people

**Comment by SimonLab** [comment]
The organisations are now clickable from the list of users:
![image](https://user-images.githubusercontent.com/6057298/30799951-6384d02c-a1d6-11e7-8b4f-b4523927b232.png)
