### ISSUE TITLE
Postgres search substring on orgs

### ISSUE THREAD

**Issue by SimonLab** [emfoundation/ce100-app#910]
ref: #326 (Free text search)
and https://github.com/emfoundation/ce100-app/issues/326#issuecomment-330276849 (use Postgres queries to search for substrings)
ref pg-people plugin issue: https://github.com/postgres-plugin/people/issues/67

This issue will focus on building a query to search organisation for a specific substring.
- [x] Create query to search on title
- [x] Use the ```lower``` function from postgres to allow searches to be case insensitive
- [x] Generalise the query to search on other fields of the organisation - Name, vision, expertise (tags)
  - [x]  search by name
  - [x] search by tags
  - [x] search by vision

Most of the work is to build the queries in the [pg-people](https://github.com/postgres-plugin/people/tree/master/lib/queries/orgs) plugin which contains the organisation table.

Once this issue is finish we can reproduce similar queries for the other elements we want to search on (People, Challenges, Insight)

**Comment by SimonLab** [comment]
Searching organisations by tags:
- 1. Search for tags where the name contains the search term
- 2. Join the tags list returned with the organistions on the tags_id field

A note concerning the API:
The API will contains all the tags. We could either filter the tags on our backend or the API can implement a function to let us search tags by name

**Comment by SimonLab** [comment]
Once the following PR (https://github.com/postgres-plugin/people/pull/70) has been reviewed and merged, I think the search on organisation is completed and can be integrated to the application by just calling the function 

```request.server.methods.pg.organisations.orgsSearch(term.toLowerCase(),function (pgErr, listOfOrgs) {...}```

in the search handler

**Comment by asimonw** [comment]
@SimonLab Should we just test search results for orgs for this? That seems to be fine to be.

**Comment by asimonw** [comment]
@SimonLab This is not specific to orgs, but two bugs related to the search query itself came in:
+ If the search string is an empty string, the result includes all items in the database. Could we instead show no results at all? On top of that, I would implement a line of JavaScript to prevent people from submitting when the search field is empty.
+ Query strings involving single quotes such as `'`, `'a'`, `that's great` or `'''` result in a 500 error. (Two single quotes with no characters between them seems to be fine). Maybe the string can be sanitised or single quotes escaped?

**Comment by SimonLab** [comment]
@asimonw an empty search will no return 0 result and I escape the search term when containing quotes.
We might need some indication on how to let people know that the search term is empty, a specific message on the result page for example?
