### ISSUE TITLE
Review how we use locations within the CE100 App

### ISSUE THREAD

**Issue by georgemillard** [emfoundation/ce100-app#911]
We have had a discussion about how location tags are used in the CE100 App. We would like to use the country tag list on the Asset Manager to populate the locations list in the App. However, this is a very long list (250 countries).

We have come up with the following suggestions:

For Adding locations:
When creating or editing an Organisation, Challenge or Insight, users will be able to add locations, separately to tags, from a drop down list. This list will be populated from the country list maintained on the Asset Manager. It would be nice if this list was searchable

For browsing by location:
Location tags will continue to be used in the same way for browsing, but only those that are in use within the App (ie, those that have been used to tag an Organisation, Challenge or Insight) will be shown in the Locations tag group. This will keep the list manageable and relevant.

It would be great to get your guys' thoughts @iteles @SimonLab @Cleop

**Comment by Cleop** [comment]
Can an org add multiple locations for those that are international? Or would there be something like an 'international' option?

**Comment by asimonw** [comment]
This was solved with #892
