### ISSUE TITLE
Search Results UI

### ISSUE THREAD

**Issue by Cleop** [emfoundation/ce100-app#912]
Relates to #326 

Create the UI for the new search functionality for desktop and mobile, in this issue building the search results page.

**Desktop search results**
<img src="https://user-images.githubusercontent.com/16775804/30747642-c799af84-9fa5-11e7-8351-0288c10ffcc2.png" width=600px />

**Mobile search results**
<img src="https://user-images.githubusercontent.com/16775804/30748499-67c66c48-9fa8-11e7-8ca5-fd1ba309fb0b.png" width=200px />
<img src="https://user-images.githubusercontent.com/16775804/30748537-839356ca-9fa8-11e7-9670-5acdf32b93d4.png" width=200px />

- [x] Draw in the search bar from the previous page
- [x] Display 'We've found X results for 'Search Term''
- [x] Add section titles on grey background:
  - [x] People
  - [x] Organisations
  - [x] Challenges
  - [x] Insights
- [x] Display section 'cards' in the same way they are displayed on the individual pages:
  - [x] People
  - [x] Organisations
  - [x] Challenges
  - [x] Insights
- [x] Display 'no results found' for categories with no results.
- [x] Show highlighted search icon in navbar when on results page

*** Tags section not included in new designs despite screenshots above ***

Questions:
- @fannyBkane - Should a 'no results found' message appear on a white card or on the greyish background like the category titles?

**Comment by fannyBkane** [comment]
@Cleop on a grey background. In default body text style.

**Comment by georgemillard** [comment]
Search is looking good. Just a thought on the UI... As we are searching against different fields for different search results (People, Org, Challenges, Insights) and returning these four very different results with their own format, would it be useful to highlight the search term where it appears on each result to show where the match happened? 

Eg. If I search "EMF" it would highlight EMF in the People's role, and in the Org name.

**Comment by georgemillard** [comment]
A good example of a use case for this: if I search for 'e n' I get matches on the Organisations 'Coca Cola' and Fanta, but I'm not sure how they match?

**Comment by asimonw** [comment]
@georgemillard That's a nice idea, but it was agreed that this would not be part of the first iteration. I'll keep it in the log for upcoming features.

**Comment by fannyBkane** [comment]
@Cleop @SimonLab looking good :)

**Comment by asimonw** [comment]
Tiny thing I noticed @fannyBkane. The org icon isn't aligned with the org name. What do you think, worth fixing in this sprint?

**Comment by fannyBkane** [comment]
@asimonw if possible, yes!

**Comment by asimonw** [comment]
@Cleop Would it be possible to still get that org logo alignment in place before end of sprint?

**Comment by Cleop** [comment]
As discussed on stand up - are you now happy to close this one @asimonw as the bug seems to have gone?
