### ISSUE TITLE
Search Modal UI

### ISSUE THREAD

**Issue by Cleop** [emfoundation/ce100-app#913]
Relates to #326 

Create the UI for the new search functionality for desktop and mobile including adding the search to the navbar, the search bar modal.

**Desktop navbar** - note only adding the search symbol, not making other navbar design changes
<img src="https://user-images.githubusercontent.com/16775804/30747632-bd67b272-9fa5-11e7-9a3d-f93c5ab36c58.png" width=300px />
**Desktop search bar**
<img src="https://user-images.githubusercontent.com/16775804/30747618-b624cdec-9fa5-11e7-9312-fbad3d50a539.png" width=500px />

**Mobile navbar**
<img src="https://user-images.githubusercontent.com/16775804/30748408-220619e2-9fa8-11e7-8184-dd71389e60b8.png" width=200px />

**Mobile search bar**
<img src="https://user-images.githubusercontent.com/16775804/30748445-3b9d3ebc-9fa8-11e7-8b6f-3473ff262dbf.png" width=200px />

- [x] Add magnifying glass icon to navbar (awaiting asset from @fannyBkane - see https://github.com/emfoundation/ce100-app/issues/887#issuecomment-331425965)
- [x] Underline or highlight search icon in the navbar when on this page - exact UI to be determined in question below.

- [x] Give page dark blue background to cover the screen
- [x] Create underlined input box with white text 'Search...' 
- [x] Create light blue 'Go' button
- [x] Add magnifying glass next to search bar

**Mobile**
- [x] magnifying glass does not display
- [x] mobile navbar
- [x] mobile search bar size
- [x] mobile navbar highlight color

**Questions:**
- @fannyBkane - On desktop when you are on the search page there is no distinction according to invision on the navbar that you are on the search page. Would you like the same convention as the other navbar items on desktop where the search icon will be underlined in light blue to show you are on this page? On mobile the design is that the background of the icon changes colour when it is selected... or is this what you want on desktop too? Or would it be better for them to all be the underline to keep consistent?

**Comment by fannyBkane** [comment]
@Cleop Can you keep the same interaction for the magnifying glass than for the ellipsis on desktop
 (that is a darker background)? That way it will also be consistent with the mobile state.
Thank you!

**Comment by fannyBkane** [comment]
@Cleop @SimonLab Looking great. Is it possible to build in a hover state on the Go button (10% darker)?

**Comment by iteles** [comment]
@fannyBkane @Cleop How are we currently communicating about hover states and similar interactive features?

**Comment by fannyBkane** [comment]
@iteles @Cleop if not in the mockup I will bring it up in the issue.

**Comment by asimonw** [comment]
@iteles @fannyBkane we could maybe work on a style guide at some point? For example, the 10% darker on hover rule for buttons has been applied throughout the app until now, as far as I can tell, but it would be good to capture it as a default rule somewhere. And create explicit issues for style guide changes. Could that be an idea?

**Comment by fannyBkane** [comment]
@asimonw good shout. I did upload style guides to Zeplin see an example here https://zpl.io/aB108Mm 

Would be good to know what are your thoughts @Cleop @SimonLab

**Comment by asimonw** [comment]
@fannyBkane My bad, forgot about that one 👍

**Comment by asimonw** [comment]
@Cleop Would it be possible to still add that 10% darker hover on the "Go" button so that we can close this one?

**Comment by Cleop** [comment]
When I follow that link @fannyBkane to the style guide I get a message saying I'm not invited to it. Would you be able to add me? I'm able to see the 'CE100 Sprint 7 mobile' work but I'm assuming because of the message that the style guide is a separate file.

**Comment by asimonw** [comment]
Thanks for adding that hover @Cleop !
@fannyBkane leaving this open for a bit so you don't miss @Cleop 's request above. But good to close for me.

**Comment by fannyBkane** [comment]
@Cleop hover state is ace. I've invited you to the right workspace in Zeplin so you should be able to view the style guides now. Thank you!

**Comment by fannyBkane** [comment]
LGTM :)
