### ISSUE TITLE
Match challenges with insights

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#919]
As a primary user, I get a list of insights matching my challenge, so that I can see what is available for me to expand my knowledge, which in turn could help tackle the challenge.

**Comment by iteles** [comment]
+ Logic for matching challenges with insights
+ Styling for matched challenges (desktop & mobile)
+ Making sure back button still working correctly

@fannyBkane to confirm final icons

**Comment by asimonw** [comment]
@iteles Here the same limit as for orgs and challenges.

**Comment by SimonLab** [comment]
@asimonw do we want to match insights that are also a resource?

**Comment by asimonw** [comment]
@SimonLab If an insight has a tag, it can be matched. No need to check whether it's a resource or not.

**Comment by asimonw** [comment]
@SimonLab: some testing feedback which came back:

+ Created Insight with the tag Anaerobic Digestion, and a Challenge with the same tag. No matches found. 
+ Then edited Challenge by adding another Tag, bioenergy. Now the original Insight matches as well as loads of others. 
+ Remove bioenergy and no longer matches

**Comment by asimonw** [comment]
@SimonLab In my comment https://github.com/emfoundation/ce100-app/issues/919#issuecomment-336404945 I suggested that you ignore whether an insight is a resource or not. I now notice that insights which are also resources won't show up in matches.

I don't think that this will be an issue in practice as there probably won't be any resources with tags, but wouldn't it be simpler to remove the check whether something has the "Show in resources" flag or not?

**Comment by SimonLab** [comment]
@asimonw I'll make sure that resources are matched too
