### ISSUE TITLE
Search people

### ISSUE THREAD

**Issue by SimonLab** [emfoundation/ce100-app#926]
"Searches all fields in people profiles - name, title, organisation name" see https://github.com/emfoundation/ce100-app/issues/326#issuecomment-330195105

Creating the query for searching on name and title is similar to the query we've created to search organisation and can be easily created.

The query for returning all people belonging to an organisation where the name of the organisation matches the search term is a bit more complex:
- 1 search all the organisation ids that match the search term on the title
- 2 Join the ids just found with the table people_organisations to get the list of the people ids
- 3 Join the people ids found in step 2 with the people table to get all the necessary people information
- 4 remove duplicates people found with the first query (search on name and title) by using the UNION sql operator

**Comment by asimonw** [comment]
LGTM!
