### ISSUE TITLE
Search challenges

### ISSUE THREAD

**Issue by SimonLab** [emfoundation/ce100-app#928]
Search through challenge title, description and tags

Searching on title and description can be don easily on the fields directly and by using the ```LIKE``` function of Postgres

Searching on tags linked to the challenges require a query a bit more complex as we need to join the challenges with the list of tags

**Comment by asimonw** [comment]
LGTM!

**Comment by asimonw** [comment]
@SimonLab This mostly looks good, but as we mentioned during the standup, archived challenges also appear!

**Comment by SimonLab** [comment]
@asimonw this should be resolved now, could you please test again and let us know if everything is ok, thanks

**Comment by asimonw** [comment]
@SimonLab LGTM now!
