### ISSUE TITLE
set up handlebars watch

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#93]
Time consuming to restart server each time when editing handlebars.

@nelsonic do you know of good a solution to this?

**Comment by nelsonic** [comment]
@JMurphyWeb _yes_ there is, as a matter of fact: https://github.com/dwyl/hapi-riot
but... let's not dive into that _before_ the demo...

**Comment by JMurphyWeb** [comment]
Parked for now.
