### ISSUE TITLE
Trim search term

### ISSUE THREAD

**Issue by SimonLab** [emfoundation/ce100-app#937]
As a user I want the application to trim the unnecessary white space added by mistake on my search term as I want to get results for the search I expected do run

**Comment by georgemillard** [comment]
@SimonLab White space needs trimming from between words to.

Eg. 
"Sally Robbins" matches
"Sally         Robbins" does not

**Comment by asimonw** [comment]
@SimonLab @georgemillard This wasn't discussed, so I'd say if this is fairly quick to incorporate, great, otherwise, let's also keep it as a separate issue. Sorry George, managing sprint scope here ;)
