### ISSUE TITLE
Respond privately to challenge - iteration 1 (by email)

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#944]
As a CE100 member, I want to send a private message about a challenge to the person who shared it so that I have an opportunity to strike up a one to one conversation

As a first step, this will simply be a button which opens the default email client with pre-filled email address  and title. 

A Google event should track button clicks.

**Comment by asimonw** [comment]
To be confirmed: title and further content of the email:

**Title: Regarding your CE100 challenge: [Challenge title]**
@LucyJW Could you have a look at what the title should be and whether it would be useful to add some pre-filled email body text as well?

**Comment by iteles** [comment]
'Send private message' button to show in the left hand column, near the '3 comments' section.

Only worth doing if we have a click event attached to it.

**Comment by iteles** [comment]
Some debate was had around whether the option to message privately should be included at this stage or whether EMF would prefer to nudge members towards publicly commenting.

@asimonw @georgemillard to confirm final decision on whether we want to implement this feature.

**Comment by asimonw** [comment]
@iteles We've decided to postpone this to a future sprint.
