### ISSUE TITLE
Edit or delete comments on challenges

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#945]
As a CE100 member, I want to be able to edit or delete my comment so that I can make sure it is still relevant even after I have posted it.

An admin will also be able to edit or delete any comment.

The delete action should invoke a confirmation message before taking place. For this sprint, this can be achieved a by using the browser's `window.confirm` function.

To be discussed: what kind of edit UX is achievable: modal, inline? Having a full page reload for it would not be ideal.

**Comment by iteles** [comment]
Only `admin` and the person who created the comment are able to edit or delete a comment.

Desktop UI:
<img width="1280" alt="screen shot 2017-10-10 at 11 05 03" src="https://user-images.githubusercontent.com/4185328/31380974-f5d54850-adaa-11e7-8a5e-76c5722757d0.png">

Mobile UI TBC - @SimonLab and @Cleop to confirm estimates of various options tomorrow (push content down or open modal that takes up the whole window?).

+ In-line JS editing, with a non-JS fallback to be estimated.
+ Both saving & cancelling have to be edited
+ Keep original timestamp on display (save edited time in DB `edited_at`), when a comment is updated and shows '(edited)' next to timestamp (watch UI here for people with long organisation or people names!)

**Comment by SimonLab** [comment]
@asimonw is the delete action remove completely the comment from the database or do you want to keep the comment but with a status "inactive" for example?

**Comment by asimonw** [comment]
@SimonLab Sounds like a good idea to keep them in the db, but capture it with an active/inactive status like we've been doing with other entries.

**Comment by Cleop** [comment]
@fannyBkane - another design consistency question. This screenshot is not great as invision highlights the elements as soon as you try to screenshot... but the it's the button to create a comment once you've entered some text in the input field:
<img src="https://user-images.githubusercontent.com/16775804/31662804-c7183030-b337-11e7-9521-9ff3f09b33df.png" width=200px />

Are you happy for this to be an entirely new button style? **It is identical to the tags hover colour/shape.** This is the tags before hover:
<img src="https://user-images.githubusercontent.com/16775804/31662892-0e330684-b338-11e7-9887-6a4fe83724b0.png" width=100px />

These are our other button styles that are generally more rounded:
<img src="https://user-images.githubusercontent.com/16775804/31662961-624de04a-b338-11e7-88d0-ca1efa4f7be4.png" width=150px />
<img src="https://user-images.githubusercontent.com/16775804/31662912-26f35a66-b338-11e7-9414-237385226a05.png" width=150px />
<img src="https://user-images.githubusercontent.com/16775804/31662984-6e50b0b6-b338-11e7-955b-13c80badb853.png" width=100px />
<img src="https://user-images.githubusercontent.com/16775804/31663011-909f7d82-b338-11e7-8b7b-3dc33c04bdb9.png" width=40px />
The only one which has the same border radius has a white background so it looks quite different from the tags:
<img src="https://user-images.githubusercontent.com/16775804/31662923-35506d24-b338-11e7-8577-cfa372a80b21.png" width=150px />

I was going to look at the style guide from Sprint 5 on zeplin but the project has now been archived.

If you'd like me to proceed with this one that's totally fine, I just thought I should check before going ahead 👍

**Comment by Cleop** [comment]
@fannyBkane - when a user is editing a challenge did you envisage this pushing all of the other comments down? The example you show with the save button takes up more space than the normal comments however, in invision you do not show what it looks like with an existing comment beneath it so I wanted to ask you to clarify...
![image](https://user-images.githubusercontent.com/16775804/31676393-63cb0d86-b35f-11e7-8212-1b7fe0e764b6.png)

**Comment by fannyBkane** [comment]
@Cleop thanks for pointing that out!

About the button - could you please keep the rounded button style, one hollow with a solid border (cancel) and one with a dark blue fill (save)?

**Comment by iteles** [comment]
Test comment

**Comment by fannyBkane** [comment]
Hi @Cleop Could you please a rounded button style like on this preview: 
![screen shot 2017-10-19 at 19 02 22](https://user-images.githubusercontent.com/20577339/31786345-16f7955e-b500-11e7-9a32-279499673c45.png)

**Comment by fannyBkane** [comment]
> when a user is editing a challenge did you envisage this pushing all of the other comments down? The example you show with the save button takes up more space than the normal comments however, in invision you do not show what it looks like with an existing comment beneath it so I wanted to ask you to clarify...

Hey @Cleop this is probably an oversight :( Can we have the 'Save' button taking up the same space than the 'Comment' button, but have it grey instead of the dark blue? Also, could the line below the text currently being edited be a darker grey. See below preview and link here: https://projects.invisionapp.com/d/#/console/11390797/256876380/preview 

![screen shot 2017-10-19 at 19 07 33](https://user-images.githubusercontent.com/20577339/31786547-d4fe121c-b500-11e7-990d-414cb1cb1444.png)

**Comment by asimonw** [comment]
@Cleop @SimonLab  Looks pretty good!

A few things:
+ When editing a comment, it's possible to delete all the text in the comment box and then press Save. This currently results in a 500. Some possibly solutions: 
    * Return a more friendly error message. Maybe as part of the ajax solution?
    * Don't allow the user to press save? (might be confusing)
    * Saving an empty comment (on delete) has the same effect as deleting the comment. Or would that also be confusing?
+ A more cosmetic issue: while editing a comment, the drop-down menu (Edit, Delete) is still visible. Maybe we could hide when the user has selected an option?

@fannyBkane Any preferred scenario for the first problem?

**Comment by asimonw** [comment]
A related issue is that a sole newline character does get saved (on edit), and looks like an empty comment. It would be great if whatever the solution above would also treat anything which is equivalent to pure whitespace the same way as an empty comment, i.e. it shouldn't be possibly to create that comment.

**Comment by fannyBkane** [comment]
@asimonw In Slack, saving an empty comment has the same effect as deleting the comment. In Facebook, a message is shown — see preview 
![screen shot 2017-10-30 at 09 59 10](https://user-images.githubusercontent.com/20577339/32164993-1b0fdafa-bd59-11e7-8ca4-726ffe8d9117.png)

Either of the solutions above work, now happy to go with the most simple to build?

**Comment by asimonw** [comment]
@SimonLab and @Cleop See my comment https://github.com/emfoundation/ce100-app/issues/945#issuecomment-340028676 and the one below that. Would it be possible to make editing+saving an empty comment equivalent to deleting the comment? This means that also here a confirmation pop-up should be shown to make sure the user isn't deleting the comment by accident.

**Comment by iteles** [comment]
@asimonw Would it be possible to add that as a separate issue in Sprint 9 so that we can estimate it and you can be clear about prioritisation? (I imagine quite high)

**Comment by asimonw** [comment]
I can do that @iteles.

Could you still handle this smaller matter in this issue:
> A more cosmetic issue: while editing a comment, the drop-down menu (Edit, Delete) is still visible. > Maybe we could hide when the user has selected an option?

Basically, clicking on the menu should just hide the menu.

**Comment by asimonw** [comment]
The issue when saving an empty comment will now be handled in #1006.

**Comment by asimonw** [comment]
@SimonLab It looks like the remaining issue from https://github.com/emfoundation/ce100-app/issues/945#issuecomment-340447519 is solved now. I assume that the label wasn't updated to `please-test`?

**Comment by SimonLab** [comment]
@asimonw yes you're right, sorry we forget to update the label on this issue

**Comment by asimonw** [comment]
In that case, that's a wrap!
