### ISSUE TITLE
New challenge view layout

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#946]
This redesign is required to accommodate the new commenting feature and will at the same time aim to strengthen the UI.

It also incorporates some changes to the archive challenge view.

## Acceptance Criteria
+ [x] New banner with photo (hard coded image)
+ [x] Back button styling (+ chevron on mobile)
+ [x] Edit button changes
+ [x] 2 column layout
+ [x] Full screen layout
+ [x] Comments not included in this issue
+ [x] Layout and fonts of tags and matches sections
+ [x] Add links to edit tags
+ [x] Change layout for matched organisations
<img width="272" alt="screen shot 2017-10-10 at 15 44 49" src="https://user-images.githubusercontent.com/4185328/31392831-27df204c-add2-11e7-96ea-a4eb9d5c3ef6.png">

**Comment by iteles** [comment]
+ New banner with photo
+ Back button styling (+ chevron on mobile)
+ Edit button changes
+ 2 column layout
+ Full screen layout
+ Comments not included in this issue
+ Layout and fonts of tags and matches sections

**Comment by iteles** [comment]
@fannyBkane Across the rest of the application we have just a pencil icon (without the word `Edit`). Do we need to have this new Edit button across the rest of the app?

Additionally, in the organisation view, the UI looks a little different for the titles (see 'People' below, different font and background) as well as the content being in a box: 
<img width="405" alt="screen shot 2017-10-10 at 15 32 02" src="https://user-images.githubusercontent.com/4185328/31392069-36a9471c-add0-11e7-8f41-6abd1f113f99.png">

How much consistency do we want to achieve here?

**Comment by iteles** [comment]
@asimonw For the 'Add tags here' link on the challenge page, we want to be clear that this will go to the 'Edit challenge' screen (as @fannyBkane has linked in invision) rather than specifically to the 'Edit tags' section (because that was chosen to be a modal, it doesn't have its own endpoint to link to).

**Comment by asimonw** [comment]
@iteles Yes "Add tags here" can link to the edit challenge page. I'll leave the UI questions for @fannyBkane but I'd definitely vote for consistency where it makes sense.

**Comment by fannyBkane** [comment]
> For the 'Add tags here' link on the challenge page, we want to be clear that this will go to the 'Edit challenge' screen (as @fannyBkane has linked in invision) rather than specifically to the 'Edit tags' section (because that was chosen to be a modal, it doesn't have its own endpoint to link to).

Agree with @asimonw "Add tags here" can link to the edit challenge page. However, on the form the button says 'Edit tags'.

It seems minor but it requires a little extra effort to understand where you should click. Would it be possible to change the button text to 'Add tags' when there aren't any tags selected? This way users will recognise the words 'Add tags' and less effort will be required. See mockup below.

![screen shot 2017-10-11 at 14 28 09](https://user-images.githubusercontent.com/20577339/31443151-8750e2ae-ae90-11e7-87e2-8ebf0d3ea41e.png)

**Comment by SimonLab** [comment]
@fannyBkane if possible could you send the background pictures for the active and archived challenges? Thanks

**Comment by Cleop** [comment]
@fannyBkane - do you have a zeplin mobile mock up for this you could share?

**Comment by fannyBkane** [comment]
@Cleop I haven't put one yet. On that note however, I wanted to ask you: Have you used the inspector mode on Invision? Let me know if that could be better than Zeplin.

**Comment by Cleop** [comment]
When I've used invision on another project I could switch between modes on a central bottom menu and do things like get assets - I'm not sure if this is what you mean by inspector mode? However on this project I don't have this menu available, I assumed it might be a permissions thing.

**Comment by fannyBkane** [comment]
It looks like this: ![screen shot 2017-10-13 at 10 38 25](https://user-images.githubusercontent.com/20577339/31540134-b090d5de-b002-11e7-866a-2a73ea985713.png)

**Comment by Cleop** [comment]
Yes, that's what I've used before...but I can't see that on my screen on this project:
![image](https://user-images.githubusercontent.com/16775804/31540374-63e0fdb2-b003-11e7-9d90-dd0d0ac150d4.png)

**Comment by fannyBkane** [comment]
Hey @Cleop are you logged in to Invision?

**Comment by Cleop** [comment]
Sorted, thanks @fannyBkane

**Comment by Cleop** [comment]
@fannyBkane @asimonw 
Would you like any text for the time being when a category ie. organisation/challenge/insight doesn't match, like this:
<img src="https://user-images.githubusercontent.com/16775804/31550953-ecb97836-b02a-11e7-9216-c15f55e56c4d.png" width=250px />

Or would you prefer it cleaner by just showing what matches there are?

There will be a message saying if there are no matches across all categories.

**Comment by fannyBkane** [comment]
> @fannyBkane if possible could you send the background pictures for the active and archived challenges? Thanks

@SimonLab I have sent it by email (not sure why but it doesn't appear in the inspect folder in invision...). I've used a seamless vector pattern, meaning I can provide you with a .jpg or a .svg file of any size to accommodate larger screens.

**Comment by fannyBkane** [comment]
@Cleop Let's do the 'cleaner' option :)

**Comment by fannyBkane** [comment]
@Cleop Following @iteles mention of a dissonance between the visual designs of the org profile and the challenge page, I reviewed them and this is the outcome, as far as the challenge page is concerned:

- masthead height changes to 264px to bring it inline with the profile's
- the main column and the side bar are now in their respective div with a white background fill

Here is a preview: 
![screen shot 2017-10-13 at 17 29 59](https://user-images.githubusercontent.com/20577339/31556284-3622be86-b03c-11e7-91b8-944f48f02dfa.png)

And a link to one updated page on Invision (I will update all the page states asap) https://projects.invisionapp.com/d/main#/console/11390797/256875074/preview

**Comment by Cleop** [comment]
@fannyBkane - would you like the mobile masthead to be the same height as on the org page. If this is the case and the title is short it looks a little empty:
<img src="https://user-images.githubusercontent.com/16775804/31606094-105ef5e0-b260-11e7-88da-a755bb6bfe90.png" width=200px />
But if it's longer it's fine:
<img src="https://user-images.githubusercontent.com/16775804/31606149-39617f76-b260-11e7-8488-fca14e464853.png" width=200px />
So would you like it to be flexible to the text size or kept at a min height the same as the org banner?

**Comment by fannyBkane** [comment]
Hi @Cleop Titles may be shorter or even longer than on the preview sceenshots. For that reason I think keeping flexibility makes sense!

**Comment by fannyBkane** [comment]
Looking good :)) 

@cleop @SimonLab 

Would it be ok to bring the line closer to the label here (see mockup)?
On this one, looks like the padding is smaller than on most buttons. Could you confirm that it is a button style that's already used somewhere else? 
![screen shot 2017-10-23 at 13 41 28](https://user-images.githubusercontent.com/20577339/31894295-edaf81ee-b805-11e7-8d5c-99956be381e7.png)

Can you confirm Edit and Delete use the same font-size?
On this one, is is possible to increase the padding top and bottom in this element as well?
![screen shot 2017-10-23 at 13 43 19](https://user-images.githubusercontent.com/20577339/31894368-2933b37a-b806-11e7-901e-89470c7703bb.png)

**Comment by asimonw** [comment]
@fannyBkane It looks like your feedback is related to comments, which hasn't been labeled ready for testing yet. Is there anything related to the rest of the challenge layout? If not, I'd like to close this issue and copy your feedback to #893

**Comment by fannyBkane** [comment]
@asimonw my bad 

Fine by me to close. Thanks!
