### ISSUE TITLE
Add links to comments on challenges

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#948]
As a CE100 member, I want to be able to add links in my comments so that I can contribute with insights hosted on the platform or on another website

**Comment by iteles** [comment]
Rather than starting from a point of adding in rich text editors (like TinyMCE) or markdown (which carries a non-technical user UX issues), we propose that a starting point is to process the text input for a comment and detect anything starting with `http` or `www` and automatically convert it into a clickable link.

This would be a 2 hour task to start off with.

**Comment by asimonw** [comment]
@iteles That sounds like the most lightweight option, which would be perfect for now. I assume that this would be done on the backend? But then, something similar might have to happen in the front-end to enable the same functionality on edit (if this will be implemented without a page refresh).

**Comment by Cleop** [comment]
@fannyBkane How should these links be styled? I imagine we want it to be recognisable that they're links but I wasn't sure if you wanted a different colour to the defaults for links?
![image](https://user-images.githubusercontent.com/16775804/32109361-6d842766-bb2c-11e7-9bdd-573b4d5bea80.png)

**Comment by fannyBkane** [comment]
Hey @Cleop please keep the links the same colour as the default. Thank you!

**Comment by iteles** [comment]
@asimonw Following on from our QA process, we'd like be doing a little more work here to remove the possibility of script injection. Do we have the go-ahead to spend an additional hour or two on this tomorrow to do this as a priority prior to deployment?

**Comment by asimonw** [comment]
@iteles Absolutely! Important to do so 👍

**Comment by asimonw** [comment]
Nice!
