### ISSUE TITLE
Refactor fix-tests branch with Nelsons comments

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#95]
- [x] [inline requires -> reduces lines of code and number of vars being set.](https://github.com/emfoundation/ce100-app/pull/64#discussion_r77640484)
- [x] [npm uninstall hashids](https://github.com/emfoundation/ce100-app/pull/64#discussion_r77637979) 
- [x] [npm uninstall codecov](https://github.com/emfoundation/ce100-app/pull/64#discussion_r77638568)
- [x] [worth adding the travis badge and david-dm badges too](https://github.com/emfoundation/ce100-app/pull/64#discussion_r77637306)  see https://github.com/dwyl/repo-badges
- [x] [Remove server/start.js](https://github.com/emfoundation/ce100-app/pull/64#discussion_r77637306)
- [x] [Remove all consts](https://github.com/emfoundation/ce100-app/pull/64#discussion_r77641302)

**Comment by nelsonic** [comment]
@JMurphyWeb `hashids` is "OK", just need to be _clear_ on how we are using it. 👍

**Comment by JMurphyWeb** [comment]
We aren't using it anymore so no problem.
