### ISSUE TITLE
Organisation profile | Visual design update

### ISSUE THREAD

**Issue by fannyBkane** [emfoundation/ce100-app#964]
This update is required to address the dissonance between this and the challenge page visual design

- [x] no margin between masthead and the two boxes below
- [x] remove grey background and underlines for 'Challenges' and 'People' header
- [x] change font size and weight of 'Challenges' and 'People' header
- [x] adjust padding in side bar

Preview ![screen shot 2017-10-13 at 17 36 05](https://user-images.githubusercontent.com/20577339/31556698-f478ffe8-b03d-11e7-9689-4723182aca3b.png)

Link to mockup https://projects.invisionapp.com/d/main#/console/11390797/249328433/preview

**Comment by Cleop** [comment]
@fannyBkane - on mobile would you still like the 'People' section to have a grey background? I've given the people cards more padding like on desktop and I've kept the heavier font weight on the title.

<img src="https://user-images.githubusercontent.com/16775804/31995496-7faaff2a-b97c-11e7-8e87-123799a41b83.png" width=300px />

With a white background it would look like this (ignore the black edge of the screenshot, that's just from dev tools) :
<img src="https://user-images.githubusercontent.com/16775804/31995529-a77e301c-b97c-11e7-8f32-8f8c939b5f9d.png" width=300px />

**Comment by fannyBkane** [comment]
@Cleop second version with white fill works better, thanks :))

**Comment by asimonw** [comment]
@fannyBkane WDYT?

**Comment by fannyBkane** [comment]
Looks good to me!
