### ISSUE TITLE
In the people list or search results, the org of a person is not linked

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#966]
When a job title is provided, the org is a link, but when no job title is provided, the org is just displayed as plain text. Could the org always we a link to the org profile, please.

**Comment by Cleop** [comment]
Thanks @asimonw, I'll fix this when I'm on a new branch, I've found where it is.

Note to self: found this in user partial line 28, needs link from line 23.

**Comment by asimonw** [comment]
@Cleop Thanks for that! Would be perfect if this could sneak into the sprint (if it's a quick fix) 😉

**Comment by asimonw** [comment]
LGTM
