### ISSUE TITLE
Archiving an organisation does not affect linked primary user

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#97]
Awaiting for a response from @asimonw to find out what we should do with a linked user when archiving an organisation

**Comment by asimonw** [comment]
@JMurphyWeb see my response in #47. Disable all linked users (there will just be one for the MVP, of course) as well.

**Comment by JMurphyWeb** [comment]
>  In general, it's rather 'disable' than archive. For instance, we imagine this option to be useful when an org is initially being set up, but we don't want it in the org list yet. A bit like a draft version.
> 
> But if there are users linked to it, the only logical thing to do is to also disable all the linked primary contacts. In this case, it's better to see it as 'archiving' before we eventually delete the org and its primary users.
