### ISSUE TITLE
Dynamically showing and hiding buttons on comment creation

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#978]
We would like to keep the cancel button in the comment creation scenario, but to make the action clearer, we would:
* Hide the Cancel and Comment buttons when the comment field is empty.
* Show both buttons once the user starts typing
* Hide both buttons and empty the comment field when the user clicks either button (the Comment button would in addition also create a comment of course)

**Comment by iteles** [comment]
@asimonw On this point:
> Show both buttons once the user starts typing

We had discussed having these buttons appear with the user clicks into the input field. Are we changing the requirement or is this just a case of wording? 😊

**Comment by asimonw** [comment]
@iteles If that's what was agreed before, that's fine!

**Comment by iteles** [comment]
@asimonw As I was walking through our list of agreed sprint 9 scope, I came to the 'disallow empty comments' issue.

Ensuring that the buttons only appear on typing as you suggested rather than when the field is clicked into would remove the need to do additional work to disable buttons until typing has occurred so in review, your original requirement will be the best one to go for 👌

**Comment by asimonw** [comment]
@iteles Very good point! Excellent suggestion 👍 👍

**Comment by iteles** [comment]
All credit to @SimonLab and @Cleop !

**Comment by asimonw** [comment]
@SimonLab Broadly works!

Two small issues:
* If you start typing and then press the cancel button, the buttons don't disappear to return to the initial state (as if I hadn't started typing a comment)
* The Save and Cancel buttons are shown in a flash when the page loads. Maybe this is because they're only hidden once the JavaScript is parsed? I think this could be improved by initially hiding both buttons with CSS.

**Comment by SimonLab** [comment]
- I'll make sure to hide the buttons when the cancel button is clicked :+1: 
- It's true that the buttons are displayed first before being hidden with javascript which might cause sometimes the flash. I've implemented this way to let users without javascript being able to still see the buttons and create comments. We could hide the buttons by default but this will block people not using js creating comments. @asimonw I let you decide which implementation you would like.

**Comment by asimonw** [comment]
@SimonLab That's a good point. But I do think that the flash is quite visible and therefore ruins the experience of the buttons only appearing when the user starts typing. Commenting is a very dynamic feature and I don't think that there are many modern commenting apps/plugins out there that work without JavaScript (happy to see examples though). So I think it's ok to hide the buttons with CSS by default.
