### ISSUE TITLE
Cancelling comments in edit mode takes you back to read-only comment

### ISSUE THREAD

**Issue by iteles** [emfoundation/ce100-app#980]
As a CE100 member, when I am editing my comment in a challenge
I would like the cancel button to both remove any edits I have already started making (but not saved) and exit me from edit mode
So that I can change my mind about editing and quickly get back to the original comment.

This also applies for admin users.

## Acceptance Criteria
+ [x] When a user presses cancel on a comment of theirs that they are editing, they are taken out of edit mode and back to the original comment (unedited) in read-only view
+ [x] When an admin presses cancel on any comment they are editing, they are taken out of edit mode and back to the original comment (unedited) in read-only view

**Comment by SimonLab** [comment]
Having just a a tag with a link to the page itself (```<a href="/challenges/{{challenge_id}}#original-comment-{{id}}">Cancel</a>```) doesn't force reload the page as the browsers know that the  page is the same. Another solution would be to create a specific "cancel" endpoint which where the handler will redirect to the page, however this feels like a lot of code just to get a cancel button working without javascript. @asimonw do you have any thoughts on this, I will focus on the js version but let us know if you still want a specific handler for a version without js?
ref: https://stackoverflow.com/questions/8174282/link-to-reload-current-page

**Comment by asimonw** [comment]
@SimonLab You're right, as it's the same page, I can't think of any way to force a reload without JavaScript. In that case, it's fine to continue without a non-js fallback. Thanks for checking though!
