### ISSUE TITLE
Upgrade node version to v6.11.4

### ISSUE THREAD

**Issue by iteles** [emfoundation/ce100-app#982]
Update Node to the latest stable release, includes DOS security vulnerability patch

![node version](https://files.gitter.im/dwyl/emf/GkYh/image.png)

**Comment by SimonLab** [comment]
The new  version has been updated with: https://github.com/emfoundation/ce100-app/blob/266f3406934221ee3f0d60a57b255a5edea78ea4/package.json#L69
