### ISSUE TITLE
Adding AJAX to improve UX

### ISSUE THREAD

**Issue by iteles** [emfoundation/ce100-app#983]
As a user
I would like to no longer see page reloads when crating or editing a comment
So that my experience is less jarring.

@SimonLab Could you please note the situations in which this will manifest from a user perspective and the breakdown of the steps required from a technical perspective?

**Comment by SimonLab** [comment]
## Add new comment:
- prevent submit form with javascript
- Attach event listener on "comment" button which will get the payload of the comment (id challenge, text of the comment)
- get cookie with javscript which will be passed to the sever to authenticate the user
- send request with payload and cookie

**Comment by SimonLab** [comment]
- When a comment is added or deleted we need to update the number of comment at the top of the comment list:
![image](https://user-images.githubusercontent.com/6057298/32228212-8b4fdcc4-be45-11e7-8467-e326ecec1d82.png)

- When a comment is added the textarea needs to be cleared

**Comment by asimonw** [comment]
@SimonLab Smooth! I'll create another issue to also deal with flagging through ajax, but for now this is perfect 👍
