### ISSUE TITLE
Travis failing

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#99]
Travis is failing on https://github.com/emfoundation/ce100-app/pull/84 and we are struggling to debug. All tests pass locally but most fail on travis and then hang until it times out.

**Comment by nelsonic** [comment]
@JMurphyWeb see: https://github.com/emfoundation/ce100-app/pull/84#issuecomment-245257033

**Comment by nelsonic** [comment]
Let's _focus_ on using a _single_ version of Node to ensure we are "_all on the same page_".
> specify node version in `package.json`: https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version

**Comment by nelsonic** [comment]
@JMurphyWeb the `config.env` in the [Google Doc](https://docs.google.com/document/d/16Yk1Y--H-9h1PQYTyRJoDBKH3MsYk44CjDR_t6T4d0g) does not match the https://travis-ci.org/emfoundation/ce100-app/settings (there are 11 in travis and only 10 lines in the GDoc).
And, I have no way of checking if the variables in Travis are _correct_... 😕 
But if you look at: https://travis-ci.org/emfoundation/ce100-app/builds/158432978#L916
It _suggests_ that the `cookie` `environment variables are the culprit...
so https://github.com/emfoundation/ce100-app/issues/108 should be prioritised.

**Comment by JMurphyWeb** [comment]
Ok I will try to dynamically create the cookie in the test files. 

I've also spotted that 2 tests in login.test.js seem to be failing due to bcrypt returning isValid as `false` on travis, whereas `true` on my local machine and everything else seems to be in order.

```
# /login admin successful
password Hello1
userdetails.password a0.g2GERnNAmOhqaDXja.P.BI5xPx9gRfopAAvyXqsyi
bcrypt err:  undefined... isValid ->  false
```

**Comment by JMurphyWeb** [comment]
I have updated all env variables on travis.

**Comment by JMurphyWeb** [comment]
I will work on removing cookies from env file

**Comment by JMurphyWeb** [comment]
Good news is that we got green on a travis 🎉  when i used a cookie not from env vars.

**Comment by nelsonic** [comment]
@JMurphyWeb that looks ok, the "Global" is contained within the context of the test...

This would obviously be _simpler_ with JWTs which have a `syncrhonous` API:
```js
var token = JWT.sign({ id: 123, "name": "Charlie" }, secret);
```
 e.g: https://github.com/dwyl/hapi-auth-jwt2/blob/master/test/basic.test.js#L210

But yeah, this will work. 👍

**Comment by JMurphyWeb** [comment]
That has been lingering in the back of my mind all day 👍

**Comment by JMurphyWeb** [comment]
Finally travis is passing
