### ISSUE TITLE
Comments of inactive users

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#992]
Comments should keep showing for inactive users, still displaying their name and org (if the org is inactive, this shouldn't be a link) and a message "No longer active".

**Comment by asimonw** [comment]
@fannyBkane It might be worth adding an example for the placement of the text "No longer active" in the prototype? Further styling to indicate the user is no longer active might be useful, but just adding the text somewhere could be a first iteration, keeping in mind that this case might not come up for a while.

**Comment by fannyBkane** [comment]
Mobile:
![challenge card-mobile-next steps](https://user-images.githubusercontent.com/20577339/32010187-0a04ef74-b9a9-11e7-91a5-9f9e7538f763.png)

Desktop:
![my challenge-matches-and-comments](https://user-images.githubusercontent.com/20577339/32010260-37ba83e8-b9a9-11e7-91a4-d6c589638d67.png)

[Link](https://projects.invisionapp.com/d/main#/console/11390797/257366755/preview) to updated page in the prototype (where you can also get the specs)

**Comment by Cleop** [comment]
- [ ] 'User no longer active' message in italics light grey
- [ ] Inactive orgs no longer a link (active orgs aren't yet a link but we can add this and make this the case)
