### ISSUE TITLE
load javascript on specific page

### ISSUE THREAD

**Issue by SimonLab** [emfoundation/ce100-app#996]
We only want to load javascript code on specific page, for example the javascript link to the comments should only be loaded on the /challenges/id endpoint. This will avoid having the following type of errors:

![image](https://user-images.githubusercontent.com/6057298/32056556-de8ccac4-ba5c-11e7-8591-11bf5f745e2c.png)

**Comment by Cleop** [comment]
Can we put in an if statement so that if the page url = 'challenges/' then some regex for a number after challenges like [0-9]+ ?

**Comment by SimonLab** [comment]
Yes I was doing this on a first stage but I think we can even not load any file by checking with Handlebars, like this the frontend doesn't need to download the file

**Comment by SimonLab** [comment]
- The maind index.js is now split in different files: https://github.com/emfoundation/ce100-app/tree/master/public/js/comments
- The list of files to load is define on the handlers:
https://github.com/emfoundation/ce100-app/blob/fc8269681be10a56b484c9692937670f0db4a568/server/handlers/challenges/challenge-view.js#L80
- The handlebars function helper return the html script tags necessary to load the js files on the page:
https://github.com/emfoundation/ce100-app/blob/master/templates/helpers/insertJS.js
